### ISSUE TITLE
FirebaseError: Function CollectionReference.add() requires its first argument to be of type object, but it was: a function

### ISSUE THREAD

**Issue by IkennaU** [prescottprue/react-redux-firebase#1005]
Pls Help, each time i try to submit, it gives the error...
FirebaseError: Function CollectionReference.add() requires its first argument to be of type object, but it was: a function

pls help me out

import React, { useState } from "react";
import { Link } from "react-router-dom";
import { useFirestore } from "react-redux-firebase";
import { useFirestoreConnect } from "react-redux-firebase";
import PropTypes from "prop-types";

function AddClient(props) {
  const firestore = useFirestore();

  let initialState = {
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    balance: "",
  };
  const [clients, setClients] = useState(initialState);
  const { firstName, lastName, email, phone, balance } = clients;

  useFirestoreConnect([{ collection: "client" }]);

  const onChange = (e) =>
    setClients({ ...clients, [e.target.name]: e.target.value });

  const onSubmit = (e) => {
    e.preventDefault();
    const newClient = setClients;

    return firestore
      .add({ collection: "client" }, newClient);
     
  };

  return (
    <div>
      <div className="row">
        <div className="col-md-6">
          <Link to="/" className="btn btn-link">
            <i className="fas fa-arrow-circle-left" /> Back To Dasboard
          </Link>
        </div>
      </div>
      <div className="card">
        <div className="card-header">Add Client</div>
        <div className="card-body">
          <form onSubmit={onSubmit}>
            <div className="form-group">
              <label htmlFor="firstName">First Name</label>
              <input
                type="text"
                className="form-control"
                name="firstName"
                minLength="2"
                required
                value={firstName}
                onChange={onChange}
              />
            </div>
            <div className="form-group">
              <label htmlFor="lastName">Last Name</label>
              <input
                type="text"
                className="form-control"
                name="lastName"
                minLength="2"
                required
                value={lastName}
                onChange={onChange}
              />
            </div>
            <div className="form-group">
              <label htmlFor="email">Email</label>
              <input
                type="email"
                className="form-control"
                name="email"
                value={email}
                onChange={onChange}
              />
            </div>
            <div className="form-group">
              <label htmlFor="phone">Phone</label>
              <input
                type="text"
                className="form-control"
                name="phone"
                minLength="10"
                required
                value={phone}
                onChange={onChange}
              />
            </div>
            <div className="form-group">
              <label htmlFor="balance">Balance</label>
              <input
                type="text"
                className="form-control"
                name="balance"
                minLength="2"
                value={balance}
                onChange={onChange}
              />
            </div>
            <input
              type="submit"
              value="Submit"
              className="btn btn-primary btn-block"
            />
          </form>
        </div>
      </div>
    </div>
  );
}

AddClient.propTypes = {};

export default AddClient;

**Comment by prescottprue** [comment]
`newClient` will be a function because of the line:
```js
const newClient = setClients;
```

`setClients` is a function because of this line here:

```js
const [clients, setClients] = useState(initialState);
```

Since this is an implementation question you usually get a faster and more complete response if you reach out over [Gitter](https://gitter.im/redux-firebase/Lobby)

**Comment by IkennaU** [comment]
Thanks
