### ISSUE TITLE
Signup doesn't generate a user document in Firestore

### ISSUE THREAD

**Issue by EladKarni** [prescottprue/react-redux-firebase#1006]
**What is the current behavior?**

Signing up a user adds them to the authenticated accounts in Firebase, but doesn't create a document in Firestore with their info.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Just calling the signup function does it for me.

**What is the expected behavior?**

A user should be created in the firebase authentication section, and a corresponding document with the user info should also be created.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Using Windows 10, Edge, Chrome Firefox were tested. Unsure about version sorry

**Comment by prescottprue** [comment]
Can you provide a full reproduction example including the configuration you are using?

**Comment by EladKarni** [comment]
> Can you provide a full reproduction example including the configuration you are using?

Hey, thanks for responding! 

Someone on the firebase slack server actually helped me figure this out, but we think we found a bug with createUser. The createUser function returns an object without the firebase ID for some reason. Should I make a new thread for that?

Does RRF, have a Discord server or slack by the way?

**Comment by EladKarni** [comment]
> Can you provide a full reproduction example including the configuration you are using?

Hey, thanks for responding! 

Someone on the firebase slack server actually helped me figure this out, but we think we found a bug with createUser. The createUser function returns an object without the firebase ID for some reason. Should I make a new thread for that?

Does RRF, have a Discord server or slack by the way?

**Comment by EladKarni** [comment]
Problem was solved. Issue was with the permissions on the Firebase side. Apologies!
