### ISSUE TITLE
Firestore query by geolocation

### ISSUE THREAD

**Issue by emersonlaurentino** [prescottprue/react-redux-firebase#1009]
Hi, I am using firestore to database and I have this model:

```ts
// Products
{
  createdBy: "userId",
  ...
}
```

```ts
// Users
{
  id: 123,
  latitude: "2.87",
  longitude: "3.44"
  ...
}
```

I want to make a query that brings the products close to the user from the location.

Do you have any idea how should I do it?

**Comment by prescottprue** [comment]
This is not built into Firestore by default, for functionality like this you will want to checkout something like [GeoFirestore](https://github.com/MichaelSolati/geofirestore-js) that uses a specific object structure for querying for location/distance.

This is out of the scope of this library
