### ISSUE TITLE
[Typescript] getFirebase().firestore should have FirestoreStatics interface

### ISSUE THREAD

**Issue by zozoens31** [prescottprue/react-redux-firebase#1012]
**Do you want to request a *feature* or report a *bug*?**  

This is a bug.

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**What is the current behavior?**

Currently, `getFirebase().firestore()` is typed with the interface `FirestoreStatics`, but this is not implemented by Firebase.
I wasn't able to reproduce in a fully functional sandbox because it requires a working Firebase app, but you can still see type-checking [here](https://codesandbox.io/s/great-murdock-76viv).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**What is the expected behavior?**

`FirestoreStatics` is actually implemented at the `getFirebase().firestore` level

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

This should affect all versions, independently from any OS or browser. The `FirestoreStatics` interface was added in v3.6.0.

**Comment by prescottprue** [comment]
I believe
