### ISSUE TITLE
If no events triggered, unmount error in useFirebaseConnect

### ISSUE THREAD

**Issue by adam-remotesocial** [prescottprue/react-redux-firebase#1019]
https://github.com/prescottprue/react-redux-firebase/blob/e67bbd71ab25fc4830d881431a1661a93b316efc/src/actions/query.js#L221

For example if I write

```
useFirebaseConnect(props.alwaysNull && [queryA, queryB])
```

In this case, `unwatchEvents` is called on unmount of the component, but `events` is undefined so `events.forEach` throws.

Workaround - create a new component to house queries that is only mounted when the query inputs are available.

**Comment by prescottprue** [comment]
Thanks for reaching out! This is for sure an issue - should be able to be solved by checking for events before calling the forEach

**Comment by rscotten** [comment]
@prescottprue Could you please respond to #1008?

**Comment by prescottprue** [comment]
[The v3.8.1 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.8.1) includes a fix for this. Reach out if it isn't working as expected thanks for reporting!

**Comment by adam-remotesocial** [comment]
Thanks a ton!
