### ISSUE TITLE
bug(types): populates is missing from ReduxFirestoreQuerySetting interface

### ISSUE THREAD

**Issue by keithkelly31** [prescottprue/react-redux-firebase#1027]
When using useFirestoreConnect in a js or jsx file it works as expected.  When working in typescript I receive an error:

'populates' does not exist in type 'ReduxFirestoreQuerySetting | ReduxFirestoreQuerySetting[] | string[] | mapper<unknown, (string | ReduxFirestoreQuerySetting)[]> | mapper<...>'.ts(2345)

Can populates be added to the proper types?

**Comment by prescottprue** [comment]
[The v3.8.1 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.8.1) includes a fix for this. Reach out if it isn't working as expected thanks for reporting!
