### ISSUE TITLE
Upgrade to react 17

### ISSUE THREAD

**Issue by michalens** [prescottprue/react-redux-firebase#1028]
I am getting an error
```
Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-redux-firebase@3.7.0
npm ERR! node_modules/react-redux-firebase
npm ERR!   react-redux-firebase@"*" from the root project
```

Should I force install react-redux-firebase? Or should I downgrade to react 16.14.0? (Or even `16.3`)

**Comment by prescottprue** [comment]
@michalens [the v3.8.0 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.8.0) includes an update to the peer dependencies to support react 17

Thanks for reporting! Please reach out if things aren't working as expected
