### ISSUE TITLE
bug(types): ExtendedFirestoreInstance doesn't extend FirestoreStatics from 3.8.0 any more

### ISSUE THREAD

**Issue by ondrejhudek** [prescottprue/react-redux-firebase#1030]
In version **3.7.0** `ExtendedFirestoreInstance` used to extend `FirestoreStatics`. 

Now in new **3.8.0** this extend was removed so the instance of `useFirestore()` which is a type of `ExtendedFirestoreInstance` doesn't have props of `FirestoreStatics`.

Because of this problem I cannot for example use prop `FieldValue` which exists on `FirestoreStatics`.

![image](https://user-images.githubusercontent.com/2676643/100465058-ef3bc500-30ce-11eb-8185-8c0c575f2404.png)

**Comment by prescottprue** [comment]
Thanks for reporting - open to a PR if you get a chance, otherwise I will try to get to it this weekend

**Comment by keithkelly31** [comment]
Just wondering if there was any progress on this?

**Comment by prescottprue** [comment]
[v3.9.0 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.9.0) includes the fix for this, thanks for reporting!
