### ISSUE TITLE
endBefore duplicated in ReduxFirestoreQuerySetting interface

### ISSUE THREAD

**Issue by keithkelly31** [prescottprue/react-redux-firebase#1033]
Just a little clean up bit.

endBefore?: FirestoreTypes.DocumentSnapshot | any | any[] is duplicated in the ReduxFirestoreQuerySetting interface.  It can be found on lines 446 & 474 of the Typescript definitions file.

**Comment by prescottprue** [comment]
Thanks for reporting - open to a PR if you get a chance, otherwise I'll try to get to it as part of an upcoming release

**Comment by keithkelly31** [comment]
It looks like pull request #1031 corrects this issue
