### ISSUE TITLE
Uncaught TypeError: u.indexOf is not a function when using populates on useFirestoreConnect

### ISSUE THREAD

**Issue by ddnazzah** [prescottprue/react-redux-firebase#1053]
`useFirestoreConnect([
		{
			collection: 'volumes',
			orderBy: ['created_at', 'desc'],
		},
		{
			collection: 'reports',
			orderBy: ['created_at', 'desc'],
			populates: [{ child: 'volume_id', root: 'volumes' }],
		},
	])
`

I want to get a data response where the volume_id on the reports collection will fetch the actual data from firestore instead of the reference type object.

`"redux": "^4.0.5"
"react-redux": "^7.2.2",
 "react-redux-firebase": "^3.8.1", 
 "react": "^17.0.1",
"redux-firestore": "^0.14.0",`

**Comment by prescottprue** [comment]
I believe that currently populates doesn't work with reference type objects - [described in this issue](https://github.com/prescottprue/redux-firestore/issues/196). Going to close as a duplicate

**Comment by ddnazzah** [comment]
Thank you
