### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by oktaysenkan** [prescottprue/react-redux-firebase#1061]
**Do you want to request a *feature* or report a *bug*?**  

Does react-redux-firebase support offline auth and database actions (sync when online)? If it supports then how i use this future?

**Comment by prescottprue** [comment]
Offline support is controlled directly through the Firebase SDK as described [in their docs](https://firebase.google.com/docs/firestore/manage-data/enable-offline)

react-redux-firebase is just hooked into the callbacks of the Firebase SDK which trigger when these events happen
