### ISSUE TITLE
Maintain/reuse state when queriying same collection again

### ISSUE THREAD

**Issue by TrySpace** [prescottprue/react-redux-firebase#1065]
**Feature/undocumented functionality** 

Not sure how it is meant to be used, but is there an existing way to keep the state of collections intact without removing the previous state? 
Every time a component renders with `useFirestoreConnect`, it will clear the existing store, which I'm not even sure if that's expected behaviour. 
It might also be why this issue: https://github.com/prescottprue/react-redux-firebase/issues/914 is causing such a render-blocking issue, because instead of replacing them in quick succession, it is adding them, causing too many re-renders, where replacing them should cause minimal or no change at all.

**Comment by TrySpace** [comment]
Closing because who cares ;p

**Comment by prescottprue** [comment]
FWIW - anyone seeing this issue, it may be worth using [reactfire](https://www.npmjs.com/package/reactfire) directly as called out [within the react-redux-firebase readme](https://github.com/prescottprue/react-redux-firebase?tab=readme-ov-file#usage-note)
