### ISSUE TITLE
fix(docs): add the required database import to use realtime database to examples

### ISSUE THREAD

**Issue by danielo515** [prescottprue/react-redux-firebase#1080]
**Do you want to request a *feature* or report a *bug*?**  

[The current getting started](http://react-redux-firebase.com/docs/getting_started.html#setting-up-app-with-store) is missing key information to start using this cool library. I think the most use case scenario is with the real time database, which this library seems to support out of the box (no extra deps). However, I can't find a single reference nowhere in the docs about setting up the real time database, only firestore. This can lead to very frustrating experiences because the first time you try to load data from the database you will find the following error:

```
Error: Firebase database is required to create watchers
```

**What is the current behavior?**

The current docs have commented code about firestore, but it doesn't contain a single reference to the requirement of importing the real time database, which is a must. It is as simple as adding `import  'firebase/database'` to the getting started example

**What is the expected behavior?**

To have a commented line telling you that you must import the real time database if you want to use it.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

**Comment by prescottprue** [comment]
Thanks for calling this out! Definitely the case, and we want to make things as easy as possible when setting up
