### ISSUE TITLE
bug(ssr): Error: The XMLHttpRequest compatibility library was not found.

### ISSUE THREAD

**Issue by jeandavid** [prescottprue/react-redux-firebase#113]
I am starting from the starter kit: [https://github.com/kriasoft/react-starter-kit](https://github.com/kriasoft/react-starter-kit)
I add the react-redux-firebase dependency. 
I follow the guidelines to get started. 

But this is the issue I got when launching the app in a browser: 
`Error: The XMLHttpRequest compatibility library was not found.`

**Comment by prescottprue** [comment]
Are you using Server Side Rendering? You need to import/require `XMLHttpRequest` mentioned in [this issue](https://github.com/prescottprue/react-redux-firebase/issues/72#issuecomment-292403834).

This will be added to the docs for `v1.4.0`.

We were also discussing including this as a dependency, but it will only be used when doing server side rendering.

**Comment by prescottprue** [comment]
[`v1.4.0` was released](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0) with this functionality included, so this is now out of pre-release.

[SSR recipe was added as well](http://react-redux-firebase.com/docs/recipes/ssr.html)
