### ISSUE TITLE
📦  Dependencies need updating

### ISSUE THREAD

**Issue by sesam** [prescottprue/react-redux-firebase#1143]
**Do you want to request a *feature* or report a *bug*?**  

Bug: regular maintenance needed!

**What is the current behavior?**
Missing out on easy regular updates, beginning with security updates.

**Reproduce**

`npm audit` and dependabot too has been signaling about this for a while.

**What is the expected behavior?**
Community, supported by maintaner(s), release regular package updates to keep up with security issues.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

**Comment by sesam** [comment]
Checking out latest main branch and running `npm install` gave this:

`found 340 vulnerabilities (25 low, 117 moderate, 166 high, 32 critical)`

**Comment by prescottprue** [comment]
Included in v3.10.1
