### ISSUE TITLE
bug(actions): LOGOUT dispatched after LOGIN_ERROR

### ISSUE THREAD

**Issue by littleStudent** [prescottprue/react-redux-firebase#115]
I am using react-boilerplate and integrated `react-redux-firebase` for authentication.
It seems like `LOGOUT` is dispatched directly after `LOGIN_ERROR`. This overrides the error message which got set.
It gets also dispatched on a reload after `AUTHENTICATION_INIT_FINISHED`.

Am I using the library incorrectly? Not sure why this is happening.

<img width="349" alt="screenshot 2017-04-23 12 35 59" src="https://cloud.githubusercontent.com/assets/815520/25312801/171a31f6-2822-11e7-8a49-866474b4d2ae.png">
<img width="344" alt="screenshot 2017-04-23 12 39 02" src="https://cloud.githubusercontent.com/assets/815520/25312802/1a3d9b84-2822-11e7-8dc7-c548c3e38823.png">

**Comment by prescottprue** [comment]
@littleStudent Which method are you using to log in?

It is hard to tell if anything is "incorrect" without seeing your current setup. Can you possibly provide a link to a repository?

**Comment by littleStudent** [comment]
I thought there may be something obvious I am missing.
Here is the [repo](https://github.com/littleStudent/react-redux-firebase-logout)

In the last commit I added react-redux-firebase for authentication. 
For reproduction: Opening the app should already show you the second case. `LOGOUT` called after `AUTHENTICATION_INIT_FINISHED`.

Hope this helps.

**Comment by prescottprue** [comment]
It seems it may be due to `react-router` 4, but I will continue to look into it.

**Comment by littleStudent** [comment]
Thanks for looking into this 👍

**Comment by prescottprue** [comment]
I believe that fixing #119 will handle this, but not sure. Putting it on the roadmap for v1.6.0.

**Comment by prescottprue** [comment]
In `v2` the `LOGOUT` action will only be able dispatched by actually calling `logout`, so this will no longer be an issue  (once `v2.0.0-beta.9 is released).

As for `v1`, a similar change would potentially be breaking if anyone was depending on state being emptied on failed redirect logins. May end up having to make it available through a config option, but will update when there is more info.

For those still experiencing the bug, which version(s) are you using?

**Comment by prescottprue** [comment]
Apparently the cause of this in `v1.*.*` was that some auth methods would return empty auth info in `onAuthStateChanged` (which dispatches `LOGOUT` action) after an auth error had been returned.

`disableEmptyAuthDispatch` config option was added in [the `v1.5.1` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.1) for disabling dispatch of `LOGOUT` action when auth updates with `null`, which should fix this for anyone still using `v1.*.*` that encounters this issue.
