### ISSUE TITLE
fix(docs): UserIsAuthenticated usage of UserAuthWrapper

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [prescottprue/react-redux-firebase#116]
```js
import { browserHistory } from 'react-router'
import { UserAuthWrapper } from 'redux-auth-wrapper'
import { pathToJS } from 'react-redux-firebase'

export const UserIsAuthenticated = UserAuthWrapper({
  wrapperDisplayName: 'UserIsAuthenticated',
  authSelector: ({ firebase }) => pathToJS(firebase, 'auth'),
  authenticatingSelector: ({ firebase }) => pathToJS(firebase, 'isInitializing') === true,
  predicate: auth => auth !== null,
  redirectAction: (newLoc) => (dispatch) => {
    browserHistory.replace(newLoc)
    // routerActions.replace // if using react-router-redux
    dispatch({
      type: 'UNAUTHED_REDIRECT',
      payload: { message: 'You must be authenticated.' },
    })
  },
})
```

Hello, the code above is in the docs, but I found something strange
isInitializing is set to false BEFORE the action that sets auth to null (or to the object representing the user) is set
So we evaluate the predicate before we know for sure if the user is logged in or not, causing unexpected redirects
My workaround for this was to use this authenticatingSelector
```js
  authenticatingSelector: ({ firebase }) => pathToJS(firebase, 'auth') === undefined
```
Am I missing something?
If this problem is confirmed, we either need to fix the docs or fix when the action that sets isInitializing to false is dispatched

**Comment by prescottprue** [comment]
This is confirmed and is intended functionality. Will updated docs.

**Comment by prescottprue** [comment]
This has been updated in the Docs and the README.


Thanks for reporting!
