### ISSUE TITLE
feat(react-router): react-router version 4 support

### ISSUE THREAD

**Issue by prescottprue** [prescottprue/react-redux-firebase#119]
If using react-router `v4.*.*`, routing patterns provided in the docs do not work.

* #115 may be related
* Issue on [redux-auth-wrapper](https://github.com/mjrussell/redux-auth-wrapper/issues/145)

This issue will be used to track progress on fully documenting usage of react-router version 4.

**Comment by JulianJorgensen** [comment]
Nice! Looking forward. Great work creating this @prescottprue! Much appreciated.

**Comment by Ethan-Arrowood** [comment]
@prescottprue if my app is already dependent on React Router v.4 should I avoid using react-redux-firebase?

**Comment by JulianJorgensen** [comment]
@Ethan-Arrowood I just upgraded to react-router v4 and it seems to be fine. I haven't tested all issues as I'm still trying to fix some react-redux-firebase v2 bugs.

**Comment by prescottprue** [comment]
@Ethan-Arrowood No, if you are not having any issues with how things work currently, then you are fine to use it. The issues are mainly around specific routing recipes with redux-auth-wrapper v1.

As @JulianJorgensen mentioned, it actually works fine in most cases.

**Comment by prescottprue** [comment]
@JulianJorgensen did you get everything working as expected? @Ethan-Arrowood as I understand, the only real issues are with the [`routing-recipes` in the docs](http://react-redux-firebase.com/docs/recipes/routing.html), specifically the stuff with `redux-auth-wrapper`.

Been trying to get time to work on an example, but stuff with `v2.0.0` has been taking up my time.

**Comment by pzmudzinski** [comment]
This is my solution for v2 and RR v4:
```import { connectedRouterRedirect } from 'redux-auth-wrapper/history4/redirect';
import locationHelperBuilder from 'redux-auth-wrapper/history4/locationHelper';
import { browserHistory } from 'react-router';
import LoadingScreen from '../components/LoadingScreen'; // change it to your custom component

const locationHelper = locationHelperBuilder({});

export const UserIsAuthenticated = connectedRouterRedirect({
  redirectPath: (state, ownProps) => locationHelper.getRedirectQueryParam(ownProps) || '/login',
  allowRedirectBack: true,
  authenticatedSelector: ({ firebase: { auth } }) =>
    auth && auth.isLoaded && !auth.isEmpty,
  authenticatingSelector: ({ firebase: { auth } }) =>
    auth === undefined || !auth.isLoaded,
  AuthenticatingComponent: LoadingScreen,
  wrapperDisplayName: 'UserIsAuthenticated',
});

export const UserIsNotAuthenticated = connectedRouterRedirect({
  allowRedirectBack: false,
  redirectPath: (state, ownProps) => locationHelper.getRedirectQueryParam(ownProps) || '/dashboard',
  authenticatedSelector: ({ firebase: { auth } }) => auth != null && auth.isLoaded && auth.isEmpty,
  authenticatingSelector: ({ firebase: { auth } }) =>
    auth === undefined || !auth.isLoaded,
  AuthenticatingComponent: LoadingScreen,
  wrapperDisplayName: 'UserIsNotAuthenticated',
});
```

**Comment by prescottprue** [comment]
Thanks @pzmudzinski. I will update the docs with this example. After I can confirm it working I will close the issue.

**Comment by prescottprue** [comment]
Confirmed and placed in docs. Thanks again @pzmudzinski.
