### ISSUE TITLE
Material example: Todos can't be deleted

### ISSUE THREAD

**Issue by gitmathub** [prescottprue/react-redux-firebase#124]
https://demo.react-redux-firebase.com/

**What is the current behavior?**

I'm logged-in as a Google user and I create a todo. I push the trash-can icon of my newly created todo. Nothing happens. **The item is not deleted.**
Other observations:
- No console output. 
- The todo I have created shows as Owner: Xbs0YRB7KJUK8V21cNouAbsJfPg2.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Mac, Chrome version 56.0.2924.76 (64-bit)

**Comment by prescottprue** [comment]
This is intended functionality, and is part of the demo that was deployed last night.

Some users were asking for a more simple example for the home container. The delete that was there before used population. If you check the `deleteTodo` method is has code commented out.that may be useful.

To make it more clear I will remove the delete button.
