### ISSUE TITLE
Populating same route in different containers

### ISSUE THREAD

**Issue by raghavendracs** [prescottprue/react-redux-firebase#135]
Data structure in Firebase that I am having

/users/uid

- experience 
- education
- refsA
- refsB

I am connecting to the /users/uid in container A where I am populating experience and education basis their ID's which are stored above and getting it into a prop UserProfile. I am checking using isLoaded(UserProfile) and all is ok.

Within container A I have a route to a link which loads up another container B where I am populating the refsA and refsB id's into a prop also called UserProfile.

When I check for isLoaded(UserProfile) in Container B I am getting true value even before populate is completed. This is obviously leading things to fail. 

Is there a way I can see isLoaded changing from false to true in Container B post populate of refsA and refsB?  For example isLoaded(UserProfile.refsA)?

**Comment by prescottprue** [comment]
If you store the result of your query in another location within redux, this will function as intended. This is what `storeAs` is for (placing data within redux under a location other than the path).

The [multiple queries example snippet shows](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/snippets/multipleQueries/App.js#L18-L28) usage of `storeAs`.

The issue boils down to the fact that the data is already within redux, so `isLoaded` will be true, unless you store the data in another path.

As for waiting for populated data, If you are using `v1.4.0-rc.2` or later, `isLoaded` waits until populated data is available before switching to `true` (again assuming you haven't already loaded data into the same place within redux).
