### ISSUE TITLE
question(auth): sign in anonymously on application starup

### ISSUE THREAD

**Issue by radicalnerds** [prescottprue/react-redux-firebase#137]
I am trying to add an onAuthStateChanged listener to the firebase object when using reactReduxFirebase. The docs here describe that this parameters should set that value.
http://react-redux-firebase.com/docs/api/compose.html

My assumption is like in the tutorial here
https://www.youtube.com/watch?v=ApG8L2RKrSI

onAuthStateChanged will get called on appStartup w/ the current user or an undefined user (which in my code will trigger an anonymous login). My goal is to make my app by default be an anonymously logged in user. Is something wrong with my approach here? Is this feature supposed to work as I have described?

`javascript
import { AsyncStorage } from 'react-native';
import { reactReduxFirebase } from 'react-redux-firebase';

// Firebase config
const firebaseConfig = {
  apiKey: '<KEY>',
  authDomain: '<Domain>',
  databaseURL: '<DB URL>',
  projectId: '<PID>',
  storageBucket: '<SB>',
  messagingSenderId: '<MSID>',
};

// react-redux-firebase options
const config = {
  userProfile: 'users',
  enableLogging: false,
  ReactNative: { AsyncStorage },
  onAuthStateChanged: (user, firebase) => {
    console.log('User INFORMATION BRO', user);
    if (user) {
      // User is signed in.
    } else {
      firebase.auth.signInAnonymously();
    }
  },
};

const FirebaseStore = reactReduxFirebase(firebaseConfig, config);
export default FirebaseStore;

// Eventually store is created like this
const createStoreWithFirebase = compose(FirebaseStore)(createStore);
const store = createStoreWithFirebase(reducers);
`

**Comment by prescottprue** [comment]
Based on your code, this is expected behavior. Your auth state has not actually changed at all (it is always just logged out).

It seems like you are attempting to sign in anonymously on application boot. If that is the case you will want to be checking to see if auth exists on that boot not when auth changes.


You would most likely want to place the sign in anonymously code into a home page component. That page can check auth, redirecting somewhere if it exists, and bringing you to a login page if not. That login page can handle the signing in anonymously.

**Comment by radicalnerds** [comment]
Great thanks for the quick reply! Just to be 100% clear this is a deviation of how this method is normally used for the 'firebase' npm package which this is based on correct?

Appreciate the suggested implementation!

**Comment by prescottprue** [comment]
@radicalnerds Yes, it is a deviation.

That said, when that decision was made, this use case was not understood. One of the goals of this library is to keep compatibility with Firebase across the board, so this is for sure a good idea for a change.

Thanks for pointing it out. This issue will be updated when/if this is changed.

**Comment by prescottprue** [comment]
[version `v1.5.0-alpha`](https://github.com/prescottprue/react-redux-firebase/pull/136)  has been released and includes the `enableEmptyAuthChanges` config option. If this is set to true, `onAuthStateChanged` will be fired with undefined on initialization as you were originally expecting.

As stated, this may become the standard functionality, but it has remained disabled by default for now to keep new `onAuthStateChanged` behavior from being a breaking change.

**Comment by prescottprue** [comment]
Just as a heads up, this is being removed from `v2.0.0`. It is replaced by `preserveOnEmptyAuthChange`, checkout the [migration guide](docs.react-redux-firebase.com/history/v2.0.0/docs/v2-migration-guide.html) for examples.
