### ISSUE TITLE
Auth Not Persisting (email + password auth)

### ISSUE THREAD

**Issue by radicalnerds** [prescottprue/react-redux-firebase#138]
So I am trying to use react-redux-firebase for auth but my auth isn't persisting app kills. When I use the npm 'firebase' package directly and I kill the app and restore the session of the users is persisted correctly but when using react redux firebase it isn't. To simplify this and make sure that I am not doing something odd I stripped down the react-native complete example w/ google sign in to just to email password auth and I still am not seeing the state persisted. Is this intended?

Here is how I am doing the authentication.
```javascript
signIn() {
    const { auth } = this.props.firebase
    return auth()
      .signInWithEmailAndPassword('email@domain.com', 'password123')
      .then(() => {
        console.error('Logged In')
      })
      .catch((err) => {
        console.error('error authing with firebase:', err)
        return Promise.reject(err)
      })
  }
```

How Auth gets piped to my component

```javascript
@firebaseConnect()
@connect(({ firebase }) => ({
  auth: pathToJS(firebase, 'auth')
}))
```

How I check if I am logged in.
```javascript
if (!this.props.auth) {
```

PS. Sorry for the questions / issues trying to get rolling on this library (see if it will work for me) and excited about the value add but hitting a few initial snags.

**Comment by prescottprue** [comment]
You will want to use `isLoaded(this.props.auth)`.

This all depends on how you are handling auth flow (so it would be best if you can share a full repro repository). Auth state is "preserved" by Firebase's lib, but there is still the time of startup where this data has not yet made it to redux state. That should come shortly after reboot though, and contain you auth data.

With react-native nothing in your redux store will "persist on app kill". If you are attempting to persist state, you will need to use something such as [`redux-persist`](https://github.com/rt2zz/redux-persist) (do not currently have an example).

**Comment by radicalnerds** [comment]
Still not seeing this persist. I assumed the firebase lib is supposed to persist that credential but it doesn't appear to be. I pushed to a fork the changes I made (left out my google plist changes and config changes for firebase)

**Comment by radicalnerds** [comment]
Dove into this some more. It appears something wonky is happening internally when you are initializing the Firebase Instance. The only reason the examples/complete/react-native demo works is because the google API is maintaining the users state in the browser session. If you simply migrate this to use signInWithEmailAndPassword it doesn't work. One way I did get it to work is by modifying the compose.js file.

I changed the signature of the to become this
```javascript
export default (fbInstance, otherConfigs) => next =>
  (reducer, initialState, middleware) => { //... function body }
```

This allowed me to initialize a firebase instance externally and pass it in. Then in here I removed all the logic around instantiating one. I am unsure what exactly is wrong with the internally defined instance but when I did this my state was properly remembered by the API.

It seems to me to be a more sustainable/future looking paradigm to just let the user define the firebaseApp Instance and this library to just be a set of wrappers / functionality on top of it. That way as the library grows this library doesn't have to change to still add value. For instance the one issue filed around using react-native-firebase instead of npm firebase could be achieved with this pattern as long as the react-native-firebase and firebase implementations have the same method signatures.

Thoughts? I probably will punt using this library for my near term implementations as they are pretty simple and the churn here is concerning. I hope that this will eventually be adoptable tho!

**Comment by prescottprue** [comment]
@radicalnerds What you are mentioning with allowing to pass in an instance, for things such as react-native-firebase, is actually already the plan moving forward [as mentioned in the roadmap](http://react-redux-firebase.com/docs/roadmap.html#future-minor-versions-v160---v1)

What you are mentioning with the `react-native` example and `signInWithEmailAndPassword` is expected. If you are attempting to store auth state within redux, you should be using [the `login` method as mentioned in the docs](http://react-redux-firebase.com/docs/auth.html#logincredentials). This is intended because not all users would like auth state to go to redux.

#### Exposing The Instance

The instance of Firebase will be exposed starting in `v1.5.0`, but this is not exactly as it sounds. Methods that are available currently call internal firebase methods and wrap them in the correct action dispatches (which in tern update redux state through the reducer).

#### Churn
Many users have asked that the features they need be released to npm quickly. [The Semver guidelines](http://semver.org/) have been followed closely so that users will not be hit with breaking changes without seeing it coming. All breaking API changes include depreciation periods and warnings to remind developers to move away from old methods/syntax for coming versions.

Open to suggestions for other ways to address any concerns on this front

**Comment by prescottprue** [comment]
@radicalnerds As of [`v2.0.0-alpha`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-alpha) passing in an already initialized Firebase instance is supported ([`v2.0.0-alpha.2`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-alpha.2) is newest). It also works with `redux-persist` out of the box (i.e. no transforms).

Closing this issue for now, let me know if ti does not work as expected for you.

**Comment by smkamranqadri** [comment]
Same happing here, I am using 1.4.6 of react redux firebase with async storage so when I login and restart the app, the auth is gone, have to relogin, even if I use getFirebase() same happen, what work is the core firebase, if I login with core and restart the app, the auth is still there.

any suggestions?

**Comment by kstott** [comment]
I've been trying everything I can think of. But, I must be misunderstanding something. My expectation was that when using redux-persist I would configure the store per you example and auto-magically it would persist in firebase. 

It persists locally, but data is not persisted in the cloud. The realtime database data is null. and it shows 0 bytes stored. It logs reads (??) but not sure what its reading. Every login it logs about 10K in reads. My security is set to 'public' for firebase. And I am able to login successfully.

Any help would be appreciated!! createStore.js is below.

`...

import { createStore, combineReducers, compose, applyMiddleware } from 'redux'
import { reactReduxFirebase, firebaseReducer } from 'react-redux-firebase'
import firebase from 'react-native-firebase'
import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage' // defaults to localStorage for web and AsyncStorage for react-native
import autoMergeLevel2 from 'redux-persist/lib/stateReconciler/autoMergeLevel2';
import logger from 'redux-logger'

const persistConfig = {
    key: 'root',
    storage,
    blacklist: ['session'],
    stateReconciler: autoMergeLevel2,
    debug: true
};

const rrfConfig = {
    userProfile: 'users',
    enableRedirectHandling: false,
    enableLogging: true
    //useFirestoreForProfile: true // Firestore for Profile instead of Realtime DB
};

const firebaseConfig =  {
    ...
};

export default (initialState = {}) => {

    // Initialize firebase instance
    firebase.initializeApp(firebaseConfig)

    // Add reactReduxFirebase store enhancer when making store creator
    const createStoreWithFirebase = compose(
        reactReduxFirebase(firebase, rrfConfig), // firebase instance as first argument
    )(createStore);

    // Add firebase to reducers (uses persistReducer and hardSet)
    const rootReducer = combineReducers({
        firebase: persistReducer(
            { key: 'firepersist', storage: storage},
            firebaseReducer
        ),
        authentication,
        usage,
        boards,
        media,
        session,
        cell
    });

    const persistedReducer = persistReducer(persistConfig, rootReducer);
    const store = createStore(
        persistedReducer,
        initialState,
        applyMiddleware(logger));
    const persistor = persistStore(store);

    return { store, persistor }
}
`

**Comment by prescottprue** [comment]
@kstott I think what you are seeing is something else all together. Would you mind opening a new issue and including your full rules and which version of `react-redux-firebase` you are using? Also what settings you are passing when you are calling `login`.
