### ISSUE TITLE
Publish 1.5 as next

### ISSUE THREAD

**Issue by cescoferraro** [prescottprue/react-redux-firebase#139]
I am getting proptypes errors with 1.4 and I see the source code fixed at 1.5
I would be nice to have a next tag pointing to the 1.5 branch
Thanks for the amazing work!

**Comment by prescottprue** [comment]
@cescoferraro Planning on releasing v1.5.0-alpha later today.

**Comment by prescottprue** [comment]
@cescoferraro It took a little longer than expected to write some of the unit tests, but [`v1.5.0-alpha`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0-alpha) has been released.

[`v1.5.0` branch](https://github.com/prescottprue/react-redux-firebase/tree/v1.5.0) will continue to hold released progress while in the pre-release phase.
