### ISSUE TITLE
bug(logout) firebase.logout does not return correct promise

### ISSUE THREAD

**Issue by Domiii** [prescottprue/react-redux-firebase#152]
[firebase.logout](https://github.com/prescottprue/react-redux-firebase/blob/v1.5.0/src/actions/auth.js#L369) calls [auth.signOut](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signOut) which returns a promise. 

However [firebase.logout](https://github.com/prescottprue/react-redux-firebase/blob/v1.5.0/src/actions/auth.js#L369) is rather presumptuous in assuming that stuff just happens instantly and always working, returning a `Promise.resolve`, leaving some state in limbo, rather than waiting for state to be pristine and things to be entirely cleaned up under the hood.

Easy fix, something along the lines (but untested):

```js
export const logout = (dispatch, firebase) => {
  return firebase.auth().signOut().
    then(() => {
      dispatch({ type: LOGOUT })
      firebase._.authUid = null
      unWatchUserProfile(firebase)
      return firebase
    })
}
```

**Comment by prescottprue** [comment]
@Domiii Good catch, this will for sure make it into the next pre-release of `1.5.0`. This seems to be around from quite a while ago.

**Comment by prescottprue** [comment]
[`v1.5.0-beta.2`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0-beta.2) was released with this fix. Thanks again!
