### ISSUE TITLE
feat(react): use the prop-types library instead of React.PropTypes

### ISSUE THREAD

**Issue by TheGhoul21** [prescottprue/react-redux-firebase#172]
**Do you want to request a *feature* or report a *bug*?**  

switch from React.PropTypes to prop-types library as it will be deprecated in next release:

> React.PropTypes is deprecated as of React v15.5. Please use the prop-types library instead.
 
**What is the current behavior?**
React.PropTypes is used, and throws warnings in both console and jest 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

just run it anywhere

**What is the expected behavior?**
should not throw warnings

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

current release

**Comment by TheGhoul21** [comment]
I tried to switch to prop-types, but I don't get through all the tests. Will try again with some patience later on

**Comment by prescottprue** [comment]
@TheGhoul21 `v1.5.0-alpha` starts usage of the `PropTypes` package instead of importing it from React. This was creating issues for some users, which is part of why it hasn't made it out of pre-release yet.

**Comment by prescottprue** [comment]
@TheGhoul21 `v1.5.0-alpha` starts usage of the `PropTypes` package instead of importing it from React. This was creating issues for some users, which is part of why it hasn't made it out of pre-release yet.

**Comment by TheGhoul21** [comment]
Oh well good to know then. It is just annoyingly to see that warning all over the time 👍
