### ISSUE TITLE
TypeError: provider.addScope is not a function in `createAuthProvider`

### ISSUE THREAD

**Issue by eloypnd** [prescottprue/react-redux-firebase#18]
I am trying to trigger a login action with the following code:

    export function onTwitterLogin () {
      return (dispatch, getState, getFirebase) => {
        getFirebase().login({
          provider: 'twitter'
        })
      }
    }

And I get the following error:

    Uncaught (in promise) TypeError: provider.addScope is not a function
        at createAuthProvider ...

This is the stack trace:

    createAuthProvider	@	auth.js:37
    getLoginMethodAndParams	@	auth.js:77
    login	@	auth.js:225
    login	@	compose.js:147
    (anonymous function)	@	auth.js:7

Looks like the `addScope` function doesn't exist for the **TwitterAuthProvider**

**Comment by prescottprue** [comment]
Great catch! I didn't catch that in the Firebase docs. Will try to get a fix for this in `1.2.0`.

**Comment by eloypnd** [comment]
I am afraid that the firebase docs have a bug too: [Class: TwitterAuthProvider](https://firebase.google.com/docs/reference/js/firebase.auth.TwitterAuthProvider). They even use `addScope` function in the example. But AFAIK, Twitter API doesn't implement scopes.

@prescottprue, do you want me to send a fix?

**Comment by prescottprue** [comment]
That would be great, I am traveling for the holidays so it might be hard to get to sit down to my comp.

**Comment by prescottprue** [comment]
Fixed within [`v1.1.3` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.1.3). I also added a unit test to cover Twitter login as well as any other providers that don't have `addScope`.

**Comment by eloypnd** [comment]
Thanks @prescottprue
