### ISSUE TITLE
enableLogging fails when using with RNFirebase

### ISSUE THREAD

**Issue by buraks** [prescottprue/react-redux-firebase#184]
`firebase.database.enableLogging is not a function. (In 'firebase.database.enableLogging(configs.enableLogging)', 'firebase.database.enableLogging' is undefined.

when I add enableLogging to my config:
```javascript
reactReduxFirebase(firebase, {
        debug: true,
        enableLogging: true,
        userProfile: 'users',
        ....
})
```

while `firebase` being an instance of RNFirebase (https://github.com/invertase/react-native-firebase) It fails.

**Comment by buraks** [comment]
Come to think of it, this probably shouldn't be an issue, but maybe a note can be put in the documentation. Anyone who wants to enable logging with RNFirebase they can do so when they initialize RNFirebase such as:

```javascript
const configurationOptions = {
  debug: true,
  persistence: true,
};

const firebase = RNFirebase.initializeApp(configurationOptions);
```

**Comment by prescottprue** [comment]
#186 adds this. It checks to make sure `enableLogging` is a function before calling it. Going to get it into `v2.0.0-beta.2`.
