### ISSUE TITLE
Can't import modules

### ISSUE THREAD

**Issue by arickconley** [prescottprue/react-redux-firebase#19]
ESLint is saying:

reduxReactFirebase not found in 'react-redux-firebase'

My import statement is:

import { reduxReactFirebase } from 'react-redux-firebase';

**Comment by prescottprue** [comment]
Both Should work:
```js
import { reactReduxFirebase } from 'react-redux-firebase' // preferred
import { reduxReactFirebase } from 'react-redux-firebase'
```

This is being used in quite a few projects that use `eslint` without seeing what you are describing.
Do you have a project you can share the repo of to reproduce? Can you possibly show your `.eslintrc`?

**Comment by prescottprue** [comment]
@arickconley Are you still seeing this or was it resolved?

If not, do you have a repo to reproduce, or the .eslintrc?

**Comment by arickconley** [comment]
It was resolved, I just deleted my node_modules folder and did a fresh npm install. Everything is working now. No idea what happened. 

Thank you!

**Comment by zgunz42** [comment]
I also have same problem using typescript
![Screenshot_2019-12-01-10-57-54-82](https://user-images.githubusercontent.com/11344981/69908951-b3bfd980-142d-11ea-92c2-f37f011cccfd.png)
