### ISSUE TITLE
databaseURL is a required config parameter for react-redux-firebase

### ISSUE THREAD

**Issue by impavidum** [prescottprue/react-redux-firebase#194]
I am using react-native-firebase and passing the RNFirebase instance into the compose function as stated in the docs. However, I am getting the error 'databaseURL is a required config parameter for react-redux-firebase'. From the docs it looks like this should be read in from the RNFirebase instance which pulls from GoogleService-Info.plist. Any help would be appreciated..

**Comment by csumrell** [comment]
Make sure you are using version 2.0.0 beta of react-redux-firebase. I had this problem yesterday only to realise the npm installed 1.4

**Comment by prescottprue** [comment]
@csumrell Is correct, react-native-firebase integration requires `v2.0.0-*`. Make sure to check the docs associated with the version you are using (dropdown on the left side of docs page).

Feel free to post if you have any issues while attempting to implement.
