### ISSUE TITLE
bug(react-native): sources for assign must be an object

### ISSUE THREAD

**Issue by prescottprue** [prescottprue/react-redux-firebase#198]
**Do you want to request a *feature* or report a *bug*?**  
Bug with `v2.0.0` on react-native

**What is the current behavior?**
When attempting to connect to nested paths (i.e. `todos/1` vs `todos`), the following error appears:

![sources_for_assign](https://user-images.githubusercontent.com/2992224/28228650-36d39534-6894-11e7-98a2-964905cb2d9b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

react-native example with nested path

**What is the expected behavior?**

It is expected that child path listening/setting is supported the same way that top level paths are

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Version: v2.0.0-* (happens on all pre-releases)
OS: iOS
browser: react-native
Previous Working Version(s): `v1.4.*` and `v1.5.*`

**Comment by koriner** [comment]
I am seeing this error as well when using react native and v2.0.0 - is there a workaround at the moment?

**Comment by prescottprue** [comment]
@koriner Have you tried `v2.0.0-beta.4`? #221 was an attempt to fix this issue (others reported it working).

Let me know if that is the version you are using so we can investigate further.

**Comment by koriner** [comment]
@prescottprue Hmm, I wasn't - but I just updated to beta 4 and I'm still getting the same error. What info do you need to help investigate?

**Comment by prescottprue** [comment]
@koriner Are you using react-native? If so did you try `watchman watch-del-all` and completely killing the server?

It is always most useful if you can provide a link to a repo where the issue is happening, but if some useful info would be:

* Environment or platform you building for (web, react-native, chrome-extension, etc)
* `firebaseConnect` and `connect` HOC settings that cause the issue to appear
* settings you have provided to `reactReduxFirebase` in your store creation
* Data format example or sample data in json format

**Comment by koriner** [comment]
@prescottprue Ahh - running that watchman command seems to have fixed it. Looking good now, thanks for the help!

**Comment by prescottprue** [comment]
@koriner Great to know. Just be sure to do that any time you are updating dependencies 😄
