### ISSUE TITLE
feat(profile): option to split user profile into private and public fields

### ISSUE THREAD

**Issue by marekolszewski** [prescottprue/react-redux-firebase#201]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**

Today, all user data generated by react-redux-firebase is stored in the `/users/<uid>/` path in Firebase. For certain applications, some of this data should be public while the rest of it should be private. For example, it's typical to keep email addresses and the providerData private from other users while keeping displayNames and photoUrls public. Unfortunately, because all the fields are in the same object, there is no way currently to specify security rules in Firebase to achieve such a security model, drastically limiting the use of this project for public sites that care about their users' privacy.

I propose converting the current user schema to look like this instead, which is recommended by other people [here](https://stackoverflow.com/questions/38921824/how-to-create-public-private-user-profile-with-firebase-security-rules).

```
user: { 
  private: {
    email,
    providerData
  },
  public: {
    displayName,
    avatarUrl
  } 
}
```
Since this would be a breaking change, perhaps it could be turned on with a flag somewhere. Alternatively, the desired schema could be specified by the library user somewhere.

**Comment by prescottprue** [comment]
@marekolszewski I am interested in working this feature into the roadmap.

That said, I think there are a few options for doing this now (used both in currently public sites):
1. Write security rules that only allow reading of email to be of the user which owns it:
```
{
  "rules": {
    "users": {
      "$uid": {

        "displayName": {
           ".read": true
        },

      }
    }
  }
}
```

**Comment by marekolszewski** [comment]
Thanks, this is a great suggestion. 

I'm also going to quickly look at your code to see how hard it would be to have both private and public parts in the user object. It would obviously be a little nicer to not have a cloud function.

**Comment by prescottprue** [comment]
@marekolszewski Totally understand not wanting the function, we currently opt for number 2 (just writing both on the client).

Interested to see what you come up with!

**Comment by marekolszewski** [comment]
@prescottprue On further review of this, I like your solution more than the one I suggested, namely using private and public fields inside the user object. While it's nice that this strategy would have allowed you to keep your keys in one place, it makes it impossible to query the public fields inside a users collection, without making the whole collection public.

**Comment by marekolszewski** [comment]
@prescottprue I'm thinking of writing a patch that changes `createUserProfile` to update two locations (private & public) at the same time using a multi-location update. We could add `userPublicProfile` and `publicUserFields` config options which specify the desired path for the public profile and which fields should be included in such an update.

By making this change, it will be possible for folks to have security rules that enforce that the shared fields under both paths are always the same, which makes for good practice when denormalizing data in firebase.

Let me know what you think and I can create a PR.

**Comment by prescottprue** [comment]
@marekolszewski Sounds great, would love to checkout the PR. This is a common pattern, so I am sure plenty of users will use a feature like this.

Going to close this issue since the originally mentioned pattern works for now (we can still reference it in any PRs that are made. Looking forward to the PR, Thanks!
