### ISSUE TITLE
bug(react-native): undefined is not a function (evaluating 'firebase.auth().getRedirectResult()

### ISSUE THREAD

**Issue by gitsad** [prescottprue/react-redux-firebase#204]
Hi guys,

I've recently updated react-redux-firebase and I've got this problem:
![2017_07_20_13 21 07](https://user-images.githubusercontent.com/13887724/28415188-f0f6f870-6d4e-11e7-8037-80beb8c8b212.png)

It is appearing when app is launched. I'm developing react-native app with ejected code and I was only testing it on Android. Any help would be appreciated.
versions:
react-redux-firebase@2.0.0-beta.3
react-native-firebase@2.0.4

**Comment by prescottprue** [comment]
@gitsad Have you tried doing `enableRedirectHandling: false` (mentioned in the [constants docs](http://docs.react-redux-firebase.com/history/v2.0.0/docs/api/constants.html#defaultconfig))? The intention for v2 was to make this `false` by default, but it has not yet been included in a release (I will check on this).

**Comment by gitsad** [comment]
Thanks! Everything seems to work.

**Comment by prescottprue** [comment]
@gitsad Thanks for letting me know. I will make sure that it is false by default for the next `v2.0.0` pre-release.
