### ISSUE TITLE
Firebase.login doesn't return an object in some cases

### ISSUE THREAD

**Issue by Shahor** [prescottprue/react-redux-firebase#206]
**Do you want to request a *feature* or report a *bug*?**  

Reporting a bug

**What is the current behavior?**

c.f. [this gist](https://gist.github.com/Shahor/26f7d824caf84d1bd1500d415c5fa726) the `firebase.login` method just returns the user `uid` when logging in instead of an object as stated in the documentation.

**What is the expected behavior?**

The `login` method should return an object as stated by the documentation.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

```
    "firebase": "^4.0.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.5",
    "react-redux-firebase": "^1.4.4",
    "react-router-dom": "^4.1.1",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
```

**Comment by prescottprue** [comment]
Released in [`v1.5.0-rc.4`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0-rc.4).

**Comment by marekolszewski** [comment]
@prescottprue The fix for this is nice, but it doesn't include the profile object as is included is social logins. Should it be?

Also, it appears that the bug still exists in v2.

**Comment by marekolszewski** [comment]
@prescottprue Perhaps more importantly, the user object is inside the 'user' field in the social case, so perhaps the fix should return `{ user: userData }` instead.

**Comment by prescottprue** [comment]
@marekolszewski You are correct that the signature should be the same. The issue with returning profile is that it would be need Yeah, the fix for that is going to be in the next [upcoming v2 release](https://github.com/prescottprue/react-redux-firebase/pull/229).
