### ISSUE TITLE
Get firebase data through action

### ISSUE THREAD

**Issue by kazupooot** [prescottprue/react-redux-firebase#21]
Is there a way to get data through action instead of doing it in container (`firebaseConnect`)?

**Comment by prescottprue** [comment]
I personally like using the [integration with `thunk`](http://react-redux-firebase.com/docs/recipes/thunks.html#example-thunk). If you don't want to use thunk, you can still follow that example, and just call `getFirebase()` within your action without passing it through thunk.

Does that answer your question?

**Comment by kazupooot** [comment]
Yep Im using thunk. So I will just use the `firebase.helpers.ref` method in action? Is this correct?

**Comment by prescottprue** [comment]
So the helpers are available to make it so you can call things directly, like so:

```js
getFirebase().ref('some/path')
getFirebase().set('some/path', { some: 'data' })
getFirebase().push('some/path', { some: 'data' })
getFirebase().update('some/path', { some: 'data' })
getFirebase().remove('some/path')
// also includes storage(), uploadFiles(), update()
```

**Comment by kazupooot** [comment]
Alright. Will try it. Thanks!
