### ISSUE TITLE
bug(updateProfile): updateProfile(updatedProfile) throws error

### ISSUE THREAD

**Issue by nguyenphucthanh** [prescottprue/react-redux-firebase#210]
hi guys, I have met an issue with latest v2. (Don't know if this is issue from previous version). 

When I call `getFirebase().helpers.updateProfile(updatedProfile)` it throws an error in try catch, the problem is in the core, it uses firebase `update()` function which returns a promise containing `snap` object then call `snap.val()`. But in firebase document, this promise should contain void.

https://firebase.google.com/docs/reference/js/firebase.database.Reference#update

Notes: It actually updated profile but it throws error because `snap` in undefined in promise.

**Comment by prescottprue** [comment]
Closing since this is released in both active `next` and `canary` versions
