### ISSUE TITLE
feat(examples): securing firebase roles and users collection example

### ISSUE THREAD

**Issue by cometta** [prescottprue/react-redux-firebase#211]
Any example of setting rules when using roles from http://docs.react-redux-firebase.com/history/v2.0.0/docs/recipes/roles.html  ?

> 
{
  "rules": {
    ".read": true,
    ".write": true
  }
}

Is there any security concern for using profileFactory to auto assign role to user upon login with firebase? Since it is a client side codes, what if the user change the code and put role=admin ?

**Comment by prescottprue** [comment]
@cometta Yes, this is meant mostly just as an example. In production scenarios, I personally have used either an external server or a Firebase Function to handle this.

It would make sense to add something about this to the docs, and maybe even point to a simple example of doing this in the fashion I mentioned above.

**Comment by cometta** [comment]
@prescottprue an example would be good how you use firebase function to add role=user to newly login user.

**Comment by prescottprue** [comment]
If you start with the [functions-samples email users quickstart](https://github.com/firebase/functions-samples/tree/master/quickstarts/email-users), you can easily modify it to do this based on an auth event.

Have the function (triggered by auth events) load a list of "approved users" from your DB (that way it can be populated by an admin UI of yours or through the Firebase console). Your list of users should be something like:

```js
{
  "approvedUsers": {
    "123SomeKey": {  // can be push keys
      "email": "someone@email.com" // approved person's email
    },
}
```

From there if the user is a new user and does not already have or `admin: true`, if they are in the list of approved users, then you update their user object with `admin: true`. Something like:

```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp(functions.config().firebase);

/**
 * Makes users admin's if their email is in the approvedUsers list
 */
exports.makeAdminIfApproved = functions.auth.user().onCreate(event => {
  const user = event.data; // The Firebase user.

  const email = user.email; // The email of the user.
  const displayName = user.displayName; // The display name of the user.
  return checkIfApproved(email)
    .then((approvedUserSnap) => {
        if (approvedUserSnap.val()) {
          // User is approved
          return admin.database().ref(`users/${user.uid}`).once('value')
            .then((userSnap) => {
              if (userSnap.val()) {
                if (userSnap.val().admin) {
                  console.log('user is already an admin')
                } else {
                  console.log('user account exists, but is not an admin')
                  return userSnap.ref.update({ email, displayName, admin: true })
                }
              } else {
                console.log('creating first user account')
                return userSnap.ref.update({ email, displayName, admin: true })
              }
            })
        }
        return approvedUsersSnap
    })
});

/**
 * Check if email is in approved list. UID is not used becuase there would be
 * no way to pre-approve a user before they have ever signed up.
 * @param  {String} email - Email of user to check for approval
 * @return {Promise} Resolves with user
 */
function checkIfApproved(email) {
  return admin.database().ref('approvedUsers')
    .orderByChild('email')
    .equalTo(email)
    .then((usersSnap) => {
       if (usersSnap && usersSnap.hasChildren()) {
         return getFirstChild(usersSnap)
       }
       return null
    })
}


/**
 * Get first child from Firebase snapshot
 * @param  {firebase.database.DataSnapshot} snap - Snapshot
 * @return {Object} First child
 */
function getFirstChild(snap) {
  let user = {}
  usersSnap.forEach((userSnap) => {
    user = userSnap.val()
    return false // exit after first
  })
  return user
}
```

Then you can use some rules to protect everything until you have `admin: true` something like:

```json
{
  "some": {
     ".read":"auth !== null && data.child('users').child(auth.uid).hasChild('admin') && data.child('users').child(auth.uid).child('admin').val() === true",
      ".write":"auth !== null && data.child('users').child(auth.uid).hasChild('admin') && data.child('users').child(auth.uid).child('admin').val() === true",
  },
  "users": {
     ".read": "auth !== null",
     ".write": "auth !== null && $uid === auth.uid"
  }
}
```

These snippets aren't necessarily all you will need, but they are based on code from a few real applications, so hopefully they get you on the right track.
