### ISSUE TITLE
[v2.0.0] bug(listeners): deep path listeners not working

### ISSUE THREAD

**Issue by marekolszewski** [prescottprue/react-redux-firebase#219]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When subscribing to multiple paths from Firebase, each reactReduxFirebase/SET action overwrites the firebase.data state entirely, wiping away any previous state from any other subscriptions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Subscribe to two paths with firebaseConnect and view the state at each reactReduxFirebase/SET action.

**What is the expected behavior?**
The data should be merged with the previous state.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
I noticed this when migrating my working 1.5 code to 2.0.0-beta.3.

**Comment by marekolszewski** [comment]
Upon some more investigation, it looks like this only fails when subscribing to multi-level paths. E.g. subscribing to both /users and /tasks works, but not to /public/users and /public/tasks.

**Comment by prescottprue** [comment]
Fix from #221 included in [v2.0.0-beta.4](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.4) release. Thank you for the contribution!
