### ISSUE TITLE
firebaseConnect creates massive empty arrays when path ends in a large number

### ISSUE THREAD

**Issue by levithomason** [prescottprue/react-redux-firebase#228]
**Bug**  

**What is the current behavior?**

When passing a path which ends in a number, `firebase.data` contains an array of length `number` filled with `undefined` where the last item in the array is the database leaf.

```jsx
firebaseConnect([`/analyses/2002938377`])

console.log(this.props.firebase.data)
```

![image](https://user-images.githubusercontent.com/5067638/29106588-a5eb761c-7c8a-11e7-9f32-3f0ee4d6f1df.png)

Removing the `id` returns the correct result.  I get all my `analyses` from firebase keyed by `id`.  There are maybe 50 leafs by id at `/analyses`:

```jsx
firebaseConnect([`/analyses`])

console.log(this.props.firebase.data)
```

![image](https://user-images.githubusercontent.com/5067638/29106642-fcbcb5dc-7c8a-11e7-85c1-d1afcfb3cb2d.png)

**What is the expected behavior?**

```js
firebaseConnect([`/analyses/2002938377`])

this.props.firebase.data.analyses['2002938377'] === { ...a single db leaf }
```

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Latest Chrome
Mac OS Sierra
`react` `^15.5.4`
`redux` `^3.6.0`
`react-redux` `^5.0.5`
`firebase` `^4.2.0`
`react-redux-firebase` `2.0.0-beta.4`

Worked in `1.*` with `dataToJS`.

**Comment by levithomason** [comment]
I should note, this actually crashes the browser tab.

**Comment by prescottprue** [comment]
@levithomason There is an update coming in [`v2.0.0-beta.5`]() that I believe fixes this (going to test to confirm).

**Comment by levithomason** [comment]
Looking forward to it.  I will give it a go once released.

**Comment by levithomason** [comment]
Version `2.0.0-beta.5` seems to have fixed the issue with the db leaf coming back as an array.  I now get the db leaf I was expecting.

However, the browser tab still freezes and eventually crashes.  Still investigating what is causing that.

**Comment by levithomason** [comment]
False positive on the array bug fix.  When connecting to a path that ends in a number, the data retrieved is still an array of size `number`:
```js
firebaseConnect([`/analyses/2002938377`])

console.log(this.props.firebase.data.analyses['2002938377'])
```
![image](https://user-images.githubusercontent.com/5067638/29238499-b7750322-7eeb-11e7-98b2-473b69a8593d.png)

**Comment by prescottprue** [comment]
@levithomason Thanks for letting me know. I will look into it further.

Going to be busy this weekend so if anyone looks into it, feel free to create a PR.

**Comment by prescottprue** [comment]
It seems that this may be due to the internals of lodash's `set`. Open to PRs if anyone has time, but I won't be able to look more until later.

**Comment by levithomason** [comment]
I'm very familiar with lodash and it's shorthand but I'm not quite sure where to look in `react-redux-firebase`.  If you could point to a suspect file or two, I can likely fix it.

**Comment by levithomason** [comment]
See #248 for the fix.

**Comment by levithomason** [comment]
Seems changing the base branch breaks the auto close feature? Closing as fixed.
