### ISSUE TITLE
feat(examples): lazy query example

### ISSUE THREAD

**Issue by mike623** [prescottprue/react-redux-firebase#232]
is HOC (ie. `firebaseConnect`) the only trigger to query? I have a situation which require to query by user's button click. I am expecting to start the query using `this.prop.firebase`. Does it make sense?

**Comment by li-xinyang** [comment]
From my understanding, when you query a data-souces inside `firebaseConnect` which bind the data-source to your components `props`. You do not need to query these data again, update them and the UI will get re-rendered.

**Comment by prescottprue** [comment]
@li-xinyang Queries in `firebaseConnect` are only created/destroyed if the array returned to `firebaseConnect` is has a different value than the last time it was run.

That means that the case of props being used in a query path, the queries will only be created and destroyed if the props change.

**Comment by prescottprue** [comment]
@li-xinyang Does this solve your use case?

**Comment by li-xinyang** [comment]
@prescottprue Yes, this does solve my use cases. Thanks for asking.

**Comment by mike623** [comment]
No, but it does not solve my case. My question is: can I create a query in my own function inside class like `handleButtonClick` instead of query on HOC

**Comment by prescottprue** [comment]
@mike623 Yes, `watchEvent` can be used externally (even thought it is an internal function) if you pass dispatch to it.

An example will be coming soon.

**Comment by mike623** [comment]
@prescottprue Thanks. will have a try

**Comment by prescottprue** [comment]
A `watchEvent` example has been added with two flavors:

* [basic](https://github.com/prescottprue/react-redux-firebase/blob/v1.5.1/examples/snippets/watchEvent/Basic.js) - simple usage of `watchEvent`
* [recompose](https://github.com/prescottprue/react-redux-firebase/blob/v1.5.1/examples/snippets/watchEvent/Recompose.js) - watchEvent usage simplified with `recompose`

**Comment by mike623** [comment]
Is the snippet different on 2.0.0?

**Comment by prescottprue** [comment]
@mike623 Only handling of state is different (i.e. no `toJS` functions needed). You can still call `watchEvent`.

The example will soon be ported over to v2
