### ISSUE TITLE
Query with Absolute Path get Full Data Set Instead of Entry Detail

### ISSUE THREAD

**Issue by li-xinyang** [prescottprue/react-redux-firebase#236]
Screenshot below is the data structure lives in Firebase,

<img width="300" alt="screen shot 2017-08-14 at 21 55 33" src="https://user-images.githubusercontent.com/3349406/29274726-55deafb2-813b-11e7-8f8a-3b800d7b196c.png">

I would like to retrieve particular account details using an absolute account path ( `/accounts/${uid}/${repositoryId}/`), however, when I try to log the returned data. It is actually the full data set under node `accounts` (see screenshot below).

```js
@firebaseConnect((props, firebase) => {
  const { match: { params: { repositoryId } } } = props
  const uid = firebase._.authUid
  const accountDetailPath = `/accounts/${uid}/${repositoryId}/`
  return [accountDetailPath]
})
@connect(mapStateToProps)
```

<img width="837" alt="screen shot 2017-08-14 at 21 57 44" src="https://user-images.githubusercontent.com/3349406/29274823-b08dc8da-813b-11e7-840c-e18c8663db5e.png">

**What I expected** is one account entry details ONLY like something below,

```js
-KrGpTHLMDGuCgEFHY_d: {name: "", note: "", owner: "VXjqmhS8TLT1hUTdCkOXQp6qZ742"}
```

When I use the same code to retrieve all the accounts under particular `uid`, it actually works.

```js
@firebaseConnect((props, firebase) => {
  //FIXME: Seems there is a way to pass `uid` to `firebaseConnect` here
  const uid = firebase._.authUid
  return [{ path: `/accounts/${uid}` }]
})
@connect(mapStateToProps)
```

<img width="838" alt="screen shot 2017-08-14 at 22 01 51" src="https://user-images.githubusercontent.com/3349406/29274997-38f3826e-813c-11e7-8856-9dbf3dcb7d23.png">

**Comment by prescottprue** [comment]
What does your mapStateToProps function look like? The path which you gather the data from redux must match the listener path.

**Comment by li-xinyang** [comment]
Hi @prescottprue, thanks for the response.

```
const mapStateToProps = state => {
  const { firebase: { data } } = state
  return { data }
}
```

This is my `mapStateToProps` function, I have to dynamic fields, so you mean I should do something like below?

```
const mapStateToProps = state => {
  // get `uid` and `account` id
  const { firebase: { data } } = state
  return { accountDetail: data.account[uid][accountId] }
}
```

**Comment by prescottprue** [comment]
@li-xinyang Correct. With your first function you are passing all firebase data from redux into your component under the prop `data` (which doesn't seem to be what you want). You second function should work as expected if I am correctly understanding the data structure.

Yup! Always glad to answer questions. If you have more questions along the way of implementation I am usually faster to respond [over gitter](gitter.im/redux-firebase/Lobby).
