### ISSUE TITLE
Support for multi location updates

### ISSUE THREAD

**Issue by mindtricksdev** [prescottprue/react-redux-firebase#238]
I would like to use firebase multi location update feature using react-redux-firebase internal instance.
https://firebase.googleblog.com/2015/09/introducing-multi-location-updates-and_86.html

Note that there's a simple workaround but it would be best if this was supported out of the box.

Instead of 
`
firebase.database().ref().update(multipleLocationUpdates)
`

it would be nice if:
`
firebase.update(multipleLocationUpdates);
`

I am using version 2.

Thanks

**Comment by prescottprue** [comment]
@mindtricksdev Update works the same in `v2`, meaning you must pass a string as the first argument to update (the path where to update). Meaning updating multiple paths looks like so:

```js
firebase.update('some', multipleLocationUpdates)
// or if you want it from the root path
firebase.update('', multipleLocationUpdates)
```

**Comment by mindtricksdev** [comment]
Actually, that throws an error
`Error: Reference.child failed: First argument was an invalid path = "". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"`

The paths to update are keys in `multipleLocationUpdates`.

**Comment by prescottprue** [comment]
There was a typo in my last comment. I actually meant for you to pass `'/'` as the path:

```js
firebase.update('some', multipleLocationUpdates)
// or if you want it from the root path
firebase.update('/', multipleLocationUpdates)
```

**Comment by mindtricksdev** [comment]
I tested this and it works. Looks good 👍 

Thanks!
