### ISSUE TITLE
Populate Profile Parameters

### ISSUE THREAD

**Issue by toytonic** [prescottprue/react-redux-firebase#24]
Hi,
I am currently playing around with your lib. Thanks for the effort,  it looks great.

I've got one question about `populate` which I wasn't able to achieve. Consider the following structure:

```json
{
  "todos": {
    "abcdef": {
      "done": false,
      "text": "example todo"
    }
  },

  "user": {
    "todos": {
      "abcdef": true
    }
  }
}
```

Can I use `populate` to query the user todos and populate them with the referenced todos?

**Comment by prescottprue** [comment]
The short answer is that currently, they pattern you have shown is not supported. That said, there is [`profileParamsToPopulate` ](http://react-redux-firebase.com/docs/populate.html#profile-parameters) available in config to populate single parameters.

I have added list population to the roadmap, and it should hopefully make it into `v1.2.0`. Planning on leaving this issue open until the patten you have listed is supported.

**Comment by prescottprue** [comment]
If you use `v1.2.0-beta` you should be able to populate your list of `todos` by passing this to your config:

```js
{
  userProfile: 'users',
  profileParamsToPopulate: [
    'todos:todos' // string notation
     // OR
    // { child: 'todos', root: 'todos' } // object notation
  ]
}
```

Population is detailed in [the populate section of the docs](http://react-redux-firebase.com/docs/populate.html#profile-parameters). Config capabilities/details are in [the compose section of the docs](http://react-redux-firebase.com/docs/api/compose.html).

Let me know if this does not solve your use case.

**Comment by toytonic** [comment]
Yes. This is basically what i was looking for. Thanks for the update.

What would be super nice if this would become a general feature for queries and not only for the user profile ;)

**Comment by prescottprue** [comment]
@toytonic That is already the case, and the major changes in the `v1.2.0-*` have been improvements to the populate API 🤓.

Going to close this issue. Feel free to open a new issue or create a PR for any changes in populate syntax/functionality you would like to see.
