### ISSUE TITLE
Connecting to a single object in firebase

### ISSUE THREAD

**Issue by dchersey** [prescottprue/react-redux-firebase#242]
I'm using a passed-in property to connect a component to a single user in my firebase database, and I'm running into some conceptual(?) problems using firebase connect. 

```javascript
@firebaseConnect((props, fb) => {
  if (props.user) {
    return ["/users/" + props.user.name];
  } else {
    return [];
  }
})
@connect(({ firebase: { data: { users } } }) => ({
  users
}))
```

The above code seems to populate firebase data with a users collection of all users (granted, there is another component I have that connects to '/users' so perhaps this is why, but I cannot seem to extract a reference to the specific user I am passing to `@firebaseConnect`. 

Furthermore, I get the error `TypeError: In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant.`. which usually means I am connecting to an attribute not an object ... yet my database has the value `{count: 1}` at the above path, and it is also visible when I inspect props.

![screenshot 2017-08-18 11 09 56](https://user-images.githubusercontent.com/800393/29465025-cc3a3740-8405-11e7-9ce0-80742a1d3121.png)

My intention is to get the count attribute of a specific user to be linked to redux through firebase; i.e. `"/users/David Hersey/count"` so I can update some text when it changes. This will be replaced by a list of todos after I get this working.

**Comment by prescottprue** [comment]
Your listeners seem correct, but your connect function must then grab the data from redux that you want.
```jsx
@firebaseConnect((props, fb) => {
  if (props.user) {
    return ["/users/" + props.user.name];
  } else {
    return [];
  }
})
@connect(({ firebase: { data: { users } } }, props) => ({
  user: users[props.user.name]
}))
```

**Comment by dchersey** [comment]
Ah, yes ... still wrapping my brain around arrow function object literals :) 

That code did the trick, with the addition of a null check for the invocation with my props (from parent) and no firebase state yet. 

```javascript
@connect(({ firebase: { data: { users } } }, props) => ({
  user: users ? users[props.user.name] : null
}))
```

Feeling nostalgic for ruby/coffee's safe navigation operator but liking ES6 more than coffee script :)

**Comment by prescottprue** [comment]
Great 👍 

You can also use the `isLoaded` and `isEmpty` helpers

**Comment by dchersey** [comment]
Ah, that's what they are for :)

revised code
```javascript
@firebaseConnect((props, fb) => {
  if (props.userName) {
    return [`/users/${props.userName}/count`];
  } else {
    return [];
  }
})
@connect(({ firebase: { data: { users } } }, props) => ({
  user: isLoaded(users) ? users[props.userName] : null
}))
```
