### ISSUE TITLE
signInWithCustomToken API inconsistent?

### ISSUE THREAD

**Issue by zhang-z** [prescottprue/react-redux-firebase#244]
I'm using react-native + react-redux-firebase. After calling `this.props.firebase.login({token: xxx})`, I got `@@reactReduxFirebase/LOGIN_ERROR`.

Inspecting the code, I found the problem is here: https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/auth.js#L328

The code is expecting `userData` to be a JSON **string**, which contains `stsTokenManager. accessToken`. But in my project, the `userData` is actually a JSON **object** as below:

```
{
  "displayName": null,
  "refreshToken": "......",
  "providerId": "firebase",
  "uid": "......",
  "emailVerified": false,
  "providerData": [],
  "email": null,
  "isAnonymous": false
}
```

Why is it behaving differently in my project?

**Comment by prescottprue** [comment]
It is not expecting it to be a JSON *string*, it is a JSON *object` (which is why there is the destructuring), then `accessToken`, which is a *string* is decoded using JWT decode.

What does the login error say? You should be able to check in state through redux devtools.

**Comment by zhang-z** [comment]
@prescottprue , thank you for the quick reply.

In my project, I saw this action been dispatched:
```
{
  type: '@@reactReduxFirebase/LOGIN_ERROR',
  authError: {
    line: 95378,
    column: 57,
    sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false'
  }
}
```

In my bundled JS file:
```
    if (method === 'signInWithCustomToken') {
      var _userData$toJSON = userData.toJSON(),    // line 95378
          accessToken = _userData$toJSON.stsTokenManager.accessToken,
          uid = _userData$toJSON.uid;
```
If I'm not wrong, it's the transformed code of:
```
const { stsTokenManager: { accessToken }, uid } = userData.toJSON()
```

I inserted debugging code to `console.log(typeof userData)`. Result was `object` rather than `string`, so `toJSON()` failed. If I changed the line to `var _userData$toJSON = userData`, it passed. But the next line `accessToken = _userData$toJSON.stsTokenManager.accessToken` then throw error. As pasted in my question, my `userData` doesn't contain `stsTokenManager`

**Comment by prescottprue** [comment]
`toJSON()` should be a method available on the object that returns from Firebase in that situation. It seems that this is a difference between the react-native-firebase API and the Firebase JS SDK API.


It would be good to open an issue on their end so that we can see if there is a reason that the API is different.

**Comment by prescottprue** [comment]
@zhang-z The authors of [react-native-firebase](http://invertase.io/react-native-firebase/#/) have confirmed that will not be changing the API to directly match the Firebase API.

It seems that we should use [`getIdToken`](https://firebase.google.com/docs/reference/js/firebase.User#getIdToken) instead. Will update soon.

**Comment by zhang-z** [comment]
My mistake, there was nothing wrong with react-native-firebase's `toJSON`, the root cause is still `stsTokenManager`.

As a workaround, I will use `this.props.firebase.auth().signInWithCustomToken(token)` to replace `this.props.firebase.login({token})` before the next version is released. Thank you for your efforts.

**Comment by prescottprue** [comment]
[`v2.0.0-beta.7`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.7) has been released, and it no longer automatically decodes the token to create the profile (left to be handle in app through `profileFactory`).

Let me know if this does not function as you expect.
