### ISSUE TITLE
Login API document outdated?

### ISSUE THREAD

**Issue by zhang-z** [prescottprue/react-redux-firebase#245]
I tried to Custom Token login by `this.props.firebase.login(tokenStr)` (react-redux-firebase@2.0.0-beta.5). It doesn't work for me. Instead, I have to `this.props.firebase.login({token: tokenStr})`. Is the [API doc](http://docs.react-redux-firebase.com/history/v2.0.0/docs/auth.html#logincredentials) not updated?

**Comment by prescottprue** [comment]
@zhang-z Looking into that now, thanks for reporting.

**Comment by prescottprue** [comment]
Updated and published along with [`v2.0.0-beta.6`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.6).
