### ISSUE TITLE
feat(examples): redux-offline example

### ISSUE THREAD

**Issue by codekiln** [prescottprue/react-redux-firebase#253]
I love how there are so many integration instructions posted in the docs. One integration that I would love to see posted in the docs is [`redux-offline`](https://github.com/jevakallio/redux-offline). Here's [a discussion of redux-offline in the firebase library's github issue related to offline-first PWAs](https://github.com/firebase/firebase-js-sdk/issues/17#issuecomment-312384837).

**Comment by prescottprue** [comment]
As you can read in the provided link, firestore is now the preferred way to handle offline stuff, and `v2.*.*` has support for firestore through `redux-firestore`.

With that in mind, going to leave it with the [`redux-persist` example](http://docs.react-redux-firebase.com/history/v2.0.0/docs/integrations/redux-persist.html) for now. Also, just as a side note, I think that [`redux-persist`](https://github.com/rt2zz/redux-persist) is similar and little more up to date (or at least is at the time of this comment).
