### ISSUE TITLE
feat(login): resetBeforeLogin option to enable/disable resetting of auth and profile on login

### ISSUE THREAD

**Issue by zhang-z** [prescottprue/react-redux-firebase#254]
I call `firebase.login({token: token})` every time my app starts, which means `login()` could be called while the user is already logged in (yup this point can be improved, but the potential issue still exist). In this case, `store.firebase.auth` got reset to `{isLoaded: true, isEmpty: true}`. Firebase actions were dispatched in this sequence:
1. AUTHENTICATION_INIT_STARTED
2. AUTHENTICATION_INIT_FINISHED
3. LOGIN  -- already logged in, action contains `auth: {...}`
4. LOGIN_ERROR  -- dispatched by `login()`, see [here](https://github.com/prescottprue/react-redux-firebase/blob/v2.0.0/src/actions/auth.js#L280)

I feel the logic of 4th action is not quite right.

To replicate this issue, you can try to run `login` twice -- 2nd call fired after 1st call finished.

**Comment by prescottprue** [comment]
LOGIN_ERROR is run with `null` so that it empties out any login errors that could have occurred from previous login attempts.

It would probably be best to check for auth before you re-run `firebase.login`.

**Comment by zhang-z** [comment]
Yup, I will add the check in my project.

> make a different action that only clears the error, but does not empty the rest of the auth state

This sounds good. Thanks.

**Comment by marekolszewski** [comment]
There are times when you might want to log the user in a second time. I believe I sometimes do that when Firebase requires a fresh login to change a user's email or password.

**Comment by prescottprue** [comment]
@marekolszewski In that case, when logging in the second time, wouldn't you want the auth/profile to be removed since it is new data?

**Comment by marekolszewski** [comment]
@prescottprue Unfortunately, in this case, no. Removing auth redirects the user away from the settings page because they are briefly no longer logged in.

I think I solved the issue on my end by using a login popup when someone is accessing a page behind a login wall, but others might still have this issue. I think firebase has a special re-login flow, but I didn't look into it too much. Maybe we can expose that through react-redux-firebase.

**Comment by prescottprue** [comment]
@marekolszewski and @zhang-z What are your thoughts on a config option (something like `emptyBeforeLogin: false`) to control this?

In v1 it would have to remain `true` by default to remain backwards compatible.

I think in v2 it should be `false` by default, but open to input on this front.

**Comment by zhang-z** [comment]
`resetBeforeLogin` sounds a better name over `emptyBeforeLogin`. Thanks!

**Comment by prescottprue** [comment]
@zhang-z Glad you saw the new name, was going to mention that. The update should be released soon, but you can try it now on [the `v2.0.0-beta.8` branch](https://github.com/prescottprue/react-redux-firebase/tree/v2.0.0-beta.8).

**Comment by prescottprue** [comment]
Released `resetBeforeLogin` option in [`v2.0.0-beta.8`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.8). Let me know if it does not work as expected :).
