### ISSUE TITLE
bug(populate) Population does not work for 'once' queries

### ISSUE THREAD

**Issue by marekolszewski** [prescottprue/react-redux-firebase#256]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When marking a query as type: 'once', population ceases to function.

**What is the expected behavior?**
Population should work the same as 'on' queries.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
I noticed this on v2, but looking at the code, this seems to be an issue in v1 as well.

**Comment by prescottprue** [comment]
Support for populating once queries was added to the [`v2.0.0-beta.8` branch](https://github.com/prescottprue/react-redux-firebase/tree/v2.0.0-beta.8). Would you mind giving it a try by before I release by testing locally [with npm linking](http://react-redux-firebase.com/docs/contributing.html#npm-linking)? Still need to write some more comprehensive tests.

If it works as expected, it will most likely be added to `v1.*.*` versions as well.

**Comment by marekolszewski** [comment]
@prescottprue Sure, will try to take a look later today. Awesome work!

**Comment by prescottprue** [comment]
Let me know if it doesn't work as expected.

**Comment by marekolszewski** [comment]
@prescottprue Looks like it works great! Thanks!!!
