### ISSUE TITLE
bug(query): remove does not update state when query is applied

### ISSUE THREAD

**Issue by nehvaleem** [prescottprue/react-redux-firebase#257]
**Do you want to request a *feature* or report a *bug*?**  

*bug*

**What is the current behavior?**

I am facing an issue when events won't fire when I delete element from my database when firebaseconnect using queryParams.  Data in redux is refreshed when creating new data, but upon deletion it stays the same.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

```javascript
export default compose(
  connect(
    ({ firebase, router }) => ({
      auth: firebase.auth,
    })
  ),
  firebaseConnect((props, firebase) => {
    return [
      { path: `/organizations`, populates, queryParams: [ `orderByChild=members/${props.auth.uid}`, 'equalTo=true' ] }
    ]
  }
  ),
  connect(
    ({ firebase, router }) => ({
      organizations: firebase.data.organizations,
      isRequesting: firebase.requesting.organizations,
      location: router.location
    })
  )
)(Organizations)
```

and when I am adding new organization it works fine, eg.
```javascript
createOrganization(data) {
    this.props.firebase.pushWithMeta('organizations', {
      name: data.name,
      members: {
        [this.props.auth.uid]: true
      },
      owners: {
        [this.props.auth.uid]: true
      },
      projects: []
    }).then((snapshot) => {
      console.log('data pushed', snapshot);
      // this.refs.createOrganizationForm.refs.formsy.reset();
      this.refs.createOrganizationForm.formsyForm.reset();
    });
  }
```
When creating new organization data in redux is refreshed. 

But when I try to delete one, the data in firebase redux isn't refreshed (until I refresh the page).

```javascript
deleteOrganization(event, organizationId) {
    event.preventDefault();

    this.props.firebase.remove(`organizations/${organizationId}`).then((snapshot) => {
      console.log('organization removed', snapshot);
    });
  }
``` 

**What is the expected behavior?**

Data in firebase redux key should be updated when deleting.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
```json
"react-redux": "^5.0.6",
"react-redux-firebase": "^2.0.0-beta.6",
"react-router-dom": "^4.1.2",
"react-router-redux": "^5.0.0-alpha.6",
"react-scripts": "1.0.10",
"react-test-renderer": "^15.6.1",
"react-three-renderer": "^3.2.1",
"redux": "^3.7.2",
"redux-devtools-extension": "^2.13.2",
"redux-saga": "^0.15.6",
```

I think that issue is browser/os independent.

**Comment by prescottprue** [comment]
Going to try to reproduce myself, but if the query is attached at that path, then removing data should come through the listener.

Side Note:

Not sure it is related, but I don't believe you can do `orderByChild=members/someId`? From what I understand, [orderByChild only accepts a single key(not a nested key)](https://firebase.google.com/docs/reference/js/firebase.database.Query#orderByChild).

**Comment by nehvaleem** [comment]
Thanks, let me know if I can provide some additional info. Creating data at given path works, but removing doesn't.

In terms of nested keys I think there is an option :) First of all it works for me, and secondly https://firebase.googleblog.com/2015/09/introducing-multi-location-updates-and_86.html (section about **_Ordering queries by deep paths_**)

**Comment by gwitteveen** [comment]
Facing a similar issue

```
const FILESPATH = 'media';

export default compose(
firebaseConnect([
    FILESPATH
]),
connect(
  ({  nav, mediaselector:{ itemsSelected, trash }, firebase: { data: { media }} }) => ({
      media,
      nav,
      itemsSelected,
      trash,
  })
))(Ads)
```
When a file is uploaded/key is added, 'media' updates. When a file/key is removed from 'media', the key itself is removed from ...firebaseio.com, but media does not update. 

Here is where it gets interesting: when I first delete a key (media doesn't update) and then add a key, media does update but **both the deleted key and new key** are in media.

When all keys are removed from media, media does update and does not contain any keys as expected. 

```
    "react-redux": "^4.4.5",
    "react-redux-firebase": "^2.0.0-beta.7",
```

**Comment by prescottprue** [comment]
This seems to be due to recent additions of merging logic. The current plan is to add an action that will be fired when calling delete at a certain path.

**Comment by prescottprue** [comment]
Can anyone confirm they are still experiencing this? If so, this can be reopened, but going to close for now.

I am no longer able to replicate through calling `remove` or through removing directly on the database. Going to add a test that checks this case

**Comment by nehvaleem** [comment]
@prescottprue to be honest I haven't checked this very precisely but I've noticed that in my case problem seems to be gone since beta.8 or later. I will let you know if the problem resurface.

**Comment by prescottprue** [comment]
@nehvaleem Thats right about where I was expecting it would have been caught too. Great to know, thanks for the update.

**Comment by sshadmand** [comment]
Just implemented a remove action and experiencing the same problem. Calling `ref.child(...).remove()` is not updating the data saved to firebase.data. 

```
    "react-redux": "^5.0.6",
    "react-redux-firebase": "^2.0.0-beta.8",
```

**Comment by prescottprue** [comment]
@sshadmand You need to update 😄 . We are on `2.0.0-beta.14` now. You can switch your package file to `"react-redux-firebase": "next"` if you always want the most up to date version of 2.0.0 (until it is stabilized and released on `latest`).

**Comment by sshadmand** [comment]
Worked. Thanks @prescottprue!

**Comment by KubaKocieba** [comment]
I'm still havong the problem in ver 2.0.4 :(

**Comment by prescottprue** [comment]
@KubaKocieba We may want to open an new issue for what you are mentioning with steps to reproduce. Not sure it is the same thing being mentioned here since deleting works.

Using `remove` shouldn't be affecting listeners attached by `firebaseConnect` - even if the item is deleted on which you have a listener, the data should become `null` not remove the listener.

**Comment by KubaKocieba** [comment]
@prescottprue , just please tell me how should I describe the problem and way to reproduce.

**Comment by prescottprue** [comment]
@KubaKocieba Create a new issue describing what you are seeing, what you expect to see, and steps to make it happen as [described in the issue template](https://github.com/prescottprue/react-redux-firebase/blob/master/.github/ISSUE_TEMPLATE.md).

It can take the form of a codesandbox, codepen, code snippets, etc.

**Comment by KubaKocieba** [comment]
ok, I prepared some code in codesandbox:
https://codesandbox.io/s/mym9p5jo99
Firebase config is empty there now.
Seems that everything is fine when setting config, though.
It might be my application's code fault, so I'm sorry for disturbing, 
I'll try to find my mistake.

**Comment by towfiqi** [comment]
@prescottprue Having the same issue. After loading the app, when I add an item, it works fine. But removing the newly added items doesnt update the state. even though the item is being removed from Firebase successfully. 
If I reload the app and remove the item, and the state is updated perfectly. So removing dynamically added new items does not update the state.

I tried your suggestion of `merge="false"` did not work:

```
firebaseConnect((props, firebase) =>  props.auth.uid && [{ path: `/playlists/${props.auth.uid}/`, merge: false }] )
```

**Comment by towfiqi** [comment]
Ok. Just set the `dispatchRemoveAction ` to `true` in config and its working fine.

**Comment by prescottprue** [comment]
`merge: false` is not yet supported. The merge parameter is an example of what the syntax may be in the future to support this.

Using `dispatchRemoveAction` or getting data from `ordered` instead of `data` should get things to update as you expect.

**Comment by towfiqi** [comment]
@prescottprue Scott, sorry to bother again. just moved from firebase to firestore and used `firestoreConnect` instead of `firebaseConnect` and same issue occurs. `dispatchRemoveAction` set to true, but doesnt solve it. Removing item doesnt update the state. Any help? Thanks.

**Comment by prescottprue** [comment]
@towfiqi `null` means that the data is loaded and does not exist. When the value is `undefined` that means it hasn't been loaded at all. For folks that have a listener attached on a path that they are deleting, they would see `isLoaded(someProps) === false`, where you would want to see it equal to `true` since you do know it is loaded, that path is just empty. With a listener attached, you would then see a flash of it going from `value -> undefined -> null`.

Open to ideas, just want to make sure we aren't breaking functionality that others are depending on.

**Comment by towfiqi** [comment]
Thanks. I understand.  I am counting the item counts like this in several places through the app: `Object.keys(data).length`.  I guess i will filter out the data with `null` value or use `getVal`.

Maybe thats whats causing issue number 1 too. (deleting a just created item is not removed). Which strangely not occurring any more. If it does, I will let you know with more info. Thanks

**Comment by prescottprue** [comment]
@towfiqi If you are counting items you could do `Object.keys(data).map(item => !!item).length` or you could use lodash's `compact`: `compact(Object.keys(data).length)`.

Also, something to note: If you are counting items, and/or mapping over them, it may be easier to use `state.firebase.ordered` (an ordered array of objects) instead of `state.firebase.data` (object by keys). That way you wouldn't be doing `Object.keys` at all, and the `data.length` would be correct.

**Comment by towfiqi** [comment]
Yeah thats what I was thinking of doing to filter the data. And since I am using firestore, I am not cannot use `state.firebase.ordered`. Thanks.

**Comment by prescottprue** [comment]
@towfiqi There is also `state.firestore.ordered` (since redux-firestore is setup the same way as react-redux-firebase). If you are filtering client side after the query make sure to use a selector.

**Comment by towfiqi** [comment]
Thanks it works! :)
