### ISSUE TITLE
bug(docs): redux-observable recipe link broken

### ISSUE THREAD

**Issue by pzmudzinski** [prescottprue/react-redux-firebase#271]
Docs are pointing to dead link: https://github.com/prescottprue/react-redux-firebase/blob/master/docs/recipes/redux-observable.md.

**Comment by prescottprue** [comment]
[I believe this page replaces it](http://react-redux-firebase.com/docs/recipes/epics.html).

Great find with the missing link though. Will clean that up.

**Comment by prescottprue** [comment]
Fixed in [`v1.5.0` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.5.0).
