### ISSUE TITLE
userProfile and profileFactory issue

### ISSUE THREAD

**Issue by henrymoulton** [prescottprue/react-redux-firebase#272]
**What is the current behavior?**
Using the 2.0 beta, when a user signs up, the auth data is not being saved to the firebase database using the following config:

```js
const rrfConfig = {
  userProfile: 'users', // where profiles are stored in database
  profileFactory: (userData) => { // how profiles are stored in database
    const { user } = userData;
    return {
      email: user.email
    };
  }
};
```
 ###   Database Rules:
```js
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

I wasn't able to create a codesandbox due to this issue:https://github.com/zeit/next.js/issues/1999

**What is the expected behavior?**
Should be saving under /users/auth.uid/email: user.email

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

"react-redux-firebase": "^2.0.0-beta.8",
    "firebase": "^4.2.0",

**Comment by prescottprue** [comment]
@henrymoulton What type of signup are you using and how do you call it?

Using `createUser`, or `login` with an external provider?

**Comment by henrymoulton** [comment]
```
handleSignup = creds => {
    console.log(creds);
    const { createUser, login } = this.props.firebase;
    createUser(creds, {
      email: creds.email,
      username: creds.username
    }).then(() => {
      login(creds);
      //https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email
      const user = firebase.auth().currentUser;
      user
        .sendEmailVerification()
        .then(() => {
          console.log('user email verification sent');
        })
        .catch(err => {
          console.error(err);
        });
    });
  };
```

Similar to the material example

**Comment by henrymoulton** [comment]
Ahhh I wasn't giving it a username properly from redux-form, my apologies!

**Comment by prescottprue** [comment]
Also, side note: `createUser` logs you in automatically by default, so calling that yourself shouldn't be necessary  😄

**Comment by henrymoulton** [comment]
https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/material/src/routes/Signup/containers/SignupContainer.js#L44

Was just following the docs 😇

**Comment by prescottprue** [comment]
@henrymoulton Thanks for pointing me to that, I will clean that up.
