### ISSUE TITLE
feat(auth): Reload auth

### ISSUE THREAD

**Issue by lench4991** [prescottprue/react-redux-firebase#273]
Calling `firebase.auth().currentUser.reload()` fetches latest account data from firebase. An example use case for this is when we want to check if user has verified their email.

This however does not update the Redux state. My workaround is pretty simple but ugly. I'm dispatching a `LOGIN` action with the new reloaded auth object.

```js
async function reloadAuth() {
    if (!firebase.auth().currentUser) return;

    await firebase.auth().currentUser.reload();
    const auth = firebase.auth().currentUser;

    store.dispatch({ type: '@@reactReduxFirebase/LOGIN', auth });
}
```

A better solution would be a `reloadAuth` function on `firebaseInstance` and a dedicated `RELOAD_AUTH` action type.

I would be glad to submit a pull request if you think this would be a good addition.

**Comment by prescottprue** [comment]
@lench4991 Yes, I think this would be a great addition. Feel free to open a pull request.

**Comment by prescottprue** [comment]
@lench4991 This can be added to v1.5, but it should also be added to v2.

**Comment by prescottprue** [comment]
Into v2.0.0-beta.9 with matching tests. Will wait to close until it is published.

**Comment by prescottprue** [comment]
[`reloadAuth` method included in `v2.0.0-beta.9` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.9)

**Comment by lopesmcc** [comment]
Shouldn't this `reloadAuth` be updating the firebase auth state? I see the message but the state is not being updated.

**Comment by prescottprue** [comment]
@lopesmcc Yes it should. The tests should be confirming this too, so I will attempt to replicate.

If I am able to replicate, we will reopen this to track.

Thanks for reporting.

**Comment by lopesmcc** [comment]
Hi again.
Has this been fixed? I think not by looking at the current reducers logic.
I you want I can prepare a PR with it.

**Comment by prescottprue** [comment]
@lopesmcc [Here is the source](https://github.com/prescottprue/react-redux-firebase/blob/94580288a028d14bc474a336a756138c0d072eb9/src/actions/auth.js#L745-L772) of the `reloadAuth` function that dispatches the `AUTH_RELOAD_SUCCESS` action.

It looks like you are right about there is not a reducer case for it (great catch), so it would be awesome if you wanted to open a PR! Don't worry too much about updating the tests if you don't have time (can be handled later).
