### ISSUE TITLE
bug(populate): multiple populates with the same root

### ISSUE THREAD

**Issue by prescottprue** [prescottprue/react-redux-firebase#274]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**

When using multiple populates that contain the same `root` parameter, data is not correctly populated.
```jsx

const populates = [
  { child: 'owner', root: 'users' },
  { child: 'collaborators', root: 'users' }
];

@firebaseConnect(
  props => [
    { path: 'projects', populates },
  ]
)
@connect(
  (state, props) => ({
    todos: populatedDataToJS(state.firebase, 'projects', populates)
  })
)
export default class TodosList extends Component {
// some component code
}
```
The reason seems to be that only data from one of the two populates is available.

More details available in #49 

**What is the expected behavior?**
It is expected for data to be merged, so two populates can have the same `root` parameter without an issue.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Multiple populates at different paths work

**Comment by raghavendracs** [comment]
Was doing further testing at my end on this bug and I wanted to share the following observations.

My structure is as follows,

```js
const populates= [
  { child: 'experiences', root: '/allExperiencesList' },
  { child: 'actionsIn', root: '/allActions' },
  { child: 'actionsOut', root: '/allActions' },
  { child: 'archivedActionsOut', root: '/allActions'},
  { child: 'archivedActionsIn', root: '/allActions'}
]
```
When the keys actionsIn, actionsOut, archivedActionsIn and archivedActionsOut all exist the populates from same root /allActions works fine. 

If any one of the "child keys" is not in the /users/ path the entire populates appears to be failing.

**Comment by prescottprue** [comment]
@raghavendracs From your error it looks like you are attempting to pass an object at the end of your query instead of a string (i.e. a uid). If you are loading auth and using the user's uid, you might want to do that in a parent component above the component using populate.

**Comment by prescottprue** [comment]
This does not appear to be an error with `v2.0.0`. If anyone experiences something similar, let me know and we can open a new issue with better repro steps.
