### ISSUE TITLE
bug(docs) Populate example has typo

### ISSUE THREAD

**Issue by pzmudzinski** [prescottprue/react-redux-firebase#279]
If you look here: http://docs.react-redux-firebase.com/history/v2.0.0/docs/populate.html#initial-data

It seems it should be `profileParamsToPopulate: [ 'displayName:displayNames' ]` instead of `'username:usernames'` (`usernames` aren't mentioned anywhere).

**Comment by prescottprue** [comment]
@pzmudzinski Looks like you are right. Will fix soon. Thanks for reporting!

**Comment by prescottprue** [comment]
Fixed. There is soon to be much more coming to the populate and query docs. Recently been busy with trying to get `v2` closer to stable.
