### ISSUE TITLE
Firebase database ref

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#28]
Hi,

Regarding this line: https://github.com/prescottprue/react-redux-firebase/blob/master/src/compose.js#L142
Is there any reason why you set `ref` to `Firebase.database().ref` instead of just referring to `ref` constant that was set above?

As it is, I cannot access `this.props.firebase.ref.child(...)` nor `this.props.firebase.ref().child(...)`. If the above line is simply changed to `ref`, I can access database with `this.props.firebase.ref.child(...)`.

**Comment by prescottprue** [comment]
Great catch! Fixing as part of `v1.1.5`.

**Comment by prescottprue** [comment]
Can you confirm that you can correctly access ref in [version v1.1.5](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.1.5)?

Want to make sure this handles your use case before closing the issue.

**Comment by DeividasK** [comment]
Yes, it works now as expected. Thanks!
