### ISSUE TITLE
feat(storage): customizable file name with uploadFile/uploadFiles

### ISSUE THREAD

**Issue by barneyb** [prescottprue/react-redux-firebase#285]
**Do you want to request a *feature* or report a *bug*?**

feature!

**What is the current behavior?**

When uploading files with `.uploadFile` or `.uploadFiles`, the `name` property of the browser's `File` object is always used for the storage path.

 - If two files are uploaded with the same name, the second overwrites the first, with no collision detection.
 - There is no way to use generated (or "unguessable") names for files; they always are stored with the uploader's naming conventions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

I'm not sure if the "no collision detection" is a bug or intended. I'd say the inconsistency between _replacing_ the storage file while _appending_ a new metadata packet in the database is a bug, but that's not the feature request. :)

Either way, to reproduce it, simply upload the same file twice with a configuration that stores file metadata in the realtime database. The example code from the docs (http://docs.react-redux-firebase.com/history/v2.0.0/docs/recipes/upload.html) is symptomatic.

**What is the expected behavior?**

I would like either a callback or an extra parameter to indicate the storage name to use for the file, rather than always using the `File` object's `name` property. Or perhaps a "gen one" option, that would use the push id of the metadata object that gets written to the database (suffixed with the same file extension, if any). But I'd be happy to have a simple callback and then _I_ can write all that stuff in my application, rather than the library trying to guess what people would want.

Perhaps a 4th param to uploadFile(s) that has a default value of `file => file.name`?

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

n/a

**Comment by prescottprue** [comment]
Agreed that this should be a feature and it is actually on the [roadmap for v1.6.0](http://react-redux-firebase.com/docs/roadmap.html#features).

I came up with a way to do it without it being a breaking change, so going to try to get it into a`v1.5.*` release.

As for a current way to get "non-guessable" names would be to provide a unique path (includes something like at timestamp) when calling upload.

**Comment by prescottprue** [comment]
Support for this will be part of the next v2.0.0 release. The 4th argument is now an options object which accepts a `name` parameter that can be either a string or a function. It can be used with the following syntax:

```js
const options = { name: (file) => `${file.name}/${Date.now()}` } }
firebase.uploadFile('path/in/storage', file, 'path/in/database', options)

// same syntax for upload files
firebase.uploadFiles('path/in/storage', files, 'path/in/database', options)
```

**Comment by prescottprue** [comment]
Available in `v2.0.0-beta.10`

**Comment by MichaelJC91** [comment]
Am I able to use a similar structure for creating custom meta data?

**Comment by prescottprue** [comment]
@MichaelJC91 Yes that is what `fileMetadataFactory` is for - feel free to open a new issue if it isn't working as you expect
