### ISSUE TITLE
firebase.auth(...).getRedirectResult is not a function

### ISSUE THREAD

**Issue by NathHorrigan** [prescottprue/react-redux-firebase#287]
BUG

**What is the current behavior?**
Error when remote debugging: firebase.auth(...).getRedirectResult is not a function

**What is the expected behavior?**
No Red box error

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
React Native: 0.48.3
react-native-firebase: ^2.2.0
react-redux-firebase: canary

OS: Android

Original Github Issue: https://github.com/invertase/react-native-firebase/issues/431

**Comment by prescottprue** [comment]
@NathHorrigan Did you try passing `enableRedirectHandling: false` to config [as mentioned in the react-native recipe doc](http://docs.react-redux-firebase.com/history/v2.0.0/docs/recipes/react-native.html#react-native).

Either way, there was code added to detect this automatically for v2, so the fact that you are experiencing it is still a bug. Thanks for reporting!

**Comment by LaloHao** [comment]
I'm still getting this error on `"react-redux-firebase": "^2.0.0-beta.8",`, but only when Remote JS Debugging is on

**Comment by prescottprue** [comment]
@NathHorrigan Any update?

**Comment by NathHorrigan** [comment]
`enableRedirectHandling: false` fixed it
@prescottprue

**Comment by prescottprue** [comment]
Going to add something to the roadmap for checking existence of `getRedirectResult` before using it. That way, the config option won't be required.

**Comment by prescottprue** [comment]
`getRedirectResult` can now only be called if it is a function, so you should no longer need this config option.
