### ISSUE TITLE
feat(firebase): multiple firebase apps

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [prescottprue/react-redux-firebase#29]
Is it possible to connect with multiple firebase apps?
My current use case is to connect to one central firebase app that has all the keys of other firebase apps. Once the user has logged in to this app, it retrieves the key for the corresponding app and connects to it

**Comment by prescottprue** [comment]
@rafaelcorreiapoli It isn't currently supported, but I will work on getting included in v1.2.0.

Do you have a prefered API for this?

I was thinking something like:

```js
const apps = {
  app1: {
   apiKey: '<your-api-key>',
   authDomain: '<your-auth-domain>',
   databaseURL: '<your-database-url>',
   storageBucket: '<your-storage-bucket>'
  },
  app2: {
   apiKey: '<your-api-key>',
   authDomain: '<your-auth-domain>',
   databaseURL: '<your-database-url>',
   storageBucket: '<your-storage-bucket>'
  }
}
const 
// React Redux Firebase Config
const config = {
  userProfile: 'users'
}

// Add react-redux-firebase to compose
const createStoreWithFirebase = compose(
 reactReduxFirebase({ apps }, config),
)(createStore)
```

Maybe it shouldn't be named "apps", but it would be nice to have it be differentiated from the normal object [passed for a single app](http://react-redux-firebase.com/docs/api/compose.html).

**Comment by rafaelcorreiapoli** [comment]
Hi! Thanks for the answer
It actually would not fix my problem
I need to instantiate my second app based on informations I get after login in to the first app
The first app holds the information about other apps (apiKey, authDomain, etc...)
I know its not a common use case.. but do you have any ideas on how to solve this ?

**Comment by prescottprue** [comment]
OH man... Yeah that changes things quite a bit. There is for sure not a way to do that in an easy way currently, especially because all of the data syncing and other methods use the default app.

I will add this to the roadmap so that it is on the menu at least, but it will take quite a bit of research to see how all the methods would need to be modified.

You might want to look into [re-base](https://github.com/tylermcginnis/re-base) for a more simple integration that easily allows for multiple apps. Even though it only syncs to components (not redux) it should handle your use case.

**Comment by rafaelcorreiapoli** [comment]
Nice! thanks! Maybe I could render another component tree with a different Provider when I get the data from the first app. This new Provider would use a store created with data from the first app
```
  const createStoreWithFirebase = compose(
    reactReduxFirebase(firebaseConfig, { userProfile: 'users' }),
  )(createStore)
```

this firebaseConfig could be something passed as a parameter to the store

:)

**Comment by prescottprue** [comment]
Sounds like a crafty work around, let me know how it goes!

**Comment by rafaelcorreiapoli** [comment]
Thanks for your help :) I will post my solution soon

**Comment by prescottprue** [comment]
Currently this can also be done by placing different apps within different stores, then using `createFirebaseConnect('storeName')`.

@rafaelcorreiapoli Did you have an example of your pattern working out? If so, I can look into making an example from it.

**Comment by prescottprue** [comment]
Closing since multiple working solutions have been posted
