### ISSUE TITLE
bug(auth) logout from custom token

### ISSUE THREAD

**Issue by Modestas** [prescottprue/react-redux-firebase#292]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
```
@firebaseConnect([{ path: "/web/metadata", storeAs: "metadata" }])
@connect(({ firebase: { auth, profile, data: { metadata } } }) => ({
  auth,
  user: profile,
  metadata
})
```
`metadata` path not fetched after logout. Metadata path in firebase is `read: true`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
1. Sign in with `this.props.firebase.login({ token: token });` (this.props.metadata OK)
1.5. **Optional**. Full refresh page (this.props.metadata OK)
2. Sign out with `this.props.firebase.logout();`
3. `this.props.metadata = undefined`
4. Refresh page
5. `this.props.metadata = {}` OK

**What is the expected behavior?**
1. Sign in with `this.props.firebase.login({ token: token });`
1.5. **Optional**. Full refresh page
2. Sign out with `this.props.firebase.logout();`
3. `this.props.metadata = {}` OK

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
2.0.0-beta.8 and 2.0.0-beta.9

**Comment by prescottprue** [comment]
@Modestas Currently listeners are not attached/detached based on auth state. That means you should be able to use `preserveOnLogout` to keep metadata from being removed. Something like:

```js
const rrfConfig = {
  userProfile: 'users',
  preserveOnLogout: [
    'metadata',
  ]
}
```
It could also be done by hand currently using the `onAuthStateChanged` option to call a function that re-applies listeners.

All of that said I am going to look into adding something to the roadmap for re-applying listeners on auth state change.

**Comment by Modestas** [comment]
Thanks for quick reply! I didn't find it in documentation because apparently it was missing in `compose.md` while `logout` docs were telling me to go look there.

Added quick PR.

**Comment by prescottprue** [comment]
@Modestas Great find! I addressed that PR.

As for you original issue, going to close since it seems like you can solve with `preserveOnLogout` (correct my if I am wrong). Going to continue to look into an option to detach/reapply listeners on auth state change.
