### ISSUE TITLE
[2.0.0] feat(populate):  childParam support for string query config

### ISSUE THREAD

**Issue by Modestas** [prescottprue/react-redux-firebase#296]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**
https://github.com/prescottprue/react-redux-firebase/blob/v2.0.0-beta.11/src/utils/populate.js#L25
Unimplemented `childParam` in populate.

Small example with correct auth:

```
{ 
  questions: [
    $questionId: {
      question: "some random question", //user read = true
      answer: "super" //user read = false
    }
  ]
}

const populates = [{ child: "questionId", root: "questions", childParam: 'question' }];
```

**Comment by prescottprue** [comment]
@Modestas Another great catch! I will try to get the logic for this into the next v2.0.0 pre-release

**Comment by prescottprue** [comment]
@Modestas Were you able to test if object notation works? Since the plan is to move away string query config in the future, I am only going to keep this open if you are having an issue with object notation (which again should work).

**Comment by prescottprue** [comment]
Closing for now since, as mentioned, string notation is not really documented much and is on the way out. Open to re-opening if object notation isn't working as expected. Thanks for reporting!
