### ISSUE TITLE
feat(examples): example showing how to query a single record from a collection

### ISSUE THREAD

**Issue by fivetwentysix** [prescottprue/react-redux-firebase#300]
I'm trying to get a single item in a collection for a component.

Perhaps it could be included in the todos examples.

**Comment by prescottprue** [comment]
The material complete example [shows this in the Project Container](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/material/src/routes/Projects/routes/Project/containers/ProjectContainer.js).

The todos example was originally made to be a bit more simple. I'll look into adding something simple that still gets the point across. Also, totally open to suggestions and/or PRs.

**Comment by fivetwentysix** [comment]
Thank you @prescottprue for getting me unstuck. Would it be simpler moving forward to merge all the examples into one example?

**Comment by prescottprue** [comment]
Thanks for the suggestion, will look into ways to make things more simple.
