### ISSUE TITLE
bug(docs): queries including startAt, endAt, equalTo & limits with orderByValue are order dependent

### ISSUE THREAD

**Issue by AVVS** [prescottprue/react-redux-firebase#302]
**What is the current behavior?**

```
        case 'startAt':
          let startAtParam = !doNotParse ? tryParseToNumber(param[1]) : param[1]
          startAtParam = startAtParam === 'null' ? null : startAtParam
          query = param.length === 3
            ? query.startAt(startAtParam, param[2])
            : query.startAt(startAtParam)
          break
        case 'endAt':
          let endAtParam = !doNotParse ? tryParseToNumber(param[1]) : param[1]
          endAtParam = endAtParam === 'null' ? null : endAtParam
          query = param.length === 3
            ? query.endAt(endAtParam, param[2])
            : query.endAt(endAtParam)
          break
```

When query is:

```js
queryParams: ['orderByValue', `limitToFirst=${limitToFirst}`, `startAt=${startAt}`],
```

`limitToFirst` and `startAt` would be treated as string failing the query. It would work if we do

```js
queryParams: [`limitToFirst=${limitToFirst}`, `startAt=${startAt}`, 'orderByValue'],
```

**What is the expected behavior?**

`orderByValue` does not turn on `doNotParse` on

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Branch 2.x.x

**Comment by prescottprue** [comment]
Good find @AVVS, the order shouldn't matter, so this is for sure a bug. I'll look into fixing it, but also open to pull requests if anyone gets to it.

It may be irrelevant, and should definitely be documented more, but did you try out the `noParse` param?

**Comment by prescottprue** [comment]
Query docs have been updated with a note about how order is important, as well as how to use `notParsed`.

In v2.0.0-beta.17 I have planned on adding a `parsed` query parameter. That way, you will be able to pass your params out of order, and enable/disable automatic parsing as needed.

Let me know if this doesn't address your concerns, and we can reopen. Thanks for reporting!
