### ISSUE TITLE
Simple example doesn't make sense to me. Please explain

### ISSUE THREAD

**Issue by chino23** [prescottprue/react-redux-firebase#308]
The simple example is really confusing me: https://github.com/prescottprue/react-redux-firebase/tree/master/examples/complete/simple/src

There is:
- no reducer which listens for dispatches
- no action ever defined

Instead, the components themselves fire actions directly by sending requests to firebase. 

How is this redux? What's the point?

I thought the whole thing was supposed to be structured in actions, which then gets read by our reducers, so we have ONE place where all actions are handled. So if i want to change an action, i do it at one place. Whereas here, i'll have to look for stuff all over the place and it might get really messy.

Could someone explain to me what i'm missing here please?

**Comment by prescottprue** [comment]
@chino23 There is very much a reducer ([here it is](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/simple/src/reducer.js)).

The whole thing **IS** structured in actions. Those actions are fired by the `firebase` library based on config that is passed when setting up your store or based on listeners you set.

Feel free to [reach out over gitter](https://gitter.im/redux-firebase/Lobby) for basic questions about usage.

**Comment by chino23** [comment]
Thanks for the quick response @prescottprue 

I've added some more detail on gitter
