### ISSUE TITLE
Subscribe to path with param

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [prescottprue/react-redux-firebase#31]
Hi! The component thta firebaseConnect is returning is receiving via props an id
Then, it must subscribe to 'items/${ownProps.id}'
How can I achieve this? since the paths you pass to firebaseConnect are an array and not obtained with a function

**Comment by rafaelcorreiapoli** [comment]
If firebaseConnect accepted a function, we could pass the props into this function and make this function return an array of paths
This concept is used on redux's connect function. mapStateToProps and mapDispatchToProps are both functions that accept the ownProps as a parameter

**Comment by DeividasK** [comment]
I believe this may be what you are looking for:
```js
@firebaseConnect((props) => ([
  `items/${props.id}`
]))

**Comment by rafaelcorreiapoli** [comment]
Yeah, that's also what I was proposing. Is it on the documentation?
Sorry!

**Comment by prescottprue** [comment]
There is a bit about it on the [connect page](http://react-redux-firebase.com/docs/api/connect.html) but I will look for other places to make it even more clear.

**Comment by wheel1992** [comment]
@prescottprue Did you manage to write about this question? Cos I've tried to search for the solution, but it doesn't work at all.

**Comment by prescottprue** [comment]
[The state based query example](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/snippets/stateBasedQuery/App.js#L53-L75) shows a query that is dynamic (I believe what you are looking for).

**Comment by ximomompo** [comment]
Is this possible without decorators?
