### ISSUE TITLE
bug(populate): undefined child causing expected behavior

### ISSUE THREAD

**Issue by aQustic** [prescottprue/react-redux-firebase#310]
**What is the current behavior?**

Every object of an array which does not have the child element defined in population rule gets transformed into an object full of arrays.

```
const populates = [
  { root: 'messages', child: 'messages' },
];
```

```
@firebaseConnect(
  ({ params }) =>
    [{ path: `groups/${params.slug}`, populates }]
)
@connect(
  ({ firebase }, { params }) => ({
    group: populate(firebase, `groups/${params.slug}`, populates),
  })
)
```

This produce the expected population
from
```
group
 - createdAt: 1509...
 - fromID: "XZ2ovIPB..."
 - messages: {...}
  -- KxSP... : true
```
to
```
group
 - createdAt: 1509...
 - fromID: "XZ2ovIPB..."
 - messages: {...}
  -- KxSP... : {...}
   --- fromID: "...."
   --- text: "...."
```

but if a group does not have a child array of messages it produces strange arrays within the group object for every attribute it has:
```
group
 - createdAt: {...}
  -- Empty Array
 - fromID: {...}
  -- 0: "X"
  -- 1: "Z"
  -- 2: "2"
  -- 3: "o"
  -- 4: "v"
 - name: {...}
  -- 0: "T"
  -- 1: "e"
  -- 2: "s"
  -- 3: "t"
```

In addition to that this arrays are returned from strings while integers are returning empty arrays.

**What is the expected behavior?**

Original state of object will not be modified. Only the child array of keys should be populated, if it exist.

**Comment by prescottprue** [comment]
@aQustic This is for sure not expected. I am going to try to replicate myself to confirm and see what could be causing it.

**Comment by prescottprue** [comment]
@aQustic Have you happened to confirm this on v2.0.0-beta.14 as well?

**Comment by aQustic** [comment]
@prescottprue i've updated to beta.14 but the same error appears.

The console says
```
Uncaught (in promise) Error: Objects are not valid as a React child (found: object with keys {0, 1, 2}).
```
and the props of the object contain the same arrays i've experienced with beta.13 if populated array don't exist 
```
group
 - createdAt: {...}
  -- Empty Array
 - fromID: {...}
  -- 0: "X"
  -- 1: "Z"
  -- 2: "2"
  -- 3: "o"
  -- 4: "v"
 - name: {...}
  -- 0: "T"
  -- 1: "e"
  -- 2: "s"
  -- 3: "t"
```

**Comment by prescottprue** [comment]
@aQustic Great to know, thanks for confirming.

**Comment by fej-snikduj** [comment]
I was able to reproduce this @aQustic .  I just released a fix for a similar issue with beta.16 (currently writing release notes) but unfortunately it doesn't fix this issue.  I know what's going on and should be able to come up with a fix for beta.17

**Comment by prescottprue** [comment]
[`v2.0.0-beta.17`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.17) includes the fix for this.

@aQustic if it doesn't work as expected for you after upgrading, please reach out. Thanks for reporting!
