### ISSUE TITLE
question(query): attach listener that returns first response in Promise

### ISSUE THREAD

**Issue by jaschaio** [prescottprue/react-redux-firebase#314]
I am using `react-redux-firebase` in combination with `react-chrome-redux` and followed the example given in https://github.com/prescottprue/react-redux-firebase/issues/157#issuecomment-308972067.

Like described in that issue, I can't use firebaseConnect but instead have set up manually `.login`, `.logout`, `.push`, `.update`, `.remove` and `.watchEvent` methods within my `redux-thunk` reducers.

This seems to work reasonable well, but I am expecting the Following error with the `.watchEvent` method. It seems that it is not returning a proper Promise:

`TypeError: Cannot read property 'then' of undefined`

This is the code that is causing the error:

    import { getFirebase } from 'react-redux-firebase';

    const aliases = {
        'MESSAGES_SYNC': (payload) => {
            return(dispatch) => {
                getFirebase().watchEvent('value', '/messagesTriggered/')
                .then((data) => {
                    console.log(data);
                })
                .catch((errors) => {
                    console.log(errors);
                });
            }
        }
    };

    export default aliases;

Resolving the promise and catching errors does seem to work with all other methods that I have tried. I experienced the same problem with the 1.5.0 version.

Maybe I am even doing it wrong. There is probably an easier way for me to update the store when the `.watchEvent` method has finished than dispatching another actions with the results. Probably with the help of `storeAs` and a redux subscribe listener.

**Comment by prescottprue** [comment]
@jaschaio `'value'` queries do not return promises as you are creating a watcher. If you intend to get just one set of data you will want to do `watchEvent` with a type `'once'`.

**Comment by jaschaio** [comment]
Thanks for your prompt reply. That makes sense. So I would probably use a once query to populate the initial state and than a value query to watch out for changes.

But I still don’t understand how I than would setup my store to update when a listener gets triggered. The storeAs property doesn’t seem to work for me and I couldn’t find anything related in the docs or within github issues as most people simply seem to use the firebaseConnect function.

**Comment by prescottprue** [comment]
@jaschaio The store is "setup to update when a listener is triggered" by the fact that you are using the `firebaseReducer` and the `watchEvent` action creator ([here is the redux docs section about action creators](http://redux.js.org/docs/advanced/AsyncActions.html#async-action-creators)). The events are dispatched by the listeners you create with `watchEvent`.

You can pass the data from the Promise result into a different part of redux yourself, but is not necessarily the "easiest" method.

Would be interested to see what you mean by `storeAs` does not work for you.

**Comment by jaschaio** [comment]
Okay I think I wasn't clear enough. Of course the state.firebase is already updating because of the firebaseReducer. But what if I wan't that data somewhere else in the store? I thought `storeAs` is responsible for that.

Here is a minimum repo example https://github.com/jaschaio/react-redux-firebase

OnClick an action is dispatched that updates the `/clicks` node on Firebase. And when the component is mounted clicks are synced from `firebase` as well. This works, I get the data within the `state.firebase.data` node.

But what I would like to do is store the data received from firebase within `state.clicks` automatically once data is received from firebase.

What I am currently doing is the following within my mapStateToProps method:

    const mapStateToProps = (state, ownProps) => {
        return {
            firebase: state.firebase,
            clicks: state.firebase.data.clicks
        };
    };

It works to get the firebase data as if it were within my store, but actually bypasses updating the reducer store altogether. Maybe I am just misunderstanding the `storeAs` property altogether and should write more reducers that are responsible for updating the state once data has been changed on firebase.

**Comment by prescottprue** [comment]
@jaschaio That should be what is happening automatically? It should happen without you even needing to provide `storeAs` since queries are automatically stored under the path of the query (in your case `/clicks`).

Would you be open to reaching out [over gitter](gitter.im/redux-firebase/Lobby) so I can work with you back and forth to better understand?
