### ISSUE TITLE
feat(auth): signInWithPhoneNumber

### ISSUE THREAD

**Issue by jacobfunch** [prescottprue/react-redux-firebase#319]
It would be much appreciated if react-redux-firebase supported Firebase signin with phone number (https://firebase.google.com/docs/auth/web/phone-auth).

Remember that it requires reCAPTCHA.

**Comment by prescottprue** [comment]
I agree, I'll make an action creator.

@jacobfunch Do you plan to [use the invisible Captcha](https://firebase.google.com/docs/auth/web/phone-auth#use-invisible-recaptcha) attached to a button? Either way, that might be what I end up using for an example.

It should be able to work like so:

```js
// appVerifer is recaptcha-verifier
firebase.signInWithPhoneNumber(phoneNumber, appVerifier)
```


Good news: There may be a way to extend Firebase's functions with dispatch (still looking into it), so in the future, hopefully calling methods directly can work as expected.

**Comment by jacobfunch** [comment]
@prescottprue perfect! And yes indeed, I plan on using the invisible reCAPTCHA – which I think most products will use as it is less intrusive.

**Comment by prescottprue** [comment]
The first swing at it is on [the v2.0.0-beta.15 branch](https://github.com/prescottprue/react-redux-firebase/tree/v2.0.0-beta.15) (not yet published to NPM). Feel free to npm link and test it yourself, but I have yet to write tests for it or do much testing myself.

**Comment by prescottprue** [comment]
`signInWithPhoneNumber` action creator added in [v2.0.0-beta.15](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.15). It was interesting to integrate with the existing profile stuff, so let me know if things do not function as expected.

**Comment by jacobfunch** [comment]
Thanks @prescottprue! When signing in after a user has been created it overwrites the entire user object even though there was custom data saved. Can one use the merge option?

**Comment by prescottprue** [comment]
@jacobfunch Are you referring to the `auth` or `profile` object be overwritten? Is it the `SET_PROFILE` action that is overwriting it or another action type?

**Comment by prescottprue** [comment]
@jacobfunch There is no merge option yet, but since #366 is asking for that, we can discuss the feature in that issue.

Thanks for your patience and clarifying your use case.
