### ISSUE TITLE
feat(integration): geoFire.js integration

### ISSUE THREAD

**Issue by beckmeindia** [prescottprue/react-redux-firebase#32]
Hi, My app use extensive amounts of geoQuery in geofire.js

I have been wondering what would be a good way to use geoFire with this module so that the result syncs with the redux state.

Please suggest!

Thanks

**Comment by prescottprue** [comment]
@beckmeindia Looking into what this would take. Do you have an idea of how you would like the syntax to look?

**Comment by beckmeindia** [comment]
Hey!
I was thinking of calling an action and processing geoFire preferably in the middleware with the action data. 
Then the redux state should update and pass the data onto the components.

Do you think that is a good idea?

**Comment by prescottprue** [comment]
@beckmeindia I meant more the interface as in what the API would look like. You mentioned calling an action, which actions would you want (guessing at least `set` and `get`)?

The query aspect of it might take some consideration though because just at first glance there seems to be a few different listeners (`'key_entered'`, `'key_exited'`, and `'key_moved'`), and not sure how that would fit in with the current query syntax. Here is a guess at syntax that may work:

```js
@firebaseConnect([
  {
    path: 'some/path', // normal path with on listener
  },
 {
    center: [0, 0],
    radius: 3000,
    type: 'key_entered'
  },
])
```

Thoughts?

I'm thinking it might make sense to include `geoFire` by passing in an already configured instance so we can avoid adding it as a dependency.

Maybe something like:

```js
import { reactReduxFirebase } from 'react-redux-firebase'
import Geofire from 'geofire'
// React Redux Firebase Config
const config = {
  userProfile: 'users', // saves user profiles to '/users' on Firebase
  integrations: {
    geofire: {
      instance: Geofire, // Pass in geofire library
      root: 'some/path' // Path within Firebase for Geofire data
    }
  }
}
const createStoreWithFirebase = compose(
 reactReduxFirebase(fbConfig, config),
)(createStore)

```

**Comment by beckmeindia** [comment]
Hi Scott,
   Thanks for your revert. I think primarily geoFire has **set** and **get** functions
Also the other important one would be the geoQuery functionalities like on eventTypes such as ready, key_entered, key_exited, and key_moved & updateCriteria

So I think the API which you wrote serves the purpose very well.

Now if we can have all the functionalities be accessed as type, it would work wonders!

Thanks

**Comment by beckmeindia** [comment]
Hi Scott,
 I saw your extraordinary implementation of Epics with redux-observable.
Talking about geofire, it essentially returns a stream is what I think from geoQuery.on() functions

I was wondering what if you could marry the geofire with redux-observable (also because there aren't any observable firbase repos on React platform)

That would be a great way to consume the API and as well run flatMap and other functions from multiple observables as and when you like.

Any downsides that I'm accidentally overlooking?

**Comment by prescottprue** [comment]
Closing, since on further investigation this seems to be outside of scope of this library alone.

@beckmeindia The things you are suggesting with dealing with geofire as a stream with observables  sounds like an interesting approach.

**Comment by michaelspeed** [comment]
Is this still on the roadmap ? Or it's already implement

**Comment by kevando** [comment]
I got this working by adding this to my `store.js` file where `/geoFire` is the firebase database reference location that I CHOSE to store my geo fire data:

``` javascript
var firebaseRef = firebase.database().ref('geoFire');
var geoFire = new GeoFire(firebaseRef);

// --------------------------
const rootReducer = combineReducers({
  firebase: firebaseReducer,
  geoFire: () => geoFire,
})
```

And then my component looks something like this:

``` javascript
/* eslint-disable no-unused-vars */
import React, { Component } from 'react'
import { compose } from 'redux'
import { connect } from 'react-redux'
import _ from 'lodash'
import {
  firebaseConnect,
  isLoaded,
  isEmpty
} from 'react-redux-firebase'
import {  Container, Table, Header, Popup, Rating, Icon, Loader  } from 'semantic-ui-react'

import GeoFire from 'geofire'

import { isAdmin } from './helpers'

class Users extends Component {

  state = {

  }

  componentDidUpdate(prevProps, prevState) {
    const { geoFire } = this.props
    // set user data from firebase
    console.log('geoFire in component',geoFire)
    //

    geoFire.get("SOME_KEY").then(function(location) {
      console.log(location)
      if (location === null) {
        console.log("Provided key is not in GeoFire");
      }
      else {
        console.log("Provided key has a location of " + location);
      }
    }, function(error) {
      console.log("Error: " + error);
    });

  }



  render() {

    return null;
  }
}

export default compose(
  firebaseConnect([
    // 'geoFire'
    { path: '/geoFire', queryParams: [ 'limitToLast=20' ] }
  ]),
  connect((state) => {
    return ({
      geoFire: state.geoFire,
      auth: state.firebase.auth,
      firebase: state.firebase,
    })
  })
)(Users)


```

Forgive all the garbage code, but if SOME_KEY exists, then it successfully pulls the data which is dope!

**Comment by prescottprue** [comment]
For those looking for an integration for Firestore, found [geofirestore](https://github.com/geofirestore/geofirestore-js) listed on [firebaseopensource.com](https://firebaseopensource.com).

**Comment by FrancisLeigh** [comment]
@prescottprue I am running into an issue when using `geofirestore` with `react-redux-firebase`, i have raised [this ticket](https://github.com/MichaelSolati/geofirestore-js/issues/178) on `geofirestore` and Michael (the creator/maintainer) is unsure to wether having this layer to my firestore via `react-redux-firebase` could cause issues wit `geofirestore` 

Have you manged to implenent `geofirestore` with `react-redux-firebase` and successfully run `.near` queries ?
