### ISSUE TITLE
bug(firebaseConnect): inconsistent arguments for the callback

### ISSUE THREAD

**Issue by optimistiks** [prescottprue/react-redux-firebase#320]
**Do you want to request a *feature* or report a *bug*?**  

A bug.

**What is the current behavior?**

Currently, on `componentWillMount`, first argument is `props`, second argument is `store`.
https://github.com/prescottprue/react-redux-firebase/blob/v2.0.0-beta.14/src/firebaseConnect.js#L47

But on `componentWillReceiveProps`, first argument is `props`, but the second argument is `firebase`.
https://github.com/prescottprue/react-redux-firebase/blob/v2.0.0-beta.14/src/firebaseConnect.js#L65

**What is the expected behavior?**

Callback function signature should be the same for both cases. `(props, store) => {}`

**Comment by prescottprue** [comment]
You are correct, Great catch! Seems like the recently release that changed it didn't change the `componentWillRecieveProps`. Going to try to add a unit test to catch this in the future.

**Comment by prescottprue** [comment]
The [v2.0.0-beta.15 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.15) includes the fix for this.

Post if this or anything else doesn't work as expected. Thanks for reporting!
