### ISSUE TITLE
Routing Recipes - Some inconsistencies

### ISSUE THREAD

**Issue by jeandavid** [prescottprue/react-redux-firebase#325]
I have noticed some inconsistencies within `docs/routing/recipes.md` page.

* In the Advanced Section - Auth Required, for react-router v4 + redux-auth-wrapper v2, you import 
`import { browserHistory } from 'react-router'` but there is no `browserHistory` in react-router v4.

* In the Advanced Section - Redirect Authenticated, for react-router v4 + redux-auth-wrapper v2, you import `import { UserAuthWrapper } from 'redux-auth-wrapper'` but it should import `connectedRouterRedirect` for v2.

Also it would be great if the examples could be updated to show how to use react-router v4 + redux-auth-wrapper v2, not only on the redux-auth-wrapper higher order component, but also on the createStore.js and App.js file. 

Thanks!

**Comment by NathHorrigan** [comment]
Hello! I would like to add to this discussion regarding an error I am having trying to implement this.
I have the following decorator (copied from docs) that doesn't have reference to firebase and so doesn't compile. Am I being stupid here?? I can't use `getFirebase` so I'm not sure what to do 😕 

```
// Decorator file
const Auth = connectedRouterRedirect({
  redirectPath: (state, ownProps) =>
  locationHelper.getRedirectQueryParam(ownProps) || '/login',
  allowRedirectBack: true,
  authenticatedSelector: ({ firebase }) => pathToJS(firebase, 'auth') !== null,
  authenticatingSelector: ({ firebase: { auth } }) =>
  pathToJS(firebase, 'isInitializing') === true ||
  pathToJS(firebase, 'auth') === undefined,
  AuthenticatingComponent: <div />,
  wrapperDisplayName: 'UserIsAuthenticated',
})
export default Auth
```

```
// How decorator is used
@firebaseConnect()
@Auth
export default class Home extends Component {
// etc...
```

The error I'm getting is: 
```
Failed to compile

./src/decorators/auth.js
  Line 51:  'firebase' is not defined  no-undef
  Line 52:  'firebase' is not defined  no-undef
```

**Comment by prescottprue** [comment]
@NathHorrigan Looks like you are using the `v1.*.*` syntax and there is an issue in the `authenticatingSelector` (`({ firebase: { auth } }) ` should be, `({ firebase }) `).

**Comment by prescottprue** [comment]
Routing recipes docs have been updated. The examples update will be coming at some point, but if you have time to capture it in a pull request, totally open to it.
