### ISSUE TITLE
How to find uid directly after createUser()

### ISSUE THREAD

**Issue by 0x80** [prescottprue/react-redux-firebase#332]
I am trying to do something like this

```javascript
await firebase.createUser({ email, password })
const newId = firebase.auth().currentUser().uid;
doSomethingWithNewId(newId);
```
However I can't seem to find a way to fetch the new user id. I have to wait for my props to update, but then the redirect kicks in.

`currentUser` should be available on the Auth instance I think but maybe I'm misunderstanding the docs: http://docs.react-redux-firebase.com/history/v2.0.0/docs/api/firebaseInstance.html#auth

Is there a way to fetch the uid right after creating a new user?

**Comment by prescottprue** [comment]
`firebase.auth().currentUser` is not a function, but instead a property [as the firebase docs explains](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#currentUser).

That means you should be able to do:

```js
await firebase.createUser({ email, password })
const newId = firebase.auth().currentUser.uid;
doSomethingWithNewId(newId);
```

**Comment by 0x80** [comment]
Thanks! I thought I'd tried that already but apparently not. It's working now. 

However, it confused me that the docs say "Returns firebase.database.Auth". Or is that correct?

**Comment by prescottprue** [comment]
@0x80 You are right about that being incorrect. I put that on the todo list to fix, great catch.
