### ISSUE TITLE
[2.0] firestore.setListeners is not a function

### ISSUE THREAD

**Issue by 0x80** [prescottprue/react-redux-firebase#333]
I'm trying to use Firestore but run into this error

`firestore.setListeners is not a function`

I have imported firestore next to my firebase config like so:

```typescript
import { default as fb } from 'firebase';
import 'firebase/firestore' // add this to use Firestore
import { firebase as firebaseConfig } from '../config';

export const app = fb.initializeApp(firebaseConfig);
// initialize Firestore
fb.firestore()
export default fb;
```
My configure store contains this:

```typescript
const rootReducer = combineReducers({
  ...reducers,
  firebase: firebaseStateReducer,
  firestore: firestoreReducer as any,
  routing: routerReducer,
});

export default function configureStore(initialState: any = {}) {
  const store = createStore(
    rootReducer,
    initialState,
    composeEnhancers(
      reactReduxFirebase(firebase, config),
      reduxFirestore(firebase, {}),
      applyMiddleware(
        thunkMiddleware.withExtraArgument(getFirebase),
        promiseMiddleware,
        routerMiddleware
      )
    )
  );
```

And in my component I do this:

```typescript
export default compose(
  firebaseConnect(),
  firestoreConnect(),
  connect(({ firebase: { auth } }) => ({ auth }))
)(Triggers) as any;
```

Am I missing something?

I will get rid of firebase realtime db later, but for now they'll live next to each other if that's ok.

**Comment by prescottprue** [comment]
@0x80 All of this seems right, but did you wrap your top level component with `Provider` from `react-redux`? Its what makes store available within context, which contains `store.firebase` and `store.firestore` (placed there by the `reactReduxFirebase` and `reduxFirestore` enhancers respectively).

**Comment by 0x80** [comment]
Yes, I was already using firebaseConnect() successfully. I basically just added the firestore parts. So I don't get it.

Are you sure the two work together? Or should I try to remove the firebase middleware etc maybe?

**Comment by prescottprue** [comment]
Yes, I'm sure they work together (currently using them together in a project). I'll be debugging this over the weekend and see if we are missing something.

**Comment by 0x80** [comment]
Thanks. Let me me know if I can help.

**Comment by prescottprue** [comment]
@0x80 Try changing the order of them as well. I noticed there is an issue where `redux-firestore` where it can collide with `react-redux-firebase`. It may be unrelated, but I have the fix for the collision working on the [branch for this PR](https://github.com/prescottprue/redux-firestore/pull/21).

Glad to have some people helping test out the Firestore integration.

**Comment by 0x80** [comment]
@prescottprue Reversing them doesn't seem to make any difference. Leaving the arguments empty results in a different error:

`Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.`

**Comment by 0x80** [comment]
I've updated from beta 14 to 17 and now the error disappeared. Forgot that I was behind already.

However when I try to call `collection()` on the `firestore` instance from props, I now get the error `firestore.collection is not a function`.

**Comment by 0x80** [comment]
Ah sorry [RTFM](https://github.com/prescottprue/redux-firestore).

But, I would like to add a document to `commands/${userId}/register`. This is a collection in a document in a collection. The API for `add` has a collection and a document parameter.  How would I go about this?

**Comment by 0x80** [comment]
After sorting out permissions...all is working 🎉

**Comment by prescottprue** [comment]
@0x80 Ok great to hear! I'll close, thanks for reporting. If anything else isn't working as expected, let me know.
