### ISSUE TITLE
Navigation is not working using redux-saga

### ISSUE THREAD

**Issue by ankit7878** [prescottprue/react-redux-firebase#336]
I am trying to navigate to Main Screen and code still work fine if the JS DEBUGGER is ON(running) but the problem is when i try to run my application when JS DEBUGGER is OFF(disable) and try to login at that time "yield put(NavigationActions.navigate({ routeName: 'Main' }));" this piece code is not redirecting to Main screen.

Given below is my code:
import { NavigationActions } from 'react-navigation';
import { call, put, takeEvery, take } from 'redux-saga/effects';
import { getFirebase } from 'react-redux-firebase';

export function* watchLoginAsync({email, password}) {
  try {
    const response = yield getFirebase().login({email,password});
    if (response.uid) {
      // dispatchToMain();
      yield put(NavigationActions.navigate({ routeName: 'Main' }));
      // yield put({type: LOGIN_SUCCESS });
    } else {
      yield put({type: LOGIN_FAIL, error: 'Something went wrong seriously!!'});
    }
  } catch(err => console.log(err))
}

export default function* watchLogin() {
  yield takeEvery(LOGIN_REQUESTING, watchLoginAsync);
}

And this the store.js file(where i have integrated redux-saga with react-redux-firebase):
const sagaMiddleware = createSagaMiddleware();
const middleware = [ sagaMiddleware ];

const firebaseConfig = {
 apiKey: '****',
 authDomain: '****',
 databaseURL: '****',
 projectId: '****',
 storageBucket: '****',
 messagingSenderId: '****',
};

const reduxFirebaseConfig = {
 userProfile: 'users',
 enableLogging: true,
 enableRedirectHandling: false,
};

// Add redux Firebase to compose
const createStoreWithFirebase = compose(
 reactReduxFirebase(fbConfig, reduxFirebaseConfig),
 applyMiddleware(...middleware)
)(createStore);

// Add Firebase to reducers
const rootReducer = combineReducers({
 firebase: firebaseStateReducer,
 ......
});

// Create store with reducers and initial state
const initialState = {}
export default createStoreWithFirebase(rootReducer, initialState);

NOTE: code is totally working fine if JS DEBUGGER IS ON in iOS simulator while app is running.

**Comment by prescottprue** [comment]
@ankit7878 Did you try placing the `applyMiddleware` enhancer before the `reactReduxFirebase` enhancer in your create store call? The order you have things in currently could potentially cause your middleware to not get some stuff `reactReduxFirebase` (since `compose` stacks things from bottom to top).

Other than that, I will have to try to replicate myself. Do you have a project that I could run with this setup in it? It may not work as expected with routing, but if your project isn't easily shareable, feel free to create [a codesandbox](https://codesandbox.io/s/ymxky5jplx), [webpackbin](https://www.webpackbin.com/), or similar.

**Comment by ankit7878** [comment]
thanks. but still i tried placing the applyMiddleware enhancer before the reactReduxFirebase enhancer. but still not working while iOS simulator is disable.
now the thing is that i am using react-redux-firebase 1.5.1, am i dont what this code "enableRedirectHandling: false" is doing .could you tell me what this enableRedirectHandling is . because some where i have readed that it kind of stop navigation listeners.

though i will create a new git repo in few hours please check code and give me some suggestion.

**Comment by ankit7878** [comment]
hey, you can close this issue for now i really dont know how this 'yield put(NavigationActions.navigate({ routeName: 'Main' }));' statement statet working after few day i will try to upload code as soon as possible
