### ISSUE TITLE
bug (reducer): error using redux-persist v5

### ISSUE THREAD

**Issue by hwaterke** [prescottprue/react-redux-firebase#341]
This library does not seem to work with the latest version of redux-persist.
The state is not rehydrated.

```redux-persist/stateReconciler: sub state for key `firebase` modified, skipping.```

Here is my store config:

```js
const reduxPersistConfig = {
  key: 'root',
  storage,
  debug: true
};

const rrfConfig = {
  userProfile: 'users'
};

firebase.initializeApp(firebaseConfigDev);

const composeEnhancers =
  (typeof window === 'object' &&
    process.env.NODE_ENV === 'development' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) ||
  compose;

export const store = createStore(
  persistReducer(reduxPersistConfig, rootReducer),
  undefined,
  composeEnhancers(reactReduxFirebase(firebase, rrfConfig))
);

export const storePersistor = persistStore(store);
```

**Comment by jackkinsella** [comment]
I also couldn't get **react-redux-firebase** to play nicely with v5 of **redux-persist**. Here's my configuration (React Native):
````javascript
import { composeWithDevTools } from 'redux-devtools-extension';
import { createStore, applyMiddleware } from 'redux';
import { reactReduxFirebase } from 'react-redux-firebase';
import { persistStore } from 'redux-persist';
import { PersistGate } from 'redux-persist/lib/integration/react';

const reduxFirebaseConfig = {
  enableLogging: true,
  enableRedirectHandling: false
};

const firebaseConfig = {
   ...
}


const composeEnhancers = composeWithDevTools({ actionCreators });
const store = createStore(
  reducer,
  composeEnhancers(
    reactReduxFirebase(firebaseConfig, reduxFirebaseConfig),
    applyMiddleware(thunk, notificationsMiddleware)
  )
);
const persistor = persistStore(store);

render => (
      <PersistGate persistor={persistor}>
        <Provider store={store}>
            ...
        </Provider>
      </PersistGate>
)
````

Next up, here are the actions that were called by Redux:
![screen shot 2017-11-24 at 18 54 07](https://user-images.githubusercontent.com/151206/33220471-f181cee2-d148-11e7-83a2-ae30188a3006.png)

Finally, here are the log entries:
````
development-level warning are ON, performance optimizations are OFF
database.js:51 p:0: Making a connection attempt  
database.js:51 getToken() completed. Creating connection. 
database.js:51 c:0:0: Connection created  
database.js:51 c:0:0:0 Websocket connecting to wss://myProjecttName.firebaseio.com/.ws?v=5  
database.js:51 c:0:0:0 Websocket connected.  
database.js:51 c:0:0: Realtime connection established.  
database.js:51 p:0: connection ready  
database.js:51 p:0: reportStats {"c":{"sdk.js.3-9-0":1,"framework.reactnative":1}}  
database.js:51 p:0: {"r":1,"a":"s","b":{"c":{"sdk.js.3-9-0":1,"framework.reactnative":1}}}  
database.js:51 p:0: from server: {"r":1,"b":{"s":"ok","d":""}}  
database.js:51 c:0:0: sending ping on primary.  
database.js:51 c:0:0: got pong on primary.  
database.js:51 c:0:0: Primary connection is healthy.  
````

**Comment by prescottprue** [comment]
It seems like this might require removing the `REHYDRATE` action from the reducers, and possibly allow for a plugin setup similar to [how redux form does it](https://redux-form.com/7.1.2/docs/api/reducerplugin.md/).

I am going to work on adding redux-persist example to an example so that we can debug this better.

**Comment by victorkvarghese** [comment]
@prescottprue . is there any workaround for now?? Im using this awesome lib with redux persist v5 .. everything works great but the data is not getting persisted :/ 

Anyway to fix this ?? or atleast an ETA??

**Comment by victorkvarghese** [comment]
@prescottprue I will try to build a boilerplate with redux persist v5 and this lib .. will update it to u soon.

Problem is the reducer firebase is not getting persisted.
meaning the data object inside firebase is becoming blank on app relaunch.
but the auth section is persisted .. i think so..

"redux-persist/stateReconciler: sub state for key `firebase` modified, skipping."

Got this in log..

**Comment by ranfdev** [comment]
This happens because by default redux-persist uses the autoMergeLevel1. As stated in the docs: 

> Auto merge means if the some piece of substate was modified by your reducer during the REHYDRATE action, it will skip this piece of state.

react-redux-firebase modifies the state before and during the rehydrate, so it invalidates the auto merge.

You can use the ```hardSet``` state reconciler to be sure it gets rehydrated correctly. 
```js
import hardSet from 'redux-persist/lib/stateReconciler/hardSet'
const rootReducer = combineReducers({
  firebase: persistReducer(
    { key: 'firepersist', storage: myStorage, stateReconciler: hardSet },
    firebaseReducer
  ),
  anotherReducer,
  myBestReducer
});
```
Then you can use redux-persist as usual

**Comment by prescottprue** [comment]
@ranfdev Great to know, thanks for posting! Going to try that out myself, then I'll look into making an example.

**Comment by prescottprue** [comment]
Included notes about using v5 in the [redux-persist integration section of the docs](http://react-redux-firebase.com/docs/integrations/redux-persist.html#v5).

If anyone has trouble implementing, feel free to reach out. Thanks to @ranfdev for providing the solution.

**Comment by ranfdev** [comment]
I edited the previous comment because i discovered it's not necessary to use the hardSet stateReconciler. You just need to wrap the firebase reducer with ```persistReducer```. Also, hardSet is a bit brutal, so it's better to not use it

**Comment by prescottprue** [comment]
@ranfdev Great to know, I'll update the the docs.

**Comment by aliharriss** [comment]
Update: @ranfdev 's solution is still useful in 2021
