### ISSUE TITLE
uploadFileWithProgress is not defined

### ISSUE THREAD

**Issue by azimgd** [prescottprue/react-redux-firebase#346]
https://github.com/prescottprue/react-redux-firebase/blob/ed6b902aee8ca225b02e307b71ff1b93b4f9f6fe/src/actions/storage.js#L25

`uploadFileWithProgress` is not defined/included into compose. While i see relevant code and tests in place.
https://github.com/prescottprue/react-redux-firebase/blob/ed6b902aee8ca225b02e307b71ff1b93b4f9f6fe/src/compose.js#L325

Is there any particular reason for this ?

**Comment by prescottprue** [comment]
`uploadFileWithProgress` was intentionally not exposed as the goal was to have a single interface where you could choose to have progress or not. The [v2.0.0-beta.18 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.18) includes the option for progress when calling `uploadFiles` or `uploadFile`:

```
uploadFiles('storage/path', files, 'metadata/path', { progress: true })
```

The option is false by default, so if you want actions dispatched for progress while uploading, you have to provide the option as shown above. It will result in actions being emmitted for each progress update like so:

![image](https://user-images.githubusercontent.com/2992224/33531029-ad8d2f56-d83c-11e7-9a60-040c22149f8c.png)


The future plan is to have a whole reducer dedicated to storage specific interactions, but that is not yet in place (an update should make it back to this ticket when it is added).

**Comment by Louis-Chen** [comment]
@prescottprue How Could I Get progress value?

**Comment by Eli1bamboo** [comment]
> @prescottprue How Could I Get progress value?

Same question here.

**Comment by prescottprue** [comment]
@Louis-Chen and @Eli1bamboo The values are dispatched in the actions since the assumption was that this value would be streamed into a view. It should be in a reducer, so [#556 will capture adding that](https://github.com/prescottprue/react-redux-firebase/issues/556). Open to a PR if anyone gets a chance, otherwise I will try to get to it soon.

**Comment by Eli1bamboo** [comment]
@prescottprue thank you bro !! I tried to add an storage reducer on my own but ir didn't work. This level of code is up to my skills. I'll wait for the update. thanks again for your effort :)

**Comment by stevenhales** [comment]
Hi, any updates on this one? Or any guidance on how to access the progress payload on the fly in the meantime? I am without upload progress at the moment with the package. Thank you!

**Comment by prescottprue** [comment]
@stevenhales The progress payload is dispatched in actions as shown in the screenshot above.

To capture them and write to state, you will want to create a reducer that responds to `FILE_UPLOAD_PROGRESS` which can be imported like so:

```js
import { actionTypes } from 'react-redux-firebase'
// Create a reducer using the following action type:
actionTypes.FILE_UPLOAD_PROGRESS
```

As noted, #556 will track adding this as a feature.
