### ISSUE TITLE
difference with other lib + size ?

### ISSUE THREAD

**Issue by flieks** [prescottprue/react-redux-firebase#35]
Hi,

What is the difference with the other lib 
https://github.com/tiberiuc/redux-react-firebase ? 
What is the size of this lib ?

Thanks
Felix

**Comment by prescottprue** [comment]
For the difference, please view the [FAQ Section of the README](https://github.com/prescottprue/react-redux-firebase#faq).

**Comment by flieks** [comment]
ok thanks for the info
