### ISSUE TITLE
Fix 2.0 beta documentation error for getting started

### ISSUE THREAD

**Issue by omoki** [prescottprue/react-redux-firebase#350]
According to the migration guide, the reactReduxFirebase function no longer takes firebaseConfig as an argument. Rather, firebase object that is already initialized should be passed in.

The error in documentation is found in getting started guide under [Compose Function](https://github.com/prescottprue/react-redux-firebase/blob/v2.0.0-beta.18/docs/getting_started.md#compose-function)

The following seems to be the correct way:

## Compose Function

```js
import { compose } from 'redux'
import { reactReduxFirebase } from 'react-redux-firebase'
import firebase from 'firebase';

// Firebase config
const firebaseConfig = {
  apiKey: '<your-api-key>',
  authDomain: '<your-auth-domain>',
  databaseURL: '<your-database-url>',
  storageBucket: '<your-storage-bucket>'
}

firebase.initializeApp(firebaseConfig); //------------> ADDED

// react-redux-firebase options
const config = {
  userProfile: 'users', // firebase root where user profiles are stored
  enableLogging: false, // enable/disable Firebase's database logging
}

// Add redux Firebase to compose
const createStoreWithFirebase = compose(
  reactReduxFirebase(firebase, config) //--------------> SUGGESTED FIX
)(createStore)

// Create store with reducers and initial state
const store = createStoreWithFirebase(rootReducer, initialState)
```

**Comment by prescottprue** [comment]
Fixed in [v2.0.0-beta.18 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.18). Thanks for reporting.
