### ISSUE TITLE
question(Usage Confusion)

### ISSUE THREAD

**Issue by Jonovono** [prescottprue/react-redux-firebase#351]
Hi. So I am looking to integrate this into a RN app. I am using firebase and redux, but not currently this library. I have my redux state currently set up as so:

```
{
    "user": {},    // just me
    "contacts": {},    // many with `userId` as the key
    "room": {}    // some info on the room I am in
}
```

So what I currently do is I set up listeners on app load on different FB paths and onChange/onCreate etc I dispatch actions which will place the data in the right place. For example, I get a new friend they will get added to the `contacts` store.

With this in my components I can just get the data directly from the store that I need to display. 

Now looking at this library I would replace my state architecture above with this:

```
{
  firebase
}
```
And then on every component I need data on I set up listeners for whatever data that component needs from firebase. Is this correct?

I guess what I am confused about is say I need the `contacts` info in multiple different components. I am now listening for the same events on each of those components, instead of just setting up one listener that places the data into the store and the components can just read from directly and will change when the state changes.

**Comment by prescottprue** [comment]
**No**, you do not necessarily need listeners for whatever components need data from Firebase. You can create listeners in a parent component and then connect to state in any other component.

Though it is a common pattern `firebaseConnect` and `connect` on the same components when building really simple applications, in larger applications many of your components can/will have no idea how data got into state, they just `connect` to a certain location in state, and render something if there is data there.

`firebaseConnect` attaches and detaches listeners only (`connect` handles getting data from state). That means that getting data into state (for Firebase data that is creating listeners) can be left for more higher level components where it makes the most sense.

**Comment by Jonovono** [comment]
Hey @prescottprue , a question related to this. Say I am using `populate`. How can I persist that value to the redux store so that on other components that I want to use that populated data within I don't have to set up the same populate query? Is that possible to do?

Thanks.

**Comment by prescottprue** [comment]
Populating profile parameters is mentioned within the [profile recipes section of the docs](http://docs.react-redux-firebase.com/history/v2.0.0/docs/recipes/profile.html#populate-parameters).

Also, unrelated to your question, but having filtering within `connect` can cause issues of unwanted re-rendering. You may want to use something like [reselect](https://github.com/reactjs/reselect) to make selectors if you are doing filtering of state (as seen in your example). [recompose](https://github.com/acdlite/recompose) is also extremely helpful for things like this (since it has HOCs like `mapProps`).

**Comment by Jonovono** [comment]
Thanks, what if it's not a profile parameter I want to populate?

And ya hah. I'm going to be looking into one of those next :p Thanks for the reminder!

**Comment by prescottprue** [comment]
@Jonovono When you use populate with parameters other that `profile` (i.e. passing to `firebaseConnect`), the data that results from the populate queries is written into redux therefore making it available to your other components.

Is there anything still unanswered here or should we close?
