### ISSUE TITLE
Dynamic limitToLast (load more feature)?

### ISSUE THREAD

**Issue by sushant23** [prescottprue/react-redux-firebase#355]
First of all, thank you so much for this awesome project, it is really helping us with our workflow.

I wanted to know if there is a way to make `limitToLast` query dynamic. My use case I want to create a chat app where I need to sync just 20 message at first and upon scrolling I need to sync 20 more data and so on. 

I would really appreciate any help

**Comment by prescottprue** [comment]
`firebaseConnect` accepts a function, which means that you can pass props and use them within your queryParams. It is common to have have query parameters from react-router be passed as props, so that your URL can show which data is loaded on the page.

```js
firebaseConnect((props) => {
  return [
    {
       path: 'todos',
       queryParams: [`limitToLast=${props.group}`]
    }
  ]
})
```

**Comment by sushant23** [comment]
Got it thank you so much.
