### ISSUE TITLE
bug(auth): login with custom token throws error

### ISSUE THREAD

**Issue by Ionut-Milas** [prescottprue/react-redux-firebase#359]
Hello,
I am using react-redux-firebase with redux-thunk to make an custom auth with LinkedIn.
I am following Google's repo here: https://github.com/firebase/functions-samples/tree/master/linkedin-auth.
All works fine, i get the token but when I call the login function auth get populated for a second and then an error message appears in console and auth is emptied.
In the DB the user is created, details are saved, everything looks good there.
What am I doing:

the token looks like this:
`{token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJsa…8B8rJkHpoAXk9uKT6lCppRzAUzHJ_bJQXwr709dfUqdaQolFQ"}`

I call the login function:
`this.props.firebase.login( { token: res.data.token } );`

The component is connected to Firebase:
`export default firebaseConnect()( Auth )`

This is the error that I get:
`validation.js:218 Uncaught Error: Reference.update failed: First argument  must be an object containing the children to replace.
    at Object../node_modules/@firebase/database/dist/cjs/src/core/util/validation.js.exports.validateFirebaseMergeDataArg (validation.js:218)
    at Reference../node_modules/@firebase/database/dist/cjs/src/api/Reference.js.Reference.update (Reference.js:140)
    at auth.js:170`

Here is how Redux state is looking:
<img width="775" alt="screen shot 2017-12-12 at 11 03 04" src="https://user-images.githubusercontent.com/8121277/33875786-1b6b1d58-df2c-11e7-9453-c195a4f07f25.png">

On login the auth get populated and then the profile, but afterwards that error appears and auth get cleared.

If I do a refresh the the user appears logged in.

Thank you for your help.

**Comment by Ionut-Milas** [comment]
It appears that by default updateProfileOnLogin is true and it updates the profile with an undefined object.
I added in config the following  `updateProfileOnLogin:false` and now it is working.
If you have any insight into this, would be greatly appreciated.

**Comment by Ionut-Milas** [comment]
@prescottprue Rules are the default ones 
`{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}`
`UNAUTHORIZED_ERROR` returned `{}`.
The strangest thing was that for a second the user was logged in.
I conditionally display a menu based on the auth state and it appeared for a second or so until the `UNAUTHORIZED_ERROR` popped.
I caught that error with `validation.js:218` on the .catch() phase of `this.props.firebase.login`.

**Comment by prescottprue** [comment]
@Ionut-Milas I may have an insight into what is going on (think it has to do with the profile not being passed with custom token) but going to test further. Hope fully `updateProfileOnLogin:false` works for you for now.

**Comment by Ionut-Milas** [comment]
@prescottprue thanks for your support on this matter!
It works with with `updateProfileOnLogin:false`

**Comment by Modestas** [comment]
Nice work! I just bumped into the same problem as defined here.

**Comment by prescottprue** [comment]
`v2.0.0-rc.2` is not yet released to npm, but the branch includes support for the `profile` param as shown above. Release coming soon.

**Comment by prescottprue** [comment]
The [`v2.0.0-rc.2` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-rc.2) includes support for the `profile` param as shown above.

@Ionut-Milas and @Modestas reach out if this doesn't cover your use case, and we can reopen.

**Comment by ghadisaurabh** [comment]
@Ionut-Milas can you share you code please? as I also using react-redux-firebase for my home project and I also want to login with linkedin.
