### ISSUE TITLE
bug(firestore): profile update error when using Firestore

### ISSUE THREAD

**Issue by QuentinBrosse** [prescottprue/react-redux-firebase#360]
Hi,

Thanks for your great library. I use it with `react-native-firebase` but I want a little issue with profile creation / update with firebase.
I want the current to be always connected (anonymously or by email/password) will using the app. 

# Auth Flow
So here is my auth flow when the user si not signed in yet:

1. Sign In Anonymously
``` js
firebase.auth().signInAnonymously()
```
2. The user discovers the app..
3. The want to create a permanent account and give me this credential (email/password)
4. Link the anonymous user with the credential
``` js
const credential = firebase.auth.EmailAuthProvider.credential(email, password);
const user = await firebase.linkWithCredential(credential);
user.sendEmailVerification();
```
5. Update the profile:
``` js
firebase.updateProfile({ firstName: 'Tic', lastName: 'Tac'});
```

# Problem
Here is my redux firebase config:
``` js
const reduxFirebaseConfig = {
  userProfile: 'users',
  useFirestoreForProfile: false,
  enableRedirectHandling: false,
};
```

If I use the `Real Time Database` to run my auth flow, everything is working perfectly. `updateProfile` create the `/users` path and add the profile into the `Real Time Database`.

**But** if I user `Firestore` to run the same auth flow (by changing the `useFirestoreForProfile` to  `true` in my `reduxFirebaseConfig`), I have a `@@reactReduxFirebase/PROFILE_UPDATE_ERROR` with the message `Firestore: Some requested document was not found. (firestore/not-found).`.

It is an expected behavior or a bug ? :/
Do you see something wrong in my auth flow ?

# One more thing
I have also noticed that the `firebase.linkWithCredential` ignore the `profileFactory` (with or without `Firestore`). It could be interesting to use it like the `firebase.createUser` no ?
And for now, do you have a work around or I need to manage it manually ?

# Dependencies versions
``` json
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-firebase": "^3.1.1",
"react-redux": "^5.0.6",
"react-redux-firebase": "^2.0.0-beta.18",
"redux": "^3.7.2",
"redux-firestore": "0.1.0-beta.6",
```

This is my first time with your library, so I don't know it I was working in previous versions or setups.

Thanks a lot for the library and your help ! :)

**Comment by barnomics** [comment]
I have just stumbled into the same error ... i have a fix if @prescottprue isn't already on it

**Comment by barnomics** [comment]
The profile _does_ actually update in Firestore but the error is thrown regardless

**Comment by barnomics** [comment]
the last line in auth.js needs to change to... 
```javascript
export const updateProfileOnFirestore = (firebase, profileUpdate) => {
  const { firestore, _: { config, authUid } } = firebase
  const profileRef = firestore().doc(`${config.userProfile}/${authUid}`)
  return profileRef
    .update(profileUpdate)
    .then(() => { return profileRef.get() });
}
```

**Comment by prescottprue** [comment]
@QuentinBrosse and @barnomics [`v2.0.0-rc.2`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-rc.2) includes this change.

Just as a side note: it is noted in the release, but v2.0.0 is stable so it will be going into master soon.
