### ISSUE TITLE
feat(populate): populate object of keys

### ISSUE THREAD

**Issue by 0xClpz** [prescottprue/react-redux-firebase#361]
Hello,
First of all, thank you for creating this library, it's really great.

My question is the following, how can I populate an Object of keys using your library when I don't know the child in advance?

Here's what my data structure looks like

```JSON
{
  "subscriptions/{some_user_id}": {
    "-k43216543": true,
    "-43dffRERE": true
  }
}
```

Where the keys are IDs for resources somewhere under /something/{resource_id} 

Thanks, Antonio.

**Comment by prescottprue** [comment]
@0xClpz If I am understanding your question correctly, then there is not yet a great solution for this. 

You should be able to get something working by querying the whole collection and populating each like so:

```js
import { compose } from 'redux'
import { connect } from 'react-redux'
import { firebaseConnect, populate } from 'react-redux-firebase'

const createPopulates = (props) => [{ ]

// Pass uid as a prop
const enhance = compose(
  firebaseConnect((props) => [
    { path: 'subscriptions', populates: createPopulates(props) }
  ]),
  connect(({ firebase }, props) => ({
    subscriptions: populate(firebase, 'subscriptions', createPopulates(props))
  }) 
)
```

An issue with this is that you are loading the whole `subscriptions`collection then populating just the one user's subscription list, but querying the whole list may not be ideal as data size grows.

It would be great if `populate` handled something like this, so I am going to put looking into a better solution for this on the roadmap. Always open to PRs if you dive into the source. Thanks for reaching out with your use case!

**Comment by prescottprue** [comment]
@0xClpz Just wanted to make sure I understand what you are asking for:

Is this to populate one user (i.e. the current user's) subscriptions or are you hoping to query/populate multiple users subscriptions at once?

**Comment by prescottprue** [comment]
@0xClpz Ping - Wanted to confirm the use case.

**Comment by prescottprue** [comment]
@muniperez Glad you enjoy it!

Unless I am misunderstanding, querying a single user at one time then you should be able to do a standard population on posts (especially since it is key/true):

```js
import { compose } from 'redux' // or recompose
import { firebaseConnect, populate } from 'react-redux-firebase'

// assuming you are populating from the "posts" root collection
const populates = [{ child: 'posts', root: 'posts' }]

const enhance = compose(
  connect(({ firebase: { auth } }) => ({ auth }),
  firebaseConnect(({ auth }) => [
    { path: `userFeed/${auth.uid}`,  populates }
  ]),
  connect(({ firebase }) => ({ 
    userFeed: populate(firebase, `userFeed/${auth.uid}`, populates)
  })
)

// Enhance your component
enhance(SomeComponent)
```

**Comment by muniperez** [comment]
Thank you Scott!

However, that’s not exactly the problem. That was the solution I was using before but now I need to implement pagination on the “/posts” child.

So now my path is /userFeed/{id}/posts - with limitToLast. So on my “populates” config I cannot associate a child anymore, because the root of the response already has the list of items.

My suggestion is to add a way of populating a list without a child, in a way that it populates each list item.

Thanks.

**Comment by prescottprue** [comment]
@muniperez That sounds like a slightly different feature than the original ticket. What are your thoughts on opening another issue to track a "custom populate query" feature you are mentioning -- it could allow for changing the query which is used to gather populate data.

The new ticket we are mentioning could be a great place to capture the functionality mentioned in #69 as well.

**Comment by muniperez** [comment]
@prescottprue sure thing! I will do that.

**Comment by muniperez** [comment]
@0xClpz  I would suggest you modify the structure of your database with data fan out.

Alongside with "subscriptions/{user_id}", you can duplicate the data and add a "{user_id}/subscriptions" and then list the user's subscription.

So whenever a user creates a subscription, you can either add both updates:

`updates = {}
updates[`/subscriptions/${user_id}/{subscription_id}`] = true
updates[`/users/${user_id}/subscriptions/{subscription_id}`] = true
firebase.ref().update(updates)
`
Or you can add a listener to the path '/subscriptions/{user_id}' to copy the data to the additional path.

Hope it solves your problem ;)

**Comment by prescottprue** [comment]
Going to close since @muniperez posted a workaround for the original issue (which has been dormant).

@0xClpz Feel free to reach out if it doesn't handle your use case.
