### ISSUE TITLE
How to query user specific data within firebaseConnect (incl. population)

### ISSUE THREAD

**Issue by ralcon** [prescottprue/react-redux-firebase#372]
Hi,

i'm working with react-native and have the problem to load only user specific data with `firebaseConnect`. Imagine there are thousends of `todos`, `users` and `doers` and don't want to reference all elements of them.

First of all, a shortcut of my data structure in the real time database:
```
- todos
  |- cleanRoom
  |    |- createdBy: alica
  |    |- title: "Clean the room up"
  |    |- doerList
  |        |- roomCleanerMichael
  |        |- roomCleanerAlica
  |- playBall
       |- createdBy: michael
       |- title: "Play the ball"
       |- doerList
           |- ballPlayerAlica

- users
  |- michael
  |    |- name: Michael
  |    |- age: 22
  |- alica
       |- name: Alica
       |- age: 27

- doers
  |- roomCleanerMichael
  |    |- user: michael
  |    |- status: done
  |- roomCleanerAlica
  |    |- user: alica
  |    |- status: done
  |- ballPlayerAlica
       |- user: alica
       |- status: done
``` 
I have a view/screen in RN, where all informations should be displayed. For now, i have...
```
const populatesTodoCreator = [{child: 'createdBy', root: 'users'}]

const mapStateToProps = (state, props) => {
  return {
    todos: populate(state.firebase, 'todos', populatesTodoCreator),
    uid: state.firebase.auth.uid
  }
}

export default compose(
  firebaseConnect((props, store) => {
      return [
        {path: 'todos', populatesTodoCreator},
      ]
    }
  ),
  connect(mapStateToProps, mapDispatchToProps)
)(TodoOverviewScreen)
```
When i log in the application with `firebase.auth.uid = michael`, i only want to reference the list of `todos`, where `michael` participates in as `doer` and populate all `doers` in `doersList` (including the `user` in a specific `doer`), and that all in only one single `compose` method.

So the redux state should look like:
```
- todos
  |- cleanRoom
      |- createdBy
      |    |- name: Alica
      |    |- age: 27
      |- title: "Clean the room up"
      |- doerList
           |- roomCleanerMichael
           |     |- user
           |     |    |- name: Michael
           |     |    |- age: 22
           |     |- status: done
           |- roomCleanerAlica
                 |- user
                 |    |- name: Alica
                 |    |- age: 27
                 |- status: done
```
Is this task possible? If yes, how do i get this done? Any structural suggestions?

PS: Is it possible to donate over **paypal**? I don't have a credit card!

**Comment by prescottprue** [comment]
If I am understanding correctly - yes it is possible to populate both`createdBy` and `doerList`. That would be done by providing multiple populates:

```js
const populatesTodoCreator = [
  { child: 'createdBy', root: 'users' },
  { child: 'doerList', root: 'doers' }
]

compose(
  firebaseConnect((props, store) => {
    return [
       { path: 'todos', populates: populatesTodoCreator }, // make sure to pass "populates"
    ]
  }),
  connect((state, props) => {
    return {
      todos: populate(state.firebase, 'todos', populatesTodoCreator),
      uid: state.firebase.auth.uid
    }
  })
)
```

Something to note: I believe where you are passing your populates parameter incorrectly, which will prevent the population queries from being created under the hood.

```js
firebaseConnect((props, store) => {
  return [
    // {path: 'todos', populatesTodoCreator}, <- wrong
    { path: 'todos', populates: populatesTodoCreator },
  ]
})
```


Glad to hear you are interested in helping the cause! To donate through paypal, please [visit this url](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=453DRUQ8DYXB8&lc=US&item_name=React%20Redux%20Firebase&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted) (this link or something will soon get added to the README)

**Comment by ralcon** [comment]
Hi, thank you very much! You are right. It was an incorrect passing of parameters. Now, it works as expected!
But what about diving into a deeper level, populating the `user` for every entry in the `doerList`?

**Comment by prescottprue** [comment]
@ralcon That is something we called "child populates" and it is [described in #85](https://github.com/prescottprue/react-redux-firebase/issues/85). 

The redux side of it is easy enough, but I think it has been long running due to the query managing side of it. It would be fun to tackle, but I haven't had the time yet.
