### ISSUE TITLE
bug(signInWithPhoneNumber): actions may not have an undefined "type" property

### ISSUE THREAD

**Issue by jacobfunch** [prescottprue/react-redux-firebase#374]
Error when calling `props.firebase.signInWithPhoneNumber(phoneNumber)`:
```Uncaught Error: Actions may not have an undefined "type" property. Have you misspelled a constant?```

Furthermore would be nice with better documentation for `signInWithPhoneNumber`: http://react-redux-firebase.com/docs/auth.html#signinwithphonenumbercode – it is not entirely clear if one need to pass the reCAPTCHA.

**Comment by prescottprue** [comment]
@jacobfunch You are correct, the reCAPTCHA verifier does need to be passed. The [docs have been cleaned up](http://react-redux-firebase.com/docs/auth.html#signinwithphonenumbercode) to make this more clear.

[`v2.0.1` was released](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.1) with a fix for the dispatch issue.

The material example also shows using it through `login`.

Let me know if it doesn't work as you expect or you are still having issues.
