### ISSUE TITLE
orderByChild and equalTo breaks for an unknown reason

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#38]
Hello again :)

The below example works for me (it returns goals where uid is my id), but it does not work for other users - for others it returns `{ "my_id": null }` where `my_id` is `8ias7814o24j...`
```js
@connect((state) => ({
  goals: helpers.dataToJS(state.firebase, 'goals'),
}))
@firebaseConnect((props) => ([
  `/goals#orderByChild=uid&equalTo=${ props.uid }`,
]))
```

However, this hand made query returns the list of objects as expected.
```js
this.props.firebase.ref('goals').orderByChild('uid').equalTo(this.props.uid).once('value').then(snapshot => {
      console.log('Here');
      console.log(snapshot.val());
    }),
```

So I suspect that somewhere must be a bug. Appreciate your help ;)

**Comment by prescottprue** [comment]
Do you have an auth connect before? Or is there a parent component that passes auth down as a prop?

Remember that wrapping goes in order, so you would want:

```js
@connect(({firebase}) => ({
  auth: helpers.pathToJS(firebase, 'auth'),
}))
@firebaseConnect((props) => ([
  `/goals#orderByChild=uid&equalTo=${ props.uid ? props.uid : '' }`, // handle there being no auth.uid
]))
@connect(({ firebase }) => ({
  goals: helpers.dataToJS(firebase, 'goals'),
}))
```

**Comment by DeividasK** [comment]
It is not a problem with auth, because it does not work even if I hard code the user id.

**Comment by prescottprue** [comment]
Since order of the connect decorators matters, is there a reason why you are placing the `connect` before the `firebaseConnect`?

**Comment by DeividasK** [comment]
Yes, because I get auth data. My full connect:

```js
@connect((state, props) => ({
  heading: state.tutorial.heading,
  actions: state.tutorial.actions,
  auth: helpers.pathToJS(state.firebase, 'auth'),
  goals: helpers.dataToJS(state.firebase, 'goals'),
  tutorial: helpers.dataToJS(state.firebase, `users/${helpers.pathToJS(state.firebase, 'auth').uid}/tutorial`, {})
}))
@firebaseConnect((props) => ([
  { path: '/goals', queryParams: [ 'orderByChild=uid', `equalTo=${ props.auth.uid ? props.auth.uid : '' }` ], populates: [{ child: 'partner', root: 'users' }] },
  `users/${props.auth.uid}/tutorial`
]))

**Comment by prescottprue** [comment]
Again though. Having goals be after you have loaded the goals is important:

```js
@connect((state, props) => ({
  heading: state.tutorial.heading,
  actions: state.tutorial.actions,
  auth: helpers.pathToJS(state.firebase, 'auth'),
  goals: helpers.dataToJS(state.firebase, 'goals'),
  tutorial: helpers.dataToJS(state.firebase, `users/${helpers.pathToJS(state.firebase, 'auth').uid}/tutorial`, {})
}))
@firebaseConnect((props) => ([
  { path: '/goals', queryParams: [ 'orderByChild=uid', `equalTo=${ props.auth.uid ? props.auth.uid : '' }` ], populates: [{ child: 'partner', root: 'users' }] },
  `users/${props.auth.uid}/tutorial`
]))
@connect((state, props) => ({
  goals: helpers.dataToJS(state.firebase, 'goals'),
}))
```

**Comment by DeividasK** [comment]
Tried that, doesn't work.

**Comment by prescottprue** [comment]
Attempting to replicate now.

If you have a repo you can share me on, I can look at that too.

**Comment by DeividasK** [comment]
Repo: https://github.com/DeividasK/my-future-ai
Project page: https://tgoals.com
Login and go through tutorial and at Step 1 when you add your goals and refresh a page you can check the console for responses.

This is the specific container wrapper that I'm referring to: https://github.com/DeividasK/my-future-ai/blob/master/app/containers/tutorial/wrapper.js

**Comment by prescottprue** [comment]
Forking now. Are you on [the gitter channel](https://gitter.im/redux-firebase/Lobby)? I might be faster at responding on there.

**Comment by prescottprue** [comment]
Responded to you in gitter, but the application appears to be functioning as intended for me, including after refresh.

**Comment by DeividasK** [comment]
In case this happens to others, this was something to do with the database. I have removed the user, for whom this was not working, and the data associated with the user. Then I signed up with the same user and it worked as expected.
