### ISSUE TITLE
Usage Question: Is there a purpose for listening to refs (firebaseConnect) if you can get everything from Profile state?

### ISSUE THREAD

**Issue by csumrell** [prescottprue/react-redux-firebase#383]
I have been using the library for awhile and manually listening to users/uid/ ref nodes in all my components. However, I realized every time those nodes are updated, SET PROFILE is called as well. 

So is there any point to doing these users/uid/ manual refs? Couldn't I just forgo them and use Profile from connect and use the user's data I need from there? The only data the app uses is from the user's profile

 Am i missing something obvious or just doing double work for no benefit?

Thanks

**Comment by prescottprue** [comment]
@csumrell Yes you can! If you set the `userProfile: 'users'` config option then the `users/${uid}` path will be automatically handled for you. There is even support for [populating profile params through `profileParamsToPopulate`](http://react-redux-firebase.com/docs/recipes/populate.html#populate-profile-parameters).

There is no inherent added benefit from doing it by hand. On a more positive note: You do get the extra practice as well as the understanding of what is being done for you automatically (which I personally feel is an important part of using libraries).
