### ISSUE TITLE
[bug] LOGIN is called after SET_PROFILE (Logout/Login) issue

### ISSUE THREAD

**Issue by evgeni-tsn** [prescottprue/react-redux-firebase#401]
Just submitted a pull request for the issue below -> #402 

I have a react app with **login / logout** functionality using this library.
I noticed a strange bug which I tracked down and I have a solution for it.

If you are logged in and you logout then relogin again without refreshing the web page, the `firebase.profile` object stays empty.

That is happening only if we go from: 
**logged in -> logged out -> logged in again**.
![image](https://user-images.githubusercontent.com/7677924/35882243-280cd3ee-0b8c-11e8-9e61-d8a032bbc756.png)

After I checked the two actions that are dispatched (**LOGIN** and **SET_PROFILE**) it looks that the SET_PROFILE is called first and sets the profile object right and after that the **LOGIN** is being dispatched and it wipes the profile data. Here are the screenshots.
The objects looks good after SET_PROFILE
![image](https://user-images.githubusercontent.com/7677924/35882378-acda4e76-0b8c-11e8-9739-99c60fac5b8b.png)
And then it is cleared by LOGIN
![image](https://user-images.githubusercontent.com/7677924/35882413-ca532ffe-0b8c-11e8-9802-71a7d7c2e159.png)

Although this is not happening if open the web app in logged out state and just login.
After some debugging I found where the issue is. 
In **actions/auth.js** in **handleAuthStateChange** currently the library is dispatching **LOGIN** after the **watchUserProfile()**.

If we replace the order of that two all goes well and the issue is fixed.

![image](https://user-images.githubusercontent.com/7677924/35883039-a453d464-0b8e-11e8-96d4-6e7d95d3ca23.png)

I can submit a PR for that if you agree that there is an issue.

Windows 10
Versions:
    "react": "16.2.0",
    "react-redux-firebase": "2.0.3",

PR -> #402

**Comment by prescottprue** [comment]
Included in [`v2.0.4` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.4). Thanks for reporting and providing the PR!
