### ISSUE TITLE
bug(updateProfile): no document to update when persisting Profile in Firestore

### ISSUE THREAD

**Issue by cosminstefanxp** [prescottprue/react-redux-firebase#403]
**What is the current behavior?**
When configuring React Redux Firebase to persist profiles in Firestore (i.e. ` useFirestoreForProfile: true`), if there is no document already created for the user in Firestore, the following error occurs when trying to write anything in the profile via `firebase.updateProfile`: 
> No document to update: projects/example/databases/(default)/documents/users/{user_id}

**Replication steps:**
1. Configure the library to use firestore for profile:
```
const rrfConfig = {
    userProfile: 'users',
    useFirestoreForProfile: true, // Firestore for Profile instead of Realtime DB
};

...
createStore(
   combineReducers(...),
   compose(
        reactReduxFirebase(firebase, rrfConfig),
        reduxFirestore(firebase, rrfConfig),
        applyMiddleware(thunk)
   )
)
```
2. Inject firebase into a component via `connect` and `withFirebase`;
3. Try to update the profile:
```
this.props.firebase.updateProfile({field: 'example'});
```
4. The following error is thrown:
> No document to update: projects/example/databases/(default)/documents/users/{user_id}

If I manually create an empty document at the right path with `user_id` in the Firestore dashboard, things work fine.

**What is the expected behavior?**
The document should be created automatically and the above error should not be thrown.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Using:
```
    "react-redux": "5.0.6",
    "react-redux-firebase": "2.0.3",
    "redux": "3.7.2",
    "redux-firestore": "0.2.6",
    "firebase": "4.9.0",
```

**Comment by prescottprue** [comment]
Included in [`v2.0.4` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.4). Thanks for reporting!
