### ISSUE TITLE
question(firestoreConnect): how to use firestoreConnect() 

### ISSUE THREAD

**Issue by michaelspeed** [prescottprue/react-redux-firebase#408]
i have simple component - 

    class Channels extends Component {

    static contextTypes = {
        store: PropTypes.shape({
            firestore: PropTypes.object
        })
      }

    state = {
        channelList: []
    }

    componentDidMount() {
        const { firebase } = this.context.store
        console.log(this.context)
    }

    render() {
        const { theme } = this.context
        console.log(this.props)
        return (
            <FocusZone direction={FocusZoneDirection.vertical} style={{ marginTop: 20 }} className='ms-slideDownIn20'>
                <List
                    items={this.state.channelList}
                    onRenderCell={this.onRenderCell}
                />    
            </FocusZone>
        )
    }

    onRenderCell = item => {
        return (
            <PrivateChannelItem item={item} user={this.props.user} />
        )
    }
    
    }

    export default compose(
    firestoreConnect(['stores']),
    connect((state, props) => ({
      stores: state.firestore.channels
    }))
     )(Channels)

but whenever i user firestoreConect() this error pops up

`firestoreConnect.js:98 Uncaught TypeError: Cannot read property 'unsetListeners' of undefined
    at FirestoreConnect.componentWillReceiveProps (firestoreConnect.js:98)
    at callComponentWillReceiveProps (react-dom.development.js:6389)
    at updateClassInstance (react-dom.development.js:6575)
    at updateClassComponent (react-dom.development.js:7848)
    at beginWork (react-dom.development.js:8225)
   `

if i do the manual way with  - 
 
       firebase.setListener({collection: 'todos'})

i get this error - 

`firebase.setListener is not a function`

what am i doing wrong?

**Comment by prescottprue** [comment]
Did you follow the [setup guide in the Firestore docs](http://react-redux-firebase.com/docs/firestore.html)? It requires passing `reduxFirestore` along with `reactReduxFirebase` when you are creating your store.

Without this, firestore will not be attached to `store`, which is passed through context to allow usage on HOCs such as `firestoreConnect`.

**Comment by michaelspeed** [comment]
my store creation is like this - 

    export default function configureStore(initialState, history) { 
      var firebaseConfig = {
      }

      firebase.initializeApp(firebaseConfig)
      firebase.firestore()

     const createStoreWithMiddleWare = compose(
        reactReduxFirebase(firebase, {
           userProfile: 'users',
           useFirestoreForProfile: true,
           enableLogging: false,
           attachAuthIsReady: true
        },
        reduxFirestore(firebase),
        typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ? 
         window.devToolsExtension() : f => f  )
          )(createStore)
         const store = createStoreWithMiddleWare(rootReducer)
        return store
      }

**Comment by michaelspeed** [comment]
this also does not work 

    componentWillMount () {
        const { firebase } = this.context.store
        firebase.setListener('todos')
        // firebase.setListener({ collection: 'todos' }) // or object notation
     }

     componentWillUnmount() {
        const { firebase } = this.context.store
        firebase.unsetListener('todos')
        // firebase.unsetListener({ collection: 'todos' }) // or object notation
      }


error - 

      firebase.setListener() is not  a function

**Comment by prescottprue** [comment]
It looks like you may have a typo:

```js

 const createStoreWithMiddleWare = compose(
    reactReduxFirebase(firebase, {
       userProfile: 'users',
       useFirestoreForProfile: true,
       enableLogging: false,
       attachAuthIsReady: true
    }, // <- you forgot ")" here. Which means you are just passing more arguments to reactReduxFirebase
    reduxFirestore(firebase),
```

**Comment by michaelspeed** [comment]
this is working! 
i would say this is the most stupid thing this year 😄
