### ISSUE TITLE
Expose unsupported methods

### ISSUE THREAD

**Issue by katha247** [prescottprue/react-redux-firebase#41]
Hi! 

Is there a way to expose firebase methods which are not supported by the framework? For example, I would like to use the method [sendPasswordResetEmail](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#sendPasswordResetEmail). If yes, what would be the best way to achieve it? 

Thanks in advance

**Comment by DeividasK** [comment]
Just to confirm - this.props.firebase.sendPasswordResetEmail() doesn't work?

If that does not work, you can always import raw firebase object and use that for any not supported functionality:
```js
import { getFirebase } from 'react-redux-firebase'

getFirebase().sendPasswordResetEmail()
```

**Comment by prescottprue** [comment]
@katha247 there is full access to [Firebase's auth]() through `firebase.auth` including [`sendPasswordResetEmail`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#sendPasswordResetEmail)

An example component could use it like so:

```js
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { firebaseConnect, helpers } from 'react-redux-firebase';

const { isLoaded, isEmpty, pathToJS } = helpers;

@firebaseConnect()
export default class Login extends Component {
  static propTypes = {
    firebase: PropTypes.shape({
      auth: PropTypes.func.isRequired,
    }),
  }

  sendResetEmail = () => {
    this.props.firebase.auth()
      .sendPasswordResetEmail()
      .then(() => {
         console.log('email sent successfully');
      })
      .catch((err) => {
          console.error('Error sending password reset email:', err)
       })
  }

  render() {
    return (
      <div>
        <button onClick={this.sendResetEmail}>Send Reset Email</button>
      </div>
    );
  }
}
```

You can also it get access to it in [thunk actions using `getFirebase`](http://react-redux-firebase.com/docs/recipes/thunks.html).

The goal is to eventually support most main methods at a top level. It should be easy enough to expose this function to the top level.

**Comment by katha247** [comment]
Thanks for your responses, I got it to work!

@DeividasK: `this.props.firebase.sendPasswordResetEmail()` does not work, but when using firebase.auth() it works fine. No need to import the raw firebase object.

@prescottprue: I used your suggestion: `this.props.firebase.auth().sendPasswordResetEmail()`

**Comment by prescottprue** [comment]
@katha247 I will update this issue (even though it will be closed) if the `sendPasswordResetEmail` is exposed as a top level method (i.e. `this.props.firebase.sendPasswordResetEmail`).
