### ISSUE TITLE
Population not working

### ISSUE THREAD

**Issue by benoj** [prescottprue/react-redux-firebase#415]
I have some data which looks like this:

<img width="465" alt="screen shot 2018-02-22 at 18 52 42" src="https://user-images.githubusercontent.com/2669116/36558034-b8c0d01c-1801-11e8-82ef-0e0651396790.png">

and a population query which looks like this:
```
@firebaseConnect(({ currentOrg, params: { jobId } }) => {
  return [
    { path: `applications/${currentOrg}/${jobId}` },
  ];
})
@connect(({ firebase }, { currentOrg, params: { jobId } }) => {
  const populates = [{ child: 'candidate', root: `candidates/${currentOrg}` }]
  return {
    applications: populatedDataToJS(firebase, `applications/${currentOrg}/${jobId}`, populates)
  };
})
```

However the data coming through is not populating the candidate field? 

Not sure why this is not working? (I'm using v1.4)

**Comment by prescottprue** [comment]
@benoj I see two things that could be causing it:
1. `firebaseConnect` must contain a query which has `populates`. Otherwise there will not be queries created for the data necessary to populate.
1. make sure that you pass an Array to `populatedDataToJS` not an object

I think this is what you want:

```js
// Populates is an array of populate config objects
const populates = [{ child: 'candidate', root: `candidates/${currentOrg}` }]

@firebaseConnect(({ currentOrg, params: { jobId } }) => {
  return [
    { path: `applications/${currentOrg}/${jobId}`, populates }, // make sure to pass populates here
  ];
})
@connect(({ firebase }, { currentOrg, params: { jobId } }) => {
  return {
    applications: populatedDataToJS(firebase, `applications/${currentOrg}/${jobId}`, populates)
  };
})
```
