### ISSUE TITLE
Persist session

### ISSUE THREAD

**Issue by Ionut-Milas** [prescottprue/react-redux-firebase#416]
Hi guys,

I have a small issue.
I cannot find a way to persist session.
Any help would be greatly appreciated.

Thanks.

**Comment by prescottprue** [comment]
The common method is persisting store. The `v4.*.*` series of [`redux-persist`](https://github.com/rt2zz/redux-persist) has worked well for others in the past (`v5.*.*` not yet supported).

For questions of implementation you will often get quicker answers over [gitter](gitter.im/redux-firebase/Lobby).

**Comment by prescottprue** [comment]
Was going to switch this to a request for example, but the [`redux-persist` example](http://react-redux-firebase.com/docs/integrations/redux-persist.html) already seems to cover the request.
