### ISSUE TITLE
Advanced populating?

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#42]
A question regarding populate with the following data structure:
```js
actions: {
  actionId: {
    goalId: 'goalId1',
    done: false
  },
  actionId2: {
    goalId: 'goalId1',
    done: false
  }
}
goals: {
  goalId1: {
    text: 'Goal title'
  }
}
```

__How would I go about populating goals with actions?__

Conditions:
- User has many goals
- Goals have many actions
- I want to display several goals with their actions

**Comment by prescottprue** [comment]
First, I would suggest taking the pattern of storing data how it will be viewed (i.e. storing a list of actions within goals):

```js
actions: {
  actionId: {
    goalId: 'goalId1',
    done: false
  },
  actionId2: {
    goalId: 'goalId1',
    done: false
  }
}
goals: {
  goalId1: {
    text: 'Goal title',
    actions: {
      actionId: true,
      actionId2: true
    }
  }
}
```

Then when calling, you can list goals with populated actions like so:

```javascript
const populates = [{ child: 'actions', root: 'actions' }]
@firebaseConnect(() => ([
  { path: 'goals', populates }
]))
```
or actions with the associated goal populated like this:

```javascript
const populates = [{ child: 'goalId', root: 'goals' }]
@firebaseConnect(() => ([
  { path: 'actions', populates }
]))
```

**Comment by DeividasK** [comment]
Thanks for the help!

**Comment by DeividasK** [comment]
I am working on implementing the above, but it doesn't seem to work. I have created the recommended structure.

My code:
```js
const populates = [{ child: 'actions', root: 'actions' }]
@firebaseConnect(() => ([ { path: 'goals', populates } ]))
@connect(({ firebase }) => ({
  users: populatedDataToJS(firebase, 'goals', populates),
}))
```

The result is an unmodified object of action ids, i.e.
```js
actions: {
  actionId: true,
  actionId2: true
}
```

Any ideas?

Package version: 1.2.2

**Comment by prescottprue** [comment]
That seems like it should be working correctly. I will attempt to replicate using the simple example and get back to you.

**Comment by prescottprue** [comment]
Right you are!

It seems that there is an issue gathering the data when populating a parameter that is a Firebase lists (`key: true`) within each item in a list.

I've started a branch for [`v1.2.3`](https://github.com/prescottprue/react-redux-firebase/tree/v1.2.3) where I have fixed this issue and added tests that will make sure that this doesn't break in the future. Hoping to try to release it tonight.

**Comment by prescottprue** [comment]
[`v1.2.3`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.2.3) should hopefully solve this issue, but I will leave it open until that is confirmed.

**Comment by DeividasK** [comment]
Great news! I can confirm that this now works as expected. Thanks a lot!

**Comment by prescottprue** [comment]
Glad to hear.

There is a unit test for this pattern now too, so it shouldn't be an issue moving forward.
