### ISSUE TITLE
Problem when adding FirebaseConnect in 2 components

### ISSUE THREAD

**Issue by immunity20** [prescottprue/react-redux-firebase#423]
Hello, don't know if I am doing it wrong (probably), I have 2 components ( both render on different URL)
from one component user is redirected to the second (via history push). I have problems when trying to firebaseConnect both components for real-time firebase data display. If I only add firebaseConnect on the second page, I will be able to see in real time data from firebase DB. But I want both page1 and page2 show real-time. - react-redux-firebase v2 is used

Page 1 component (map state etc)

```
...
history.push("/page2"); 
...

function mapStateToProps(state) {
  return {
    firebase: state.firebase,
    user: state.user
  };
}

function mapDispatchToProps(dispatch) {
  return {
    onSaveUserName: (data) => {
      dispatch(saveUserName(data))
    },
    onSaveSession: (session) => {
      dispatch(saveSession(session))
    },
  };
}

export default compose(
  firebaseConnect(['scanner']),
  connect(
    mapStateToProps,
    mapDispatchToProps,
  )
)(Page1);
```

Page 2 component ( map state etc)
```
function mapStateToProps(state) {
  return {
    firebase: state.firebase,
    user: state.user
  };
}

function mapDispatchToProps(dispatch) {
  return {
    onSaveUserName: (data) => {
      dispatch(saveUserName(data))
    },
    onSaveCompanyName: (data) => {
      dispatch(saveCompanyName(data))
    },
  };
}

export default compose(
  firebaseConnect(['scanner']),
  connect(
    mapStateToProps,
    mapDispatchToProps,
  )
)(Page2);
```

**Comment by floppyxyz** [comment]
I think you are running into the same bug as [#368](https://github.com/prescottprue/react-redux-firebase/issues/368).

Adding listeners manually in your components should help you at the moment.

**Comment by immunity20** [comment]
And how should that be done ? :D

I tried (dont know if its wrong)
this.props.firebase.watchEvent('value', `scanner`)
but i am getting watchEvent is not a function

**Comment by floppyxyz** [comment]
Ther should be no problem when adding to componentDidMount lifecycle method:

`componentDidMount() {
		this.props.firebase.watchEvent('value', `/fahrer`);
}`

**Comment by kdela** [comment]
So I found out solutions for the same issue but with firestore listener.
It's still not possible to unsubscribe listeners used across the app, which can cause performance issues and also increase some costs.


```javascript
import { withFirestore } from 'react-redux-firebase'
import { compose, lifecycle, pure } from 'recompose'

const mapStateToProps = (state, props) => {
  return {
    products: state.firestore.ordered[`products/${props.match.params.id}/list`],
    locations: state.firestore.ordered[`locations/${props.match.params.id}`]
  };
}

const enhance = compose(
  withFirestore,
  lifecycle({
    componentWillMount() {
      this.props.firestore.setListeners([
        { collection: `products/${this.props.match.params.id}/list` },
        {
          collection: `locations`, 
          where: [[`providers.${this.props.match.params.id}`, '==', true]],
          storeAs: `locations/${this.props.match.params.id}`
        }
      ]);
    },
    componentWillUnmount() {
      this.props.firestore.unsetListeners([
        {
          collection: `locations`, 
          where: [[`providers.${this.props.match.params.id}`, '==', true]],
          storeAs: `locations/${this.props.match.params.id}`
        }
      ]);
    }
  }),
  connect(mapStateToProps)  
);

export default enhance(ProvidersDetailsStock);
```

**Comment by karltaylor** [comment]
Sounds similar to #368 and people have said that adding a `storeAs` is a workaround fix. Have not tried that way though and just continued by manually setting listeners

**Comment by immunity20** [comment]
firebaseConnect(props => [
    {path: 'scanner',
      storeAs: 'dashScanner'},]) 
fixed the problem

**Comment by prescottprue** [comment]
It seems that using `storeAs` fixes the issue because it makes a new listener path. Discussing in #368 how we are going to try to approach a solution, so please feel free to give input. Going to close this so that #368 is the single place for updates on this issue.

@kdela For the performance concerns - Firebase/Firestore internally handles listener management (preventing unnecessary network communication), so  to mimic that behavior `redux-firestore` only attaches one listener callback (since it writes data to redux) for provided query settings unless you provide [`allowMultipleListeners: true`](https://github.com/prescottprue/redux-firestore/blob/master/src/constants.js#L96).

Listener management is currently at the top of the priority list. Thanks to all for reporting.
