### ISSUE TITLE
bug(firestoreConnect): startAt parameter dropped from query when used with other parameters

### ISSUE THREAD

**Issue by mukeshyadav-cdac** [prescottprue/react-redux-firebase#426]
when  you use

```
firestoreConnect((props) => {[
      {
        collection: 'posts',
        orderBy: [['headline', 'desc']],
        startAt: 'headline'
        limit: 3
      }
    ]
 })
```

it does not support startAt parameter. It drops that parameter. See the request from chrome.
```
{"database":"projects/**/databases/(default)","addTarget":{"query":{"structuredQuery":{"from":[{"collectionId":"posts"}],"orderBy":[{"field":{"fieldPath":"headline"},"direction":"DESCENDING"},{"field":{"fieldPath":"__name__"},"direction":"DESCENDING"}],"limit":{"value":3}},"parent":"projects/**/databases/(default)"},"targetId":**}}

```

**Comment by prescottprue** [comment]
@mukeshyadav-cdac I believe this is due to code within [`redux-firestore`](https://github.com/prescottprue/redux-firestore), but we can still track progress on it in this issue. Thanks for reporting.

**Comment by mukeshyadav-cdac** [comment]
@prescottprue should i look into this and fix it?

**Comment by prescottprue** [comment]
@mukeshyadav-cdac Yeah that would be great! That is what open source is all about.

You will most likely want to be changing code [in the query utilities of `redux-firestore`](https://github.com/prescottprue/redux-firestore/blob/master/src/utils/query.js).

**Comment by mukeshyadav-cdac** [comment]
@prescottprue This has been fixed in latest version mine was older one.
