### ISSUE TITLE
bug(reducer): firestore state not correctly updated when key contains a dot

### ISSUE THREAD

**Issue by compojoom** [prescottprue/react-redux-firebase#427]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
In firestore it's valid to have a document id like test@test.com However if you have such a key in redux-firebase it's stored as
test@test: {
  com: {}
}
instead of
test@test.com: {}

If one uses lodash's get method - we don't immediately see the issue since
get(state, `firebase.data.whatever.${keyWithDot}.something`) fetches the correct data.

I noticed that if the key is not holding a collection - but a document, than it is correct.

2.0.4

**Comment by prescottprue** [comment]
Great find and thanks for reporting.

**Comment by prescottprue** [comment]
@compojoom Open to suggestions on how to make this more clear, but since it is with usage of lodash's `get`, not sure how much can be done. Maybe we add something somewhere in the docs? Does anywhere specific come to mind?

You weren't experiencing an issue with `getVal` where you?

**Comment by prescottprue** [comment]
@compojoom Is this still an issue? If so we should open an issue on `redux-firestore`.

**Comment by prescottprue** [comment]
Progress on debugging this issue will be tracked in [139 of redux-firestore](https://github.com/prescottprue/redux-firestore/issues/139)
