### ISSUE TITLE
Compatibility with react-redux-router ?

### ISSUE THREAD

**Issue by MentalGear** [prescottprue/react-redux-firebase#43]
Thanks for your work and looks like a great package, however will it work seamless with react-router-redux as well ?
https://github.com/reactjs/react-router-redux

**Comment by prescottprue** [comment]
The library does not affect anything with routing choices. It keeps Firebase in sync with your redux store, and provides a Higher Order Component (`firebaeConnect`) for ease of use with react components (provides `this.props.firebase`).

**Comment by MentalGear** [comment]
Thanks for the quick reply, Prescott. Only thing I'm worried about (and I'm writing it here as others might also be interested) is that, as react-router-redux also saves it's routing state in redux, the routing state could get end up in firebase.

Sry if that's sounds noob-ish, but I'm new to react and I'm trying to chose the best set-up.

**Comment by prescottprue** [comment]
So things actually work the other way.

You decide what is "synced" with firebase by providing paths within the `firebaseConnect` HOC. Nothing in your state is automatically synced, and it is all placed within whatever namespace you give to the reducer (i.e. "firebase" if you follow the [use instructions](http://react-redux-firebase.com/#use):

```js
import { createStore, combineReducers, compose } from 'redux'
import { reactReduxFirebase, firebaseStateReducer } from 'react-redux-firebase'

// Add Firebase to reducers
const rootReducer = combineReducers({
  firebase: firebaseStateReducer // placing the reducer under the "firebase" namespace within redux
})

// Add redux Firebase to compose
const createStoreWithFirebase = compose(
  reactReduxFirebase(config, { userProfile: 'users' }),
)(createStore)

// Create store with reducers and initial state
const store = createStoreWithFirebase(rootReducer, initialState)
```

This is actually by design too.

**Comment by prescottprue** [comment]
Also, if you want to get up and running quickly:

Check out [`generator-react-firebase`](https://github.com/prescottprue/generator-react-firebase) which is a command line tool that helps you start projects (a yeoman generator).
