### ISSUE TITLE
Anonymous login

### ISSUE THREAD

**Issue by Cretezy** [prescottprue/react-redux-firebase#430]
**Do you want to request a *feature* or report a *bug*?**  

Feature.

**What is the current behavior?**

No way to anonymously login.

**What is the expected behavior?**

https://firebase.google.com/docs/auth/web/anonymous-auth

Would expect:

```js
props.firebase.anonymous()
```

**Comment by prescottprue** [comment]
`firebase.auth().signInAnonymously()` can be called directly - `onAuthStateChange` then updates state through an action dispatch. Then `linkWithCredential` can also be used which dispatches actions.

Does that handle your use case or is there something I am missing here? Should definitely be documented better.

**Comment by Cretezy** [comment]
I think that makes sense. The function works of the `firebase` passed by the HOC?

**Comment by prescottprue** [comment]
@Cretezy Yup, as noted in [the auth docs](http://react-redux-firebase.com/docs/auth.html#note) it must be grabbed from context. That can be done by hand or with either the `withFirebase` or `firebaseConnect` HOCs.

**Comment by Cretezy** [comment]
Alright, sounds good, thank you!
