### ISSUE TITLE
firebaseConnect doesnt respect the Firebase rules

### ISSUE THREAD

**Issue by towfiqi** [prescottprue/react-redux-firebase#432]
**Do you want to request a *feature* or report a *bug*?**  
Probably a bug.  a question if this is how the library is designed

**What is the current behavior?**
 I have a component that is connected to by firebase with firebaseConnect HOC to retrieve all the playlists stored in `/playlists/${props.uid}/ `

```
  firebaseConnect((props, firebase) => { 
        return [{ path: `/playlists/${props.uid}/`}];
  }),
```

And the Database structure:
![Image of Yaktocat](https://i.imgur.com/Ffd9qTG.png)

And I am restricting loading the playlists based on the "status" value of each playlist. Restricted if its set to "private", I want firebaseConnec to connect to : `/playlists/${props.uid}/` and retrive all the playlist that has `status= public` or if the current auth used is the paylist owner. 

```
{
  "rules": {
    ".read": "auth !== null",
    ".write":false,
    "playlists": {
      ".read": "auth !== null",
    	".write":false,
      "$uid": {
        ".read": "auth !== null",
    		".write":"auth !== null",
        "$playlist": {
            ".read": "$uid === auth.uid || data.child('status').val() === 'public'",
            ".write": "auth !== null && ($uid === auth.uid)"
          }
        }
    }
  }
}
```

**The Issue:**

The issue is the rules works great on firebase rules simulator, the playlists with status "private" cannot be accessed using the rules simulator. But the firebaseConnect is not respecting the rules, its loading all the playlists. So now if it doesnt respect the firebase rules, do we have to manually restrict the data inside the hoc? 

Thanks

**Comment by towfiqi** [comment]
**Update:**

Looks like this: `nextProps.firebase.database().ref('/playlists/' + nextProps.authorID+'/temp/')` returns `null`. 

But this returns all the playlists bypassing the rules: `nextProps.firebase.database().ref('/playlists/' + nextProps.authorID+'')`

So I think this could be a firebase permission structure issue.. :worried:

**Comment by towfiqi** [comment]
Ok. digged around more and looks like it is indeed my firebase rules which was faulty.  This is how my rules look now:
![Image of Yaktocat](https://i.imgur.com/SGjYxyU.png?1)

I am setting `/playlists/$uid/` read rules to `false` and later inside the playlist: `/playlists/$uid/$playlist/` I am checking if the status is public or private. if private, set the read to `true` only if the owner of the playlist is the authenticated user. This works, only when you access `/playlists/$uid/playlistID` and not when you access `/playlists/$uid/`  which I am doing through firebaseConnect:

```
  firebaseConnect((props, firebase) => { 
        return [{ path: `/playlists/${uid}/`}];
  })
```
It will only work if I set to a specific playlist, that have dynamic keys which I cannot know.
```
  firebaseConnect((props, firebase) => { 
        return [{ path: `/playlists/${uid}/$playlist`}];
  })
```
The only way I could think of is saving each playlist key inside `/playlists/${uid}/playlistids` and then connect to that using firebaseConnect and then loop through each key and get playlist data for each `/playlists/${uid}/$playlist` . Which doesnt sound so good.. :/


It would be great if someone could give me direction on how I can achieve what I am trying to achieve.

**Comment by prescottprue** [comment]
Correct - this is how Firebase rules work.

What we have done to handle this in the past is a function which receives a request from the client and retrieves relevant data and responds. Another way to go about it is to have a function which indexes/copies data to another collection which is just parameters to query.

**Comment by prescottprue** [comment]
Going to close since this is more of a usage question. Feel free to [react out over gitter](gitter.im/redux-firebase/Lobby) if you want to further discuss options.
