### ISSUE TITLE
Components don't update their `firebaseConnect` subscriptions as a result of Redux store updates.

### ISSUE THREAD

**Issue by santiago-elustondo** [prescottprue/react-redux-firebase#438]
This seems like a bug to me. 
However, if this is intended behaviour, I don't understand how to achieve what `firebaseConnect()` seems to claim to do in the docs. 
I would love to know what the pattern should be to achieve a component that updates it's `firebaseConnect` subscriptions as a result of redux store updates.

The docs describe the pattern in question:
<img width="531" alt="screen shot 2018-03-27 at 12 28 10 pm" src="https://user-images.githubusercontent.com/10526720/37980950-5f0f3d6a-31ba-11e8-875e-03bcaa34a20a.png">

**What is the current behavior?**

The `firebaseConnect()` callback gets called once during component mount, and if I update the props.
However, a redux store update will not trigger an update. A redux store update will trigger the `connect()` callback, but not `firebaseConnect()`.

The result is that if you have a pattern like the one above, if the value of `store.firebase.auth.uid` is updated in the redux store, the component will not update. 

This seems to be true for any redux state updates, meaning that the only real use case for using state data in `firebaseConnect` would be when you know that the state will have what you need during mount, and you won't need to update.

**What is the expected behavior?**

In general, I would expect that a store update should retrigger `firebaseConnect()` and check to see if the returned paths have changed. This would be consistent with the way that `connect()` works.

In my particular case, I mount the component while waiting for the authentication to come in. Once the user's auth comes back, `store.firebase.auth.uid` gets updated. This should update my component from a "waiting" state.

If this is actually intended behaviour, I would love to know what the pattern should be to achieve a component that updates it's firebase subscriptions as a result of redux store updates.

**Comment by santiago-elustondo** [comment]
UPDATE:
Reversing the order of  `connect()` and `firebaseConnect()` seems to achieve the desired result, since `connect()` will convert relevant state changes into props, triggering the `componentWillReceiveProps()` hook that causes `firebaseConnect()` to update its subscriptions.

Would there be any issues with this approach?

**Comment by prescottprue** [comment]
Using auth from store is seen as bad practice because of the issue you are mentioning. [The README of the state based query example](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/snippets/stateBasedQuery#another-way) discusses how this is possible, but is not suggested.

In v3 store is most likely going to be removed as the second argument of functions passed to `firebaseConnect` (or at the very least a deprecation warning).

**Comment by santiago-elustondo** [comment]
But Auth itself doesn't seem to be the problem, unless i'm misunderstanding something.
Any query that relies on state would have this issue. For example, imagine a `ChatRoom` component that is separate from another `ChatRoomSelector` component, where `ChatRoomSelector` updates the state, and `ChatRoom` reads that state in `connect()` and `firebaseConnect()`. Once the `ChatRoom` component has been mounted, the redux state update wouldn't update the respective firebase subscription. (that is, unless you reverse the connects as in my example above)

**Comment by santiago-elustondo** [comment]
The docs are misleading because `connect()` functions are generally expected to connect your component with the redux state in some way. I agree with removing the `store` parameter, and making it clear that `connectFirebase()` only reacts to props. (which is perfectly fine)

**Comment by santiago-elustondo** [comment]
Why is the recommendation in [stateBasedQuery](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/snippets/stateBasedQuery#another-way) to create a parent container, rather than just reverse the order of `connect()` and `firebaseConnect()`, as in my update? It seems more painless and allows you to have all the logic in one place.

**Comment by prescottprue** [comment]
@santiago-elustondo That is so that you can wait for auth data to be loaded (handling the case of needing a loading spinner as well as if the page is visited without auth all together).

What you have shown is more "painless" to write, but doesn't some handle common use cases - especially since many people have the no auth case when refreshing (since it is still loading). The example is meant to be general.

**Comment by santiago-elustondo** [comment]
Fair enough. 
This looks like a great tool so far.
