### ISSUE TITLE
example/complete/firestore error when npm start

### ISSUE THREAD

**Issue by woosuk288** [prescottprue/react-redux-firebase#441]
**Do you want to request a *feature* or report a *bug*?**  

bug

**What is the current behavior?**

i copied react-redux-firebase/examples/complete/firestore folder and enterd npm install.
but it wasn't work when i enterd npm start.

error messages are related to 'recompose'.

i did 'npm install recompose' and it works.

**Comment by prescottprue** [comment]
Just pushed changes that added to the `package.json`. Try removing node modules and reinstalling now.

Thanks for reporting!
