### ISSUE TITLE
Using an import statement for HOC causing DOM render issues.

### ISSUE THREAD

**Issue by cworf** [prescottprue/react-redux-firebase#446]
This is an issue that is likely caused by my lack of a full understanding of redux or HOC's or something but hopefully someone can point me in the right direction:

using the firestore todo list example you have as a starting point, I wanted to make the code a little DRYer I decided to try to separate the `compose()` high order function to a separate file that included all necessary actions for the listing of todos. so I combined each of them from the `NewTodo.js`, `TodoItem.js`, and `Todos.js` files into the `ToDoActions.js` file in the actions folder, and imported that file into each of the components. 

You can see this whole setup here https://codesandbox.io/s/1rwlrn6k5j

The problem with this is that, while the CRUD functionality still works, the DOM only updates after the first change, and every consecutive change requires a manual refresh to reflect. 

## Steps to reproduce

in the sandbox, if you create two items, then try to delete or check both of them as done, the DOM stops re-rendering after the first action, only by refreshing manually does the page show the current persistent state with both items having been removed. 

it seems this is only a problem with the `TodoItem.js` file, because if I manually define the HOC locally within that file instead of using an import, it fixes the problem. (see commented code at the bottom of the `TodoItem.js` file)

I really dont know where to go from here, but im sure this is simply related to my novice coding experience. Thanks very much for any help!

**Comment by cworf** [comment]
Im closing this, if anyone else has this issue, the solution is to keep the compose exports separated for the individual todo item component, passing all of the unnecessary props into that function breaks it. the working solution can be seen here. https://codesandbox.io/s/10o9ll1v8q

**Comment by prescottprue** [comment]
@cworf Correct. If you use the same enhancer for two components you will be running over your own props and creating multiple listeners for the same path (which you should use redux-firestore's `allowMultipleListeners` option). Thanks for closing.
