### ISSUE TITLE
isLoaded may not be working with firestore

### ISSUE THREAD

**Issue by Floriferous** [prescottprue/react-redux-firebase#452]
When using the `isLoaded` helper with a subscription on firestore, it always returns true, not matter what I do.

Could it be that `isLoaded` does not work with firestore?

**Comment by prescottprue** [comment]
I am using it in Fireadmin in a few places including the [project list page](https://github.com/prescottprue/fireadmin/blob/v0.4.0/src/routes/Projects/components/ProjectsPage/ProjectsPage.enhancer.js#L20-L39) which uses [a `spinnerWhileLoading` HOC](https://github.com/prescottprue/fireadmin/blob/v0.4.0/src/utils/components.js#L35-L57) that leverages `isLoaded and it seems to be functioning as expected.

Could you post your use case? Maybe it isn't working correctly in your case?

**Comment by cworf** [comment]
@Floriferous I had the same issue, the documentation has a typo in a few spots:

```javascript
{
        isLoaded(auth)
        ? <span>Loading...</span>
        : isEmpty(auth)
          ? <span>Not Authed</span>
          : <pre>{JSON.stringify(auth, null, 2)}</pre>
      }
```

Should be this:

```javascript
{
        !isLoaded(auth) //must include the "!" or "Loading..." will always show
        ? <span>Loading...</span>
        : isEmpty(auth)
          ? <span>Not Authed</span>
          : <pre>{JSON.stringify(auth, null, 2)}</pre>
      }
```

you must include the "!" before isLoaded, or "Loading..." will always show, as per [ternary operator documentation ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

hope that helps!

**Comment by prescottprue** [comment]
@Floriferous Bump. Did you have examples of where `isLoaded` was not working for you as expected? What version of `redux-firestore` are you using?

**Comment by Floriferous** [comment]
Will try to prepare a reproduction this weekend, thanks for following-up!

**Comment by prescottprue** [comment]
@Floriferous were you able to prepare a repro? Hoping to understand the use case where things aren't working as expected.

**Comment by prescottprue** [comment]
Going to close since reproduction steps were not provided. @Floriferous reach out if you are able to repro.

**Comment by eleventhaus** [comment]
Having a similar issue where `isLoaded` returns `true` before `firestore.data` or `firestore.ordered` have loaded.

```
firestoreConnect(props => [{ 
  collection: `petParents/${props.profile.ppid}/pets`,
  storeAs: "pets" }]),
connect(state => ({
  pets: state.firestore.ordered.pets <---------------------- results in undefined error
})),
connect((state, props) => ({
  initialValues: {
    contactInfo: {...state.firebase.profile.contactInfo},
    vetInfo: {...state.firebase.profile.vetInfo},
    pets: [...state.firestore.data.pets], <---------------------- results in undefined error
    emergencyContacts: [...state.firebase.profile.emergencyContacts]
  }
}))
````
![screen shot 2019-02-22 at 2 35 41 pm](https://user-images.githubusercontent.com/34343079/53275249-2639a700-36af-11e9-93b9-7366a3c961d0.png)

**Comment by prescottprue** [comment]
@eleventhaus It is `undefined` before it exists, so you need to make use of `isEmpty` as well as `isLoaded` if you are doing things that way in your connect.

It is`undefined` before loading then defined if it does exist, and `null` if it does not.

**Comment by eleventhaus** [comment]
I might be using `isEmpty` incorrectly but `isEmpty` remains false regardless of whether the firestore data is empty.

In my previous reply, at `SET_LISTENER`, `isEmpty` is false but there is no data in firestore.

I get `undefined` up until the `LISTENER_RESPONSE` action is called by firestore.

**Comment by eleventhaus** [comment]
Could it be because I'm using storeAs as in issue #585 ?

**Comment by eleventhaus** [comment]
@prescottprue I've tried using `firestoreConnect` and `isLoaded`/`isEmpty` with and without `storeAs` but no combination seems to load data from firestore into props.

I continue to get `undefined` up until the LISTENER_RESPONSE action is called by firestore.

**Comment by eleventhaus** [comment]
Hey @prescottprue its been a few months and I returned to this same issue. Can you help?

Why is firestore data/ordered undefined up until the LISTENER_RESPONSE action is called by firestore? It's throwing everything off for me.

Can I get a component to reload after LISTEN_RESPONSE is called?

**Comment by prescottprue** [comment]
That is intentional so that a difference can be told between not loaded (`undefined`), loaded but empty (`null`) -> and loaded and existing (a value).

You get a component to reload by passing the value as a prop from state (through `connect`) or through a hook doing the same (`useSelector`).

Not sure I understand what is unexpected

**Comment by eleventhaus** [comment]
when `isLoaded` is true and `isEmpty` is false, firebase has loaded but firestore has not loaded, per the screenshots in my post above.

Why is `isLoaded` true if firestore still hasn't received data?

**Comment by prescottprue** [comment]
@eleventhaus For the case and code you listed above, it doesn't look like you have isLoaded or isEmpty in there to check? You should also be able to provide `initialValues` in the same `connect` as your first state connection - also the error you are showing in your screen shot appears to be because you are trying to spread that value when it won't exist on initial render.

Can you open up a new issue with a full reproduction of what you are describing with codesandbox or a similar tool? It will be easier to show how code should change if there is more to reference

**Comment by seanenriquez** [comment]
Hey, was wondering why firestore queries don't have the same `isEmpty `and `isLoaded` property provided on them like a firebase auth profile does.  I see that they have different states, `undefined`, `null`, and value while working pretty well with the helper functions but think it would be more clear with the properties on the state.

 Or maybe i'm missing a simple redux implementation.

**Comment by jaddoescad** [comment]
having similar issues

**Comment by prescottprue** [comment]
@seanenriquez I think you are going down the right path with the isEmpty isLoaded - those are on auth/profile.

With null it should work, but could anyone that is having an issue with some specific data not loading correctly open a new issue with full code and reproduction steps?
