### ISSUE TITLE
Awaiting the snapshot ref of a pushed object not working

### ISSUE THREAD

**Issue by smoll** [prescottprue/react-redux-firebase#453]
**Do you want to request a *feature* or report a *bug*?**  

Possible bug/incorrect documentation.

**What is the current behavior?**

Promise resolves to `null` instead of a snapshot ref.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

have an action creator that does something like
```js
const thing = {str: 'foo'}
const snap = await firebase.push(`things/${uid}`, thing) // works fine
console.warn('snap=', snap) // prints null
```

**What is the expected behavior?**

Based on the docs http://react-redux-firebase.com/docs/api/props-firebase.html#push , I expect some kind of snapshot obj that I can call `.key()` on to get the id of the pushed object. This is useful for setting an index as recommended in https://firebase.google.com/docs/database/web/structure-data

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Based on https://github.com/prescottprue/react-redux-firebase/blob/3e41c91b87c120317c71ff7a7635ee36f2734e59/test/unit/enhancer.spec.js#L114 I'm not entirely sure this behavior was actually tested, so unsure if this is a new/old bug.

**Comment by smoll** [comment]
Hmm... so according to the FB docs https://firebase.google.com/docs/database/admin/save-data this is actually a synchronous call and this actually gives me exactly what I want:

```js
const thing = {str: 'foo'}
const snap = firebase.push(`things/${uid}`, thing)
console.warn('snap=', snap.key) // -Ljs9dja9whatevs
```

Sorry if this should have been obvious, I was thrown off by the RRF docs mentioning a Promise

**Comment by prescottprue** [comment]
Yeah, just like with the Firebase JS API, you can use the promise piece or just get the key.

Do you think something in the docs would make it more clear? If so, totally open to a PR if you have the time.
