### ISSUE TITLE
firestore.data and firestore.ordered do not update when listeners change

### ISSUE THREAD

**Issue by cworf** [prescottprue/react-redux-firebase#454]
_EDIT: I think this is possibly similar to the bug in #368 but since the fix appears to be to use the `storeAs` method, and storeAs does not work for firestore yet, perhaps I have to work around it. I was able to access the data properly when I use the firestore.data object because its just a single document, but I imagine I will have this issue again when I want the ability to use ordered documents with sub-collections._

**What is the current behavior?**

mounting a child component which uses firestoreConnect() to connect to a sub collection of the same document as the parent changes the array of listeners, as well as the required documents array in firestore.data or firestore.ordered, but when the listeners array changes back to the parent document, firestore.data and firestore.ordered do not update.

**My specific details**

I have a simple parent component that connects to a document and displays a form with pre-filled values based on what is in the selected document. This component connects to firestore as such: 

```javascript
  firestoreConnect([
    { collection: 'truetours', doc: '0gZUKuyKD95hHsXaZ4Ny' },
  ]),
  connect(
    ({ firestore }) => ({
      usersDoc: firestore.ordered.truetours
    })
  ),
```

The form includes a button which opens a modal component that displays a list of images to select, all of which are contained within a sub-collection inside the same document, this modal component connects to firestore as such:

```javascript
  firestoreConnect([
    { collection: 'truetours', doc: '0gZUKuyKD95hHsXaZ4Ny', subcollections: [{ collection: 'images' }]}
  ]),
  connect(
    ({ firestore }) => ({
      gallery: firestore.ordered.truetours,
    })
  ),
```

The problem occurs when I open the modal which accesses the subcollection 'images' inside the same document as the parent, it seems to override the listener reference to the parent document `truetours/0gZUKuyKD95hHsXaZ4Ny` with `truetours/0gZUKuyKD95hHsXaZ4Ny/images`, so now the `usersDoc` prop is a reference to the sub-collection and not the parent doc. when I then select the image and the modal closes to show the main form, the usersDoc prop still has the reference to the sub-collection because when I try to update the parent doc using `usersDoc.id` I get an error referencing a document inside the subcollection, which of course does not exist in the parent collection.

Ive tried adding the `allowMultipleListeners: true` option in the store config incase that was the problem, and it appears to not have any effect

The weird thing is the following console log returns the expected array of listeners for each step of the way, however:

```javascript
  connect(
    ({ firestore }) => {
      console.log('listeners: ', firestore.listeners.allIds); //correct array of listeners
      console.log('documents: ', firestore.ordered); //incorrect array of documents
      return ({
      userDoc: firestore.ordered.truetours //thus this returns the incorrect documents
    })}
  ),
```

**What is the expected behavior?**

the firestore prop in the connect() should reflect the documents of the current listener

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

```javascript
"dependencies": {
    "firebase": "^4.12.1",
    "prop-types": "^15.6.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.6",
    "react-redux-firebase": "latest",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-firestore": "^0.3.2",
    "redux-thunk": "^2.2.0",
  },
```

perhaps I am using the firestoreConnect wrong, but I have followed your instructions in the documentation.

Thanks for any help you can give me!

**Comment by prescottprue** [comment]
The [`v0.4.0` release of `redux-firestore`](https://github.com/prescottprue/redux-firestore/releases/tag/v0.4.0) was published earlier today, and it should address this. Did you want to update to that and confirm you are still seeing the issue?

**Comment by prescottprue** [comment]
On second read of the issue, the new release may not help, but still worth a try. Going to try to reproduce to see.

**Comment by cworf** [comment]
I gave the new release a try, sadly, still the same result. I don't have any more time tonight but ill put together a sandbox for ya tomorrow, thanks for getting back to me!

**Comment by cworf** [comment]
oh! looks like you added the storeAs ability! I can only presume that will solve the issue. ill give it a go

**Comment by prescottprue** [comment]
Let me know how trying it out goes 😄 

There has also been quite a bit of discussion around moving subcollections to their own piece of redux state. As much as it makes sense logically with small applications, things can get pretty messy when you have multiple subcollection updates from different listeners along with the main document listener.

Open to ideas for a new pattern, but yeah `storeAs` should hopefully solve it for you for now.

**Comment by prescottprue** [comment]
Recent updates to redux-firestore (i.e. `0.4.1` and `0.4.2`) fix these issues. Reach out if things aren't working as expected.
