### ISSUE TITLE
It looks like the react-redux-firebase docs site is down 

### ISSUE THREAD

**Issue by codekiln** [prescottprue/react-redux-firebase#459]
https://github.com/prescottprue/react-redux-firebase --> ERR_NAME_NOT_RESOLVED

https://downforeveryoneorjustme.com/react-redux-firebase.com --> "It's not just you! react-redux-firebase.com looks down from here."

**Comment by prescottprue** [comment]
@codekiln Thanks for reaching out! Seeing that too, but it should be fixed now.

It turned out to be changes made by the DNS provider I am using. Going to their page and providing some config fixed things.
