### ISSUE TITLE
feat(populate): set limit on populate query

### ISSUE THREAD

**Issue by meksikann** [prescottprue/react-redux-firebase#461]
Hi. I have propfile with nearly 400 matches in it:

`  {
        
     "friends" : {
        "-Kp-ky6hOPq-nImOpVGk" : "gsTflZjxoYcdQJUrS6nw6uxLFa93",
        "-KyzHhAr6QgdAcqnE5VF" : "frByC4g8cJTxcCNjfL2TWUMj9aR2"
      },
      "matches" : {
        "2LA4QQHfMQhP6Gdk8iaEFvlN1Du2" : 14,
        "YxqFK8M2nJOKt0Wz17Fj8sTNY1u1" : 18,
        "gsTflZjxoYcdQJUrS6nw6uxLFa93" : 34,
       "frByC4g8cJTxcCNjfL2TWUMj9aR2": 35
      },
      "uid" : "GauAnEhTaNOepGJbEmlxTW7Ex7G3"
    }`

to populate matches i use this:

`@connect(
  (state) => ({
    profile: populate( state.firebase, 'profile',   [  { child: 'matches', root: 'users', populateByKey: true, childAlias: 'matchedUsers' },])
  })
)`

Is it possible to set limits to populate JUST e.g. first 10 matches?
maybe some constraints like:

` { child: 'matches', root: 'users', populateByKey: true, childAlias: 'matchedUsers' ,startAt:0, endAt:10},`

I don't want to populate all 400 matches, want to make pagination for it.

**Comment by meksikann** [comment]
thanks a lot...wanted to write in the morning that it works well..but, could you take a look, I can't find what I am doing wrong, but it returns me same values as 'matches'(limitToFirst - works) but in 'matchedUsers'
`
const populates = [
  { child: 'matches', root: 'users', populateByKey: true, childAlias: 'matchedUsers' }
];

@firebaseConnect((props, store)=> {
  let uid = store.getState().firebase.auth.uid;

  if(uid){
    return [
      {
      path:`users/${uid}/matches`, queryParams: [ 'limitToFirst=10' ],storeAs:'limitMatches.matches'
    },{
        path: 'limitMatches', populates
      }
    ]
  }
})

@connect(
  (state) => ({
    authError: getVal(state.firebase, 'authError'),
    auth: getVal(state.firebase, 'auth'),
    limitMatchesUsers: populate(state.firebase, 'limitMatches', populates),
    profile: state.firebase.profile
  })
)
`

**Comment by prescottprue** [comment]
Going to close since this is similar to the feature request within #445.
