### ISSUE TITLE
create-config file missing

### ISSUE THREAD

**Issue by 4nd3rs** [prescottprue/react-redux-firebase#465]
Hi! First, thanks for a great project.

I'm going to setup a CI environment with this now, but seems like the `create-config.js`file is missing from the repo? Or is there another way of copying config files for different environments?

**Comment by prescottprue** [comment]
@4nd3rs Glad you find it useful!

I found myself often rewriting this "create config" logic along with other simple scrips for use on CI. To address that I made a [tool called `firebase-ci`](https://github.com/prescottprue/firebase-ci). It calls `firebase-tools` from settings loaded from your `.firebaserc` file.

**Comment by 4nd3rs** [comment]
@prescottprue Perfect, thanks, will try that!
