### ISSUE TITLE
Deprecated firebase.User.prototype.signInWithEmailAndPassword

### ISSUE THREAD

**Issue by jaschaio** [prescottprue/react-redux-firebase#467]
Getting this console warning when logging in with username and password:
```
Deprecated firebase.User.prototype.signInWithEmailAndPassword in favor of firebase.User.prototype.signInAndRetrieveDataWithEmailAndPassword.
```

Using `react-redux-firebase:2.1.1` together with `react-native-firebase:4.1.0` – not entirely sure which of the two is causing this warning but I suspect it's `react-redux-firebase` as `react-native-firebase` should only be a native wrapper of the normal `firebase` sdk API methods.

**Comment by prescottprue** [comment]
Reproduced with new Firebase version.

Weirdly, when putting this simple logic in place, I got a warning that is telling me the exact opposite?

![image](https://user-images.githubusercontent.com/2992224/40360055-a18c904e-5d79-11e8-8c86-a77aeb081681.png)

Going to investigate more before making a change. Any input is welcome.

**Comment by prescottprue** [comment]
@jaschaio Just to confirm which method did you call to sign in?

**Comment by prescottprue** [comment]
[`v2.1.5`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.1.5) should fix the issue for you thanks to a PR from @kadikraman. Reach out if you are still seeing the warning, thanks for reporting.

**Comment by dustingraves** [comment]
I am also seeing `firebase.auth.Auth.prototype.signInAndRetrieveDataWithEmailAndPassword is deprecated. Please use firebase.auth.Auth.prototype.signInWithEmailAndPassword instead.`

```javascript
      emailLogin: ({ firebase, router, showError }) => creds =>
      firebase.login(creds).catch(err => showError(err.message)),
```

**Comment by fredrik-sogaard** [comment]
I'm seeing this as well. Oddly only sometimes. Can't really figure out when this is happening.

**Comment by fredrik-sogaard** [comment]
"firebase": "^5.0.4",
 "react-redux-firebase": "^2.1.5",

Now I seem to get it every time. Screenshot: https://cl.ly/0q2U0Z07012D

**Comment by fredrik-sogaard** [comment]
I can try updating Firebase and react-redux-firebase to the latest release and see if that helps.

**Comment by fredrik-sogaard** [comment]
It's the same with Firebase 5.2.0 and react-redux-firebase 2.1.6.

**Comment by Roustalski** [comment]
I'm using `"firebase": "^5.2.0",` in my react-redux app, but without `react-redux-firebase` and am also receiving the warning. This is an issue with the firebase web SDK itself.

**Comment by peterpalau** [comment]
Anyone has a solution for this? I'm using `"react-redux-firebase": "^2.1.8"` and `"firebase": "^5.4.2"`.

**Comment by oacstevens** [comment]
I found a similar issue with facebook login via signInWithCredential (signInAndRetrieveDataWithCredential in newer firebase). I've got a [fix](https://github.com/prescottprue/react-redux-firebase/pull/554) working essentially copying @kadikraman 's [PR](https://github.com/prescottprue/react-redux-firebase/pull/484) but for credential auth

**Comment by prescottprue** [comment]
Released in [2.1.9](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.1.9). Reach out if it doesn't fix the warning as expected.

**Comment by fredrik-sogaard** [comment]
I haven't done detailed testing, but for me it seems like this happens when I'm already logged in and try to log in again.

**Comment by oacstevens** [comment]
I tried flipping the logic around in `/src/utils/auth.js` so `signInWithEmailAndPassword` is attempted first (falling back to `signInAndRetrieveDataWithEmailAndPassword`), and that gets rid of the warning on firebase 5.5.5. My guess is that if the new method didn't exist in firebase 4.x then this flip would work there too?

**Comment by oacstevens** [comment]
Looking in the firebase js sdk [here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/auth.js) `signInAndRetrieveDataWithEmailAndPassword` is deprecated so shows a warning, but passes through to `signInWithEmailAndPassword`. I think that explains why I found it was working despite the warning. 

I'm not familiar with the firebase sdk history, but I'm looking though the [auth history](https://github.com/firebase/firebase-js-sdk/commits/master/packages/auth/src/auth.js) to see what older versions did

**Comment by DickerHobbit** [comment]
I also still face this warning using the email login method. For the credential login it seems indeed to be gone.

Version: 
`react-redux-firebase: "2.2.3"`

**Comment by kdela** [comment]
I'm also receiving a warning `firebase.auth.Auth.prototype.signInAndRetrieveDataWithEmailAndPassword is deprecated. Please use firebase.auth.Auth.prototype.signInWithEmailAndPassword instead.`
on use `this.props.firebase.login({ username, password })`.

`"react-redux-firebase": "^2.2.3",`

**Comment by prescottprue** [comment]
@DickerHobbit and @kdela thanks for reaching out. When looking back at it, it seems there was logic calling `signInAndRetrieveDataWithEmailAndPassword` but it was pointing to this issue number. That makes me think that there are different warnings based on the version of Firebase's JS SDK you are using, but with the newest one the warning went away by just removing that logic (doing as part of next release).

**Comment by prescottprue** [comment]
Released [v2.2.4](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.2.4) with the change that only calls `signInAndRetrieveDataWithEmailAndPassword` if `signInWithEmailAndPassword` is not defined (so it won't be called if you are using the newest Firebase SDK version).

If anyone still sees warnings or incorrect behavior after updating to `v2.2.4` reach out!

**Comment by chethanbhat** [comment]
Hello, if you are following Brad Traversy's React Front to Back Course from Udemy and getting this warning, you should use following code
`    firebase.auth().signInWithEmailAndPassword(email, password).catch(err => notifyUser('Invalid Login Credentials', 'error'));`

Do not use below code from the original tutorial. 
`    firebase.login({email,password}).catch(err => notifyUser('Invalid Login Credentials', 'error'));
  };`

**Comment by prescottprue** [comment]
@chethanbhat Thanks for reaching out about the context for the tutorial. Something to note is that doing that will mean that one won't get the functionality listed with `login` like profile creation.

With newer versions of react-redux-firebase you shouldn't get the warning even when using `login`. If anyone is still seeing the warning we should reopen this issue.

**Comment by oliver-ni** [comment]
Hi,

Apparently `signInAndRetrieveDataWithCredential` is deprecated and `signInWithCredential` is the new method now.

**Comment by prescottprue** [comment]
[This code is](https://github.com/prescottprue/react-redux-firebase/blob/v3.0.0-beta.3/src%2Futils%2Fauth.js#L94-L101) supposed to only run it if it exists, but maybe that logic should just be removed all together if it throws this warning.
