### ISSUE TITLE
firestoreConnect failing in child component

### ISSUE THREAD

**Issue by klopfer** [prescottprue/react-redux-firebase#472]
I'm using firestoreConnect in a project.  It was working just fine.  I recently updated react-redux-firebase and redux-firestore (lastest as of 22 May) and now I have an issue.  I have replicated the issue as follows.

I checked out the current react-redux-firebase repo.  Went to the examples/complete/firestore todos example.  I add recompose (doesn't seem to be in package.json) and build. Everything is fine.  

I then make a new component (called HomeContainer).  It simply returns a div surrounding the existing Home component.  I then import that component into App.js and replace the home component with the homecontainer in App.js.

I thought that nothing should change - homecontainer should return the home component.  But in fact, firestore doesn't seem to connect.  It gets stuck on loading.  

I see that I could create a homecontainer HOC with firestoreconnect and then just connect todos to the store in home, but there are cases where I'd want the child to connect to firestore given the props it has.  That is where it seems to fail.  

I think this is a bug (it was working with earlier versions), but I could be misunderstanding or doing something wrong.

**Comment by prescottprue** [comment]
@klopfer Can you point to what versions you may have been using before? It would also help to see some actual code snippets.

Listeners based on provided props is a common pattern that is in use in multiple applications including [fireadmin](https://github.com/prescottprue/fireadmin), so I would be surprised to see it functioning incorrectly. That said, maybe I am misunderstanding and the certain use case has been broken - a code example is the only real way to test.

**Comment by klopfer** [comment]
@prescottprue Thanks.  Previous versions were 2.0.5 for react-redux-firebase and 0.3.2 for redux-firestore.  

I'm attaching the modified src directory from the complete/firestore todos example.  If you swap out this src directory for the one in the repo it should demonstrate the behavior.   For reference, the modifications I made were.

In Home.js added the following after the imports:
```
export const HomeContainer = () => (
  <div><Home /><p>test</p></div>
)
```

And in App.js changed 
`import Home from './Home'`
to `import Home, {HomeContainer} from './Home'`

and changed
```
export default () => (
  <Provider store={store}>
    <Home />
  </Provider>
)
```
to 
```
export default () => (
  <Provider store={store}>
    <HomeContainer />
  </Provider>
)
```

I think in theory the app should still run just fine.  Simply nesting the component in another component.  But this stops firestore from connecting to the Home component.  Perhaps I am missing something about the surrounding context.  

Please let me know if I can provide anything further, or if I'm just doing this wrong.  Thanks.

[src.zip](https://github.com/prescottprue/react-redux-firebase/files/2029019/src.zip)

**Comment by prescottprue** [comment]
@klopfer After following your example through, I have realized something:

You can't just place `Home` directly into your HomeContainer without it's enhancer (which is also in Home.js). If you look at the bottom of the file there is `export default enhance(Home)`, which is the Home component being "enhanced" with the listener attaching/detaching and state connection which goes on in the `enhance` wrapper.

In an attempt to make this more clear, `Home` (the unwrapped component) is not actually exported from the file, only the wrapped version of Home is exported (as default).

If you are looking to wrap the home component, make sure that you import the enhanced version of that component:

`HomeContainer.js`

```js
import Home from './Home' // wrapped version of home from default export

const HomeContainer = () => (
  <div><Home /><p>test</p></div>
)

export default HomeContainer
```

For sake of example, if you want to, you can also wrap the component in it's enhancer as you use it. Personally I have found this to be unclear in some cases, but it is possible:

```js
// rest of code from Home.js and enhancer function

const HomeContainer = () => (
  <div>enhance(<Home />)<p>test</p></div>
)
```

**Comment by klopfer** [comment]
Thanks for the thoughtful explanation.  I'll investigate further and reach out if it was anything more than my misunderstanding.  Thanks.
