### ISSUE TITLE
feat(auth): expose new linkWith methods which dispatch AUTH_LINK_SUCCESS

### ISSUE THREAD

**Issue by barbsicle** [prescottprue/react-redux-firebase#473]
**What is the current behavior?**

Similar to #268 which was fixed in a previous version, the latest `link` type functions for Firebase Auth include `linkAndRetrieveDataWithCredential()`,`linkWithPopup()`, and `linkWithRedirect()`. The auth object in the redux state is not being updated upon the success of the above 3 functions.

Note: `linkWithCredential()` has been deprecated. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Create a new Firebase account (anonymous), and then run the following:
```
const provider = new this.props.firebase.auth.FacebookAuthProvider();
provider.addScope('email');
this.props.firebase
    .auth()
    .currentUser.linkWithPopup(provider)
    .then(result => {
        // auth object should be updated here, but is not
    });
```

**What is the expected behavior?**

Auth object should be updated. In following with #268, I ran the following snippet manually, which worked to update the auth object:

```
this.props.dispatch({ type: actionTypes.AUTH_LINK_SUCCESS, payload: result.user });
```

I'm quite sure these functions can be extended much like they were for #268. I may work on a PR soon if I have some spare time. @prescottprue let me know if this is the best way moving forward!

**Comment by barbsicle** [comment]
@prescottprue sorry I haven't replied till now. Yes, dispatching the action is a current workaround to resolve the new account. Would you like me to create a PR to perform the dispatch with the new methods like `linkWithPopup()`?

**Comment by prescottprue** [comment]
@barbsicle It would be great if you could create a PR that added usage of the new methods. If you are just adding dispatching of actions, it may be nice to use the `wrapInDispatch` function, which simplifies dispatching before and after calling a method (it follows a pattern similar to redux-middleware). [`deleteFile` is an example of it being used](https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/storage.js#L135-L139) within react-redux-firebase, but if you want a more complex example with modified payloads, [redux-firestore also uses it](https://github.com/prescottprue/redux-firestore/blob/master/src/actions/firestore.js#L77-L106).

**Comment by barbsicle** [comment]
@prescottprue Sorry for the delay, I'm currently working on the PR now. 

Will try your suggestion of transitioning to `wrapInDispatch`, although I don't know if the method `firebase.auth().linkAndRetrieveDataWithCredential(credential)` qualifies as the argument for `method`. Will try it out though.

**Comment by prescottprue** [comment]
@barbsicle Always open to the PR if you get a chance, otherwise I will try to get to it when possible.

**Comment by barbsicle** [comment]
@prescottprue please go ahead. I've since moved on and no longer require the functionality, so I haven't prioritized writing the PR.

**Comment by jake-nz** [comment]
I see these are in the codebase now, but they don't seem to be exposed. `linkWithCredential` is [exposed on firebaseInstance](https://github.com/prescottprue/react-redux-firebase/blob/fe7a4cef10003bc62a08eb915dc53b146055cce9/src/createFirebaseInstance.js#L511) but it looks like `linkWithPopup` is not. Am I missing something? How can I use `linkWithPopup`
