### ISSUE TITLE
getDerivedStateFromProps creates warning and general issues

### ISSUE THREAD

**Issue by benoj** [prescottprue/react-redux-firebase#476]
When I implement `getDerivedStateFromProps` in a component I get the following issue. I'm thinking this is because of the way @firebaseConnect mounts?

```
index.js:2178 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

FirebaseConnect(Connect(Application)) uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by prescottprue** [comment]
@benoj Not sure, that sounds correct though. Haven't worked much with `getDerivedStateFromProps` yet, but it should be handled.

**Comment by benoj** [comment]
Hmm found another person finding this issue online and Dan Abramov suggested updating react-redux to the latest. I  will update and message back here for anyone else in the future who may find this issue and come here...

**Comment by prescottprue** [comment]
@benoj Great to know, thanks for the update. I have been able to update my projects to `react-redux` v4 and have yet to find issues, so hopefully it is possible for you to do the same.

Going to leave this ticket open for now until we know more.

**Comment by prescottprue** [comment]
@benoj Any update on this? Still have not been able to repro this, but wasn't sure what versions to try.

Going to close for now, but lets reopen it if can repro. Thanks for reaching out!
