### ISSUE TITLE
Populate with `childParam` does not work

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#48]
Hello again :) `childParam` feature does not work for me. Maybe I'm doing something wrong?

Data:
```js
goals: {
  goalId1: {
    uid: 'userId'
  }
}
users: {
  userId: {
    displayName: 'John Smith'
  }
}
```

Code:
```js
const populates = [
  { child: 'uid', root: 'users', childParam: 'displayName' }
]
@firebaseConnect(() => ([
  { path: 'goals', populates }
]))
@connect(({ firebase }) => ({
  allGoals: helpers.populatedDataToJS(firebase, 'goals', populates)
}))
```

Result:
```js
goals: {
  goalId1: {
    uid: {
      displayName: 'John Smith'
    }
  }
}
```

Expected:
```js
goals: {
  goalId1: {
    uid: 'John Smith'
  }
}
```

**Comment by prescottprue** [comment]
It looks like it might just be `populatedDataToJS` not supporting childParam (I believe it is still being loaded into redux).

Hopefully this will be a quick fix that can make it in a coming version of `v1.2.*`, but as mentioned in #49, populate will be undergoing a re-write for `v1.3.0`.

**Comment by prescottprue** [comment]
[`v1.2.3`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.2.3) should hopefully solve this issue, but I will leave it open until that is confirmed.

**Comment by DeividasK** [comment]
I can confirm that this works now.
