### ISSUE TITLE
bug(FileMeta): uploadFile errors out trying to access 0th item of undefined (prevents reading/writing file meta info/file URL)

### ISSUE THREAD

**Issue by nasimoyz** [prescottprue/react-redux-firebase#480]
**What is the current behavior?**

When attempting to upload an image using `uploadFile` or `uploadFiles` the following error occurs:
![image](https://user-images.githubusercontent.com/1500565/40692681-29f6b51a-6381-11e8-922e-0a40cfbf9f5b.png)

The file uploads, but fails to write metadata or subsequently update redux state: `firebase.data[filesPath]` is null

Error occurs in `utils/storage.js` function `writeMetadataToDb` when trying to access 0th item of downloadURLs, where downloadURLs is undefined (property does not exist on `uploadTaskSnapshot`)

<img width="708" alt="screen shot 2018-05-29 at 8 36 44 pm" src="https://user-images.githubusercontent.com/1500565/40692527-5bff898e-6380-11e8-89f0-dc941edb1a53.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

```
...
this.props.firebase.uploadFile(filesPath, file, filesPath);
...
compose(
  firebaseConnect([ filesPath ]),
)(FormComponent);
```

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

```
"firebase": "^5.0.4",
"react-redux-firebase": "^2.1.4",
```

I would downgrade firebase, but if conflicts with the firestore requirements.

**Comment by prescottprue** [comment]
@nasimoyz Thanks for reporting. For now, it should be easy to just not include it if doesn't exist. It looks like to keep the results of the method the same, we may have to add an internal [`getDownloadURL`](https://firebase.google.com/docs/reference/js/firebase.storage.Reference#getDownloadURL) call.

**Comment by prescottprue** [comment]
As mentioned by @harvitronix in #483, a current work around for this is:

```js
this.props.firebase.uploadFile(FILES_PATH, file)
  .then(ret => ret.uploadTaskSnapshot.ref.getDownloadURL())
  .then(url => console.log(url));
```

To keep the resulting metadata the same, I am going to change the code within [the v2.1.5 PR](https://github.com/prescottprue/react-redux-firebase/pull/481) to call the `getDownloadURL` method if the download URL is not already on the response (i.e. when using Firebase JS SDK that is v5).

**Comment by prescottprue** [comment]
[`v2.1.5`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.1.5) should fixes this issue. It also includes the logic for getting the download url by default if it doesn't exist on original response.

**Comment by PranavPanchal** [comment]
Hey, I am still not getting the downloadURL field in the snapshot:

<img width="1404" alt="screen shot 2018-08-14 at 12 07 23 am" src="https://user-images.githubusercontent.com/17016563/44071273-31753468-9f56-11e8-92f3-e6c47105c280.png">

Can I get a usage example (to see what I am doing wrong) or can someone tell me why I am not getting the downloadURL?

Thanks!

**Comment by PranavPanchal** [comment]
Hey, I am still not getting the downloadURL field in the snapshot:

<img width="1404" alt="screen shot 2018-08-14 at 12 07 23 am" src="https://user-images.githubusercontent.com/17016563/44071363-a7f62db8-9f56-11e8-98c3-f76ca7fbf72a.png">

Can I get a usage example (to see what I am doing wrong) or can someone tell me why I am not getting the downloadURL?

Thanks!

**Comment by prescottprue** [comment]
@PranavPanchal `uploadTaskSnapshot.ref.getDownloadURL()` can be used to get it. In the [PR for v2.2.0-alpha.2](https://github.com/prescottprue/react-redux-firebase/pull/524), I have been working on changes which will include the download URL within the metadata written to RTDB. That functionality is captured in #487.

**Comment by PranavPanchal** [comment]
@prescottprue I used `uploadTaskSnapshot.ref.getDownloadURL()` , however, this is the JSON object that is being returned: 

<img width="1217" alt="screen shot 2018-08-14 at 11 27 34 am" src="https://user-images.githubusercontent.com/17016563/44101477-8565b6a6-9fb5-11e8-88a1-7c162615c87e.png">

When I try to access the "i" field (which holds the URL), I am getting undefined because before expanding the object in the console, the value of the "i" field is showing undefined.

I am confused as to how to retrieve the URL from that object.

**Comment by prescottprue** [comment]
@PranavPanchal Are you handling it as a promise or you mean just returned directly by calling it? Lets hop over to #487 to continue talk about it so that any talk of handling that download URL is captured there.
