### ISSUE TITLE
feat(storage): make downloadURL available for file metadata (firestore/firebase v5)

### ISSUE THREAD

**Issue by nasimoyz** [prescottprue/react-redux-firebase#487]
**What is the current behavior?**
Thanks for all your amazing work on this library and for quickly deploying the fix for file upload (for firebase v5)!

I was wondering about the best way to write the `downloadURL` to the File Metadata when working with the firebase v5 updates?

Currently the File Metadata is written before the downloadURL is retrieved (with the downloadURL retrieval occurring in `uploadResultFromSnap`).
I can write it to the File Metadata after the `firebase.uploadFile` promise resolves, only issue is then writing File Metadata will always incur a second network call.

On dependencies:
```
"firebase": "^5.0.4",
"react-redux-firebase": "^2.1.5",
```

**Comment by prescottprue** [comment]
@nasimoyz Yup! Glad the issues were reported so quickly!

As for getting `downloadURL` with v5: [this logic, which is new as of `v2.1.5`, gets the `downloadURL`](https://github.com/prescottprue/react-redux-firebase/blob/master/src/utils/storage.js#L78-L91). I'm glad you pointed this out because it seems that the promise is running on result of the meta set promise when it should go before it so that can be included in the meta (exactly as you are saying).

The change should be easy enough to make, but it would be nice to capture this functionality with a unit test as well while we are at it. Thanks for reporting.

**Comment by PranavPanchal** [comment]
Hey, I am carrying over from where we last left off from this thread: #480 

I am using an async action. The following is the code:

`export const uploadToFirebase = file => async (
  dispatch,
  getState,
  { getFirebase, getFirestore }
) => {
  const fileName = cuid();
  const firebase = getFirebase();
  const firestore = getFirestore();

  const path = "files";
  const options = {
    name: fileName
  };

  try {
    // upload the file to firebase storage
    let uploadedFile = await firebase.uploadFile(path, file, null, options);

    console.log(uploadedFile.uploadTaskSnapshot.ref.getDownloadURL());

    // get url of the file
    let downloadURL = await uploadedFile.uploadTaskSnapshot.downloadURL;

    // add the new files to files collection
    await firestore.add(
      {
        collection: "files"
      },
      {
        name: fileName,
        url: ""
      }
    );
  } catch (error) {
    console.log(error);
  }
};`

The screenshot that I posted in the previous comment was from console logging the file that was uploaded to firebase storage.

`    console.log(uploadedFile.uploadTaskSnapshot.ref.getDownloadURL());`

**Comment by PranavPanchal** [comment]
Hey, I am carrying over from where we last left off from this thread: #480

I am using an async action. The following is the code:

`try {
// upload the file to firebase storage
let uploadedFile = await firebase.uploadFile(path, file, null, options);

console.log(uploadedFile.uploadTaskSnapshot.ref.getDownloadURL());

// get url of the file
let downloadURL = await uploadedFile.uploadTaskSnapshot.downloadURL;

// add the new files to files collection
await firestore.add(
  {
    collection: "files"
  },
  {
    name: fileName,
    url: ""
  }
);
} catch (error) {
console.log(error);
}
};`

The screenshot that I posted in the previous comment was from console logging the file that was uploaded to firebase storage.

console.log(uploadedFile.uploadTaskSnapshot.ref.getDownloadURL());

**Comment by prescottprue** [comment]
@PranavPanchal `uploadedFile.uploadTaskSnapSHot.ref.getDownloadURL()` is a promise, so you will want to make sure you `await` it.

**Comment by PranavPanchal** [comment]
@prescottprue Thank you very much for clearing that up!

**Comment by prescottprue** [comment]
This was released in v2.2.0-alpha.2 with associated unit tests that confirm `downloadURL` is available within the `metadataFactory` and `fileMetadataFactory` before writing the metadata to RTDB/Firestore. Reach out if it isn't working as expected.
