### ISSUE TITLE
Multiple populates do not work

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#49]
Hello again :)

Having multiple fields populated does not work for me. I'm not sure if it's supposed to work.

Data:
```js
goals: {
  goalId1: {
    uid: 'userId',
    partner: 'userId2'
  }
}
users: {
  userId: {
    displayName: 'John Smith'
  },
  userId2: {
    displayName: 'Jim Rogers'
  }
}
```

Code:
```js
const populates = [
  { child: 'uid', root: 'users'},
  { child: 'partner', root: 'users' }
]
@firebaseConnect(() => ([
  { path: 'goals', populates }
]))
@connect(({ firebase }) => ({
  allGoals: helpers.populatedDataToJS(firebase, 'goals', populates)
}))
```

Result:
```js
goals: {
  goalId1: {
    uid: 'userId',
    partner: 'userId2'
  }
}
```

Expected:
```js
goals: {
  goalId1: {
    uid: {
      displayName: 'John Smith'
    },
    partner: {
      displayName: 'Jim Rogers'
    }
  }
}
```

**Comment by prescottprue** [comment]
@DeividasK Great ask!

It is intended to be working, but does not currently have much testing for it. Will try to get it in to `v1.2.3`, but populate will be undergoing a re-write for `v1.3.0`. The hope is for much more advanced population functionality including what you have mentioned (also new features like #40, and fixing #48, #42)

**Comment by prescottprue** [comment]
Looked into it more, and it seems to be a deeper issue with populate. This functionality will not be available until `v1.3.0`, for now you might be able to do the following:

```js
const populates = [
  { child: 'uid', root: 'users'},
  { child: 'partner', root: 'users' }
]
@firebaseConnect(() => ([
  { path: 'goals', populates },
]))
@connect(({ firebase }) => ({
  goalsWithOwners: helpers.populatedDataToJS(firebase, 'goals', [populates[0]]),
  goalsWithPartners: helpers.populatedDataToJS(firebase, 'goals', [populates[1]])
}))
```

**Comment by psych0der** [comment]
Hi @prescottprue, 

I am using v1.3.1,
and still, multiple populate doesn't seem to work.

Here's the structure I am using,
```js
const populates = [{ child: 'owned', root: 'co' }, { child: 'mem', root: 'co' }];
@connect(
  ({ firebase }) => ({
    user: pathToJS(firebase, 'auth'),
  })
)
@firebaseConnect(
  props => ([
    { path: `/xxx`, populates },
  ])
)
@connect(
  (state, props) => ({
    co: populatedDataToJS(state.firebase, `/xxx}`, populates), // eslint-disable-line max-len
  })
)
```

`co` doesn't contain populated objects. Also, does it matter if currently, `mem` child doesn't exist?

**Comment by prescottprue** [comment]
Two things about your implementation @psych0der:

1. "`/xxx}`" in populatedDataToJS needs to be '/xxx' to match what you have in Firebase Connect
2. The first connect is only needed if need something passed as props into `firebaseConnect`

I will try to replicate myself, but it would be helpful if you could provide a full repository (including data format) for complete reproduction of the situation

**Comment by psych0der** [comment]
Here you go,

data format:
```js
companies: {
  'company1': {
    'id': 'company1'.
    'name': 'SomeCompany1',    
  },
  'company2': {
    'id': 'company2'.
    'name': 'SomeCompany2',    
  },
  'company3': {
    'id': 'company3'.
    'name': 'SomeCompany3',    
  },
  'company4': {
    'id': 'company4'.
    'name': 'SomeCompany4',    
  }
}

users: {
  'userid1123': {
    '_id' : 'userid1123',
    'name': 'Person1',
    'email': 'email1@gmail.com'
  },
  'userid9jh6': {
    '_id' : 'userid9jh6',
    'name': 'Person2',
    'email': 'email2@gmail.com'
  }
}

myOrgCharts: {
  'userid1123': {
    'owned': {
      'company1': true,
      'company2': true
    }
  }
}
```


Here's the code:

```js

const populates = [{ child: 'owned', root: 'companies' }, { child: 'member', root: 'companies' }];

@connect(
  ({ firebase }) => ({
    user: pathToJS(firebase, 'auth'),
  })
)
@firebaseConnect(
  props => ([
        { path: `/myOrgCharts/${props.user.uid}`, populates },
  ])
)
@connect(
  (state, props) => ({
    companies: populatedDataToJS(state.firebase, `/myOrgCharts/${props.user.uid}`, populates)
  })
)
export default class CompaniesList extends Component {

```

Now if you notice, member attribute doesn't exist for `userid1123` in `myOrgCharts`. In this case, react-redux-populate won't populate the existing owned companies. Only when member key exists for the user, it works.

I hope it's clear. Let me know if you need any other info.

**Comment by raghavendracs** [comment]
Think it was working earlier, but seem to getting same behaviour as detailed by @psych0der . Tried with both versions 1.4 and 1.5. Am I missing something?

**Comment by prescottprue** [comment]
@raghavendracs and @psych0der With v1, if you have multiple populates with the same root in redux (i.e. `companies`), then the second query results will overwrite the first. This doesn't happen in v2 as it merges the data at a given path if it exists, which should yield better results for this type of thing.

I am going to open up a new issue with multiple paths at the same root so that the bug is clearly defined, and we can track work on the fix for v1.

**Comment by prescottprue** [comment]
#274 Will be used to track issue with multiple populates at the same path.
