### ISSUE TITLE
feat(auth): link email address and password credentials to a user account

### ISSUE THREAD

**Issue by dancomanlive** [prescottprue/react-redux-firebase#490]
I could only find this http://react-redux-firebase.com/docs/api/firebaseInstance.html#linkwithcredential but how is this implemented ? Where is the credential coming from ?

Web SDK link  https://firebase.google.com/docs/auth/web/account-linking

**Comment by dancomanlive** [comment]
What I need to so is:

1. Have user log in with Google or Facebook - done
2. Get email and password from user - done
3. Link email and password to the user's social login account(without creating a new user) - not done

**Comment by harrison0723** [comment]
@prescottprue What is a good way to convert anon users with email/password for now?
https://firebase.google.com/docs/auth/web/anonymous-auth

**Comment by prescottprue** [comment]
@harrison0723 There is not currently support in `login` for anonymous auth, but feel free to open an issue requesting that as a feature so we can outline the exact case. Thanks for reporting!
