### ISSUE TITLE
Facebook error validating client secret

### ISSUE THREAD

**Issue by Fandekasp** [prescottprue/react-redux-firebase#493]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**
Following the documentation, I simply login using the provider and type popup
```es6
  doLogin = provider => () => {
    const credentials = {
      provider,
      type: "popup",
    };
    this.props.firebase.login(credentials);
    if (!isEmpty(this.props.auth)) {
      this.props.closeDialog();
    }
  };
```
This works well for google, but fails for facebook
```
"{"error":{"errors":[{"domain":"global","reason":"invalid","message":"Error getting access token from FACEBOOK, OAuth2 redirect uri is: https://XXX.firebaseapp.com/__/auth/handler, response: OAuth2TokenResponse{params: error=OAuthException&error_description=Error+validating+client+secret., httpMetadata: HttpMetadata{status=400, cachePolicy=NO_CACHE, cacheDuration=null, cacheImmutable=false, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"}],"code":400,"message":"Error getting access token from FACEBOOK, OAuth2 redirect uri is: https://XXX.firebaseapp.com/__/auth/handler, response: OAuth2TokenResponse{params: error=OAuthException&error_description=Error+validating+client+secret., httpMetadata: HttpMetadata{status=400, cachePolicy=NO_CACHE, cacheDuration=null, cacheImmutable=false, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"}}"
```

Note that the `https://XXX.firebaseapp.com/__/auth/handler` redirect uri found in firebase sign-in methods (with facebook provider obviously enabled) has been properly set in my facebook app → products → Facebook Login → Settings → Client Oauth Settings → Valid OAuth Redirect URIs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
Just using the default example with a facebook app and facebook provider enabled in firebase authentication.

**What is the expected behavior?**
Like for the google  provider, authentication should work and log me in my application

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
firebase@5.0.4
react-redux-firebase@2.1.5
react@16.4.0

**Comment by Fandekasp** [comment]
Firebase sign-in Facebook method had the wrong secret set. No bug, closing.

**Comment by prescottprue** [comment]
Good to hear.

Remember that `login` is a promise that should be getting resolved before doing anything else. It looks like you are are using `isEmpty` with a prop, but to do that correctly it would need to receive prop updates (i.e. within a `render` or `connect`). Where it is placed in your example (within a method) it will only fire once when the method is called.

**Comment by Fandekasp** [comment]
Oh. I suppose I misunderstood the usage of isEmpty then. Will look into it, thanks for the support @prescottprue !
