### ISSUE TITLE
FetchProvidersForEmail

### ISSUE THREAD

**Issue by Fandekasp** [prescottprue/react-redux-firebase#495]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**
Following https://stackoverflow.com/a/44040373/885053, it appears that the proper way to handle linking on login is to auto-fetch the provider for the same email, sign in with that provider, then link the new provider to that account.

Used methods from firebase.auth are:
* fetchProvidersForEmail
* linkWithCredential
* login
* signInWithCredential

I understand that react-redux-firebase uses `login({credential: firebase.auth.AuthCredential})` as replacement to signInWithCredential, and you're already supporting [linkWithCredential](https://github.com/prescottprue/react-redux-firebase/blob/master/docs/api/firebaseInstance.md#linkwithcredential).
But `fetchProvidersForEmail` seems to be missing. Can you add support for it ?
Or is there a better way to handle linking in this situation ?

Cordially

**Comment by prescottprue** [comment]
The full auth instance is available for methods which are not exposed. They can be accessed through `props.firebase.auth()` or `getFirebase().auth()` as mentioned in [the docs](http://react-redux-firebase.com/docs/auth.html).

Only methods which dispatch actions are exposed at the top level. Is there a state update or action dispatch that you would like to see associated with `fetchProvidersForEmail`? If so we can reopen. Thanks for reaching out!
