### ISSUE TITLE
bug(material example): running on windows produces error: "'cross-env' is not recognized as an internal or external command, operable program or batch file"

### ISSUE THREAD

**Issue by bakbuz** [prescottprue/react-redux-firebase#497]
app is not build. how i can fixed. thanks.

error message:

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-redux-firebase-material-example@0.0.1 start: `cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-firebase-material-example@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bayra\AppData\Roaming\npm-cache\_logs\2018-06-25T12_45_04_303Z-debug.log

log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\bayra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-firebase-material-example@0.0.1~prestart: react-redux-firebase-material-example@0.0.1
6 info lifecycle react-redux-firebase-material-example@0.0.1~start: react-redux-firebase-material-example@0.0.1
7 verbose lifecycle react-redux-firebase-material-example@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-redux-firebase-material-example@0.0.1~start: PATH: C:\Users\bayra\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Developments\RDC\Genel\react-redux-firebase\examples\complete\material\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\bayra\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\bayra\AppData\Local\Yarn\bin;C:\Users\bayra\AppData\Roaming\npm
9 verbose lifecycle react-redux-firebase-material-example@0.0.1~start: CWD: C:\Developments\RDC\Genel\react-redux-firebase\examples\complete\material
10 silly lifecycle react-redux-firebase-material-example@0.0.1~start: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start' ]
11 silly lifecycle react-redux-firebase-material-example@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle react-redux-firebase-material-example@0.0.1~start: Failed to exec start script
13 verbose stack Error: react-redux-firebase-material-example@0.0.1 start: `cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\bayra\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\bayra\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid react-redux-firebase-material-example@0.0.1
15 verbose cwd C:\Developments\RDC\Genel\react-redux-firebase\examples\complete\material
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bayra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.2
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error react-redux-firebase-material-example@0.0.1 start: `cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start`
22 error Exit status 1
23 error Failed at the react-redux-firebase-material-example@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by prescottprue** [comment]
Guessing that you are talking about the material complete example?

Are you sure that you ran `npm install` before calling `npm start`? It appears that `cross-env` is within the dev dependencies so it should be available.

Other thoughts:
* It appears that you are using node 8.11.2 - can you possibly try node 6.14.0 (matches cloud functions runtime)?
* Can you confirm that `cross-env` installed, and if so which version (using `npm ls cross-env`)? Interested if it is an issue with this.

**Comment by bakbuz** [comment]
Thank you very much.

**Comment by Edw1nLee** [comment]
I got stuck here, can anyone helps?

I tried to use node 6.14.0 and got the errors below:

➜  material git:(master) ✗ npm ls cross-env
react-redux-firebase-material-example@0.0.1 /Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material
├── cross-env@5.1.6 
└── UNMET PEER DEPENDENCY redux@4.0.0

npm ERR! peer dep missing: redux@^3.0.0, required by redux-form@7.3.0
➜  material git:(master) ✗ npm install cross-env
react-redux-firebase-material-example@0.0.1 /Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material
├─┬ cross-env@5.2.0 
│ └─┬ cross-spawn@6.0.5 
│   └── nice-try@1.0.4 
└── UNMET PEER DEPENDENCY redux@4.0.0

npm WARN redux-form@7.3.0 requires a peer of redux@^3.0.0 but none was installed.




***************************
> react-redux-firebase-material-example@0.0.1 start /Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material
> cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start

Error: listen EADDRINUSE :::1234
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1277:14)
    at listen (net.js:1313:10)
    at Server.listen (net.js:1409:5)
    at Server.listen.Server.attach (/Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material/node_modules/socket.io/lib/index.js:228:9)
    at new Server (/Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material/node_modules/socket.io/lib/index.js:52:17)
    at Server (/Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material/node_modules/socket.io/lib/index.js:40:41)
    at Object.<anonymous> (/Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material/node_modules/webpack-dashboard/bin/webpack-dashboard.js:47:14)
    at Module._compile (module.js:577:32)

npm ERR! Darwin 17.5.0
npm ERR! argv "/Users/Edwin/.nvm/versions/node/v6.14.0/bin/node" "/Users/Edwin/.nvm/versions/node/v6.14.0/bin/npm" "start"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-redux-firebase-material-example@0.0.1 start: `cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-firebase-material-example@0.0.1 start script 'cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-firebase-material-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dashboard -p 1234 -c cyan -m -t material -- node build/scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-firebase-material-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-firebase-material-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Edwin/Documents/GitHub/react-redux-firebase/examples/complete/material/npm-debug.log
