### ISSUE TITLE
populatedDataToJS does not return `null` if the data endpoint is empty

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#50]
I saw you've mentioned that populate will undergo a rewrite, but I just want to note that `populatedDataToJS` helper does not return `null` if the data endpoint is empty. It always returns `undefined`.

**Comment by prescottprue** [comment]
Going to try to replicate this to confirm, but if so that is not the intended functionality.

Thanks for noting!

**Comment by prescottprue** [comment]
[`v1.2.3`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.2.3) should hopefully solve this issue, but I will leave it open until that is confirmed.

**Comment by prescottprue** [comment]
@DeividasK Have you been able to verify this fix?

**Comment by DeividasK** [comment]
Sorry for such a long delay. Yes, I can verify that this works for me now. Thanks!
