### ISSUE TITLE
limit firestore data with firestore.setListeners

### ISSUE THREAD

**Issue by aphexyuri** [prescottprue/react-redux-firebase#502]
I'm have a complex dataset and would like to return a subset with only certain fields. Is this possible using `firestore.setListener('mycolection/' + docuemntWithId)` or something similar?

**Comment by prescottprue** [comment]
Not if you are talking about only certain fields on a document. All fields within a document (queried by doing `firestore.setListener('mycolection/' + docuemntWithId)`) are returned when that document is queried.

Once that data is in state though, you can easily filter as part of connecting to state (either by hand or with a selector).

If you have a large data set, you may want to [consider subcollections](https://firebase.google.com/docs/firestore/data-model).

Usually for implementation questions like this, you will get a faster and more complete response by reaching out [over gitter](gitter.im/redux-firebase/Lobby).
