### ISSUE TITLE
material example install fail

### ISSUE THREAD

**Issue by Edw1nLee** [prescottprue/react-redux-firebase#504]

**Comment by calvinlang** [comment]
I'm having the same issue on NPM install

`npm WARN deprecated material-ui@1.0.0-beta.47: You can now upgrade to @material-ui/core
WARN tar ENOENT: no such file or directory, open '/Users/calvin/Desktop/material/node_modules/.staging/har-validator-e65ea76d/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/calvin/Desktop/material/node_modules/.staging/ajv-093391aa/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/calvin/Desktop/material/node_modules/.staging/har-validator-e65ea76d/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/calvin/Desktop/material/node_modules/.staging/ajv-093391aa/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/calvin/Desktop/material/node_modules/.staging/har-validator-e65ea76d/LICENSE'
npm ERR! path /Users/calvin/Desktop/material/node_modules/.staging/react-redux-firebase-919168ab/node_modules/@babel/helper-function-name
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/calvin/Desktop/material/node_modules/.staging/react-redux-firebase-919168ab/node_modules/@babel/helper-function-name' -> '/Users/calvin/Desktop/material/node_modules/.staging/@babel/helper-function-name-f051b521'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
`

**Comment by prescottprue** [comment]
@calvinlang Not sure if the issue what your issue is due to here, but did you try removing and reinstalling your node_modules? It looks like you have you still have material-ui@1.0.0-beta.47 installed instead of @material-ui/core.

**Comment by calvinlang** [comment]
I fixed it, turns out `package-lock.json` wasn't updated
