### ISSUE TITLE
firebase.auth(...).onAuthStateChanged is not a function when using firebase-admin

### ISSUE THREAD

**Issue by panayi** [prescottprue/react-redux-firebase#506]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When using `firebase-admin`:

```javascript
import * as firebase from 'firebase-admin';
```

 I get the following error:

```
TypeError: firebase.auth(...).onAuthStateChanged is not a function
    at Object.init (node_modules/react-redux-firebase/lib/actions/auth.js:297:19)
```

A quick workaround is to set `auth` to null. A fix would be to check if `onAuthStateChanged` is a function, but not sure if there are other places where it breaks when using `firebase-admin`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**What is the expected behavior?**

Should work with firebase-admin.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

```
"react-redux-firebase": "2.1.6"
"firebase-admin": "5.12.1"
```

Not sure if it worked in previous versions of RRF.

**Comment by prescottprue** [comment]
@panayi react-redux-firebase was mostly built to be used on the front end with the firebase client or with another front end library (such as react-native-firebase which uses native modules).

Is there something specific you are planning on doing with react-redux-firebase in combination with firebase-admin?

**Comment by prescottprue** [comment]
Going to close for now since there wasn't a response on the use case. @panayi let me know if there was something you were hoping to do with `react-redux-firebase` in combination with `firebase-admin`, and we can reopen.
