### ISSUE TITLE
isLoaded helper always returns false when a default value is supplied to dataToJS

### ISSUE THREAD

**Issue by will-hart** [prescottprue/react-redux-firebase#51]
If you provide a default value to `dataToJS` the `isLoaded` helper always returns true, meaning loading spinners cannot be displayed.

Minimal working example from the `yo` generator: https://github.com/will-hart/react-redux-firebase-mwe

All the action is in here https://github.com/will-hart/react-redux-firebase-mwe/tree/master/src/routes/Home

Database looks like this:

![image](https://cloud.githubusercontent.com/assets/391950/22526729/79c71ca6-e920-11e6-88a8-71999bee4d33.png)

**Comment by prescottprue** [comment]
Will attempt to replicate.

The original intent of notSetValue was to return that value right away (i.e. no loading time) meaning that `isLoaded` is always true, but that is correct (since data is available right away). Either way, it isn't working as intended for your use case, so it will take some changing.

**SIDE NOTE:** `isLoaded()` accepts a list of arguments, not an array (i.e. `isLoaded(this.props.empty, this.props.full)` [instead of in the array](https://github.com/will-hart/react-redux-firebase-mwe/blob/master/src/routes/Home/NeverLoading.js#L25))

**Comment by will-hart** [comment]
Oh yes, sorry I took that array out on the other container and forgot for the `neverloading` one.

I see what you mean re the default, however if you supply a default it means that perfectly normal code can result in weird behaviour, I.e. long running request may show a "you do not have any projects" message and then suddenly populate with a whole list of projects when the request returns. This is kinda weird UX which is not currently obvious.

I mean I don't suppose it's a bug by the sound of it, but once you set the default `isLoaded` no longer does what it says. It seems to me it should be documented? I.e. I'm wondering if this could be resolved by a comment in the docs for `isLoaded`, something along the lines of:

> Note if you set a default value in `dataToJS` then `isLoaded` will always return `true`

**Comment by prescottprue** [comment]
@will-hart I totally agree that it is somewhat unexpected UX.

In the future we could only return the notSetValue if the data doesn't exist on Firebase. That way, isLoaded will be false until data is checked for, but either way should be documented.

Going to leave this issue open for a marker of making `notSetValue` only set after null is returned. Also, in the meantime I will add that note to the docs.

**Comment by prescottprue** [comment]
Docs have been updated to include the note to clarify.

The functionality you are asking (a default return value for a query that is null) might be added to the roadmap in the near future (will update this issue).
