### ISSUE TITLE
react-redux-firebase mutates the state

### ISSUE THREAD

**Issue by Fandekasp** [prescottprue/react-redux-firebase#510]
**Do you want to request a *feature* or report a *bug*?**  

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)
Bug

**What is the current behavior?**
react-redux-firebase mutates the state while [Redux's principle](https://redux.js.org/introduction/three-principles) is **State is read-only**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
Install [redux-immutable-state-invariant](https://github.com/leoasis/redux-immutable-state-invariant)

Then restart the app using react-redux-firebase. Console will raise the error `A state mutation was detected inside a dispatch, in the path: actionsById.1`:
![](https://i.imgur.com/k3c39Ht.png)

**What is the expected behavior?**
No firebase related errors.

Currently, I need to ignore firebase:
```es6
if (process.env.NODE_ENV === "development") {
  middleware = compose(
    middleware,
    window.devToolsExtension ? window.devToolsExtension() : f => f,
    applyMiddleware(
      immutableStateInvariantMiddleware({
        // dispatch for @@reactReduxFirebase/AUTHENTICATION_INIT_STARTED
        // mutates the state actionsById.1
        ignore: ["actionsById"],
      }),
    ),
  );
}
```

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Using redux@4.0.0, react-redux@5.0.7, react-redux-firebase@2.1.6 and  redux-immutable-state-invariant@2.1.0

**Comment by prescottprue** [comment]
@Fandekasp I understand the redux principle of state being read-only, but not undestanding the issue in this case. There is no reducer offered by `react-redux-firebase` that stores `actionsById` in state. The one reducer that does handle that action type being dispatched is [the isInitializingReducer`](https://github.com/prescottprue/react-redux-firebase/blob/master/src/reducers.js#L45) which is [dispatched by an auth state change](https://github.com/prescottprue/react-redux-firebase/blob/44fa39d3c43b029891c317ef54804ee345d310fb/src/actions/auth.js#L406).

What I am not understanding is what piece of state is not being treated as read-only in this case? That slice of state is only a boolean, and it is being switched from `false` to `true`. Do you possibly have some sort of initial state?

Totally open to a change, just trying to understand what is wrong here first. Thanks for reporting!

**Comment by Fandekasp** [comment]
Looks like PERFORM_ACTION and actionsById is handled by [redux-devtools](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L41).

Not sure what's wrong (can't spend too much time debugging this issue either), and no idea why this only happens for the AUTHENTICATION_INIT_STARTED action.
But since this is a dev-only issue, it looks like a very-low priority issue.

Thank you for your support, closing
