### ISSUE TITLE
Redux persist v5 example

### ISSUE THREAD

**Issue by Fandekasp** [prescottprue/react-redux-firebase#512]
The example for redux-persist v5 can be cleaned:
- autoRehydrate imported from redux-persist in `createStore.js` and left unused
- browserHistory sent to createStore and left unused.

http://react-redux-firebase.com/docs/integrations/redux-persist.html

Thank you for the example, feels like I avoided a major implementation headache :heart:

**Comment by prescottprue** [comment]
Fixed, thanks for reaching out with the input!

**Comment by geminiyellow** [comment]
hi @prescottprue , this title say `clean up redux persist v5 example` but v5 say `remove autoRehydrate`. i think we should remove it.

**Comment by prescottprue** [comment]
@geminiyellow Thanks for reaching out. Would you mind opening an issue? Open to PRs to if you get a chance to do the update yourself, otherwise I'll try to get to it soon.
