### ISSUE TITLE
create-react-app build

### ISSUE THREAD

**Issue by tebogos** [prescottprue/react-redux-firebase#515]
**Do you want to request a *feature* or report a *bug*?**  

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**What is the current behavior?**
My App is working fine when using the create-react-app life server but however fail to work when I deploy my app on firebase hosting.
I used create-react-app build script to build my app. I am not sure if the creat-react-app buils script is a problem.
When I run my hosted App I get the following error on my browser console:

Error: Collection can only be run on a document. Check that query config for subcollection: "tasks" contains a doc parameter.
    at query.js:93
    at n (_arrayEach.js:15)
    at r (forEach.js:37)
    at l (query.js:90)
    at s (query.js:134)
    at c (firestore.js:178)
    at firestore.js:252
    at Array.forEach (<anonymous>)
    at Object.d (firestore.js:248)
    at Object.setListeners (actions.js:92)
In @ react-dom.production.min.js:188

Below is my code 

```
import React from "react";
import PropTypes from "prop-types";
// react plugin for creating charts
import { withStyles } from '@material-ui/core/styles';
import Grid from '@material-ui/core/Grid';
import dashboardStyle from "assets/jss/material-dashboard-react/dashboardStyle";
import CircularProgress from '@material-ui/core/CircularProgress';
import { get, some } from 'lodash'

import {
  TaskDetails,
  ItemGrid,
  MyTaskCard
} from "components";

import { compose } from 'redux'
import { connect } from 'react-redux'
import { withHandlers, 
  mapProps,
  branch,
  renderComponent } from 'recompose'
import {
  firestoreConnect,
  isLoaded,
  isEmpty
} from 'react-redux-firebase'





// HOC that shows a component while condition is true
export const renderWhile = (condition, component) =>
  branch(condition, renderComponent(component))

// HOC that shows loading spinner component while list of propNames are loading
export const spinnerWhileLoading = propNames =>
  renderWhile(
    props => some(propNames, name => !isLoaded(get(props, name))),
    CircularProgress
  )

const enhance = compose(
  connect(({ firebase: { auth } }) => ({ auth })),
  spinnerWhileLoading(['auth']),
  firestoreConnect(props =>[
    // Load task from Firestore 
    { collection: 'user-data',doc:props.auth.uid,subcollections: [{ collection: 'tasks',doc:"" }] , storeAs: 'mytasks', where: ['status', '==', 'active']}
  ]),
  connect(
    ({ firebase: { auth },firestore: {ordered} }) => ({
        mytasks: ordered.mytasks,
        auth:auth
       
    })
  )
)




class MyTasks extends React.Component {
  state = {
    showDetails: false,
    task:{}
  };
  hideDetails = () => {
    this.setState({ showDetails:false });
  };

   showDetails = (task) => {
    this.setState({ showDetails: true });
    this.setState({task:task})
    console.log("task form Mydetails --> ",task);
    
  };
  render() {
  const {auth}=this.props;
    
 console.log(" mytasks --> ",this.props.mytasks);
 
if(this.props.mytasks)
    return (
      !isLoaded(auth)
      ? <span>Loading ...</span>
      : isEmpty(auth)
        ? <span>Not Authed</span>
        :
      <div>
        <Grid container>
          
          <ItemGrid xs={12} sm={12} md={6}>
          {this.state.showDetails ? <TaskDetails hideDetails={this.hideDetails} task={this.state.task} /> : 
            <MyTaskCard tasks={this.props.mytasks} showDetails={this.showDetails} />

            }
          </ItemGrid>
          
        </Grid>
      </div>
    );
    else
    return <h4>Loading1...</h4>
  }
}

MyTasks.propTypes = {
  classes: PropTypes.object.isRequired
};

export default  enhance(withStyles(dashboardStyle)(MyTasks)) ;
```
My package.json file is as follows:

```
 "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^1.3.1",
    "@material-ui/icons": "^1.1.0",
    "chartist": "0.10.1",
    "classnames": "^2.2.6",
    "fg-loadcss": "^2.0.1",
    "firebase": "^5.2.0",
    "lodash": "^4.17.10",
    "material-ui": "^0.20.1",
    "moment": "^2.22.2",
    "npm-run-all": "4.1.2",
    "perfect-scrollbar": "1.3.0",
    "react": "^16.4.1",
    "react-chartist": "^0.13.1",
    "react-dom": "^16.4.1",
    "react-popper": "^1.0.0",
    "react-redux": "^5.0.7",
    "react-redux-firebase": "^2.1.6",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.0.17",
    "react-swipeable-views": "0.12.12",
    "redux": "^4.0.0",
    "redux-firestore": "^0.5.7"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
```

The expected behavior is that I get the list of task from firestore.
   
You help will be highly appreciated

**Comment by prescottprue** [comment]
It seems like you are passing `doc: ""` with your query settings. Not sure what that is trying to accomplish, but it may cause issues.

For a pattern that scales a bit more, you may want to checkout [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase) - it is a yeoman generator that myself and my company use to start projects. It is also nice for developing quickly since there are [sub-generators for things like components](https://github.com/prescottprue/generator-react-firebase#component).

**Comment by tebogos** [comment]
Thank you for your response.

> It seems like you are passing doc: "" with your query settings. Not sure what that is trying to accomplish,but it may cause issues.

I have included the doc:"" when I was troubleshooting the error and I should have removed it.

> You are using auth in your query, so you should make sure that it has loaded (takes time). Waiting for data to load is mentioned in the query docs, but if you are looking for a more specific example, the state based query example snippet shows loading auth.

I did wait for the auth before rendering. I use the auth in the query as well, to get the tasks for a specific user. as shown below:
```
 connect(({ firebase: { auth } }) => ({ auth })),
  spinnerWhileLoading(['auth']),
  firestoreConnect(props =>[
    // Load task from Firestore 
    { collection: 'user-data',doc:props.auth.uid,subcollections: [{ collection: 'tasks',doc:"" }] , storeAs: 'mytasks', where: ['status', '==', 'active']}
  ]),
```
The code works well in development but however gives error when deployed. I suspect that the issue is with create-react-app build script(It seems like it does not build the react-redux-firebase well). I will try the generator-react-firebase as you have suggested.

Thank you for your help.

**Comment by prescottprue** [comment]
@tebogos I would have to look into the create-react-app build scripts to know for sure, but it does sound like a good theory. From what I understand, there isn't much in the way of being able to configure create-react-app unless you eject.

**Comment by tebogos** [comment]
Thanks a lot Scott.
I will in the meantime try generator-react-firebase, and refactor my app around generator-react-firebase.

Thank you.

**Comment by prescottprue** [comment]
I am not seeing this when building the basic create-react-app (with multiple versions of create-react-app), adding react-redux-firebase + redux-firebase and deploying to Firebase hosting.

Make sure your `firebase.json` is pointing to the right folder for where code is built. In the newer versions of create-react-app it is the `build` folder instead of the `public` folder (which is the default when using `firebase init`).

Going to close for now since I can't replicate, but post if you find any more information.
