### ISSUE TITLE
feat(storage): blobs with undefined values work with uploadFile

### ISSUE THREAD

**Issue by diericx** [prescottprue/react-redux-firebase#519]
**Do you want to request a *feature* or report a *bug*?**  
Report a bug

**What is the current behavior?**

When trying to upload an image that someone has chosen from their camera roll (in React Native), it returns some metadata error relating to cacheControl.
`    
    const { firebase } = this.props
    const response = await fetch(image.uri);
    const blob = await response.blob();
    console.log(image);
    firebase.uploadFile('uploads', blob, 'uploads', {name: 'test', cacheControl: 'max-age'})
`
Error:
`
Error uploading file: Reference.push failed: first argument contains undefined in property 'uploads.cacheControl', [Error: Reference.push failed: first argument contains undefined in property 'uploads.cacheControl']
`
What's interesting though is that the file is getting uploaded. It's in the correct place in storage and everything, the client is just getting this error for some reason.

**What is the expected behavior?**
Uploading shouldn't throw this cacheControl error. I'm wondering if this metadata is now required by FireBase? It would be nice to set a value for this but I can't find anything on setting metadata for uploads.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
React Native Expo v26

**Comment by prescottprue** [comment]
@diericx Not sure why the blob would have undefined values on it, but that is interesting. You should be able to solve this by only including values which are not `undefined`. In the future it would be nice to include something that does this automatically, but in the meantime you could use Lodash's `omit` like so:

```js
import { omit } from 'lodash'

const keysToOmit = ['uploads']
const cleanBlob = omit(blob, keysToOmit)
firebase.uploadFile('uploads', cleanBlob, 'uploads')
```

**Comment by diericx** [comment]
I think that fixed it, thanks!

**Comment by tetor** [comment]
I have same issue with Web. I can save file on Storage but can't save metadata to Firestore.
![screen shot 2018-09-12 at 16 28 06](https://user-images.githubusercontent.com/2876841/45409021-fe2e2c80-b6a8-11e8-8eae-ab57ced470a5.png)

version:
react-redux-firebase: 2.1.8
firebase: 5.2.0

**Comment by prescottprue** [comment]
@tetor I believe you are seeing something different since that is with metadata. Trying installing from `@next` and see if that helps. There have been some recent bug fixes for upload.

Providing a `metaFactory` option (when calling `uploadFile`) or a top level [`fileMetadataFactory`](http://react-redux-firebase.com/docs/recipes/upload.html#change-file-metadata) would allow you to change this metadata before it writes to Firestore - that way you can remove the undefineds.

**Comment by guuibayer** [comment]
I'm having the same problem, but @tetor with your implementation to ignore the undefined attributes, I'm having a permission error.

```js
const options = {
  metadataFactory: response => {
    const { metadata: {
      cacheControl,
      contentLanguage,
      customMetadata,
      ...data
    }} = response

    return data
  }
}
```
Error after upload,

![image](https://user-images.githubusercontent.com/5483459/46122274-32980180-c1ee-11e8-9dc7-af7bb43e37db.png)
