### ISSUE TITLE
Snippet from upload.md throwing errors

### ISSUE THREAD

**Issue by PranavPanchal** [prescottprue/react-redux-firebase#520]
### **Do you want to request a *feature* or report a *bug*?**  

Report a bug.

### **What is the current behavior?**

**When using the first snippet from the upload.md page:**

[https://github.com/prescottprue/react-redux-firebase/blob/master/docs/recipes/upload.md](url)

<img width="930" alt="screen shot 2018-08-10 at 2 28 51 pm" src="https://user-images.githubusercontent.com/17016563/43974843-c2496982-9ca9-11e8-9c56-0148d0707b16.png">

**It is throwing this error:**

<img width="1076" alt="screen shot 2018-08-10 at 2 18 08 pm" src="https://user-images.githubusercontent.com/17016563/43974860-d2430c76-9ca9-11e8-8581-77b2f9c5dfbb.png">

### **What is the expected behavior?**

I am assuming the file upload should upload the files when you drop them into React Dropzone component and be delete files when you click the "Delete File" button.

**Comment by prescottprue** [comment]
It looks like there is a missing `}` in there. It should be `connect(({ firebase: { data } }) => ({`. Thanks for pointing it out, I'll try to get to a fix of the docs soon.

**Comment by prescottprue** [comment]
Fixed, thanks for reaching out! Hoping to add a full working example on something like codesandbox soon.
