### ISSUE TITLE
Firestore storeAs examples did not work

### ISSUE THREAD

**Issue by JamesMcIntosh** [prescottprue/react-redux-firebase#523]
Documentation bug

https://github.com/prescottprue/react-redux-firebase/blob/master/docs/firestore.md

I couldn't get the 'storeAs' examples to work, I don't think the firestoreConnect parameters are correct for firestore.

```js
firestoreConnect(props => [
    { path: 'projects' },
    {
      path: 'projects',
      storeAs: myProjectsReduxName,
      queryParams: ['orderByChild=uid', '123']
    }
  ]),
```

In my own code when I used "collection, orderBy and where" parameters rather than "queryParams"  it works correctly. i.e.

```js
import { compose } from 'redux'
import { connect } from 'react-redux'
import { firestoreConnect } from 'react-redux-firebase'
const myProjectsReduxName = 'myProjects'

compose(
  firestoreConnect(props => [
    { collection: 'projects' },
    {
      collection: 'projects',
      storeAs: myProjectsReduxName,
      orderBy: [
        ['done'],
        ['name', 'desc']
      ],
      where: [
        ['done', '==', false],
        ['id', '<', 10]
      ]
    }
  ]),
  connect((state, props) => ({
    projects: state.firestore.data.projects,
    myProjects: state.firestore.data[myProjectsReduxName], // use storeAs path to gather from redux
  }))
)
```

Could I suggest linking out to the redux-firestore documentation directly at the top of this page also rather than the bottom?
https://github.com/prescottprue/redux-firestore

**Comment by prescottprue** [comment]
That is correct. redux-firestore expects `collection`, `where`, and `orderBy`. I'll cleanup the example, thanks for reporting!

**Comment by prescottprue** [comment]
Published the changes, thanks again for reaching out!
