### ISSUE TITLE
Auth and profile are not flushed upon logout

### ISSUE THREAD

**Issue by xpsdeset** [prescottprue/react-redux-firebase#525]
Whenever a user logs out, and when a different users logs into the same browser or device incase of react-native. Previous auth and profile is not cleared/ refreshed. 
Hence the newly logged in user get auth and profile of previously logged in user.   

I used simple config for redux-firebase.

> const rrfConfig = {  userProfile: 'users'}

>   props.firebase.logout()

**Comment by prescottprue** [comment]
@xpsdeset What version are you using? Did you check to see if actions are dispatched? Did you handle logout as a promise? Are you seeing auth in state still or localStorage/sessionStorage?

**Comment by prescottprue** [comment]
@xpsdeset Are you still experiencing this? Did you get a chance to look into any of the above questions?
