### ISSUE TITLE
bug(reducer): DELETE_SUCCESS action causes item to be added back to ordered state causing "flicker"

### ISSUE THREAD

**Issue by sdacunha** [prescottprue/react-redux-firebase#530]
**Do you want to request a *feature* or report a *bug*?**  
Bug
(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**What is the current behavior?**
I currently have two listeners setup via firestoreConnect. One is for the parent collection 'users' at a specific document and the other for its subcollection 'trips'.

When I delete an item, the follower actions are fired:
<img width="1181" alt="screen shot 2018-08-30 at 2 09 09 pm" src="https://user-images.githubusercontent.com/6006129/44870490-6ec35b00-ac5e-11e8-926b-2dd51eaf55a4.png">
<img width="1178" alt="screen shot 2018-08-30 at 2 09 27 pm" src="https://user-images.githubusercontent.com/6006129/44870494-7256e200-ac5e-11e8-9912-34bf67a8b623.png">
<img width="1180" alt="screen shot 2018-08-30 at 2 09 37 pm" src="https://user-images.githubusercontent.com/6006129/44870504-797df000-ac5e-11e8-897f-86301871c77f.png">
<img width="1181" alt="screen shot 2018-08-30 at 2 09 52 pm" src="https://user-images.githubusercontent.com/6006129/44870510-7daa0d80-ac5e-11e8-8418-4c21235061cf.png">
<img width="1184" alt="screen shot 2018-08-30 at 2 10 00 pm" src="https://user-images.githubusercontent.com/6006129/44870516-80a4fe00-ac5e-11e8-9999-a747fde105d7.png">

What happens here, is that the item gets deleted on the subcollection listener catching it, then delete success re-adds the key with a null value, the next listener response re-inserts the entire value and the last one deletes it, which causes my list (from which i performed the delete) to flicker.

Here is what my listeners look like:
``
export default firestoreConnect((props, store) => ([
  {
    collection: 'users',
    doc: store.firebase.auth().currentUser.uid
  },
  {
    collection: 'users',
    doc: store.firebase.auth().currentUser.uid,
    subcollections: [ { collection: 'trips' } ],
    storeAs: 'trips'
  },
]))(withNavigation(withFirebase(connect(mapStateToProps)(Trips))));
``

and the delete function:
``
this.props.firestore.delete({
      collection: 'users',
      doc: this.props.firebase.auth().currentUser.uid,
      subcollections: [ { collection: 'trips', doc: trip.id } ],
    });
``

Any ideas?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**What is the expected behavior?**
The delete should not re-insert the deleted item or its key via the listener.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Using:
"redux-firestore": "^0.5.8"
and
"react-redux-firebase": "^2.2.0-alpha" (switched to this version hoping it was fixed here)

Thanks! And great work on redux-firebase and redux-firestore, it saved me a ton of time.

**Comment by prescottprue** [comment]
Going to look into replicating, but at first glance, it seems like the following may be related:
[113](https://github.com/prescottprue/redux-firestore/issues/113), [115](https://github.com/prescottprue/redux-firestore/issues/115), and [116](https://github.com/prescottprue/redux-firestore/issues/116) issues of redux-firestore

In the meantime: `storeAs` allows you to store your data in redux under different paths, so you can make your two separate queries not collide within redux.

**Comment by sdacunha** [comment]
I do use storeAs right now, so the subcollection in stored under 'trips', but I notice this behaviour regardless

**Comment by prescottprue** [comment]
Going to close since tracking is on redux-firestore
