### ISSUE TITLE
storeAs has no Effect

### ISSUE THREAD

**Issue by Ortimis** [prescottprue/react-redux-firebase#532]
**What is the current behavior?**
```
firestoreConnect((props) => [
    {collection: `/users/${props.auth.uid}/annotations`},
    {
      collection: `/users/${props.auth.uid}/annotations`,
      storeAs: 'annotations'
    }
  ]
    
  )
```
stores collection in redux `firestore { data { users/someid/annotations { } }`

**What is the expected behavior?**
stores collection in redux `firestore { data { annotations { } }`

**Comment by prescottprue** [comment]
@Ortimis Do you have `redux-firestore` setup? If so, what version?

I believe this may be because you are providing a doc path as part of the collection name instead of passing it as `doc`. It seems like you are also trying to reference a subcollection. Slash path notation works using the string syntax, but I don't believe it will work as you are intending when passing the slash path as `collection`.

**Comment by Ortimis** [comment]
@prescottprue I updated to ^0.5.8 now, this didn't change the behavior.

However, I changed the markup to

```
firestoreConnect((props) => [
    { collection: '/users/',
      doc: `${props.auth.uid}`,
      subcollection: [{collection: 'annotations'}]
    },
    {
      doc: `${props.auth.uid}`,
      subcollection: [{collection: 'annotations'}],
      storeAs: 'annotations'
    }
  ])
```
Works like a charm now :) thank you

**Comment by Ortimis** [comment]
Actually no.
After it worked a few times (maybe some cache thing going on), it threw the error `Collection is required to build query name`, meaning that the second object needs a declaration auf `collection: ????`, too. So I tried:
```
firestoreConnect((props) => [
    {
      collection: '/users/',
      doc: `${props.auth.uid}`,
      subcollection: [{collection: '/annotations/'}]
    },
    {
      collection: '/users/', // I also tried '/annotations/'
      doc: `${props.auth.uid}`,
      subcollection: [{collection: '/annotations/'}],
      storeAs: 'annotations'
    }
  ])
```
Which added a 'users' object in firestore.data.users.

There seems to be no clear documentation about how firestoreConnect is supposed to be used with subcollections. I would be very glad about more clarification.

Thank you!

**Comment by Ortimis** [comment]
Found out all my problems were caused by a type. "subcollection" instead of "subcollections"!
Thank you for your help, in this case, the doc is not too hard to navigate, actually. My bad!

**Comment by prescottprue** [comment]
@Ortimis Glad to hear it is working! Thanks for reaching out to clarify what it was. It may be helpful to add a warning for any non used keys in a coming version - that way you could have been warned about the `subcollection` param being incorrect.
