### ISSUE TITLE
idToken returned from Google Login object is renamed to accessToken in redux store, having the same name with the Google accessToken

### ISSUE THREAD

**Issue by hinsxd** [prescottprue/react-redux-firebase#534]
When using Social Login with google,
```
firebase.login({ provider: 'google', type: 'popup' }, result => console.log(result)
```
gives the following object in Chrome Console
```
{profile: {…}, user: Q, credential: Kf, additionalUserInfo: Af, operationType: "signIn"}
...
accessToken: "ya29....."
idToken: "eyJhb..............."
providerId: "google.com"
...
```
while inside `store.firebase.auth.sksTokenManager`,`accessToken(pin): "eyJhb..........`

The naming is confusing, and the tokens have difference usages.
I think the variables in the store should follow the officially returned object.

**Comment by prescottprue** [comment]
I believe the most common way of loading tokens, and [the one mentioned in the Firebase docs](https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients) is using `firebase.auth().currentUser.getIdToken`. Not sure what you are intending to use the token for, but does that method work for you?

Will look into if this token is modified in the response, but I didn't think the response was being modified other than to attach the profile.

**Comment by prescottprue** [comment]
Were you able to get things working after following the above mentioned docs? Going to close for now since the response just extends the Firebase JS SDK, and using `firebase.auth().currentUser.getIdToken` is the way their docs suggest getting the access token.
