### ISSUE TITLE
profileFactory doesn't work for roles

### ISSUE THREAD

**Issue by salmazov** [prescottprue/react-redux-firebase#535]
My firebase:
![image](https://user-images.githubusercontent.com/1635615/45412471-5c461a00-b67f-11e8-9453-00dc9e265275.png)

My config:
https://bitbucket.org/Almazov/react-redux-firebase-base-app/src/99db6caca4e071c720125b16bd831bc438dafb33/src/index.js?at=roles-support&fileviewer=file-view-default

![image](https://user-images.githubusercontent.com/1635615/45412546-92839980-b67f-11e8-9bf1-9752895749db.png)

But I don't actually understand why data doesn't pass to firebase?

**Comment by salmazov** [comment]
I want to add roles support for my app like this:
http://react-redux-firebase.com/docs/recipes/roles.html

But I don't understand how to put roles data to firebase.

![image](https://user-images.githubusercontent.com/1635615/45412952-a67bcb00-b680-11e8-9083-dc95cadb8e59.png)
It is correct place to handle roles?

**Comment by prescottprue** [comment]
@salmazov Most of this looks correct except it doesn't look like the profiles you have contain `role`. What method did you use to sign in? Also what version of `react-redux-firebase`?

**Comment by salmazov** [comment]
@prescottprue I solve 1/3 of my problem =)

First of all, I used this method:
// export const doCreateUser = (id, username, email) =>
//   db.ref(`users/${id}`).set({
//     username,
//     email
//   });

Now I use this:
export const authUserAction = (credentials, history) => (dispatch, getState, getFirebase) => {
    const {email, passwordOne, username} = credentials;
    
    console.log('getFirebase', getFirebase());
    
    getFirebase().createUser({name: username, password: passwordOne, email: email}).then(res => {
      console.log('res', res);
    });

So profileFactory is working now. But I don't understand how to put role to Firebase correctly and how to manage it.

my versions:
    "firebase": "^5.2.0",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "react-redux-firebase": "^2.1.6",
    "react-router-dom": "^4.3.1",

**Comment by prescottprue** [comment]
What you had before (i.e. setting to the user path) is not going to do anything but write data to Real Time Database - there is no auth interaction.

As you show in your second example, you need to use `createUser` in order to have actions dispatched and profile created.

To answer about role: You can put role into firebase by passing it as part of the profile (the second argument of `createUser`):

```js
const creds = { password: passwordOne, email }
const profile = { name: username, email, role: 'user' }
getFirebase().createUser(creds, profile).then(res => {
  console.log('res', res);
});
```

Closing for now. Let me know if you think adding something to the docs would make things more clear.

**Comment by salmazov** [comment]
@prescottprue Thanks for the answer, but in this case profileFactory will ignore second argument (profile) in this example.

So I can use:
second parameter
or profileFactory

Can you add this to documentation?
