### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by gino-m** [prescottprue/react-redux-firebase#537]
This turned out to be due to a call to firestore.update() where the path was referring to a collection rather than a doc. This occured because the doc id was unintentionally `null`. i.e.

```js
 props.firestore.update({ collection: "projects", doc: projectId }, {title: newTitle});
```
`projectId` here was null.

Would it be possible to catch and report this earlier and log a more specific error?

**Comment by prescottprue** [comment]
@gino-m Love the idea. Can we open an issue on `redux-firestore` for this since that is where the update methods lives?

**Comment by gino-m** [comment]
Sure, I'll open an issue there!
