### ISSUE TITLE
fix(docs): update redux-auth-wrapper example to use connectedAuthWrapper instead of UserAuthWrapper

### ISSUE THREAD

**Issue by salmazov** [prescottprue/react-redux-firebase#542]
In react-redux-firebase I use "redux-auth-wrapper/connectedAuthWrapper" instead of "UserAuthWrapper".

UserAuthWrapper is deprecated.

I don't see this notes in migration guide.

**Comment by salmazov** [comment]
What about this migration guide?
https://mjrussell.github.io/redux-auth-wrapper/docs/Migrating.html

This is hell for developer! So if I want to use 2.0.0 of react-redux-firebase I have to read 1.0, then migration guide to 2.0, and, in parallel mode I have to read redux-auth-wrapper 1 and migration guide to 2.

Are you serious?! OMFG...

**Comment by prescottprue** [comment]
@salmazov The migration guide is for migrating to the new version of `react-redux-firebase` (v2) not other tools like `redux-auth-wrapper`. The examples use `redux-auth-wrapper`, but you are in no way required to use it when using`react-redux-firebase`. The examples are there to help by showing how one **could** use these tools together.

If you would like to use the newest version of `redux-auth-wrapper`, then you may follow their docs for that. If you would like to use the version of the tools that are included in the example then do that.

If you are asking "Why are the examples not more up to date?"
The answer is: It takes time to update and verify dependencies across the many apps/environments I am running (especially in production environments). I am still in the process of testing out the switch to `redux-auth-wrapper` accross my projects. In my experience it is much better to get things running right rather then rush them.

Open to a PR that updates the docs to make this more clear. Something to keep in mind is that this is open source and all work is done by volunteers.

**Comment by prescottprue** [comment]
Both the example and the docs have been updated. The redux-auth-wrapper v2 examples now appear before the older ones within the docs.
