### ISSUE TITLE
fix(docs): remove autoRehydrate from redux-persist v5 example

### ISSUE THREAD

**Issue by geminiyellow** [prescottprue/react-redux-firebase#545]
**Do you want to request a *feature* or report a *bug*?**  

Remove autoRehydrate from redux-persist v5 example

**What is the current behavior?**

https://github.com/prescottprue/react-redux-firebase/issues/512#issuecomment-427246048

**Comment by prescottprue** [comment]
Docs updated, thanks for reporting.
