### ISSUE TITLE
(new feature?) Support to handle persisted auth state

### ISSUE THREAD

**Issue by Eli1bamboo** [prescottprue/react-redux-firebase#549]
I'm trying to switch google accounts but the persisted state is always stuck on the same account. The logout method does effectivle log out the authed user but it does not clear the persisted state.

Firebase documentation ref:
https://firebase.google.com/docs/auth/web/auth-state-persistence?hl=en-419

thanks in advance !

**Comment by prescottprue** [comment]
I believe you are talking about the "prompt" custom auth parameter option which prompts for the user to select their account every time when logging in through Google.

You can do this through react-redux-firebase by passing `customAuthParameters` to your react-redux-firebase config:

```js
{
  userProfile: 'users',
  customAuthParameters: {
    google: {
      prompt: 'select_account'
    }
  }
}
```

Under the hood, it uses [`setCustomParams`](https://firebase.google.com/docs/reference/js/firebase.auth.GoogleAuthProvider#setCustomParameters) as noted as an option [in the Google Auth section of the Firebase Docs](https://firebase.google.com/docs/auth/web/google-signin#handle_the_sign-in_flow_with_the_firebase_sdk).


Other than that, I am not really aware of a "persisted state" that would not be getting cleared
