### ISSUE TITLE
How come collection returns to null?

### ISSUE THREAD

**Issue by donPuerto** [prescottprue/react-redux-firebase#552]
As seen below database is connected to the state as "project" collection were populated however "notifications" collection" return to null.

Firestore Database
![image](https://user-images.githubusercontent.com/9329005/47409516-8ec25700-d795-11e8-9f1f-113f3386d69f.png)

console.log for the "state"
![image](https://user-images.githubusercontent.com/9329005/47409561-b4e7f700-d795-11e8-953c-91d6c0d60039.png)

```
import React, { Component } from 'react';
import ProjectList from '../projects/ProjectList';
import Notifications from './Notifications';
import { connect } from 'react-redux';
import { firestoreConnect } from 'react-redux-firebase'
import { compose } from 'redux'
import { Redirect } from 'react-router-dom'


class Dashboard extends Component {
  render() {

    const { projects, auth, notifications } = this.props;
    console.log('dashboard', this.props)
    
    // When it is not authenticted then it will be directed to 'signin in route'
    // route guarding before rendering dom
    if (!auth.uid) return <Redirect to='/signin' />

    return (
      <div className="dashboard container">
        <div className="row">
          <div className="col s12 m6">
            <ProjectList projects={projects} />
          </div>
          <div className="col s12 m5 offset-m1">
            <Notifications notifications={notifications} />
          </div>
        </div>
      </div>
    );
  }
}

const mapStateToProps = (state) => {
  console.log('state firestore', state)
  // return {
  //   projects: state.project.projects
  // }
  return {
    projects: state.firestore.ordered.projects,
    auth: state.firebase.auth,
    notifications: state.firestore.ordered.notifications
  }
}

export default compose(
  connect(mapStateToProps),
  firestoreConnect([
    { collection: 'notifications', limit: 3, orderBy: ['time', 'desc']},
    { collection: 'projects', orderBy: ['createdAt', 'desc']},

  ])
)(Dashboard)

```

**Comment by donPuerto** [comment]
its okay now. Error was on the firebase security rules.

**Comment by marcobiedermann** [comment]
@donPuerto 
I run into the same issue. Could you please share your Firebase config how to fix it.

Right now I have set everything to read and write

```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}
```

I know this should never be the case for production but for local development it would be fine. Still I get `null` for each collection

**Comment by prescottprue** [comment]
@marcobiedermann Please open a new issue with the query you are running - my guess is that a query error is being written to state (since `null` is an indication of empty, meaning that the query did most likely go out).

**Comment by marcobiedermann** [comment]
@prescottprue 

Sorry, my bad. I used `firebaseConnect()` instead of `firestoreConnect()` 🙈
