### ISSUE TITLE
Dealing with multiple queries on the same route

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#56]
I would like to make a couple of queries to the same path, but with different params. However, these queries are stored in the store based on 'path' param.

Example:
```js
@firebaseConnect((props) => ([
  { path: 'goals', queryParams: [ `orderByChild=partner`, `equalTo=partnerId`] },
  { path: 'goals', queryParams: [ `orderByChild=expert`, `equalTo=expertId`] },
]))
@connect(({ firebase }, props) => ({
  ???
}))
```

Would it be possible to name a path for the queries to be stored at?

Example of the feature:
```js
@firebaseConnect(() => ([
  { path: 'goals', storeAs: 'partnerGoals', queryParams: [ `orderByChild=partner`, `equalTo=partnerId`] },
  { path: 'goals', storeAs: 'expertGoals', queryParams: [ `orderByChild=expert`, `equalTo=expertId`] },
]))
@connect(({ firebase }) => ({
  partnerGoals: helpers.dataToJS(firebase, 'partnerGoals'),
  expertGoals: helpers.dataToJS(firebase, 'expertGoals'),
}))
```

I think this solution would also help with issue #55 whereas I could just store the data under different paths, so they would not be mixed and I would save some calls to the database.

Ideas?

Edit: Checked the source and I see you have `dest` variable ( [link](https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/query.js#L22) ), but I couldn't find how it's used.

**Comment by prescottprue** [comment]
This is a great idea, thanks for the suggestion! I would love to look into what it will take and get back to you about when/where it will fit into the road map.

**Comment by mattapperson** [comment]
I am also in need of this feature

**Comment by prescottprue** [comment]
There has been progress on this functionality. Hoping to get it into one of the upcoming release candidates so it can make it into v1.3.0.

Will post here when there is a published version.

**Comment by prescottprue** [comment]
[`v1.3.0-rc.1`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.3.0-rc.1) has been released with multiple query support using `storeAs` as described.

[Multiple queries example](https://github.com/prescottprue/react-redux-firebase/tree/v1.3.0-rc.1/examples/snippets/multipleQueries) has also been added to illustrate usage of `storeAs`.

Docs updates will not be published to [docs site](https://react-redux-firebase.com) until `v1.3.0` is released. Going to leave this open until someone else gets a chance to confirm it works as expected.

**Comment by DeividasK** [comment]
Works like a charm!
