### ISSUE TITLE
Does the accessToken in the stsTokenManager refresh automatically ? 

### ISSUE THREAD

**Issue by NirLud** [prescottprue/react-redux-firebase#562]
Hi, Does the accessToken in the stsTokenManager refreshes automatically ? 
If so, whats the name of the action ?
if not, whats the best practice to refresh it?

the token is expired after 60 minutes. i want to refresh it before its happened.

Thanks

**Comment by prescottprue** [comment]
I believe what you want is [Firebase's getIdToken](https://firebase.google.com/docs/reference/js/firebase.User#getIdToken) or getIdTokenResult. As mentioned in the docs passing `true` to getIdToken should automatically refresh it:

```js
firebase.auth().currentUser.getIdToken()
  .then((token) => {
    console.log('the token is', token)
  })
  .catch((err) => {
    console.error('Error refreshing id token', err)
  })
```

**Comment by Wgil** [comment]
I need to have access to the latest auth token and I thought that `stsTokenManager` had the latest token. It would be nice to dispatch an action when the token refreshes. Something like:
```
firebase.auth().onIdTokenChanged.(token => dispatch({type: "tokenRefreshed", token})
```

Is `stsTokenManager.accessToken` used for something internally?

**Comment by prescottprue** [comment]
@Wgil I don't believe it is - feel free to open a new issue to request that as a feature so we can track
