### ISSUE TITLE
undefined is not a function (evaluating '_app.default.auth()')

### ISSUE THREAD

**Issue by HamzaMehmmod786** [prescottprue/react-redux-firebase#563]
![screenshot_1542103074](https://user-images.githubusercontent.com/41784309/48405809-d6188380-e754-11e8-84e9-17dd2555d205.png)

**Comment by HamzaMehmmod786** [comment]
This error is showing while i use auth().

**Comment by HamzaMehmmod786** [comment]
@prescottprue  thanks for reply but i fix it later.

**Comment by prescottprue** [comment]
@HamzaMehmmod786 ok, seems to be due to something with react-native. Not sure if you are using react-native-firebase or not.

**Comment by mynksrv** [comment]
@HamzaMehmood786  how did you solve it?

**Comment by prescottprue** [comment]
@mynksrv Make sure you are importing `'firebase/auth'`

**Comment by mynksrv** [comment]
wow! that works.
thanks. @prescottprue

**Comment by asadnawaz126** [comment]
@HamzaMehmood786 @prescottprue I'm getting this exact error, but it won't go away with what you guys have suggested

**Comment by ZwelLHAg** [comment]
@prescottprue Thank . Really work with import auth from '@firebase/auth'

**Comment by prescottprue** [comment]
@ZwelLHAg Things have changed since when I made that response. You are correct that it is now `@firebase/auth`

**Comment by Proton2-Limitless** [comment]
> Could you possible post how your initialize Firebase and how you use it in your component? Kinda hard to try to replicate otherwise.

pls how do you resolve this issue , i am having the same problem right now....nedd your help asap,will b gratefull

**Comment by Proton2-Limitless** [comment]
pls how do you resolve this issue , i am having the same problem right now....nedd your help asap,will b gratefull

**Comment by prescottprue** [comment]
@Proton2-Limitless - if you are on the newer versions of the firebase sdk, try downgrading to v8 in confirm your imports
