### ISSUE TITLE
feat(Material example using firestore)

### ISSUE THREAD

**Issue by tugal** [prescottprue/react-redux-firebase#568]
Feature wanted

As a noob in redux world, it would be awesome to have a material example working with firestore.
I try to start with material example, and add firestore support but i still get error messages(Firebase.firestore is not a function)

Thanks..
Nelson

**Comment by prescottprue** [comment]
@tugal It seems like you may be missing the import of firestore, something like `import firebase/firestore`. Using Firestore requires importing Firestore from the Firebase JS SDK as well as adding the `reduxFirestore` store enhancer as described in the [the firestore section of the docs](https://react-redux-firebase.com/docs/firestore.html). Doing this is [also shown in the Firestore example](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/firestore/src/store.js).

If you would like to start a new project with this library and @material-ui/core, you can checkout [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase). It has options to include Firestore as well as some other features.

Feel free to reach out if that doesn't get you going in the right direction - Also answers usually get answered a little faster [over gitter](https://gitter.im/redux-firebase/Lobby).
