### ISSUE TITLE
How to work with state outside of firebase, redux

### ISSUE THREAD

**Issue by brianlovin** [prescottprue/react-redux-firebase#57]
This repo is amazing, thanks so much for the work! 

I'm a bit confused how to include non-firebase state into redux when using these connect methods.

Here's the example code:

```
const wrappedTodos = firebaseConnect([
  '/todos'
])(Todos)

export default connect(
  ({firebase}) => ({
    todos: dataToJS(firebase, 'todos'),
  })
)(wrappedTodos)
```

This generates a redux store with 
firebase > data > todos

My question is how to manage store and connect()-ing when using things outside of firebase.

For example:

firebase > data > todos
activeTodo
otherStateToManage

Do you have any advice on including `activeTodo` and `otherStateToManage` in the connect() method?

**Comment by brianlovin** [comment]
Was able to fix:

```
const wrappedTodos = firebaseConnect([
  '/todos'
])(Todos)

export default connect(
  ({firebase, outsideStateFromAnotherReducer}) => ({
    todos: dataToJS(firebase, 'todos'),
    outsideStateFromAnotherReducer.foo,
    outsideStateFromAnotherReducer.bar,
    ...
  })
)(wrappedTodos)
```

**Comment by prescottprue** [comment]
@brianlovin Correct, the first argument passed to the `connect` function is redux state. Firebase is commonly plucked off for usage with `dataToJS`.

The functionality of `connect` is not at all affected by this library (it is imported directly from redux), which is intended.

**Comment by dchersey** [comment]
Thank you @brianlovin & @prescottprue; this was a helpful issue for me solving the same problem. 
Might be a good update for the docs.

My 2.0 @connect code with mix of firebase and local state looks like: 

### reducers 
```javascript
export default combineReducers({
  localUserInfo,
  firebase
});
```
### component connect
```javascript
@firebaseConnect(["/count"])
@connect(({ firebase: { data: { count } } }, localUser) => ({
  count,
  localUser
}))
export default class HomeScreen extends React.Component
...
```
