### ISSUE TITLE
Switch status is not being updated on db value

### ISSUE THREAD

**Issue by muscaiu** [prescottprue/react-redux-firebase#575]
Not sure why this is happening either react-redux-firebase library or material-ui, so i posted this issue on both pages.

Please check the example below ot get the full details of the issue.

[Codesandbox Demo](https://codesandbox.io/s/j3yl9wz555)

**Comment by prescottprue** [comment]
When checking out the sample I am not sure I understand the issue.

The data is changing in Firebase, and it appears that you are just not waiting for it to load before rendering. It will be `undefined` before loading, then it will be the value from the database. 

If you add the following to you Header.js component, then you are waiting for the data to load before setting the value:


```js
    if (!isLoaded(status)) {
      return <div>Loading</div>;
    }
```

Here is a fixed version of your example: https://codesandbox.io/s/ko4q560q3
