### ISSUE TITLE
How to deploy app with react-redux-firebase as a firebase function?

### ISSUE THREAD

**Issue by salmazov** [prescottprue/react-redux-firebase#576]
I want to deploy my app as SSR-ready via using firebase function.

But I got an error:
`i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

undefined`

It's very difficult to understand what I do wrong. But when I comment compose function - it works.
//   ,
//   compose(
    // applyMiddleware(
    //   thunk.withExtraArgument(getFirebase) // Pass getFirebase function as extra argument
    // ),
    // reactReduxFirebase(firebase.firebase, rrfConfig), // pass in firebase instance instead of config
    // window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
    //  reduxFirestore(firebase) // <- needed if using firestore
    //  applyMiddleware(...middleware) // to add other middleware
//   )

**Comment by prescottprue** [comment]
It seems like you are using `window.` which I don't believe will be available when running SSR (since node doesn't have the window variable). It may be best to start with a redux SSR example and add react-redux-firebase.

**Comment by illuminist** [comment]
So the solution is to check whenever `window` is available or not. For me, it is:
```javascript
if (typeof window !== 'undefined') {
  // some statements involving window object here
}
```

**Comment by salmazov** [comment]
Thank you! I'll try it
