### ISSUE TITLE
createPersistoid: error serializing state on createUser failure

### ISSUE THREAD

**Issue by Nolence** [prescottprue/react-redux-firebase#577]
**Do you want to request a *feature* or report a *bug*?**  
A Bug

**What is the current behavior?**
I'm not trying to persist the error myself, but when the createUser function times out, the error created by the catch won't be correctly serialized and saved by redux-persist. I thought it might be related to  [this question](https://github.com/rt2zz/redux-persist/issues/644) but it looks more like a general problem of trying to serialize cyclic data.

If this isn't just me being dumb and forgetting something special in the docs, is there any chance someone could just blacklist the error inside the config options for a quick fix? I don't know where it'd be found.

<img src="https://user-images.githubusercontent.com/29642168/49179298-40155900-f30f-11e8-9abc-f1b2c81aa410.PNG" alt="react-native-firebase-error" width="400" height="600"/>

**What is the expected behavior?**
The error to be persisted and serialized.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
This is my first time encountering this error. I'm using react-native and with redux-persist integration.
react-redux-firebase: "5.1.1"
redux-persist: "5.10.0"

**Comment by Nolence** [comment]
Nope, I think I found the right key of the reducer and I tried adding some persist config but that didn't do it.

```javascript
const firebasePersistConfig = {
  key: "firebase",
  storage,
  blacklist: ["authError"]
};

const rootReducer = combineReducers({
  app: appReducer,
  search: searchReducer,
  firebase: persistReducer(firebasePersistConfig, firebaseReducer),
  webSocket: webSocketReducer
});
```

**Comment by prescottprue** [comment]
Hmmm super interesting. Was this every type of error with `createUser`? How were you able to cause the error that then didn't persist?

Later tonight I will try to intentionally dispatch some errors and see if I can get this to happen. Thanks for reporting!

**Comment by Nolence** [comment]
@prescottprue 
HI Scott, I haven't tried to blacklist anything else yet, but I've found that this same error occurs for me even using the  `login` method exposed by `firebase`.

I ran into the problem by just not having any internet connection and trying to register or sign-in using the above methods on my react-native app from an android simulator. With an internet connection, both `createUser` and `login` work just fine. Thanks for the help!

**Comment by prescottprue** [comment]
I thought I saw this at some point as well when using redux-persist, but didn't get it to happen again when going back to repro. Does anyone have a full example to repro the issue? The original message points to a non existing version of react-redux-firebase, so kinda confused.

Going to close for now, but down to reopen if it can be reproduced.
