### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by GuyWithCookies** [prescottprue/react-redux-firebase#583]
This bug elaborates on the discussion in Issue #578.

**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When upgrading `react-firestore` from version `0.5.8` to `0.6.0` the Error: 

`TypeError: Cannot assign to read only property '0' of object '[object Array]'`

is thrown when using the below code.

**What is the expected behavior?**
The component should properly connect to the firestore and not throw the above error.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

`react-firestore: 0.6.0` (worked in `0.5.8`)

**Already tried**
As suggested in the Issue #578 I removed `PersistGate` (`redux-persist` in general) from my stack but this does not resolve the issue. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

```
import React from 'react';
import { Container, View } from 'native-base';
import PropTypes from 'prop-types';
import { GiftedChat } from 'react-native-gifted-chat';
import { compose } from 'redux';
import connect from 'react-redux/es/connect/connect';
import { CONVERSATION_COLLECTION } from 'shared-modules/config';
import { withFirestore } from 'react-redux-firebase';
import NavigationHeader from '../../components/NavigationHeader';
import { convertFirebaseUserToGiftedChat } from '../../../libs/utils';

/**
 * Chat Screen
 */
class Chat extends React.Component {
    static propTypes = {
        conversation: PropTypes.object.isRequired,
        firestore: PropTypes.object.isRequired,
        auth: PropTypes.object.isRequired
    };

    onSend(messages = []) {
        const { firestore, conversation } = this.props;

        firestore
            .update(
                { collection: CONVERSATION_COLLECTION, doc: conversation.id },
                {
                    messages: [
                        ...(conversation.messages || []),
                        ...messages
                    ]
                },
            )
            .then(
                () => {
                    // FIXME: Seems like a bug in redux-firestore
                    firestore.get(CONVERSATION_COLLECTION + '/' + conversation.id);
                },
                (err) => {
                    console.log(err);
                },
            );
    }

    render() {
        const { conversation, auth } = this.props;

        return (
            <Container
                testID="Screen:Chat"
                style={{flex: 1}}
            >
                <NavigationHeader
                    headerText="Chat"
                />
                <View
                    style={{flex: 1}}
                >
                    <GiftedChat
                        messages={conversation.messages.sort((a,b) => {
                            return -(a.createdAt - b.createdAt);
                        })}
                        alwaysShowSend
                        isAnimated
                        onSend={(messages) => this.onSend(messages)}
                        user={convertFirebaseUserToGiftedChat(auth)}
                    />
                </View>
            </Container>
        );
    }
}


export default compose(
    withFirestore,
    connect((state, ownProps) => {
            const conversationID = ownProps.navigation.getParam('conversationID', undefined);

            return {
                loading: state.firestore.status.requesting[CONVERSATION_COLLECTION] || false,
                conversation: {
                    id: conversationID,
                    ...state.firestore.data[CONVERSATION_COLLECTION][conversationID]
                },
                auth: state.firebase.auth
            };
        }
    )
)(Chat);

**Comment by JCBsystem** [comment]
same for me 0.6 broke my code 
going back to 0.5.8 its all good again

**Comment by prescottprue** [comment]
@JCBsystem Great to know, thanks for reaching out.

**Comment by JCBsystem** [comment]
@prescottprue 
for me the errors is when 
i try to add data straight to the object (coming from the firestore)
for example 
in one place instead of updating the object true redux i just set a flag on the object 
obj.removed = true 
that throwes errors in 0.6
not in 0.5.8
so maybe its not a bug :) 
maybe it suppose to be like that

**Comment by GuyWithCookies** [comment]
@JCBsystem Thanks for pointing it out!
Indeed for me was the same problem.
I mutated the `conversations` object with the sorting function in the GiftedChat Component.

Removing this (actually just clone the array and sorting this instead) solved the issue.

@prescottprue I assume this is intended behavior but maybe a slightly clearer ErrorMessage could help next users to prevent this? 

Thanks - and keep up the great work! I close this issue.
