### ISSUE TITLE
bug(helpers): isLoaded incorrectly returns false on non-existing data that is loaded using storeAs

### ISSUE THREAD

**Issue by optimistiks** [prescottprue/react-redux-firebase#585]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

If you use `storeAs`, `isLoaded` will return false on the related data item, if that item does not exist in the actual database.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Example:

`firestoreConnect([{ collection: "items", doc: "myItem", storeAs: "myItem" }])`

Before loading, `firestore.data` looks like this - `{}` (empty object). `firestore.data.myItem` is undefined, `isLoaded(firestore.data.myItem)` is `false`, which is correct.

After loading, `firestore.data` looks like this - `{ myItem: undefined }`, `isLoaded(firestore.data.myItem)` is `false`, which is incorrect.

**What is the expected behavior?**

`isLoaded` should be `true` after loading.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

`"react-redux-firebase": "^2.2.2"`

**Comment by prescottprue** [comment]
`undefined` usually means that the value is not loaded yet for Real Time Database, since the value is `null` if it is loaded and does not exist. Are you sure you aren't getting query errors of some sort? Maybe related to rules?

Other than that, wondering which version of redux-firestore you are running.

**Comment by prescottprue** [comment]
Interesting, thanks for the input from your debugging. Always open to a suggested code change if you get the time, otherwise I will try to look into it soon.

**Comment by optimistiks** [comment]
Sorry, I don't have time to make a PR, but here is another example of the bug, but now I'm not even using "storeAs". Trying to load non-existing data, `/books/123`. In redux, `store.firestore.data.books.123` should become `null` after loading, but it is `undefined`, and `isLoaded(state.firestore.data.books.123)` is always `false. Hopefully it will help to catch that bug. 

![selection_062](https://user-images.githubusercontent.com/2562823/50091730-318ad500-021d-11e9-8afd-66e2bf99c59a.png)

**Comment by prescottprue** [comment]
I believe that if you also check for the list before hand (i.e. `isLoaded(state.firestore.data.books) && isLoaded(state.firestore.data.books.123)` ) things should work as expected if not, lets open an issue on the redux-firestore repo. Thanks for reporting!
