### ISSUE TITLE
bug(actions): pushWithMeta and updateWithMeta not working with react-native-firebase

### ISSUE THREAD

**Issue by qalqi** [prescottprue/react-redux-firebase#587]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behaviour?**
Current Behaviour is we get an error 'Cannot read property 'TIMESTAMP' of undefined on using pushWIthMeta or updateWithMeta in react-native with properly configured react-native-firebase along with react-redux-firebase. 

The fix is when using react-native-firebase we have to use  
const serverTime = firebase.database().getServerTime() instead of firebase.database.ServerValue.TIMESTAMP

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

react-native, Android and iOS

**Comment by prescottprue** [comment]
@qalqi Thanks for reporting. Open to a PR if you get the time. Otherwise I will try to get to it when I have a chance.

**Comment by qalqi** [comment]
I can do PR.. suggest me how should I go about detecting the react-native-firebase integration ?

**Comment by qalqi** [comment]
Also, noticed push() and update() are not thenable and doesn’t return promise. Instead they return a Reference Object

**Comment by prescottprue** [comment]
We could just do it by detecting if `database.ServerValue` is defined for this case (just handling the error you reported initially by falling back to your suggestion).

Do you mean `push` and `update from react-native-firebase are not thenable? The ones from react-redux-firebase and the firebase js sdk should both be thenable, so not sure why they wouldn't be. Do you have an example or want to open another issue for that?

**Comment by qalqi** [comment]
Here is the reference to database API https://rnfirebase.io/docs/v5.x.x/database/reference/Reference

As per them 
The web SDK includes a Reference & ThenableReference interface. In RNFirebase, Reference combines these into one.

Now, that react-native-firebase push is not thenable, I have noticed react-redux-firebase push also is not thenable and not returning promise instead return reference object.

**Comment by prescottprue** [comment]
Not sure I understand the issue here. react-redux-firebase is returning the result of calling push on a ref to keep consistent with the Firebase JS SDK. Are you saying the issue is that you are not able to call `.then`?

**Comment by qalqi** [comment]
As on `^2.1.8`.  `pushWIthMeta` or `updateWithMeta` is not working with react-native-firebase

**Comment by prescottprue** [comment]
Going to close since I believe react-native-firebase updated to include both of these and things should be working as expected. If not, please feel free to open a new issue with a description and repro steps
