### ISSUE TITLE
withFirebase.render - TypeError: Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by weslenng** [prescottprue/react-redux-firebase#591]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

Current Behaviour is we get an error "Cannot read property 'dispatch' of undefined" on using withFirebase in React Component.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

I just followed the "read me" from web-site adapting it to my boilerplate.
Clone [here](https://github.com/weslenng/issue).

**Comment by prescottprue** [comment]
@weslenng Did you include the `ReactReduxFirebaseProvider`?

**Comment by prescottprue** [comment]
@weslenng What version are you using of react-redux and react-redux-firebase? If you are using a `2.*.*` version of react-redux-firebase you need to also make sure to include the `reactReduxFirebase` store enhancer.

If you are using a `v6.*.*` version of react-redux, you will need to use a `v3.*.*` version of `react-redux-firebase` from the `next` tag/branch (as mentioned [in the installation section of the main README](https://github.com/prescottprue/react-redux-firebase#installation)). There [is a different setup for the new version which includes a provider from react-redux-firebase](https://github.com/prescottprue/react-redux-firebase/tree/next#use).

**Comment by weslenng** [comment]
I lost that detail, sorry.
Thank you for your help!

**Comment by prescottprue** [comment]
@weslenng All good! Actually glad to know it happened to another person. I am going to look into adding a warning in the current version since you are not the first to have this happen.
