### ISSUE TITLE
React read from firebase, error

### ISSUE THREAD

**Issue by shafaqat309** [prescottprue/react-redux-firebase#596]
I am trying to get data from firebase collection but getting this error, can anybody help?
I am getting this error

> Error: Context from react-redux not found. If you are using react-redux v6 a v3.*.* version of react-redux-firebase is required. Please checkout the v3 migration guide: http://bit.ly/2SRNdiO

import React, { Component } from 'react'
import Notifications from './Notifications';
import ProjectList from '../projects/ProjectList';
import {connect} from 'react-redux';
import {firestoreConnect} from 'react-redux-firebase';
import {compose} from 'redux';
import { firebaseConnect, isLoaded, isEmpty } from 'react-redux-firebase'

class Dashboard extends Component {
  render() {
    
    return (
      <div className="dashboard container">
        <div className="row">
            <div className="col s12 m6"><ProjectList projects={this.props.projects}></ProjectList></div>
            <div className="col s12 m5 offset-m1"><Notifications></Notifications></div>
        </div>
      </div>
    )
  }
}
const mapStateToProps = (state) =>
{
  console.log(state);
  return ({projects:state.projectReducer.projects})
}
export default compose(firebaseConnect([
  'projects'
]), connect(mapStateToProps)) (Dashboard)

here is my package.json

`{
  "name": "myproject",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "firebase": "^5.7.0",
    "firedux": "^1.1.0",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-redux": "^6.0.0",
    "react-redux-firebase": "^2.2.5",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1",
    "redux": "^4.0.1",
    "redux-firestore": "^0.6.0",
    "redux-thunk": "^2.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
`

**Comment by prescottprue** [comment]
As noted in the error you need to be using `react-redux-firebase` version 3, and it appears you have v2.2.5 installed. Try installing from the next tag: `react-redux-firebase@next`.
