### ISSUE TITLE
version: v3.0.0-alpha.3 Object(...) is not a function 

### ISSUE THREAD

**Issue by Louis-Chen** [prescottprue/react-redux-firebase#598]
this is my configureStore.js
https://gist.github.com/Louis-Chen/b62ca309f263b6e3a73896dbac089354

and throw error

![https://i.imgur.com/PKmsDEW.png](https://i.imgur.com/PKmsDEW.png)

**Comment by Max-Zviagintsev** [comment]
Having the same issue

**Comment by Louis-Chen** [comment]
thanks i fixed it
