### ISSUE TITLE
feat(auth): role(admin, user) is overwritten whenever signed-in with google

### ISSUE THREAD

**Issue by sungmin-kim-0129** [prescottprue/react-redux-firebase#599]
**What is the current behavior?**
I tried to sign in with Google and set the role as admin with `profileFactory` but the role is changed to user when I change `role: "admin"` to `role: "user"` in profileFactory 

- the head in index.js
**index.js**
![image](https://user-images.githubusercontent.com/37981164/50513707-79a0c780-0a67-11e9-97d8-2bbb8e23e6b8.png)

1. set up the role as an admin 
**index.js**
![code_admin](https://user-images.githubusercontent.com/37981164/50513462-f8950080-0a65-11e9-96dc-2df4ecf33cfe.PNG)
2. the result as the admin in role
![image](https://user-images.githubusercontent.com/37981164/50513522-4b6eb800-0a66-11e9-9f7f-8629dca95dd8.png)

**After changing the admin to user in the role**

3. set up the role as an user
**index.js**
![image](https://user-images.githubusercontent.com/37981164/50513630-e10a4780-0a66-11e9-989a-bb9b43275432.png)

4. the result as the user in role
![image](https://user-images.githubusercontent.com/37981164/50513645-0ac36e80-0a67-11e9-979e-9578498ea2ae.png)

Is there any way to prevent the role from being overridden?

**Comment by prescottprue** [comment]
1. Setting `updateProfileOnLogin` to `false` should prevent the profile from being overwritten
1. You may not want to be writing role from your client, but instead from a cloud function. This way your rules can prevent that node from being written by clients (good move to prevent a client from changing their own role in attempt to become an admin).
1. Unrelated, but you shouldn't need `attachAuthIsReady` unless you are doing SSR

**Comment by sungmin-kim-0129** [comment]
**Gosh!** Thanks, Scott!  The role is no longer overwritten(not overridden:) ). I really appreciate it!
And Thank you for the additional information about `attachAuthIsReady`! Happy New Year

**Comment by prescottprue** [comment]
@sungmin-kim-0129 Glad to hear!
