### ISSUE TITLE
bug(HOCs): withFirestore doesn't provide firebase anymore

### ISSUE THREAD

**Issue by cgestes** [prescottprue/react-redux-firebase#606]
**Do you want to request a *feature* or report a *bug*?**  
not sure if this is a feature or a request!

withFirestore only set firestore on branch 'next'. It used to set dispatch and firebase also.

The obvious fix is to use withFirebase to get firebase.

I guess, we could either document it in the migration guide or fix it :)

**Comment by prescottprue** [comment]
@cgestes Great to know - I'll look into the fix
