### ISSUE TITLE
feat(typings): general upgrade of typescript definitions/typings

### ISSUE THREAD

**Issue by rscotten** [prescottprue/react-redux-firebase#610]
Hello,

Big fan of this library so far.  Great job!

As a Typescript user, I'd like to help out on the Typescript definition file.  I've forked the repo and have been upgrading the types on the 3.0.0-alpha.5 branch.  I'll make a pull request when ready.

Just to make sure I'm not duplicating anyone's work, 

is anybody else was working on this?

**Comment by prescottprue** [comment]
Reach out with any updates (even small ones). We can get changes out to the `next` tag/branch pretty quickly, and I am sure that there are others using typescript that would enjoy the changes.

**Comment by sambokai** [comment]
Commenting to voice my support for this move.

@rscotten Are you currently working on it?

**Comment by rscotten** [comment]
@sambokai yes, I have updated some types for the functions I'm using, but it's by no means complete.  

You can see my current draft here: https://github.com/rscotten/react-redux-firebase/blob/v3.0.0-alpha.6-upgrade-ts-definitions/index.d.ts

**Comment by rscotten** [comment]
Just got motivated to work on this right now.

@prescottprue Any reason why this package has a package.json devDependency of `"firebase": "4.12.0",` instead of `5.8.1`?

**Comment by rscotten** [comment]
@sambokai made some more progress on this.  It's still not complete, but if you're in a pinch, you can replace your `index.d.ts` file with mine and it might help out some.

**Comment by sambokai** [comment]
Will try it and report back if i notice anything

**Comment by prescottprue** [comment]
@rscotten The old dev dependency is just from how long ago I set it, I'm sure it won't break anything.

Even if it isn't finished I am open to trying out some of the changes because I agree with @sambokai that the typings for `firebaseConnect` would be super useful

**Comment by idanlo** [comment]
@prescottprue  I'm working on some types, will open a PR to the `next` branch soon.

**Comment by rscotten** [comment]
@prescottprue @idanlo I submitted my PR: https://github.com/prescottprue/react-redux-firebase/pull/627

**Comment by prescottprue** [comment]
Just did a pretty big upgrade to the types as part of the [v3.0.0-alpha.13 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.0.0-alpha.13) and am planning to continue updates to them regularly. Going to close this issue for now, but please feel free to open new issues/PRs with your input. Thank you everyone for all for your contributions!
