### ISSUE TITLE
Does where respect the array_contains inside firebaseConnect?

### ISSUE THREAD

**Issue by Manouli** [prescottprue/react-redux-firebase#616]
Hello please accept my apologies for posting here. I tried the chat first but nobody came back to me. 

I am trying to get a field inside firestore which is an array of numbers. [1, 2, 3]. 

When I do the following the data that are being returned are all the data and not the data containing only the number passed as the 3rd argument. 

When I do a traditional onSnapshot I am getting the desired data which indicates that array_contains works fine. 

So my question here and maybe my bug report is if the below code is supported `array_contains`

```
firestoreConnect(props => [
    {
      collection: 'channels',
      where: ['users', 'array_contains', props.user],
    },
  ]),
```

**Comment by Manouli** [comment]
I will close this issue as I am being dumb! its `array-contains` and not `array_contains`

**Comment by smakosh** [comment]
Hey @Manouli  Please open this again as I'm having issues with `array-contains` as it returns `null` all the time

**Comment by prescottprue** [comment]
@smakosh Please open a new issue with the versions that you are using and repro steps (preferably with a codesandbox or similar where the issue can be replicated).

**Comment by smakosh** [comment]
I managed to solve it! never mind 😆
