### ISSUE TITLE
question(integrations): support for redux-observable in v.3?

### ISSUE THREAD

**Issue by Louis-Chen** [prescottprue/react-redux-firebase#617]
i found in ver.3 

`getFirebase` is deprecated

i want to ask how the way to use firebase in redux-obserable?

**Comment by prescottprue** [comment]
Haven't looked a best approach for this yet specifically, but it seems like `createFirebaseInstance` should be exposed so that a singleton could be made then passed around.

Open to ideas if anyone wants to give an example a go. Going to add this to `v3.0.0` todo, thanks for reaching out.

**Comment by prescottprue** [comment]
Closing since I believe it is a similar question to #607
