### ISSUE TITLE
bug(query): SET event fired after UNSET_LISTENER

### ISSUE THREAD

**Issue by nahuelhds** [prescottprue/react-redux-firebase#618]
**Do you want to request a *feature* or report a *bug*?**  

This is a bug.

**What is the current behavior?**

I have a component that uses `firebaseConnect` and does the following:

```
class TripViewContainer extends React.Component {
    // .. component definition
}

const mapStateToProps = ({ firebase, auth, currentTrip }) => {
  // Some other actions
  const { tripData, driverPosition } = firebase.data;
  return {
    tripData,
    driverPosition
  };
};

const mapFirebaseListeners = props => [
  {
    // Trip data listener
    path: props.currentTrip.tripRefPath,
    storeAs: `tripData`
  },
  {
    // Driver movement
    path: `remis_location/${props.driver.id}`,
    storeAs: `driverPosition`
  }
];

export default compose(
  connect(mapStateToProps),
  firebaseConnect(mapFirebaseListeners)
)(TripViewContainer);
```

Basically, `TripViewContainer` is mounted every time I have a new trip accepted by a driver. When that happens I receive the trip firebase ref in `props.currentTrip.tripRefPath` which is something like "new_trip/4/430/-LWm7TjvAqzEW1JJSHu7" and the driverPosition is something like "remis_location/430". Notice here that "430" is my driver ID.

While the trip is ongoing, the `@@reactReduxFirebase/SET` events are called normally and as expected.

When the trip finishes, the component is unmounted and doing so, the events `@@reactReduxFirebase/UNSET_LISTENER` are also called as expected.

The unexpected thing is that `@@reactReduxFirebase/SET` events from those unseted listeners are still being executed.

For worse, when I do a new trip with another driver, both listeners report all the time to the same `storeAs` param, which of course makes the UI handling impossible.

**What is the expected behavior?**

No more `@@reactReduxFirebase/SET` after `@@reactReduxFirebase/UNSET_LISTENER` is called.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

```
    "expo": "^30.0.1",
    "firebase": "^5.5.4",
    "react": "16.3.1",
    "react-redux": "^5.0.7",
    "react-redux-firebase": "^2.1.9",
    "redux": "^4.0.0",
```

Thanks in advance

**Comment by nahuelhds** [comment]
Temporarilly, I'm manually executing the `off` native method like so:

```


  componentWillUnmount() {
    const { firebase } = this.props;

    firebase
      .database()
      .ref()
      .child(this.props.currentTrip.tripRefPath)
      .off("value");
    firebase
      .database()
      .ref()
      .child(`remis_location/${this.props.driver.id}`)
      .off("value");
  }
```

**Comment by prescottprue** [comment]
@nahuelhds Wondering if the fact that the `connect` is before the Firebase connect is impacting it since props are used in the query? Either way, I will try to repro, thanks for reporting.

**Comment by nahuelhds** [comment]
I didn't figure out how to get the props from my other stores if I set `firebaseConnect` **before** `connect`.

Having `connect` first, let me access to the props retrieved from the other stores.

Maybe that can be done in other way I really don't know. If you could guide, that'd be nice.

Thanks in advance!

**Comment by prescottprue** [comment]
@nahuelhds You can use `connect` before `firebaseConnect` to get props to be used in a query. It is just usually suggested to use `connect` later down in the component try to actually get the Firebase data out of state. This is common because listeners are often attached a higher level (usually at the page/route level) since they are attached/detached on mount/unmount and `connect` is used at the lowest level possible before each component (that is also the main the upside! The state is easily shared across components with a single listener!)

Since what you are describing is so common though (i.e. listener attaching and props connecting in one HOC), I have been thinking about having a build in tool just for that, but haven't finalized anything yet. Mostly since it is usually much more performant to attach to state as low as possible, especially with use of state selectors.

**Comment by nahuelhds** [comment]
So I've been fooled by my own thinking.

For being able to access props in my state I needed, I thought that I needed to fill the props before trying to access them in the firebaseConnect.

Such a lineal thinking from me haha.

I'll give it a try by writing `firebaseConnect` **after** and see how it works.

Thanks for you feedback.

No need to say that this project rocks, but I'll say it anyway xD
