### ISSUE TITLE
Facebook login removing email field from Firebase

### ISSUE THREAD

**Issue by lucasharada** [prescottprue/react-redux-firebase#623]
**Do you want to request a *feature* or report a *bug*?**  

Bug.

**What is the current behavior?**

I have a use case where I request a valid email if the user doesn't allow my application to get it from Facebook during Facebook login. After that, I'm getting the user email and updating the user profile on Firebase. If the user do logout and login with Facebook again, the email field is nullified.

1. Login with Facebook
2. Deny email permission when asked during the Login
3. You can go to Firebase console and add `email` field with any value to your profile
4. Logout and Login with Facebook again
5. Your profile should have no email value in Firebase

**What is the expected behavior?**

After signing in again with Facebook, if the email returned from Facebook is `null`, just ignore instead of removing any value from Firebase.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
macOS Mojave 10.14.2
```
"firebase": "^5.5.6",
"react": "16.6.0",
"react-dom": "16.6.0",
"react-redux-firebase": "^2.1.8",
"redux": "4.0.1",
```

**Comment by prescottprue** [comment]
If you provide `updateProfileOnLogin: false` then the user's profile will not be updated when logging in if it already exists. That said, update should not be removing anything, so I would be interested to try to replicate to see if an invalid value is passed for email or something.

**Comment by lucasharada** [comment]
Thanks, @prescottprue! This will solve my problem for now. I can't provide a way to replicate the exact behaviour I described in my app, but I mapped the issue to be exactly what I mentioned: when logging in with Facebook and access to email is not provided, the user profile will be updated to set email to null on every sign in.
