### ISSUE TITLE
bug(docs) Missing profileFactory from defaultConfig in constants page

### ISSUE THREAD

**Issue by mate-h** [prescottprue/react-redux-firebase#636]
Just though I would let you know that despite providing `profileFactory` in [Change how profiles are stored](http://react-redux-firebase.com/docs/recipes/profile.html#change-how-profiles-are-stored) it's not included in the `defaultConfig` object in the constants page of the docs.

**Comment by prescottprue** [comment]
Fixed, thanks for reporting!
