### ISSUE TITLE
Error : Firebase database is required to create watchers

### ISSUE THREAD

**Issue by Louis-Chen** [prescottprue/react-redux-firebase#638]
react-redux-firebase version: v3

I create react app by next.js

when i connect firebase data i will get this error throw

my connection firebase code
```
export default compose(
   firebaseConnect('products'),
   connect(mapStateToProps)
)(Page)

```
maybe this problem from nextjs ssr?

**Comment by prescottprue** [comment]
@Louis-Chen Are you sure you imported database? Like so:

```js
import firebase from 'firebase/app'
import  'firebase/database'
// import 'firebase/firestore'
```

**Comment by prescottprue** [comment]
@Louis-Chen Going to close assuming that things were not correctly imported. Feel free to reach out if you are still experiencing the issue.

**Comment by khmaies5** [comment]
i imported database like what you said but i still have the same Error

**Comment by prescottprue** [comment]
@khmaies5 How is your store setup? Are you passing any config into the react-redux-firebase enhancer?

**Comment by khmaies5** [comment]
@prescottprue i was importing react-redux-firebase/lib and that what caused the error.
now i have other error :
Uncaught Error: Supplied prop/s "firebase", "dispatch" are reserved for internal firebaseConnect() usage.

this happens when i use react-redux-firebase inside a component and then call that component inside other component where i also use react-redux-firebase

**Comment by prescottprue** [comment]
Looks like you are using the new version (from next) with the syntax from the old version (uses the `reactReduxFirebase` store enhancer) - this is detailed in [the v3 migration part of the docs](http://docs.react-redux-firebase.com/history/v3.0.0/docs/v3-migration-guide.html).

**Comment by khmaies5** [comment]
@prescottprue ithe only difference from v3 migration was that i am importing firebaseStateReducer not firebaseReducer i changed that to the correct one but i still get: Uncaught Error: Supplied prop/s "firebase", "dispatch" are reserved for internal firebaseConnect() usage.

even after i tried [this ](https://github.com/prescottprue/react-redux-firebase/issues/675#issuecomment-487438179)

**Comment by olefritsch** [comment]
I'm getting this error as well, auth works as expected but when trying to access a subcollection for a given user's document, (or any other path) using `useFirebaseConnect` I get the error: "Firebase database is required to create watchers". 

**Provider:**
```js
import 'firebase/auth'
import 'firebase/firestore'
import firebase from 'firebase/app'
import React from 'react'
import PropTypes from 'prop-types'
import { createFirestoreInstance } from 'redux-firestore'
import { ReactReduxFirebaseProvider } from 'react-redux-firebase'
import { firebaseConfig } from 'config'
import store from 'redux/store'

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig)
  firebase.firestore()
}

const rrfProps = {
  firebase,
  config: {
    userProfile: 'users',
    useFirestoreForProfile: true,
  },
  dispatch: store.dispatch,
  createFirestoreInstance,
}

function FirebaseProvider({ children }) {
  return <ReactReduxFirebaseProvider {...rrfProps}>{children}</ReactReduxFirebaseProvider>
}

FirebaseProvider.propTypes = {
  children: PropTypes.node.isRequired,
}

export default FirebaseProvider
```

**Store:**
```js
import { configureStore, getDefaultMiddleware } from '@reduxjs/toolkit'
import rootReducer from './rootReducer'

const store = configureStore({
  reducer: rootReducer,
  middleware: getDefaultMiddleware({
    serializableCheck: false,
    immutableCheck: false,
  }),
})

export default store
```

**Comment by bt1** [comment]
@olefritsch you need to use compat version of the libraries
```
import firebase from "firebase/compat/app";
import 'firebase/compat/database';
```
