### ISSUE TITLE
How do you create a new user

### ISSUE THREAD

**Issue by tevanovich** [prescottprue/react-redux-firebase#639]
I think is a stupid question but, I tried to register a new user and save it to the Database. 

I'm getting two errors and I don't know how to fix them, I've read the docs and still have no clue. 

Error: Real-Time Database or Firestore must be included to enable user profile
Uncaught TypeError: firebase.database is not a function

Any help would be great, thanks for this awesome project.

**Comment by prescottprue** [comment]
Did you make sure to import database when importing Firebase? Like so:

```js
import firebase from 'firebase/app'
import  'firebase/database'
// import 'firebase/firestore'
```

Just noticing that the Use section of the README still uses the old import method that Firebase no longer suggests, though both should work.

**Comment by tevanovich** [comment]
Thanks that resolved my issue. I feel so silly by overlooking this. If I want to save it to the firestore and not the realtime DB, how is it

**Comment by prescottprue** [comment]
@tevanovich Details on how query Firestore [are covered in the Firestore section of the docs](http://react-redux-firebase.com/docs/firestore.html)
