### ISSUE TITLE
May need appropriate loader

### ISSUE THREAD

**Issue by wolfadex** [prescottprue/react-redux-firebase#64]
```
ERROR in ./~/react-redux-firebase/src/connect.js
Module parse failed: <project-directory>\node_modules\react-redux-firebase\src\connect.js Unexpected token (43:24)
You may need an appropriate loader to handle this file type.
|     }
|
|     static contextTypes = {
|       store: PropTypes.object.isRequired
|     };
 @ ./~/react-redux-firebase/src/index.js 1:0-31
 @ ./ui/src/index.js

ERROR in ./~/react-redux-firebase/src/helpers.js
Module parse failed: <project-directory>\node_modules\react-redux-firebase\src\helpers.js Unexpected token (252:14)
You may need an appropriate loader to handle this file type.
|           if (dataToJS(data, pathString)) {
|             return {
|               ...dataToJS(data, path),
|               [p.child]: dataToJS(data, pathString)
|             }
 @ ./~/react-redux-firebase/src/index.js 5:0-36
 @ ./ui/src/index.js

ERROR in ./~/react-redux-firebase/src/actions/auth.js
Module parse failed: <project-directory>\node_modules\react-redux-firebase\src\actions\auth.js Unexpected token (283:12)
You may need an appropriate loader to handle this file type.
|           firebase,
|           { uid },
|           { ...extraJWTData, uid }
|         )
|       }
 @ ./~/react-redux-firebase/src/actions/index.js 1:0-37
 @ ./~/react-redux-firebase/src/compose.js
 @ ./~/react-redux-firebase/src/index.js
 @ ./ui/src/index.js`
```

I got this error after adding react-redux-router to my project.

webpack: v2.2.1
webpack.config.js
```
module.exports = {
	entry: './ui/src/index.js',
	output: {
		path: path.resolve(__dirname, 'ui/dist'),
		filename: 'bundle.js',
	},
	resolve: {
		alias: {
			actions: path.resolve(__dirname, 'ui/src/actions'),
			App: path.resolve(__dirname, 'ui/src/App'),
			assets: path.resolve(__dirname, 'ui/src/assets'),
			components: path.resolve(__dirname, 'ui/src/components'),
			reducers: path.resolve(__dirname, 'ui/src/reducers'),
			root: path.resolve(__dirname, 'ui/src'),
			utils: path.resolve(__dirname, 'ui/src/utils'),
		},
	},
	target: 'electron',
	devtool: 'eval-source-map',
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: 'babel-loader',
			},
			{
				test: /\.css$/,
				use: ExtractTextPlugin.extract({
					fallback: 'style-loader',
					use: 'css-loader'
				})
			},
			{
				test: /\.less$/,
				use: ExtractTextPlugin.extract({
					fallback: 'style-loader',
					use: 'css-loader!less-loader'
				})
			},
			{
				test: /\.(jpg|png|svg)$/,
				use: 'url-loader',
			},
		],
	},
	plugins: [
		new ExtractTextPlugin('styles.css'),
	],
};
```

.babelrc
```
{
  "presets": [
    "stage-0",
    "node5",
    "react"
  ],
  "plugins": [
    "transform-react-display-name",
    "transform-decorators",
    "transform-class-properties",
    "transform-es2015-classes"
  ]
}

```

**Comment by prescottprue** [comment]
Webpack 2 points to `module` parameter of package file, which points to the unbuilt source of the library.

That means that you will need to include all relevant loaders to build `react-redux-firebase`.

Try installing `es2015` and `stage-1` and including them in your config.

Note: You might also be able to use the `modules: false` for babel to keep TreeShaking from happening on modules like so:

```js
options: { presets: [ [ 'es2015', { modules: false } ] ] }
```

**Comment by wolfadex** [comment]
I've updated my .babelrc to
```
{
  "presets": [
    "stage-0",
    "stage-1",
    [
      "es2015",
        {
          "modules": false
        }
    ],
    "react"
  ],
  "plugins": [
    "transform-decorators-legacy"
  ]
}

```
Without `options: { presets: [ [ 'es2015', { modules: false } ] ] }` I get the same errors, with I get the same errors plus
```
WARNING in ./ui/src/index.js
11:38-56 "export 'reactReduxFirebase' was not found in 'react-redux-firebase'

WARNING in ./ui/src/reducers/index.js
7:11-31 "export 'firebaseStateReducer' was not found in 'react-redux-firebase'
```

However if I change my imports from
`import { reactReduxFirebase, firebaseStateReducer } from 'react-redux-firebase';`
to
`import { reactReduxFirebase, firebaseStateReducer } from 'react-redux-firebase/dist';`
then all of my errors go away.

**Comment by prescottprue** [comment]
@wolfadex Just now getting to try out Webpack 2, but I believe it is due not correctly setting up for the new [Tree Shaking](https://moduscreate.com/webpack-2-tree-shaking-configuration/). Hopefully it will be a simple change, but I will update you after more investigation.

### For Now
Point to the dist version like you did with `from 'react-redux-firebase/dist';` (perferred in my mind)

**or**

Use Webpack `^1.*.*` (`^2` should be supported very soon, so switching back may be overkill)

**Comment by prescottprue** [comment]
@wolfadex 
Was able to get it working by building multiple versions with Webpack and including transforms (see the [`v1.3.0-alpha` branch](https://github.com/prescottprue/react-redux-firebase/tree/v1.3.0-alpha). The plan is to release the change within the next few days as part of [`v1.3.0-alpha`](http://react-redux-firebase.com/docs/roadmap.html#v130-alpha).

[The roadmap](http://react-redux-firebase.com/docs/roadmap.html#v130-alpha) has been updated to show that info.

**Comment by prescottprue** [comment]
The [`v1.3.0-alpha` release](https://github.com/prescottprue/react-redux-firebase/releases/edit/v1.3.0-alpha) includes the start of this functionality.

Let me know if you get a chance to give it a try.

**Comment by wolfadex** [comment]
Just tried v1.3.0-beta and as far as I can tell it's working. My `.babelrc` doesn't include `modules: false` and my imports are from `'react-redux-firebase'`. Thank you!
