### ISSUE TITLE
Usage Question: How to add custom fields for userProfile?

### ISSUE THREAD

**Issue by mungees** [prescottprue/react-redux-firebase#645]
I'm using userProfile to store data associated with a user.

In addition, to add a custom properties(such as role, active in my case), I'm using 'profileFactory'.

For example, 

```
...
userProfile: 'users',
profileFactory: (userData, profileData) => {
    return {
        ...profileData,
        active: false,
        role: 'user'
    }
}
```

However, it seems like when user logs in, the user object always updated to the original data(active becomes false and role becomes 'user').

I don't want this behaviour every time when user logs in. The user object should be remained as it is. 

Is this wrong way to achieve this goal?

**Comment by prescottprue** [comment]
There is a the config option named `updateProfileOnLogin` (described [in the `constants` section of the docs](http://react-redux-firebase.com/docs/api/constants.html#defaultconfig))  which is set to `true` by default to handle cases of when the user's auth data changes in relation to their profile. If you set that to `false` you should see the behavior you are expected.

Feel free to reach back out if that isn't the case and we can reopen.
