### ISSUE TITLE
Uncaught TypeError: getFirebase is not a function

### ISSUE THREAD

**Issue by wesleyamaro** [prescottprue/react-redux-firebase#650]
Hey Guys, 

I am having a problem when using `getFirebase` with `redux-thunk`. I was reading and trying to figure out that problem through the [documentation](http://docs.react-redux-firebase.com/history/v3.0.0/) but I couldn't solve it.

I don't know what I am doing wrong :/

**Packages version:**
`redux: 6.0.0`
`react-redux-firebase: 3.0.0-alpha.10`
`redux-thunk: 2.3.0` 
`redux-firestore: 0.7.1`

_Note: At the version 2, it was working very well._

**Error:**
<img width="524" alt="Screen Shot 2019-03-09 at 21 41 28" src="https://user-images.githubusercontent.com/3964422/54079965-8be38100-42b4-11e9-83cf-804e136af0b8.png">

**firebaseConfig
<img width="448" alt="Screen Shot 2019-03-09 at 23 03 09" src="https://user-images.githubusercontent.com/3964422/54080518-9e16ec80-42bf-11e9-9cac-3a68a7d0ad7d.png">

**This is my `index.js`**
<img width="636" alt="Screen Shot 2019-03-09 at 21 40 27" src="https://user-images.githubusercontent.com/3964422/54079975-b03f5d80-42b4-11e9-8675-b820c89c077d.png">

**`action.js`**
<img width="529" alt="Screen Shot 2019-03-09 at 21 40 56" src="https://user-images.githubusercontent.com/3964422/54079980-bfbea680-42b4-11e9-85d7-4c628e1daa70.png">

Note: I have seen that we do not have the method `reactReduxFirebase` and `getFirebase` from the version `react-redux-firebase: 3.0.0-alpha.10`. How can we solve that problem?

**Comment by prescottprue** [comment]
@wesleyamaro `getFirebase` is not part of the v3 API. There have been a number of o

**Comment by MasriNaser** [comment]
Hello everyone!
I have the same issue.
<img width="1434" alt="Screen Shot 2019-08-05 at 11 01 54" src="https://user-images.githubusercontent.com/42206435/62452515-9ecd8500-b770-11e9-9a53-2560cf2b01ae.png">

**Comment by prescottprue** [comment]
@MasriNaser It appears you are using a version from `latest` and not from `next`, which has a different setup as noted [in the v3 migration guide](http://docs.react-redux-firebase.com/history/v3.0.0/docs/v3-migration-guide.html)
