### ISSUE TITLE
bug(firestore): No results with firestoreConnect() and orderBy

### ISSUE THREAD

**Issue by francodgstn** [prescottprue/react-redux-firebase#651]
Hi, it looks like that `firestoreConnect` doesn't work properly with `orederBy`. 

I have this simple query that runs fine without orderBy but gives no results if I add the orderBy. Both `firestore.data` and `firestore.ordered` are empty. Please note that the index for that field is already defined in firebase. 

```javascript
firestoreConnect( (props) => [
{
    collection: 'events', 
    where: [
        ['teacher', '==', props.auth.uid],
        ['deleted_at', '==', null]
     ],
     orderBy: ['startDate'],    // No results if I use this
     //orderBy: 'startDate'    // Also this doesn't work
     //orderBy: ['title'],         // No results also with a text field
}
```

  Currently I'm using these versions:
```javascript
"react-redux": "^6.0.0",
"react-redux-firebase": "^3.0.0-alpha.10",
"redux-firestore": "^0.7.0",
```

A similar bug was already fixed in redux-firestore  [orderBy don't return any results](https://github.com/prescottprue/redux-firestore/issues/50).

**Comment by prescottprue** [comment]
@francodgstn You are most likely missing the index for this. Did you check state to see if there are any listener errors?

**Comment by francodgstn** [comment]
Hi, yep I already set an index on Firebase.

When I add the orderBy I see this error in the listner errors.

```javascript
byQuery: {
    events?where=teacher:==:l39De0OTZ5f8FQzVRWKkSYF90Zs2,where=deleted_at:==:
    {
      "code": "failed-precondition",
      "name": "FirebaseError"
    }
}
```

This is the complete action:
```javascript
{
  type: '@@reduxFirestore/LISTENER_ERROR',
  meta: {
    collection: 'events',
    where: [
      [
        'teacher',
        '==',
        'l39De0OTZ5f8FQzVRWKkSYF90Zs2'
      ],
      [
        'deleted_at',
        '==',
        null
      ]
    ],
    orderBy: [
      'start'
    ]
  },
  payload: {
    code: 'failed-precondition',
    name: 'FirebaseError'
  },
  merge: {}
}
```

**Comment by illuminist** [comment]
It has to be a composite index with 3 keys. When an error occurs, take a look in a console, firebase will tell you about the error and will give you a link to create a proper index.

PS. @francodgstn  your second comment has orderBy key different from the first comment: `start` and `startDate`

**Comment by prescottprue** [comment]
Going to close since this is presumed to be an issue with indexes not being set. Feel free to reach out if that is not the case and we can reopen

**Comment by nickwebha** [comment]
I have a very similar issue. I am using TypeScript, if that matters.

```
"react-redux": "4.4.10",
"react-redux-firebase": "2.3.0",
"redux-firestore": "0.8.0",
```

```
{
	collection: "location",
	orderBy: [
		[ "name", "asc" ],
	],
	where: [
		[ "chainId", "==", props.chainId ],
	],
}
```

When I do not use orderBy everything is peachy. When I use orderBy it sometimes pulls the data, it sometimes does not. There is never an error in the React Native Debugger console. When it does work it does not update (reflect changes in Firestore data, deletes of documents, adds of documents, etc). Again with no error.

I am testing every last thing I could thing of and I am pretty sure `firestoreConnect()` is the issue. I am confirmed that the indexes exist (besides, it works some percentage of the time, any way).

**Comment by prescottprue** [comment]
@nickwebha Can you open a new issue with a code base to reproduce the issue as well as your settings for your indexes? Seems like it may be something specific to react-native since I believe the above issue was narrowed down to an issue with indexes.

**Comment by nickwebha** [comment]
> @nickwebha Can you open a new issue with a code base to reproduce the issue as well as your settings for your indexes? Seems like it may be something specific to react-native since I believe the above issue was narrowed down to an issue with indexes.

[https://github.com/prescottprue/react-redux-firebase/issues/729](https://github.com/prescottprue/react-redux-firebase/issues/729)
