### ISSUE TITLE
Getting 'TypeError: firebase.auth not a function'

### ISSUE THREAD

**Issue by wizzywit** [prescottprue/react-redux-firebase#657]
hello i am having a slight issue on my react app concerning ' typeError: firebase.auth not a funtion 

the code below is my index.js
![index](https://user-images.githubusercontent.com/40175713/54865246-eaa00480-4d62-11e9-9927-ac21624106bb.PNG)

below is my fbConfig.js file
![config](https://user-images.githubusercontent.com/40175713/54865256-158a5880-4d63-11e9-88ae-78d0cec72aab.PNG)

also the authAction.js file
![authAction](https://user-images.githubusercontent.com/40175713/54865259-22a74780-4d63-11e9-88d3-32629ae0b4b3.PNG)

So finally this is my Signin.js which contains the higer order component connect to mapDispatchToProps
![signin1](https://user-images.githubusercontent.com/40175713/54865267-3ce12580-4d63-11e9-89ba-bf1a842e5e54.PNG)
![signin2](https://user-images.githubusercontent.com/40175713/54865269-4074ac80-4d63-11e9-9d0a-fcb1e57aaeb5.PNG)

**Comment by wizzywit** [comment]
this is the error message i get
![error](https://user-images.githubusercontent.com/40175713/54865275-58e4c700-4d63-11e9-8e2c-1bc18cbf5ab6.PNG)

**Comment by prescottprue** [comment]
@wizzywit The instance that you are referencing does not contain auth. If you are attempting to use auth and dispatch your own actions, you can just use firebase directly. The instance you are using is comes from react-redux-firebase and has methods on it which already dispatch actions.

**Comment by prescottprue** [comment]
Closing since this appears to be a misunderstanding more than an issue.
