### ISSUE TITLE
User Profile doesn't load correctly even after configuration 

### ISSUE THREAD

**Issue by MufassirShaw** [prescottprue/react-redux-firebase#659]
**Do you want to request a *feature* or report a *bug*?**  

A bug possibly 

**Note: I'm using this package with RNfirebase**

**What is the current behavior?**

The user profile loads correctly on first few builds but then starts to break.

**What is the expected behavior?**
The user profile should load correctly on each build and not only on the first few builds

**Which versions of dependencies, and which browser and OS are affected by this issue?**

    "babel-polyfill": "^6.26.0",
    "libphonenumber-js": "^1.7.11",
    "native-base": "^2.12.1",
    "react": "16.6.3",
    "react-native": "0.58.0-rc.2",
    "react-native-easy-grid": "^0.2.1",
    "react-native-firebase": "^5.2.0",
    "react-native-image-picker": "^0.28.0",
    "react-native-simple-dialogs": "^1.1.0",
    "react-native-splash-screen": "^3.2.0",
    "react-redux": "^6.0.1",
    "react-redux-firebase": "^2.2.6",
    "redux": "^4.0.1",
    "redux-firestore": "^0.7.2",
    "redux-thunk": "^2.3.0"

Here is the my store logic

const reduxFirebaseConfig = {
    enableRedirectHandling: false,
    userProfile: 'Users',
    useFirestoreForProfile: true,
 };

const reactNativeFirebaseConfig = {
    debug: true
};

const fb = RNFirebase.initializeApp(reactNativeFirebaseConfig);

const rootReducer = combineReducers({
    firebase: firebaseReducer,
    firestore: firestoreReducer,
    AuthReducer:AuthReducer
})

export const Store  = createStore(
    rootReducer,
    compose(
        applyMiddleware(thunk.withExtraArgument({getFirebase,getFirestore})),
        reduxFirestore(fb),
        reactReduxFirebase(fb,
            reduxFirebaseConfig
        )

    )    
);

** Did this work in previous versions or setups?**
 I haven't done any updates.

**Comment by prescottprue** [comment]
As stated [in the installation section of the README](https://github.com/prescottprue/react-redux-firebase#installation), if you are looking for support react-redux v6, use the [upcoming version released through the `next`](https://github.com/prescottprue/react-redux-firebase/tree/next) tag. The setup is different for the new version, so make sure [to checkout the new setup instructions](https://github.com/prescottprue/react-redux-firebase/tree/next).

**Comment by MufassirShaw** [comment]
I'm still facing the same issue even though i have migrated to v3. The profile loading is unpredictable, loads correctly but as i refresh a few times it stop loading.  :(

**Comment by prescottprue** [comment]
@MufassirShaw Please provide code that replicates the issue. Not sure where AuthReducer is being pulled from. Also not sure if react-native-firebase is working exactly the same as firebase's sdk would in this situation.

**Comment by MufassirShaw** [comment]
Hi Thank you much for response here is the detail code. And I have noticed that the issue is because firestore doesn't load up. I have access to firebase though.


**App.js**
`import React, { Component } from 'react';
import { Container, Button, Text } from 'native-base';
import { Provider } from "react-redux";
import { Store } from "./src/Store";
import Form from "./src/Components/Form/index";
import { ReactReduxFirebaseProvider } from 'react-redux-firebase'
import { createFirestoreInstance } from 'redux-firestore'
import RNfirebase from 'react-native-firebase';


class App extends Component {

  render() {
    const reactNativeFirebaseConfig = {
      debug: true
    };

    const firebase = RNfirebase;

    const rrfConfig = {
      enableRedirectHandling: false,
      userProfile: 'Users',
      useFirestoreForProfile: true,
      // updateProfileOnLogin: true
    };

    const rrfProps = {
      firebase,
      config: rrfConfig,
      dispatch: Store.dispatch,
      createFirestoreInstance
    }


    return (
      <Provider store={Store}>
        <ReactReduxFirebaseProvider {...rrfProps} >
          <Container>
            <Form />
          </Container>
        </ReactReduxFirebaseProvider>
      </Provider>
    );
  }

}


export default App;`


**Store/index.js**

`import {createStore, applyMiddleware, compose} from "redux";
import thunk from "redux-thunk";
import {rootReducer} from "./../Reducers/index";


export const Store  = createStore(
    rootReducer,
    compose(
        applyMiddleware(thunk),
    )
);
`

**Form/index.js**


`import React, { Component } from "react";
import { Alert, StyleSheet, View, TextInput } from "react-native";
import {
  authRequest,
  codeVerification,
  signOut
} from "../../Actions/AuthActions";
import { connect } from "react-redux";
import { ParseError, parsePhoneNumber } from "libphonenumber-js";
import { ConfirmDialog, ProgressDialog } from "react-native-simple-dialogs";
import { compose } from "redux";
import {
  withFirebase,
  withFirestore,
  firestoreConnect,
  firebaseConnect
} from "react-redux-firebase";

import {
  Container,
  Header,
  Left,
  Body,
  Right,
  Icon,
  Title,
  Input,
  Content,
  Item,
  Text,
  Grid,
  Col,
  Row,
  Button,
  H2
} from "native-base";

class SignInForm extends Component {
  constructor(props) {
    super(props);
    this.state = {
      number: "",
      formError: "",
      code: ""
    };
  }

  handlePhoneChange = number => {
    this.setState({
      number
    });
  };

  handlePhoneSubmit = () => {
    //@ Convert the number to E.164 format and validate the input
    try {
      const number = parsePhoneNumber(this.state.number, "PK");
      if (number.isValid()) {
        const num = number.formatInternational();
        this.setState({
          formError: "",
          number: num
        });
        this.props.auth(num);
      } else {
        this.setState({
          formError: "INVAILD NUMBER"
        });
      }
    } catch (err) {
      if (err instanceof ParseError) {
        this.setState({
          formError: err.message
        });
      } else {
        throw err;
      }
    }
  };

  handleOTPChange = code => {
    this.setState({
      code
    });
  };
  handleOTPSubmit = () => {
    this.props.submitCode(
      this.state.code,
      this.props.authState.codeConfirmState
    );
  };

  renderInputConfirmPopUp() {
    const { confirmPopUpState } = this.props.authState;
    return (
      <ConfirmDialog
        title="Confirm Dialog"
        visible={confirmPopUpState}
        positiveButton={{
          title: "Submit",
          onPress: this.handleOTPSubmit
        }}
      >
        <View>
          <TextInput
            style={{
              fontSize: 20,
              borderColor: "rgba(196, 196, 196,1)",
              textAlign: "center",
              borderWidth: 2
            }}
            maxLength={6}
            placeholder="Put Code..."
            onChangeText={e => this.handleOTPChange(e)}
          />
        </View>
      </ConfirmDialog>
    );
  }

  renderProgressPopUp = () => {
    const { progressState } = this.props.authState;

    return (
      <ProgressDialog
        visible={progressState}
        title="Please Wait"
        message="Sending Code..."
      />
    );
  };

  render() {
    const { auth, profile } = this.props.firebaseReducer;
    /* 
      
      auth loads correctly but NOT the profile because
      firestore doesn't hook up (may load the first time but not after a few refreshes )
    
    */ 

    console.log(profile); //form firebase Reducer
    return (
      <Container>
        <Header>
          <Body>
            <H2
              style={{
                color: "#fff"
              }}
            >
              Form
            </H2>
          </Body>
          <Right>
            <Text>Logo</Text>
          </Right>
        </Header>
        <Content>
          {auth.uid ? (
            //if auth is loaded check if photoUrl is there

            <Button
              primary
              large // show the rest of part
              onPress={() => {
                this.props.signout();
              }}
            >
              <Text>Logout</Text>
            </Button>
          ) : (
            //     // if auth not loaded show sign in form

            <Grid style={{ height: 250 }}>
              <Col style={{ backgroundColor: "rgba(196, 196, 196, 0.25), " }}>
                <Row style={{ alignItems: "center" }}>
                  <Item style={{ borderWidth: 2 }}>
                    <Input
                      placeholder="03xx-xxxxxxx"
                      keyboardType="phone-pad"
                      onChangeText={this.handlePhoneChange}
                      value={this.state.number}
                      maxLength={15}
                      autoFocus={true}
                      style={styles.input}
                      onSubmitEditing={this.handlePhoneSubmit}
                    />
                    {!!this.state.formError && (
                      <Icon
                        type="MaterialIcons"
                        name="error"
                        style={{ color: "rgba(226, 79, 79,.88)" }}
                      />
                    )}
                  </Item>
                </Row>
                <Text style={styles.formError}>
                  {this.state.formError || this.props.authState.err}
                </Text>
                <Text style={styles.formSucess}>
                  {this.props.authState.message}
                </Text>
              </Col>
            </Grid>
          )}
          {this.renderInputConfirmPopUp()}

          {this.renderProgressPopUp()}
        </Content>
      </Container>
    );
  }
}

const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    auth: phone => dispatch(authRequest(ownProps, phone)),
    submitCode: (code, confirmCode) =>
      dispatch(codeVerification(ownProps, code, confirmCode)),
    signout: () => dispatch(signOut(ownProps))
  };
};

const mapStateToProps = state => {
  return {
    authState: state.AuthReducer.authState,
    firebaseReducer: state.firebaseReducer
  };
};

export default compose(
  withFirestore, //for firebase and firestore via props.fire(X).anyAction
  withFirebase,
  firestoreConnect(() => {
    //connect to firestore
    return [
      { collection: "Users" } // object notation
    ];
  }),
  connect(
    mapStateToProps,
    mapDispatchToProps
  )
)(SignInForm);

const styles = StyleSheet.create({
  input: {
    fontSize: 26,
    paddingLeft: 10,
    borderColor: "rgba(196, 196, 196, 0.45)",
    textAlign: "center"
  },
  formError: {
    fontSize: 18,
    paddingTop: 5,
    paddingBottom: 15,
    textAlign: "center",
    color: "rgba(226, 79, 79,.88)"
  },
  formSucess: {
    fontSize: 18,
    paddingTop: 5,
    paddingBottom: 15,
    textAlign: "center",
    color: "rgba(46, 125, 50, 0.93)"
  }
});
`


**rootReducer**


`import { firebaseReducer } from "react-redux-firebase";
import { firestoreReducer } from "redux-firestore";
import AuthReducer from "./../Reducers/AuthReducer";

import { combineReducers } from "redux";

export const rootReducer = combineReducers({
  firebaseReducer,
  firestoreReducer,
  AuthReducer: AuthReducer
});
`
### IDK if these files are relevant but just so can have a more clearer pic of the issue  
**AuthReducer.js**

`import {
  PHONE_AUTH_REQUESTED,
  PHONE_AUTH_SUCCESS,
  PHONE_CODE_ERR,
  PHONE_CODE_SENT,
  PHONE_AUTH_ERR
} from "./../Actions/Types";

const initState = {
  authState: {
    progressState: false,
    confirmPopUpState: false,
    codeConfirmState: null,
    err: ""
  }
};

export default (state = initState, action) => {
  switch (action.type) {
    case PHONE_AUTH_REQUESTED: {
      return {
        ...state,
        authState: {
          ...state.authState,
          progressState: true
        }
      };
    }
    case PHONE_CODE_SENT: {
      return {
        ...state,
        authState: {
          ...state.authState,
          progressState: false,
          confirmPopUpState: true,
          err: "",
          codeConfirmState: action.payload
        }
      };
    }
    case PHONE_CODE_ERR: {
      return {
        ...state,
        authState: {
          ...state.authState,
          confirmPopUpState: false,
          codeConfirmState: null,
          err: "Invalid Code..."
        }
      };
    }
    case PHONE_AUTH_SUCCESS: {
      return {
        ...state,
        authState: {
          ...state.authState,
          confirmPopUpState: false,
          codeConfirmState: null,
          err: ""
        }
      };
    }
    case PHONE_AUTH_ERR: {
      return {
        ...state,
        authState: {
          ...state.authState,
          confirmPopUpState: false,
          progressState: false,
          err: action.payload
        }
      };
    }
    default: {
      return {
        ...state
      };
    }
  }
};
`



**AuthAction.js**

`import {
  PHONE_AUTH_REQUESTED,
  PHONE_CODE_ERR,
  PHONE_AUTH_SUCCESS,
  PHONE_CODE_SENT,
  PHONE_AUTH_ERR
} from "./Types";
export const authRequest = (ownProps, phoneNo) => (dispatch, getState) => {
  const firebase = ownProps.firebase; //the v3 way of accessing firebase through 
  const firestore = ownProps.firestore;

  dispatch({
    type: PHONE_AUTH_REQUESTED
  });
  firebase
    .auth()
    .signInWithPhoneNumber(phoneNo)
    .then(confirmResult => {
      dispatch({
        type: PHONE_CODE_SENT,
        payload: confirmResult
      });
    })
    .catch(error => {
      dispatch({
        type: PHONE_AUTH_ERR,
        payload: error.message
      });
    });

  // Auto Verifcation method
  firebase.auth().onAuthStateChanged(user => {
    if (user) {
      // console.log(user)
      //      add the user to firestore db
      firestore
        .collection("Users")
        .doc(user.uid)
        .set(
          {
            phoneNumber: user.phoneNumber
          },
          { merge: true }
        )
        .then(() => {
          dispatch({
            type: PHONE_AUTH_SUCCESS
          });
        });
    }
  });
};

//Manual verficaition Method
export const codeVerification = (ownProps, code, confirmResult) => (
  dispatch,
  getState
) => {
  const firestore = ownProps.firestore;

  confirmResult
    .confirm(code)
    .then(user => {
      //add the user to firestore db
      firestore
        .collection("Users")
        .doc(user.uid)
        .set(
          {
            phoneNumber: user.phoneNumber
          },
          { merge: true }
        )
        .then(() => {
          dispatch({
            type: PHONE_AUTH_SUCCESS
          });
        });
    })
    .catch(err => {
      dispatch({
        type: PHONE_CODE_ERR
      });
    });
};

export const signOut = ownProps => {
  return (dispatch, getState) => {
    const firebase = ownProps.firebase;
    firebase
      .auth()
      .signOut()
      .then(() => {
        console.log("signed Out Success");
      });
  };
};
`

**Comment by prescottprue** [comment]
@MufassirShaw Glad to have the detail, but is it possible to share it in a project with the package file and everything? I was hoping to run the actual code

**Comment by MufassirShaw** [comment]
@prescottprue  Here is the complete repo. You can use 03139277452 for demo with a code of 123456. Or if you want you can tell me to add another number of demo purposes. Hope this will help

**Comment by MufassirShaw** [comment]
@prescottprue  I did a few more tests and find out that i can write perfectly to the firestore but having issues when reading from it. May be there is so issue in the firestoreReducer or i'm not doing it "the right way"

**Comment by prescottprue** [comment]
@MufassirShaw You shouldn't need to attach a listener to the whole collection of `Users` if you are just trying to get the profile (which lives in `profile`). You also don't need to attach your own listeners if you use `userProfile: "Users"`. [The profile section of the docs](http://react-redux-firebase.com/docs/recipes/profile.html#basic) explains how this value lives on `state.firebase.profile` - where you are getting from the actual `users` list.

**Comment by MufassirShaw** [comment]
@prescottprue  actually i wanna handle the auto phone verification for android as mentioned [here](https://rnfirebase.io/docs/v5.x.x/auth/phone-auth#3.-[Android]-Handle-Auto-Verification). I don't know how to handle that in redux. And i don't think the issue is because of this event listener as it is not even used on an emulator. Anyway i removed the listener at all but still had the same issue.  And please note that there is no signup procedure or the sign up is the same as login. As you can see i'm merging the user so that i can make sure that i don't overwrite the existing user. 



  ```



    firestore
        .collection("Users")
        .doc(user.uid)
        .set(
          {
            phoneNumber: user.phoneNumber
          },
          { merge: true } //merging it so that i don't overwrite and existing user
        )
        .then(() => {
          dispatch({
            type: PHONE_AUTH_SUCCESS
          });
        });
    }
```

**Comment by prescottprue** [comment]
@MufassirShaw Thanks for letting me know, I'll try to replicate.

**Comment by MufassirShaw** [comment]
@prescottprue I'm really looking forward for a fix or a work around. Thanks

**Comment by MufassirShaw** [comment]
@prescottprue i don't know if this is really the issue with this package but i solution to the problem is to only reopen your app in the emulator with ever closing the packager or the emulator. **Every time the firebase or firestore dbs aren't hooked up, just close the app and reopen it (with closing the emulator)** plus i don't think this bug is gonna be there in the production environment as you can't rebuild the app over and over (the original reason for this bug) and you get an already build app.

So i think for now you should close this and if i ever had an issue. I'll report it here. Thank you so much for this awesome package and please work more on the docs if possible. Happy coding :)
