### ISSUE TITLE
firestoreConnect With Multiple Listeners to Same Collection

### ISSUE THREAD

**Issue by Frank-The-Tank** [prescottprue/react-redux-firebase#660]
Hey guys, I am been trying to solve my issue by looking at a few other issues include #368, but I have not been able to get my code to work. I have two different pages you can navigate to with react router that change the url (navigated to with a navbar) and both are pulling data from the same collection -> document but then differ on the inner collection they are grabbing. When I try to alternate between pages at first an error is throw, but if I reload the page all of the data comes up correctly. This is the code in my two components: 

```
export default compose(
  connect(
    mapState,
    actions
  ),
  firestoreConnect(props => {
    const authId = props.authUID == null ? "placeholder" : props.authUID;
    return [
      {
        collection: "users",
        doc: authId,
        subcollections: [{ collection: "budget" }]
      }
    ];
  })
)(BudgetDashboard);
```

VS 

```
export default compose(
  connect(
    mapState,
    actions
  ),
  firestoreConnect(props => {
    const authId = props.authUID == null ? "placeholder" : props.authUID;
    return [
      {
        collection: "users",
        doc: authId,
        subcollections: [{ collection: "profile" }]
      }
    ];
  })
)(ProfileDashboard);
```

**Comment by prescottprue** [comment]
@Frank-The-Tank I think that it might be that you aren't [waiting for auth to load](http://react-redux-firebase.com/docs/queries.html#loading before attaching your query. You should also try placing your connect after the `firebaseConnect` (though it is hard to tell if that would even help since the state collection logic is not provided). Something else you might want to try is [`storeAs`](http://react-redux-firebase.com/docs/queries.html#storeAs).

**Comment by Frank-The-Tank** [comment]
Connection logic: 

```
const mapState = ({ firebase: { auth }, firestore: { ordered, data } }) => ({
  users: data.users,
  authUID: auth.uid
});

const actions = {
  updateBudgetData,
  compareChooser,
  openModal,
  removeSavingsItem,
  removeDebtItem
};
```

Load Logic:

```
render() {
    const { users, authUID } = this.props;
    if (!isLoaded(users) || !isLoaded(authUID))
      return <LoadingComponent inverted={true} />;
    const user = users[authUID].budget;
    return (
      <Grid>
        <Grid.Column width={16}>
          <BudgetNav />
          <BudgetHeader
            general={user.general}
            onCompareChange={this.onCompareChange}
            openIncomeModal={this.displayIncomeModal}
          />
```

**Comment by Frank-The-Tank** [comment]
When I add storeAs to either of my firestoreConnect return hashes it causes the page to never load

**Comment by prescottprue** [comment]
What version of redux-firestore are you using? It seems like it is an issue merging on the subcollection level, so also sure why `storeAs` wouldn't work. What do you mean by "return hashes it causes the page to never load"? Did you change the connection logic to match the new `storeAs` names you where using?

It would be much easier to understand what is going on with a full working application to replicate with.  Feel free to start with one of the examples or [this codesandbox](https://codesandbox.io/s/71198q6q86).
