### ISSUE TITLE
question(examples): firestoreConnect pagination need help

### ISSUE THREAD

**Issue by selimyalinkilic** [prescottprue/react-redux-firebase#661]
Hi,

I wanna make pagination, but i can't make it. Maybe someone knows how to make it. Can you help me please. My dashboard component codes are as below. 

```

> import React, { Component } from 'react';
> import ProductListTable from '../products/ProductListTable';
> import { connect } from 'react-redux';
> import { firestoreConnect } from 'react-redux-firebase';
> import { compose } from 'redux';
> import { Link, Redirect } from 'react-router-dom';
> 
> class Dashboard extends Component {
>   render() {
>     const { products, auth } = this.props;
>     if(!auth.uid) return <Redirect to='/admin/login' />
>       return (
>         <div className="admin-dashboard">
>           <div className="container">
>             <h3 className="mt-5 mb-5 text-dark text-center">Product List</h3>
>             <div className="row">
>               <div className="col-12 mb-2">
>                 <button className="btn btn-primary btn-sm mr-2" disabled>Delete All</button>
>                 <Link to="/admin/product/create" className="btn btn-primary btn-sm">Add Product</Link>
>               </div>
>             </div>
>             <ProductListTable products={products} />
>           </div>
>         </div>
>       )
>   }
> }
> 
> const mapStateToProps = (state) => {
>   return {
>     products: state.firestore.ordered.products,
>     auth: state.firebase.auth,
>   }
> }
> 
> export default compose(
>   firestoreConnect([
>     { 
>       collection: 'products',
>       orderBy : ['createdAt','desc']
>     }
>   ]),connect(mapStateToProps)
> )(Dashboard);

```

**Comment by selimyalinkilic** [comment]
I found this, https://codepen.io/PiotrBerebecki/pen/pEYPbY?editors=0110 and i used in my project. It's working good.

**Comment by prescottprue** [comment]
@selimyalinkilic Thanks for posting, glad to know you got something going.

Not sure that the posted solution will work for all folks since it seems that it is loading all data then just breaking it down into pages instead of only querying data necessary for the current page and loading other pages once they are navigated to (interesting task to accomplish on real time database)

**Comment by selimyalinkilic** [comment]
yes I know. I applied this way because I failed in real-time database. I didn't find a result despite searching on the internet. I started the project after a video series I saw on youtube and wanted to add some non-features. How can I do it in real time database? can you help me ?
