### ISSUE TITLE
firestoreConnect how to change collection name

### ISSUE THREAD

**Issue by hamsahmedansari** [prescottprue/react-redux-firebase#678]
Hey guys, I am confused !! I used collection **"Users"** to fetch all users from firebase and it added to state.firestore.user... but when I am  try to fetch sub-collection of user **"chatRooms"** it overwrite the previous state of state.firestore.user is it possible to change key in **chatRooms** of **Users** 
Code 
`export default compose(
  connect(
    mapStateToProps,
    mapDispatchToProps
  )
  firestoreConnect(props => [
    {
      collection: "users",
      doc: props.uid,
      subcollections: [{ collection: "chatRooms" }]
    }
  ])
)(NewMessage);
`

**Comment by illuminist** [comment]
Apply `storeAs` to change data location.
```javascript
firestoreConnect(props => [{
  collection: "users",
  doc: props.uid,
  subcollections: [{ collection: "chatRooms" }],
  storeAs: "userChatRooms" // Add this, use whatever name you seem fit
}])
```
A new data will be available in `state.firestore.data.userChatRooms` and `state.firestore.ordered.userChatRooms`,

**Comment by hamsahmedansari** [comment]
You're a Rockstar
