### ISSUE TITLE
Does the order of firebaseConnect matter?

### ISSUE THREAD

**Issue by mbrnwsk** [prescottprue/react-redux-firebase#68]
I want to avoid directly calling `this.props.firebase.push(...)`, so I am wrapping it in mapStateToProps, like this: 

```
const NotesContainer = connect((state, {firebase}) => ({
  notes: dataToJS(state.firebase, '/notes'),
  createNote: (note) => firebase.push('/notes', note)
}))(Notes);

const wrappedNotes = firebaseConnect([
  '/notes'
])(NotesContainer);

export default wrappedNotes;
```

in examples `firebaseConnect` is always before redux `connect`. Am I safe with the approach above?

**Comment by prescottprue** [comment]
Yes, that is a safe approach, and should work as expected.

You should also be able to have the same thing work in the reverse order. `connect` is run on relevant updates, so the only time that the order matters is if you are trying to run a state/props based query.

The [state based query example snippet shows](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/snippets/stateBasedQuery/App.js#L49-L71) using `auth` from an initial `connect` call within a later `firebaseConnect` call.
