### ISSUE TITLE
bug(storage): uploadFiles() not updating metadata

### ISSUE THREAD

**Issue by jnamkung** [prescottprue/react-redux-firebase#680]
**Do you want to request a *feature* or report a *bug*?**  

bug

**What is the current behavior?**

When I call `uploadFiles` with a third argument, metadata is not being updated, instead I get the following error:

<img width="739" alt="uploadFiles-console-error" src="https://user-images.githubusercontent.com/5976470/56071268-26b2fd80-5d42-11e9-8072-882019bbc304.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

```
firebase
 .uploadFiles(storagePath, newFiles, dbPath)
 .then(snap => {
      console.log(snap);
  }) 
 .catch(err => console.log(err)); 
```  

**What is the expected behavior?**

When I call `uploadFiles` with a third argument, I expect to have metadata updated in the realtime database at the path represented by the third argument.

I see there was discussion and similar error with `uploadFile/uploadFiles` discussed in #480, but that was version 2 of react-redux-firebase. I wonder if this functionality still works in version 3.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

I am currently upgrading from react-redux-firebase 2.1.7 to 3.0.0-alpha.10 (and firebase 4.9.1 to 5.9.1). This code worked before the upgrade.

**Comment by prescottprue** [comment]
Did you provide a `fileMetadataFactory`? It seems like the stack trace is pointing to your `config.js` file - so that seems like it has to do with custom `fileMetadataFactory` logic, but not sure.

**Comment by jnamkung** [comment]
I do provide a `fileMetadataFactory` but I was returning the wrong value for downloadURL. I had 

`downloadURL: downloadURLs[0], `

and that's where the error was. Thanks for the pointer!
