### ISSUE TITLE
Possible to do load data based on a state change in the connected component

### ISSUE THREAD

**Issue by esbenvb** [prescottprue/react-redux-firebase#681]
**Do you want to request a *feature* or report a *bug*?**  

Feature

**What is the current behavior?**

Not possible as far as I can see

**What is the expected behavior?**

In my Firestore, I have two collections,

```
tournaments
 - id
 - name
 - currentSeasonId
```
```
seasons/
  {seasonId}/
    attributes/
      teams
      standings
```

In React I have a component where a user does the following:
- Select a tournament from all tournaments
- Select a team or view standings from the list of teams in the current season of the tournament

What I'm looking for is a way to make `firestoreConnect()` map the teams/standings of a given season, to the props, based on the `currentSeasonId` whenever a tournament selected by the user.

I see a few options here:

- Either I can connect standings/teams for all seasons right away, and then pick the needed data from that list on the client side. But it's not that elegant and not that scalable.
- I can also duplicate my data so the tournament document itself contains a copy of all teams and standings of the current season. That would make the backend generating the data way more complex, as these data are continuously updated.
- I already tried making a connected container `TournamentTeamSelector`, which allows the user to pick a tournament, and renders a `TeamSelector` component which is given the selected tournament as a prop (based on the state of the `TournamentTeamSelector` component), and is also connected to firestore, requesting the teams of the current season of the tournament provided in the prop. This works, but it feels a little awkward to have nested connected components, if it could be avoided.

So what I'm looking for, is a way that I can communicate with `firestoreConnect`, telling it that a field in the state of my component should be used as a parameter for the data mapping.

Something like this:

```tsx
export default compose(
  connect(mapStateToProps),
  firestoreConnect((props: Props, componentState: State) => [
    {
      collection: 'tournaments',
      where: [['body.countryCode', '>', '']],
      storeAs: 'tournaments',
    },
    {
      collection: 'seasons',
      doc: componentState.selectedTournament.currentSeasonId,
      subcollections: [{ collection: 'attributes', doc: 'teams' }],
      storeAs: 'teams',
    },
  ])
)(TeamSelector)
```

Or maybe, the `doc` argument can be some value found in the redux store?

Something like:

```tsx
export default compose(
  connect(mapStateToProps),
  firestoreConnect((props: Props, reduxState: ReduxState) => [
    {
      collection: 'tournaments',
      where: [['body.countryCode', '>', '']],
      storeAs: 'tournaments',
    },
    {
      collection: 'seasons',
      doc: reduxState.selectedTournament.currentSeasonId,
      subcollections: [{ collection: 'attributes', doc: 'teams' }],
      storeAs: 'teams',
    },
  ])
)(TeamSelector)
```

Is it something that's on the roadmap, or even doable at all?

**Comment by illuminist** [comment]
You already can map whatever redux state into props for `firebaseConnect`. Therefore your `mapStateToProps` need to return `state.selectedTournament.currentSeasonId` along with the other state value.

```javascript
const mapStateToProps = state => ({
  currentSeasonId: state.selectedTournament.currentSeasonId,
  seasonData: state... // wherever the value is
})
```
Then `currentSeasonId` will appear as a prop in `firebaseConnect`.

**Comment by esbenvb** [comment]
@illuminist Thanks :) I did not expect that one to work, since I assumed that the `mapStateToProps` was only applied AFTER loading the data from firestore, so the props mapped here from `state.firestore` would not exist.

I think this solution is a good compromise, instead of letting `firestoreConnect` use the local component state if even possible...

**Comment by illuminist** [comment]
But it's still true that `mapStateToProps` can't find firestore data before loading from firestore if one query depends on data of another query. Because of that initially doc id will be undefined and could cause `firestoreConnect` to load entire `seasons` collection instead one single doc.

To prevent that, you can lodash `_.get` function to get state that might initially not exist to prevent error from accessing an undefined object. Then in `firestoreConnect`, conditionally apply a query when depending data is available.

**Comment by esbenvb** [comment]
@illuminist yes indeed I have to guard the second query until the first one has delivered the prop values.

I tried a simple solution like this, but unfortunately, `firestoreConnect` does not accept undefined entries...

```tsx
  firestoreConnect((props: Props) => [
   {
      collection: 'tournaments',
      where: [['body.countryCode', '>', '']],
      storeAs: 'tournaments',
    }, 
    props.activeTournament && {
      collection: 'seasons',
      doc: props.activeTournament.currentSeasonId,
      subcollections: [{ collection: 'attributes', doc: 'teams' }],
      storeAs: 'teamsFavorite',
    }   
  ])
```

Therefore, I had to make it like this.

```tsx
  firestoreConnect((props: Props) => {
    const tournaments = {
      collection: 'tournaments',
      where: [['body.countryCode', '>', '']],
      storeAs: 'tournaments',
    }
    if (!props.activeTournament) {
      return [tournaments]
    }
    const teamsForSeason = {
      collection: 'seasons',
      doc: props.activeTournament.currentSeasonId,
      subcollections: [{ collection: 'attributes', doc: 'teams' }],
      storeAs: 'teamsFavorite',
    }
    return [tournaments, teamsForSeason]
  })
```

**Comment by illuminist** [comment]
You can also use `Array.filter` to filter out undefined value. Or use lodash `_.compact`. Or push only available query to returning array. Or even spread operation with empty array in tertiary condition.

**Comment by esbenvb** [comment]
FYI i actually found that I can skip the mapping the redux state to props before using it in the query.

2nd argument of `firestoreConnect` seems to be the Redux store, so I can say

```ts
firestoreConnect((props: Props, store: Store<ReduxState>) => {
  const state = getState()
  return [{
    collection: "stuff",
    doc: state.someKey,
  }]
})

**Comment by illuminist** [comment]
@esbenvb That's undocumented part of the library and it won't work with v3 and newer as it relies on react's legacy context api. If you plan to migrate to v3 then you should do the documented way.

**Comment by esbenvb** [comment]
@illuminist Thanks for noting that it's not part of v3.

Do you have any link to "the documented way", or is it just like you mentioned, to map redux state to props, map props to firestore queries, and then map the query results of the state, to props?

It just seems like quite a detour to run all these connect functions multiple times if it can be avoided...

**Comment by illuminist** [comment]
Seem I wasn't quite right because a way of mapping redux state to connector query doesn't documented anywhere. I see this as the best practice for me, you don't really need multiple `connect`,  you can use single `connect` for both getting redux state for a query and for a result.

```javascript
const enhancer = compose(
  connect(state => {
    const itemId = _.get(state, 'currentItemId')
    return {
      itemId, // This one to be used in query
      itemData: _.get(state, ['firestore', 'data', currentItemId]) // Will initially be undefined and will have data after fetching from firestore, use in renderer component
    }
  }),
  firestoreConnect(({ itemId }) => {
    const queries = []
    if(itemId != null) { // If no itemId provided as a prop then no query will run
      queries.push({ collection: 'items', doc: itemId })
    }
    return queries    
  )
)
export default enhancer(MyComponent)
```
So I map both `itemId` to be used in query and `itemData` which is a result from the query within the same `connect` HOC. `firestoreConnect` doesn't necessary to be before `connect` that map the result or even the same component that use the result. It can be anywhere. The result will initially be undefined, then later will be available to be used.
