### ISSUE TITLE
firestoreConnect passing incorrect value to firestore.ordered

### ISSUE THREAD

**Issue by philberg** [prescottprue/react-redux-firebase#687]
**What is the current behavior?**
I have a situation where I am modifying an array of objects in the firestore
The document is a `game` and the field is `game.cards` where each item in `game.cards` is it's own object

When I modify `game.cards` from an array with a few items, into a new, empty array, it breaks.
When using firestoreConnect to pass this down as state and into props, the data in `firestore.data.games[$id]` is correct, but the data in `firestore.ordered.games[0]` is not. 
In the latter, `games.cards` gets set to an array with a single item when it should be empty

**What is the expected behavior?**
They should be the same

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
```
  "dependencies": {
    "@material-ui/core": "^3.9.3",
    "final-form": "^4.12.0",
    "firebase": "^5.9.4",
    "firebase-admin": "^7.2.0",
    "firebase-functions": "^2.2.1",
    "lodash": "^4.17.11",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-final-form": "^4.1.0",
    "react-firebaseui": "^3.1.2",
    "react-redux": "5",
    "react-redux-firebase": "^2.2.6",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8",
    "redux": "^4.0.1",
    "redux-firestore": "^0.7.3",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "uuid": "^3.3.2"
  },
```

Chrome Version 73.0.3683.103 (Official Build) (64-bit) on OSX

**Comment by illuminist** [comment]
Could you provide reproduction or some part of the code where you said it was an issue? It isn't easy to figure the problem code from given description.

**Comment by philberg** [comment]
Sorry if that was unclear.

See sample code below to reproduce:
```
import React from 'react';
import { compose } from "redux";
import { connect } from 'react-redux'
import {firestoreConnect} from "react-redux-firebase";
import {get} from 'lodash';

class Test extends React.Component {render() {return (<div></div>);}}

const mapStateToProps = (state) => {
  console.log('FS DATA', JSON.stringify(get(state, 'firestore.data.aaa.IGFoFG3OXh80wgqVOaDm')))
  console.log('FS ORDERED', JSON.stringify(get(state, 'firestore.ordered.aaa')))
  return {}
}

export default compose(
  firestoreConnect([{
    collection: 'aaa',
    doc: 'IGFoFG3OXh80wgqVOaDm'
  }]),
  connect(mapStateToProps),
)(Test)
```
Document before change
![Screen Shot 2019-04-18 at 1 06 44 PM](https://user-images.githubusercontent.com/7586829/56388091-fd2f2180-61da-11e9-93fe-5b7de4d38cf6.png)

After removing a single map from the array
![Screen Shot 2019-04-18 at 1 06 56 PM](https://user-images.githubusercontent.com/7586829/56388110-03250280-61db-11e9-975f-c7ba389c3897.png)

Logs (you can see the issue after the change)
![Screen Shot 2019-04-18 at 1 07 00 PM](https://user-images.githubusercontent.com/7586829/56388133-0fa95b00-61db-11e9-9fce-6f173dea4e22.png)

I tried to look at the code, but I couldn't figure it out. I thought maybe a shallow vs deep equal, but you're using `_.isEqual` which should work great

**Comment by illuminist** [comment]
I definitely think it related to https://github.com/prescottprue/redux-firestore/issues/140

Not sure how I couldn't reproduce the issue in https://codesandbox.io/s/k5yz4x71r5 even adding and removing from array directly via console still update both `data` and `ordered` state correctly.

**Comment by philberg** [comment]
That is strange.  You do have slightly a slightly newer react-redux version, although I doubt that matters.

I'll play around with it a bit and see what I can come up with

**Comment by prescottprue** [comment]
@philberg If you are able to repro could you open an issue on [redux-firestore](https://github.com/prescottprue/redux-firestore) since that is where the logic for firestore lives currently.
