### ISSUE TITLE
Uncaught Error: Firebase database is required to create watchers

### ISSUE THREAD

**Issue by khmaies5** [prescottprue/react-redux-firebase#698]
react-redux-firebase v3
i imported database like what you said but i still have the same Error
```javascript
const fire = firebaseConnect(props => [
  { type: 'once', path: '/courses', queryParams: ['orderByChild=slug', `equalTo=${props.match.params.slug}`] }
]);

const con = connect(state => ({
  courseData: state.firebase.ordered.courses
}), mapDispatchToProps);

export default compose(con, fire)(Course);
```
i have also two warnings in the console:
Warning: Failed prop type: The prop `dispatch` is marked as required in `FirebaseConnectWrapped(Course)`, but its value is `undefined`.
Warning: Failed prop type: Invalid prop `firebase` of type `string` supplied to `FirebaseConnectWrapped(Course)`, expected `object`.
edit: i removed the import 'firebase/database' and then i added it again, now i got this error:
TypeError: Cannot read property 'watchers' of undefined

_Originally posted by @khmaies5 in https://github.com/prescottprue/react-redux-firebase/issues/638#issuecomment-491111881_

**Comment by khmaies5** [comment]
my bad, i was importing react-redux-firebase/lib instead of react-redux-firebase

**Comment by valerii-cognite** [comment]
`react-redux-firebase/lib` proposed in examples https://github.com/prescottprue/react-redux-firebase/tree/next. Migrating to a regular import, i.e.
```
import { ReactReduxFirebaseProvider } from 'react-redux-firebase';
```
solved an issue for me, shouldn't we consider to update docs?

**Comment by prescottprue** [comment]
`import ReactReduxFirebaseProvider from 'react-redux-firebase/lib/ReactReduxFirebaseProvider'` should still work as expected. @valerii-cognite what exactly was it that didn't work for you when pulling from `/lib`?

**Comment by valerii-cognite** [comment]
I'm not sure what went wrong, but in that case error from the issue topic occurred `Uncaught Error: Firebase database is required to create watchers`
