### ISSUE TITLE
Filter by multiple fields on firestoreConnect

### ISSUE THREAD

**Issue by guilopes22** [prescottprue/react-redux-firebase#704]
Hi, I want to do a filter by multiple fields, something like that:

```js
firestoreConnect(({ location }) => [
  {
    collection: 'students',
    where: ['age', '>=', 12],
    where: ['name', '==', 'Gabe'],
  },
];
```

**Comment by illuminist** [comment]
firestoreConnect(({ location }) => [
  {
    collection: 'students',
    where: [
      ['age', '>=', 12],
      ['name', '==', 'Gabe'],
    ]
  },
];
