### ISSUE TITLE
Prevent isAuthenticated from continually re-rendering the component

### ISSUE THREAD

**Issue by DevJHansen** [prescottprue/react-redux-firebase#705]
The route protection wrapper is constantly re-rendering my component. This rendering is causing my material UI dialogue box to close 

To re-create it you can simply create a component that contains a material UI dialogue box. Protect that component with your route protection, open the dialogue and you'll see that it will automatically close after a few seconds.

**Comment by illuminist** [comment]
There're dozens of different way to implement things in an app, and with your *minimal* description, I couldn't figure out which kind of implementation that causing an error. https://codesandbox.io/s/reactreduxfirebase-templete-6cv6g feel free to fork this sandbox to create a repro.

**Comment by DevJHansen** [comment]
My apologies for the bad description. I'll try to re-create my problem with code sandbox. But in the meantime I'll give you more info here. 

My material-UI dialogue box is either opened or closed based on the current state of my component. 
So if open: false then the dialogue box is closed and if open: true, then it is open. By default the state is set to false. 
What is happening is that the component that contains my dialogue box is set to a specific route, and this route is protected by the react-redux-firebase route protection wrapper. The wrapper seems to be re-rendering the component every few seconds which sets my state back to false, which closes my dialogue box. 

Since I wrote the first post I came across another issue. In the same component that renders the dialogue box, I have a scrollable list. As I scroll down the list, the component is then automatically re-rendered by the route protection wrapper, which then scrolls the list back to the top. Meaning I can't scroll down my list.

**Comment by illuminist** [comment]
Usually re-rendering doesn't reset component state, unless the said component getting unmounted. I think there's another issue lying in here.

Also I believe `isAuthenticated` isn't a thing in react-redux-firebase as I tried to find by keyword.
