### ISSUE TITLE
How do integrate firestore react-redux-firebase with react-native-firebase

### ISSUE THREAD

**Issue by zzbynzz** [prescottprue/react-redux-firebase#708]
I am using react-native-firebase instead of firebase/app . So I can't import firestore of 'firebase/firestore'. How can do that with react-native-firebase ?
Thanks you very much.

**Comment by prescottprue** [comment]
@zzbynzz You can follow their instructions for importing and pass the react-native-firebase instance in as [mentioned in the react-native section of the docs](http://react-redux-firebase.com/docs/integrations/react-native.html#native-modules).

Feel free to reach back out if it doesn't work as intended

**Comment by 1990-X** [comment]
Hi @prescottprue, how would one go with integrating `redux-firestore` with React Native? I can't figure it out for the life of me! I'm using `react-native-firebase` and following along with the `RNFirebase` component to initialize the Firebase application.

I can't find any resources on how to integrate this. Any ideas?

**Comment by prescottprue** [comment]
You would include the `reduxFirestore` store enhancer and pass the RNFirebase instance into that as well the same way you do with `reactReduxFirebase`.
