### ISSUE TITLE
feat(query): callback when data is ready from firestore.setListener

### ISSUE THREAD

**Issue by esbenvb** [prescottprue/react-redux-firebase#710]
I suggest the following feature.

* Get a callback on the first response, when setting up a listener with `firestore.setListener()`.

Use case:
When starting an app, before navigating in the UI, i need to check that some of the user generated content meets all requirements, otherwise, I'll send the user to the another screen in order to complete the data, before navigating to the main screen of the app.

My current solution is a workaround where I "sleep" until the data is ready but that's not ideal

```js
export const sleep = (duration: number) =>
  new Promise(resolve => setTimeout(resolve, duration))


export function isLoading(state: ReduxState): boolean {
  return !!Object.values(state.firestore.status.requesting).find(
    value => !!value
  )
}
......
// My thunk:
  const firestore = getFirestore()
  firestore.setListener({
      collection: 'tournaments',
      where: [
        ['body.isDefaultForTeams', '==', true],
      ],
      storeAs: this.key(),
  })
  let state = getState()
  console.log('defaultTournaments before wait', state.firestore.data.defaultTournaments)  // this will be undefined

  while (isLoading(state)) {
    console.log('Waiting 100')
    await sleep(100)
    state = getState()
  }
  const defaultTournaments = state.firestore.data.defaultTournaments 
  console.log({ defaultTournaments })
```

**Comment by illuminist** [comment]
`setListener` isn't supposed to do synchronized job.

Here's my suggestions:
- Easy way: directly read data using `await firestore.collection(...).get()`. Or...
- Hard way: use `firestoreConnect` and use `connect` to get data and loading state, then redirect user inside component when conditions are not met.

**Comment by prescottprue** [comment]
+1 to what @illuminist said

Another way to accomplish this is using Higher Order Components as described in the [routing recipes section of the docs](http://react-redux-firebase.com/docs/recipes/routing.html#auth-required-route-protection) (often called route protection)

**Comment by prescottprue** [comment]
@esbenvb do the proposed solutions work for your use case or are you still feeling that this feature has a place? Going to close for now, but feel free to reach out to discuss further - we can reopen
