### ISSUE TITLE
How to store user auth in localStorage

### ISSUE THREAD

**Issue by dinorhythms** [prescottprue/react-redux-firebase#711]
Please am having problem storing user auth into localstorage. Need to store auth in localstorage for persistency. I think its not friendly as user keeps waiting on page refresh for auth load.

Thanks.

**Comment by illuminist** [comment]
The idea is to save redux state into localStorage with [redux-persist](https://github.com/rt2zz/redux-persist). You can figure it out.

**Comment by dinorhythms** [comment]
@illuminist thanks for the hint. will look into it.
