### ISSUE TITLE
question(core): firebase.auth is not a function

### ISSUE THREAD

**Issue by yrufai** [prescottprue/react-redux-firebase#712]
okay thanks.. did what you suggested still giving same error

_Originally posted by @wizzywit in https://github.com/prescottprue/react-redux-firebase/issues/249#issuecomment-475859493_

came to the same issue and so far no solution has worked for me. please how were you able to solve that problem

**Comment by prescottprue** [comment]
@yrufai Please provide code to reproduce the issue - in the referenced comment it was noted that the action was being dispatched without passing a firebase instance into the action.
