### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by isubhokarma** [prescottprue/react-redux-firebase#718]
**Do you want to request a *feature* or report a *bug*?**  

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**Bug**

**What is the current behavior?**

**On LocalHost** -- TypeError: Object(...) is not a function
**On CodeSandBox** -- TypeError: (0 , _reactReduxFirebase.reactreduxFirebase) is not a function

```
const store = createStore(
  rootReducer,
  compose(
    applyMiddleware(
      thunk.withExtraArgument({
        getFirebase,
        getFirestore
      })
    ),
    reactreduxFirebase(fbConfig),
    reduxFirestore(fbConfig)
  )
);
```
In this part of code.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**Please visit the repo here:** _https://github.com/neonbroly/neonbroly-main-web/tree/sector-firebase-setup-v-1_

**Please visit CodeSandBox here:** _https://codesandbox.io/s/sector-ro41m_

`/sector/src/index.js`

**What is the expected behavior?**

Expected to run correctly without any error and let me post my content on firestore db.
`localhost:3000/asset`

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

OS: Windows 10
npm: 6.9.0
node: 12.1.0

```
  "dependencies": {
    "firebase": "^6.2.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^7.1.0",
    "react-redux-firebase": "^3.0.0-alpha.12",
    "react-router-dom": "^5.0.1",
    "react-scripts": "3.0.1",
    "redux": "^4.0.1",
    "redux-firestore": "^0.6.0-beta",
    "redux-thunk": "^2.3.0"
  },
```

Yes, I did tried the stable versions of packages for both react-readux-firebase & redux-firestore.

**PLEASE HELP**

**Comment by illuminist** [comment]
You're using `react-redux-firebase` version 3 but initialized using version 2 method. Please refer to v3 documents for proper initialization http://docs.react-redux-firebase.com/history/v3.0.0/

**Comment by isubhokarma** [comment]
@illuminist downgraded to the current stable version 2.2.6. Still giving the same output.

https://github.com/neonbroly/neonbroly-main-web/tree/sector-firebase-setup-v-1

![Annotation](https://user-images.githubusercontent.com/49366380/59840173-75e36300-936f-11e9-8915-240421e6e20c.png)

**Comment by illuminist** [comment]
You also misspelled `reactreduxFirebase` it has to be `reactReduxFirebase`

**Comment by isubhokarma** [comment]
AAAAAAAAAAAAAA BROOOOOOOO THAAAAAANNNKKKKKSSSSSSS
YOUUUUUUU AREEEEEEE AWESOOOMEMEMEMEM

**Comment by isubhokarma** [comment]
@illuminist AAAAAAAAAAAAAA BROOOOOOOO THAAAAAANNNKKKKKSSSSSSS
YOUUUUUUU AREEEEEEE AWESOOOMEMEMEMEM

**Comment by MananDesai54** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import { createStore,applyMiddleware,compose } from 'redux';
import { Provider } from 'react-redux';
import rootReducer from './store/reducers/rootReducer';
import thunk from 'redux-thunk';
import { getFirestore,reduxFirestore } from 'redux-firestore';
import { getFirebase,reactReduxFirebase } from 'react-redux-firebase';
import firebaseConfig from './config/firebaseConfig'

const store = createStore(rootReducer,
  compose(
      applyMiddleware(thunk.withExtraArgument({ 
        getFirebase, 
        getFirestore
      })),
      reduxFirestore(firebaseConfig),
      reactReduxFirebase(firebaseConfig)
  )
);

ReactDOM.render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();


but i am still getting this error
used same requiements as above

**Comment by MananDesai54** [comment]
it worked when i restared all thing , i don't no why 😂😂😂😂

**Comment by Amartya982** [comment]
> it worked when i restared all thing , i don't no why 😂😂😂😂

bro can u help me out..I am stuck ith same problem

**Comment by MananDesai54** [comment]
> > it worked when i restared all thing , i don't no why 😂😂😂😂
> 
> bro can u help me out..I am stuck ith same problem

Problem was due to versions, use the same old version of all firebase libraries, I am damn sure that you are using latest one that's why facing error
