### ISSUE TITLE
array removal still broken in 0.8.0, 0.7.0 did not fix it

### ISSUE THREAD

**Issue by vans163** [prescottprue/react-redux-firebase#719]
So the standard case firestoreConnect a doc and match on ID.  map it doc[0]. Now do a firestore.collection().doc().update() where the doc has 1 less element, firestore DB sees the correct array, redux seems to do a merge, and by the time render function is hit, it renders the collection with erroneous elements.

A workaround is to use storeAs, but it should work without it as well.

Ref: https://github.com/prescottprue/react-redux-firebase/issues/648 https://github.com/prescottprue/redux-firestore/pull/141  https://github.com/prescottprue/redux-firestore/issues/140

**Comment by prescottprue** [comment]
Reopened the redux-firestore issue. Going to close this one so we aren't tracking it in two places
