### ISSUE TITLE
Uncaught Error: Firebase database is required to create watchers

### ISSUE THREAD

**Issue by lidaof** [prescottprue/react-redux-firebase#723]
Related to #638 but I didn't find a solution.

version 2.2.6
my import:
```
import * as firebase from 'firebase/app';
import 'firebase/database';
import { firebaseReducer, reactReduxFirebase } from 'react-redux-firebase';
```
Error msg:
![image](https://user-images.githubusercontent.com/102806/60540319-7c110200-9cd4-11e9-9009-55e420695d74.png)

Can you please suggest a way to fix this? thank you.

**Comment by prescottprue** [comment]
The import should look like so:

```js
import firebase from 'firebase/app'
import 'firebase/auth'
import 'firebase/database'
```

Notice that there is no `*`

**Comment by prescottprue** [comment]
Going to close - Feel free to reach out if it doesn't fix the issue. Thanks for reporting!
