### ISSUE TITLE
firebase/firestoreConnect is not providing redux store

### ISSUE THREAD

**Issue by iamthefox** [prescottprue/react-redux-firebase#727]
**Do you want to request a *feature* or report a *bug*?**  
_bug_

**What is the current behavior?**
firebaseConnect and firestoreConnect no longer provide redux store as a second parameter. 

E.g. 

```js
compose(
  firebaseConnect((ownProps, store) => {
    // store is undefined for firebaseConnect and same as ownProps for firestoreConnect
    const state = store.getState() 
    // return subscriptions based on current redux state
  })
)
```

**What is the expected behavior?**

Should provide redux store.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Every version from `next` branch.

**Comment by iamthefox** [comment]
Ref.: 

This one is passing this.store which is undefined
https://github.com/prescottprue/react-redux-firebase/blob/next/src/firebaseConnect.js#L63

This one is passing props and prop :)
https://github.com/prescottprue/react-redux-firebase/blob/next/src/firebaseConnect.js#L45

**Comment by iamthefox** [comment]
I did a bit of experimenting on my custom fork and here what I came up with:

https://github.com/iamthefox/react-redux-firebase/blob/next-store/src/ReactReduxFirebaseProvider.js#L22

https://github.com/iamthefox/react-redux-firebase/blob/next-store/src/firebaseConnect.js#L45

It sort of fixes the problem I mentioned but I am not quite sure if thats the best way of doing it.

Or maybe it will make more sense to use something like this:
https://react-redux.js.org/using-react-redux/accessing-store#using-reactreduxcontext-directly

**Comment by prescottprue** [comment]
The first way you passed works - In general though I have suggested that folks actually place a `connect` before `firebaseConnect` so that you can pass state values as props and use those props in `firebaseConnect` instead of state. This is because there have been issues reported in the past with reloads not happening when state changed

**Comment by illuminist** [comment]
There’s a problem with passing entire store to a connector. If store state updated should a connector try to get a new query object every time even for minor store update? If not, it will cause update blocking where the store updated but it does not get the updated store until props has changed. Instead, selectively get necessary state using react-redux’s `connect` will lift almost all comparing old and new query object to just a a small amount of props comparing.

**Comment by iamthefox** [comment]
Make sense.

**Comment by jeloagnasin** [comment]
Is the redux store going to return in the `firebaseConnect` or `firestoreConnect` APIs? Or should we start refactoring our code to follow this pattern:

```diff
 compose(
+  connect(state => ({ id: get(state, 'auth.user.id', null) })),
   firebaseConnect((props, store) => {
-    const state = store.getState();
-    const id = get(state, 'auth.user.id', null);
+    const { id } = props;
     return [
       {
         path: 'notifications',
         queryParams: ['orderByChild=to', 'notParsed', `equalTo=${id}`],
       },
     ];
   }),
   connect(mapStateToProps),
 )(SampleComponent)
```

**Comment by illuminist** [comment]
I assume you meant "Is the redux store going to ***be passed into*** the functions". As for reason I and prescott mentioned before, it's going to be no.

**Comment by iamthefox** [comment]
Yeah, using connect makes much more sense in this case.

**Comment by jeloagnasin** [comment]
Okay, thanks for the clarification!

**Comment by iamthefox** [comment]
Closing this since original question was answered. Maybe worth putting a note in migration guide for people who still relied on store.
