### ISSUE TITLE
bug(HOCs): withFirestore not functioning as expected

### ISSUE THREAD

**Issue by botv** [prescottprue/react-redux-firebase#728]
**Do you want to request a *feature* or report a *bug*?**  
*bug*

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**What is the current behavior?**
Using `withFirestore` adds `firestore` to `props`, but the value is `"ReduxFirestore"` (just a string, no object). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
```javascript
export default compose(
  connect(mapStateToProps),
  withFirestore,
  withRouter
)(ExampleComponent);
```

**What is the expected behavior?**
`props.firestore` should be an object with functions such as `get`, `set`, and `push`.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
This problem occurs using `react-redux-firebase` version `^3.0.0-alpha.12`.

**Comment by prescottprue** [comment]
Hmm... weird... I will try to replicate. This is a big one thanks for reporting!

**Comment by botv** [comment]
@prescottprue I figured it out. I was missing a line in the configuration. 

```
const rrfProps = {
	firebase,
	config: {
		userProfile: 'users',
		useFirestoreForProfile: true
	},
	dispatch: store.dispatch,
	createFirestoreInstance // This line was missing
};
```

My IDE (WebStorm) suggests that the property is never used. My bad.

**Comment by prescottprue** [comment]
Ahh, gotcha - great to know. I'll look into having a better error message
