### ISSUE TITLE
Firebase Timestamp returns null

### ISSUE THREAD

**Issue by gopinav** [prescottprue/react-redux-firebase#731]
Bug

I am logging the profile object in the console and all server timestamps are returned as null.
![image](https://user-images.githubusercontent.com/13146172/61605673-3fe21900-ac64-11e9-9b9d-b66757d336b9.png)
![image](https://user-images.githubusercontent.com/13146172/61605750-92bbd080-ac64-11e9-9291-5807bf167b33.png)

Set a document field to Server TimeStamp value and read it in your component.

Should show the server time stamp

Seems to be happening in iOS devices

**Comment by prescottprue** [comment]
What did you use for the timestamp, `firebase.firestore.FieldValue.serverTimestamp()`?

Is this with react-native? Are you able to provide a repo/codebase where the error can be reproduced?

**Comment by gopinav** [comment]
Hi, yes this is with react native. I found out that this is a pods issue and not with this library. Will close the issue thanks!

**Comment by rusakovic** [comment]
@prescottprue 
Hello. I have the same problem.
```
useFirestoreConnect([
    {
      collection: 'chatMessages',
      doc: chatID,
      subcollections: [
        { collection: 'messages'}
      ],
      storeAs: 'fetchedMessages'
      }
  ])
```

![image](https://user-images.githubusercontent.com/17801144/77967341-9886ad00-72ed-11ea-9e39-1036a67e9d76.png)

But:
![image](https://user-images.githubusercontent.com/17801144/77967405-b48a4e80-72ed-11ea-9b97-c68bbb5c2cd1.png)

I tried:
```const firestore = getFirestore()
const firebase = getFirebase()

createdAt: firestore.Timestamp.now(),
createdAt: firebase.firestore.FieldValue.serverTimestamp()

Seems, that we have async setting of timestamp on firebase, right?
Maybe you know how to fix it? 
Thank you in advance.

**Comment by prescottprue** [comment]
@rusakovic That is the expected functionality with Firestore which comes directly from the firebase SDK - the value is null initially on the client since it is a server timestamp, the value is only set once it is on the server. More about this can be found [in this medium post about serverTimestamp](https://medium.com/@CodingDoug/the-secrets-of-firestore-fieldvalue-servertimestamp-revealed-29dd7a38a82b)

If you believe this is incorrect, please open a new issue with steps to reproduce what you are seeing

**Comment by rusakovic** [comment]
@prescottprue 
Thank you. Sure. I absolutely agree that is normal for firebase SDK.
But how to add this logic 
```
ref.onSnapshot(snap => {
    const data = snap.data()
    if (data) {
        if (!data.createdAt && snap.metadata.hasPendingWrites) {
            // we don't have a value for createdAt yet
            const ts = firebase.firestore.Timestamp.now()
            console.log(`timestamp: ${ts} (estimated)`)
        }
    }
    else {
        // now we have the final timestamp value
        console.log(`timestamp: ${data.createdAt} (actual)`)
    }
})
```
to 
`useFirestoreConnect` listener?

I think this info will be very helpful. And it can be added to docs.
I can help with it.
