### ISSUE TITLE
bug(types): firebaseConnect/firestoreConnect type definitions are missing React.FunctionalComponent

### ISSUE THREAD

**Issue by lanice** [prescottprue/react-redux-firebase#736]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

When using `firestoreConnect` with a functional component, the Typescript compiler throws an error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

```
import React from 'react';
import { firestoreConnect } from 'react-redux-firebase';

const SomeFunctionalComponent = (props: any) => {
  return <div />;
};

export default firestoreConnect()(SomeFunctionalComponent);
```
Typescript error for the last line:
```
Argument of type '(props: any) => Element' is not assignable to parameter of type 'Component<WithFirestoreProps, {}, any>'.
  Type '(props: any) => Element' is missing the following properties from type 'Component<WithFirestoreProps, {}, any>': context, setState, forceUpdate, render, and 3 more.ts(2345)
```

**What is the expected behavior?**

`firestoreConnect` should accept functional components (turning off type checking for that specific line makes it work as expected).

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

- react@16.8.6 
- react-redux@7.1.0 
- react-redux-firebase@3.0.0-alpha.13
- typescript@3.5.3

**Comment by prescottprue** [comment]
Fix released in [v3.0.0-alpha.14](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.0.0-alpha.14) thanks for the PR!
