### ISSUE TITLE
bug: Redundant field is added after deleting an item from firestore collection

### ISSUE THREAD

**Issue by Staxxx6** [prescottprue/react-redux-firebase#751]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When page is loaded, I get exptected data which looks like this:

![Screenshot (43)_LI](https://user-images.githubusercontent.com/47669215/62884484-5816f680-bd3f-11e9-8899-563dfbe1d35e.jpg)

However, after deleting an item, redundant `todayFeed` is embedded. With every deleted item, `todayFeed` field is added again(this field ins't created in firestore cllection and exists only in redux store before the page is refreshed ). After the store is updated, the length of the array of actual items is the same and it doesn't look like an item was deleted(even though an item was deleted from firestore collection and after refreshing the page data looks like on the first screenshot but with one less item in the array, as expected)

![Screenshot (44)_LI](https://user-images.githubusercontent.com/47669215/62884676-ccea3080-bd3f-11e9-886e-f2833fd59f1d.jpg)

User dispatches an action(redux) to delete an item in firestore collection
```javascript
this.props.deleteItem(item);
```
After that, i'm using `redux-thunk` in middleware with extra arguments(`getFirebase`, `getFirestore`) to have access to firebase and firestore in action creator. 

```javascript
let store = createStore(reducer,
  compose(
    applyMiddleware(thunk.withExtraArgument({ getFirebase, getFirestore })),
    reduxFirestore(firebaseConfig),
    reactReduxFirebase(firebaseConfig, { useFirestoreForProfile: true, userProfile: 'users', attachAuthIsReady: true })
  )
);
```
Action cretor: 
```javascript
import { getFirestore } from "redux-firestore";

export const deleteItem = itemToDelete => {
  return (dispatch, getState, { getFirebase, getFirestore }) => {
    const firestore = getFirestore();
    const authorId = getState().firebase.auth.uid;
    const userRef = firestore.collection("users").doc(authorId);

    userRef
      .collection("todayFeed")
      .doc(itemToDelete.uid)
      .delete()
      .then(res => {
        dispatch({ type: "CHANGE_ITEM_STATE_SUCCESS", res });
      })
      .catch(err => {
        dispatch({ type: "CHANGE_ITEM_STATE_ERROR", err });
      });
  };
};
```

I use `react-redux-firebase` to get the data in my view file.

```javascript
let mapStateToProps = state => {  
  return {
    auth: state.firebase.auth,
    items:
      state.firestore.ordered.users &&
      state.firestore.ordered.users.length &&
      state.firestore.ordered.users[0].todayFeed
  };
};

export default compose(
  connect(mapStateToProps),
  firestoreConnect(props => {
    return [
      {
        collection: "users",
        doc: props.auth.uid,
        subcollections: [
          { collection: "todayFeed", orderBy: ["pubDate", "desc"] }
        ]
      }
    ];
  })
)(Dashboard);
```

**What is the expected behavior?**
Get the data in the expected format(without embedding redundant `todayFeed` field) after deleting an item.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
OS: Windows 10
Dependencies: 
```json
"dependencies": {
    "cors": "^2.8.5",
    "firebase": "^5.5.5",
    "googleapis": "^42.0.0",
    "moment": "^2.24.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-firebaseui": "^3.1.2",
    "react-redux": "^5.0.7",
    "react-redux-firebase": "^2.3.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.0.5",
    "react-spring": "^5.1.3",
    "react-with-gesture": "^1.0.10",
    "redux": "^4.0.1",
    "redux-firestore": "^0.5.8",
    "redux-thunk": "^2.3.0",
    "scriptjs": "^2.5.9",
    "styled-components": "^3.2.6"
  },
```

**Comment by jjang16** [comment]
Try updating redux-firestore to 0.9.0 (current latest).

**Comment by prescottprue** [comment]
Going to close for now as I believe this is fixed by newer versions of redux-firestore. @Staxxx6 try updating to `0.9.0` as mentioned - if you are still experiencing the problem, we can reopen. Thanks for reporting!

**Comment by daiky00** [comment]
@prescottprue isn't `getFirebase, getFirestore` no longer available in V3? if so whats alternative how do we use it with `redux-thunk` can you props an example please?
for this part in specific 
```
const middlewares = [
  reduxThunk.withExtraArgument(getFirebase)
]```

**Comment by prescottprue** [comment]
It is available, it was added back to the API
