### ISSUE TITLE
question(core): issue building for production with react-boilerplate

### ISSUE THREAD

**Issue by lucasharada** [prescottprue/react-redux-firebase#752]
**Do you want to request a *feature* or report a *bug*?**  
Bug.

**What is the current behavior?**
Component following the Load Data example works locally, but doesn't work when building for production. On production, when the component is mounted, the following exception is thrown:

> @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'length' of undefined

For reference: 
```
export default compose(
  firebaseConnect([
    'todos' // { path: '/todos' } // object notation
  ]),
  connect(state => ({
    todos: state.firebase.data.todos
    // profile: state.firebase.profile // load profile
  }))
)(Todos)
``` 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

1. Create a project using React Boilerplate (https://github.com/react-boilerplate/react-boilerplate)
2. Include the related code
3. Build for production

**What is the expected behavior?**
Mount the component and receive the data as props, without any Firebase exception thrown.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

OS: MacOS 10.14.6
Browsers: Chrome and Firefox

react@16.9.0
react-redux@5.1.0
react-redux-firebase@2.2.1

**Comment by prescottprue** [comment]
I am not able to reproduce this issue. Are you still experiencing it on the v3 version?

**Comment by prescottprue** [comment]
Going to close since the issue was not reproducible
