### ISSUE TITLE
cannot read property dispatch of null

### ISSUE THREAD

**Issue by AOUNT** [prescottprue/react-redux-firebase#754]
**Do you want to request a *feature* or report a *bug*?**  

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

Bug

**What is the current behavior?**

After adding the firestoreConnect argument I'm receiving the error. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Hello,

Sorry to ask but I'm facing an issue when migrating. I'm receiving this error:
![image](https://user-images.githubusercontent.com/27626560/63642107-5d1e6300-c6ba-11e9-9f6a-cba6973bea90.png)

I ensured to use the correct versions:
      "react": "^16.9.0",
     "react-redux": "^7.1.0",
     "react-redux-firebase": "^3.0.0-alpha.16",

Before using firestoreConnect, when logging state I see this:

<img width="663" alt="Capture d’écran 2019-08-24 à 22 01 17" src="https://user-images.githubusercontent.com/27626560/63642120-c43c1780-c6ba-11e9-8373-063b2c2d8ac3.png">

I'm using a simple component:

`const mapStateTopProps = state => {
    console.log(state);
    return {
        orders :  state.firestore.data.orders
    };
}`

`export default compose(
    firestoreConnect([
        { collection: 'orders' }
      ]), 
    connect(mapStateTopProps)
  )(FoodBuilder) `

I got rid of old getFirestore and getFirebase. 

my index.js looks like this:

![Capture d’écran 2019-08-24 à 22 07 59](https://user-images.githubusercontent.com/27626560/63642170-bf2b9800-c6bb-11e9-8d02-c731af9322f9.png)

it's been 2 days i'm trying to debug :(

thank you in advance ! 

**What is the expected behavior?**

Connecting correctly to firestore. 

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

**Comment by prescottprue** [comment]
How do your imports looks? Are you sure that you also imported firestore? It looks like `createFirestoreInstance` is being pointed to by your linter, is that because it isn't imported? That will be required in order to setup the `ReduxFirestoreProvider` internally.

Something else to note is that you may want to be using `redux-firestore@alpha` (i.e. the v1.*.* pre-release series) to have things correctly work with new react-redux

**Comment by jjang16** [comment]
I was having a same problem.

The official v3.0.0 documentation has an example snippet which imports with
`
import withFirebase from 'react-redux-firebase/lib/withFirebase'
`

When I changed to this
`
import { withFirebase } from 'react-redux-firebase'
`

The problem disappeared, firebase being connected correctly.

So I guess it's a documentation error :)

**Comment by AOUNT** [comment]
Hello @prescottprue,

Thank for getting back.

Here are my imports:

import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import { createStore, compose, applyMiddleware } from 'redux';
import rootReducer from './store/reducers/rootReducer';
import { Provider } from 'react-redux';
import thunk from 'redux-thunk'

import { reduxFirestore, createFirestoreInstance } from 'redux-firestore';
import fbConfig from './config/fbConfig';
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
import 'firebase/firestore';
import ReactReduxFirebaseProvider from 'react-redux-firebase/lib/ReactReduxFirebaseProvider';

I tried with contextType (without firestoreConnect) and it's working:

    static contextType = ReactReduxContext; (we can main be update the documentation because it's the old way declaring contextTypes)
    
    componentDidMount () {
        const orderId = localStorage.getItem('orderId');
        const { firestore } = this.context.store
        firestore.get({ 
            collection: 'orders',
            doc: docId
        });
      }

Thank you

**Comment by prescottprue** [comment]
As @jjang16 mentioned, I believe it is due to the import of `import ReactReduxFirebaseProvider from 'react-redux-firebase/lib/ReactReduxFirebaseProvider';` which could be `import { ReactReduxFirebaseProvider } from 'react-redux-firebase'.

Going to make sure the docs are up to date on that front

**Comment by nithish1245** [comment]
https://react-redux-firebase.com/docs/firestore

read this , may be helpful
