### ISSUE TITLE
(Question) Are all the docs on the website updated for v3?

### ISSUE THREAD

**Issue by zaptrem** [prescottprue/react-redux-firebase#760]
I’m planning to use this library on a React-Redux/Expo project I’m working on (I’m new to all of these). Are the tutorials and examples in the v3 section of http://docs.react-redux-firebase.com/ updated yet? I don’t want to use v2 just to have to rebuild everything when it’s no longer supported in a short while. Instability is okay as I’m not planning on releasing the app for a while.

**Comment by prescottprue** [comment]
The [v3.0.0 docs](http://docs.react-redux-firebase.com/history/v3.0.0/) are up to date, if you find anything that doesn't work as documented then please feel free to open an issue.

That said, I believe a few of [the complete examples](https://github.com/prescottprue/react-redux-firebase/tree/next/examples/complete) are not yet updated but should be shortly.

I would definitely go with the v3.0.0 syntax since it is soon to be released to latest

**Comment by zaptrem** [comment]
The complete examples are totally separate from the docs right? E.g., the tutorials aren’t made out of the complete examples.

**Comment by prescottprue** [comment]
Correct they are separate - I just like to note that since some folks have also asked if/when those are being updated.

**Comment by zaptrem** [comment]
Alright, final question from an inexperienced person: will I need to change anything (e.g., in my packages file) when v3 becomes the main release?

**Comment by prescottprue** [comment]
You will go from wanting to change your package file to point to a version on latest instead of just using `next` (which most folks stick to while things are still in pre-release):

```diff
-- "react-redux-firebase": "next",
++ "react-redux-firebase": "^3.0.0",
```

To install while it is in pre-release you can use `npm i --save react-redux-firebase@next`

**Comment by zaptrem** [comment]
Thanks. If I have further questions (e.g., looks like the method of integrating Firestore with my Redux state is different from the normal middlewear combination function now) is there a better place to ask than here?

**Comment by prescottprue** [comment]
[The gitter channel](https://gitter.im/redux-firebase/Lobby) is where most back and forth chat goes. You can also feel free to send me a DM
