### ISSUE TITLE
bug(types): uploadFile() return type is incorrect

### ISSUE THREAD

**Issue by fuhrmannb** [prescottprue/react-redux-firebase#762]
**Do you want to request a *feature* or report a *bug*?**  

bug

**What is the current behavior?**

To upload a file on Firebase and get its download URL, the documentation suggests to write something like this:

```typescript
const uploadedFile = await props.firebase.uploadFile(path, imgFile)
const downloadURL = await uploadedFile.uploadTaskSnapshot.ref.getDownloadURL()
```

However, Typescript raised the following error:

```
Property 'uploadTaskSnapshot' does not exist on type 'UploadTaskSnapshot'
```

The `uploadFile()` Typescript return type is `Promise<StorageTypes.UploadTaskSnapshot>` but `UploadTaskSnapshot` does not have this field.

The [relative source code](https://github.com/prescottprue/react-redux-firebase/blob/60b5e868d780caa77fcb8a5128f2d727ebaedcac/src/actions/storage.js#L77) show that the object returned by the Promise does not fit Typescript type (with also a strange old `uploadTaskSnaphot` field) but fit more with the documentation.

**What is the expected behavior?**

Typescript type must be correct, or function must return the right type and documentation updated with the right type.

I can make a PR for the right Typescript type if we decide to make the change here.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

* react-redux-firebase@3.0.0-beta.2
* typescript@3.5.3

**Comment by prescottprue** [comment]
Feel free to make a PR with the changes to the types, but if not I will try to get to is soon. Thanks for reporting!

**Comment by prescottprue** [comment]
This was release in v3.0.0-beta.3 to the `next` tag. Thanks for reporting
