### ISSUE TITLE
react-redux 5 componentWillUpdate

### ISSUE THREAD

**Issue by rtessler** [prescottprue/react-redux-firebase#764]
react-redux 5.1.1 is using componentWillUpdate which wont be around in react 17. It seems like the current version of react-redux-firebase needs react-redux 5. Do I need the @next version or can I just wait for the next official release of react-redux-firebase. At the moment just doing a npm update in my project doesnt make the warning go away. I need to update react-redux but Im worried react-redux-firebase will break

**Comment by prescottprue** [comment]
Yes, for newer versions of react-redux, you will need to use the `next` version of react-redux-firebase. It is a pretty major shift in the internals and how things are set up for react-redux-firebase, so it has been on `next` while some of the bugs are ironed out.

Keep an eye on the the `next` tag/branch for updates, but I'm hoping to have the new version out in the next couple weeks

**Comment by prescottprue** [comment]
This has been released to latest. Please open a new issue if things are not working as you expect.

Thanks for reporting 😄
