### ISSUE TITLE
Listeners keys is not the same on reactjs and react native ? 

### ISSUE THREAD

**Issue by JCBsystem** [prescottprue/react-redux-firebase#765]
Is it a bug or am i doing something wrong ? 

exact the same code running from react js and react native 
generate diffrent keys 

console.log('state.firestore.listeners.allIds', state.firestore.listeners.allIds)

React js = 
"projects/cjoh61emj000002s69x2m8sid"
"projects/cjoh61emj000002s69x2m8sid/weekview/2019-38_2019-38"
"projects/cjoh61emj000002s69x2m8sid/shiftMetaData/2019-38_2019-38"

this uses the path as name

----------------------------------------------------

React Native = 
"project"
"weekview_2019-38_2019-38"
"weekview_2019-38_2019-38_meta"

this uses the storeAs as name

both are using the same libs 
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-ga": "^2.6.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0",
    "react-redux": "^5.0.7",
    "react-redux-firebase": "^2.2.5",
    "react-redux-toastr": "^7.4.0",
    "redux": "^4.0.0",
    "redux-auth-wrapper": "^2.0.3",
    "redux-devtools-extension": "^2.13.5",
    "redux-firestore": "^0.7.0",
    "redux-form": "^7.4.2",
    "redux-thunk": "^2.3.0",

**Comment by prescottprue** [comment]
No idea what this would be off the top of my head. Could you provider your listener settings just so that I can be sure I am replicating the issue?

**Comment by JCBsystem** [comment]
It looks like this
       
   var doc = {
                    collection: "projects",
                    doc: projectKey,
                    subcollections: [{
                        collection: "weekview",
                        doc: dateKey,
                    }],
                    storeAs: listnerKey
                }

                context.store.firestore.onSnapshot(doc);

**Comment by JCBsystem** [comment]
@prescottprue 
sorry it was a user error on my side :(
