### ISSUE TITLE
Page doesn't update after Firestore data appears in Redux store

### ISSUE THREAD

**Issue by jarodpeachey** [prescottprue/react-redux-firebase#767]
**Do you want to request a *feature* or report a *bug*?**  
A bug
(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**What is the current behavior?**
I use firestoreConnect and connect to grab a single doc from a collection in firestore. The data gets updated in the Redux store, but my component does not update. Only after I click the back button, and then go to the client details page, does the client show. However, than it shows two clients: the first one that would not update the page, and the new one.

This is the file I connect to redux and firestore in:

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { compose } from 'redux';
import { firestoreConnect } from 'react-redux-firebase';
import { LinearProgress } from '@material-ui/core';

class ClientDetails extends Component {
  static propTypes = {

  };

  constructor (props) {
    super(props);
    this.state = {};
  }

  componentDidMount () {

  }

  shouldComponentUpdate (nextProps) {
    if (this.props.client !== nextProps.client && this.props.client) {
      return true;
    }
    return false;
  }

  render () {
    console.log(this.props);
    const { client } = this.props;
    console.log('Client: ', client);

    return (
      <>
        {client ? (
          <h1>Client Details</h1>
        ) : (
          <>
            {!client ? (
              <>
                <div className="center-text mb-md">
                  <h3>Loading client details...</h3>
                </div>
                <LinearProgress />
              </>
            ) : (
              <div className="center-text">
                <h3>Sorry, there was an error fetching your clients.</h3>
              </div>
            )}
          </>
        )}
      </>
    );
  }
}

export default compose(
  firestoreConnect(props => [
    { collection: 'clients', storeAs: 'client', doc: props.match.params.id },
  ]),
  connect(({ firestore: { data } }, props) => ({
    client: data.client,
  })),
)(ClientDetails);

```

Here's a GIF of the process: You can see that the data is added to Firestore, but the page is not updated.

![redux_firestore_issue](https://user-images.githubusercontent.com/46693952/66008206-62be5400-e483-11e9-87d7-4eeeb2f49df4.gif)

**What is the expected behavior?**
I expect the page to update once the data appears in the Redux store.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Here are the versions: 
```
"react-redux": "^7.1.0",
"react-redux-firebase": "^3.0.0-beta.2",
"firebase": "^7.0.0-0",
"redux": "^4.0.4",
"redux-devtools-extension": "^2.13.8",
"redux-firestore": "^0.9.0",
```

**Comment by prescottprue** [comment]
storeAs was originally meant to work for storing lists at a different location - it appears that is what is happening in the gif you posted of it going into redux state.

It also looks like your state connection is expecting the client object to be at that location of the redux store, not an array which contains the client object.

You might want to try not using store as and just looking up the single item by id within the `data` section of state (i.e. `data.clients[props.match.params.id]`)

**Comment by illuminist** [comment]
```js
  shouldComponentUpdate (nextProps) {
    if (this.props.client !== nextProps.client && this.props.client) {
      return true;
    }
    return false;
  }
```
`this.props.client` initially is `undefined`. When new props come, `&& this.props.client` conditioned as `undefined` will prevent component update no matter what. You probably should avoid using `shouldComponentUpdate` entirely if you don't know what are you doing.

**Comment by prescottprue** [comment]
Going to close since I believe this is due to the `shouldComponentUpdate` as @illuminist pointed out. If you are still having the issue, please provide an example code base where the issue can be reproduced and we can reopen. Thanks for reporting!
