### ISSUE TITLE
enableRedirectHandling option ignored?

### ISSUE THREAD

**Issue by miickel** [prescottprue/react-redux-firebase#77]
Hi! For a project I'm working on I would like to manually handle the auth state and profile creation/updates. I have therefore tried using the config below to disable most of these features.

However, when using this configuration the middleware still seem to interfere with my own getRedirectResult handler. When plugging in this middleware the result to my getRedirectResult handler is always `{ user: null }`, but when removing the middleware it works as expected.

I suspect it is because somehow the `enableRedirectHandling`-option is ignored, but it's only my best guess.

Any ideas?

```javascript
const reduxFirebaseConfig = {
  updateProfileOnLogin: false,
  enableRedirectHandling: false,
  autoPopulateProfile: false,
  setProfilePopulateResults: false,
  userProfile: null,
  enableLogging: false,
}

const createStoreWithFirebase = compose(
  reactReduxFirebase(
    config.firebase.config,
    reduxFirebaseConfig
  ),
)(createStore)

export default createStoreWithFirebase(
  rootReducer,
  applyMiddleware(epicMiddleware),
)
```

**Comment by prescottprue** [comment]
`enableRedirectHandling: false` just disables adding of the listener for redirect handling, and should be working as intended (going to try to replicate now to verify).

As for getting `user: null` back from the redirect result, we might have to enable logging to see what is coming back from the Firebase library. Will also try to replicate this to verify. If you have a repo you can share, feel free to direct message me over [gitter](https://gitter.im/redux-firebase/Lobby).

**Comment by miickel** [comment]
I'm not able to share this repo, but I might be able to create a smaller one to reproduce.

The reason for not needing the profileDecorator is because we've solved this using a combination of redux-observable and cloud functions.

**Comment by prescottprue** [comment]
@miickel Please to try to create a smaller example to reproduce the error you are seeing.

**Comment by prescottprue** [comment]
@miickel Did you get a chance to make a small reproduction example?

**Comment by miickel** [comment]
@prescottprue no sorry, it slipped my mind. We've decided to not use react-redux-firebase for now. I'll maybe take a stab at it in the future, but will close the issue for now. thanks 👍
