### ISSUE TITLE
feat(example): Examples of testing components using RRF Hooks? (Jest/React-Testing-Library etc.)

### ISSUE THREAD

**Issue by dsgriffin** [prescottprue/react-redux-firebase#788]
Hi all, wondering if there are any examples of how to test components/providers that use React Redux Firebase hooks? Specifically using Jest/React Testing Library but other libraries are welcome. Thanks!

**Comment by harish-aka-shivi** [comment]
Looking into it. 🙂

**Comment by prescottprue** [comment]
Thanks @harish-aka-shivi!
