### ISSUE TITLE
Cannot login with Google, only in version 3.0.4

### ISSUE THREAD

**Issue by MichalKalita** [prescottprue/react-redux-firebase#789]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

```
await firebase.login({ provider: "google", type: "popup", scopes: [] });
```

Throws exception 
```
TypeError: createUserProfile(...).then is not a function
    at http://localhost:3000/static/js/0.chunk.js:386008:8
    at e.g (http://localhost:3000/static/js/0.chunk.js:6040:21)
    at kc (http://localhost:3000/static/js/0.chunk.js:6132:19)
    at gc (http://localhost:3000/static/js/0.chunk.js:6123:28)
    at B.push../node_modules/@firebase/auth/dist/auth.esm.js.k.Zb (http://localhost:3000/static/js/0.chunk.js:6116:32)
    at Qb (http://localhost:3000/static/js/0.chunk.js:5879:13)
```

Workaround is downgrade to 3.0.3

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**What is the expected behavior?**
It should work like 3.0.3

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

only version 3.0.4

**Comment by prescottprue** [comment]
Thanks for pointing this out! This was a silly mistake from switching back from async/await in v3.0.4 - I updated the tests to confirm that a promise is always being returned from `createUserProfile`. Fix went out in [v3.0.5 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.0.5)
