### ISSUE TITLE
feat(example): redux saga support and implementation

### ISSUE THREAD

**Issue by joeyhipolito** [prescottprue/react-redux-firebase#79]
I can see that you support thunks and observables, how about redux saga?

**Comment by anthonychung14** [comment]
@prescottprue any idea on the scope of work necessary to make this supported? I moved from observables into sagas (since I know sagas better) and would like to stay with this lib if possible

**Comment by prescottprue** [comment]
Docs updated with [a simple redux-saga recipe](http://react-redux-firebase.com/docs/recipes/redux-saga.html). Always open to pull requests if there are any ideas.
