### ISSUE TITLE
fix(examples/docs): Firestore

### ISSUE THREAD

**Issue by doublejosh** [prescottprue/react-redux-firebase#791]
The "complete" example for Firestore is fairly broken. This includes various errors when trying to run the example after adding your own config.

Additionally, the docs snippets and examples around Firestore are inaccurate.

Here's my best attempt at listing issues...

**Example:**
1. Static file locations
1. Config variable passing
1. Redux Thunk dependency
1. Data structure docs (to setup the Firestore collection)
1. Failed `todos` variable with `useSelector`
1. Failed handling for empty collection

**Docs:**
1. Missing `mapStateToProps`

**Comment by prescottprue** [comment]
Thanks for reporting, I'll look into it. It has been a while since I did an update of that example.

If you are looking for a way to start a redux-firestore based project in the meantime, checkout [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase). This is actually what I will use to regenerate this example

**Comment by prescottprue** [comment]
Working on updating, but wanted to note for each point:
1. - 3. (being updated)
4. By "undocumented" do you mean it should be listed somewhere that the todo contains `text` and `done`?
5. `todos` seems to be working just fine?
6. Handling of the empty collection is being done with `isEmpty` (pictured below)
7. Where would there be a `mapStateToProps` in this case? That is for the `connect` HOC? The `useSelector` hook is taking care of connecting to redux state

![image](https://user-images.githubusercontent.com/2992224/68829649-5d098000-0677-11ea-8e38-2feeadd467b2.png)

**Comment by doublejosh** [comment]
Thank you.

I updated the description to call-out that the missing "Missing `mapStateToProps`" was actually in the docs rather than the functional example. This is regarding the `FirestoreConnect` technique. As a noob, this threw me for a loop... but might be more of an assumption for an expert.

**Comment by doublejosh** [comment]
**4. "undocumented"**
It's required to setup a collection before using the app, but it's tough to figure out what it needs to look like just by looking through code alone.

It's possible other trouble was purely due to the above issue.

**Comment by harish-aka-shivi** [comment]
I have been working on the firestore example and able to get it working. Can i create a PR for it?

**Comment by prescottprue** [comment]
Merged changes in [this PR](https://github.com/prescottprue/react-redux-firebase/pull/820) which fixes a number of issues.

@doublejosh I added a [section to the README of the example](https://github.com/prescottprue/react-redux-firebase/pull/820/files#diff-6c723d76e71cf2cdfd6093d20f54fdd4R11-R27) to clarify the format of the todo and where they are loaded from. You can also create a new todo through the UI after running `yarn start`.

Going to close for now, but reach out if you think anything else is unclear or if the example isn't working as expected.
