### ISSUE TITLE
Can't import modules reduxReactFirebase

### ISSUE THREAD

**Issue by zgunz42** [prescottprue/react-redux-firebase#795]
Im using typescript and use react-native-firebase at first starting app, ITS crash with error' like this
![Screenshot_2019-12-01-10-57-54-82](https://user-images.githubusercontent.com/11344981/69908970-3c3e7a00-142e-11ea-938b-d9d1f2a41bf0.png)

**Comment by prescottprue** [comment]
The store enhancer (reactReduxFirebase function) is no longer part of the API in v3. This is due to the usage of react context. There is more information available in the [v3 migration guide](http://react-redux-firebase.com/docs/v3-migration-guide.html).
