### ISSUE TITLE
TypeError: Cannot read property 'enableLogging' of undefined

### ISSUE THREAD

**Issue by kudenv** [prescottprue/react-redux-firebase#797]
** current behavior?**
while trying to initialize firebase app, base with React App & Redux  the process is throwing Error 
TypeError: Cannot read property 'enableLogging' of undefined
here: 
createFirebaseInstance.js:23 Uncaught TypeError: Cannot read property 'enableLogging' of undefined

configuration and implementation have been taken from https://react-redux-firebase.com/docs/getting_started.html

here ReactReduxFirebaseProvider , while firebase initializing, one of the config property is enableLogging: false, has been went, but while runs the application we have cal this method more than 1 time, and after we have another call of this method the configuration property is released and due to this on next call (2)
const extendedFirebaseInstance = React.useMemo(
    () => {
      const extendedFirebaseInstance = createFirebaseInstance(
        firebase,
        config,
        dispatch
      )
      if (initializeAuth) {
        extendedFirebaseInstance.initializeAuth()
      }
      return extendedFirebaseInstance
    },
    [firebase, config, dispatch]

call (2)
createFirebaseInstance : 
// here i got configs undefined TypeError: Cannot read property 'enableLogging' of undefined
if (
    configs.enableLogging &&
    firebase.database &&
    typeof firebase.database.enableLogging === 'function'
  ) {
    firebase.database.enableLogging(configs.enableLogging)
  }

app file : Compose all to one file that shoul make sance to what i did to get this exaption 
import React from 'react';
import ReactDOM from "react-dom";
import App from "./app/App";
import {Provider} from "react-redux";
import {applyMiddleware, compose, createStore} from "redux";
import rootReducer from "./reducers";
import logger from "redux-logger";
import thunk from "redux-thunk";

/* Firebase HOC component */
import { ReactReduxFirebaseProvider, getFirebase  } from "react-redux-firebase";
import firebase from 'firebase/app';
import 'firebase/auth';
const firebaseConfig = {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: ""
  };

firebase.initializeApp(firebaseConfig);
// db.enableLogging(false, false);

const middlewares = [
    thunk.withExtraArgument({getFirebase})
];
// Create store with reducers and initial state
const createStoreWithMiddleware = compose(
        applyMiddleware(...middlewares),
        typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ? () => window.__REDUX_DEVTOOLS_EXTENSION__ : f => f
)(createStore)
const store = createStoreWithMiddleware(rootReducer);

const ffConfig = {
    userProfile: 'users',
    useFirestoreForProfile: false, 
    enableLogging: false
}

const rrfProps = {
    firebase,
    config: ffConfig,
    dispatch: store.dispatch,
    initializeAuth: false
  }

const Main = () => (
    <Provider store={store}>
        <ReactReduxFirebaseProvider {...rrfProps} />
            <App />       
         <ReactReduxFirebaseProvider />   
    </Provider>
);

ReactDOM.render(<Main/>, document.getElementById('root'));
**What is the expected behavior?**
I am expecting, to load app properly and get firebase instance obtain properly

**Which versions of dependencies, browser Chrome, latest version, **
node version : 10.9.0, npm 6.2.0
dependencies list
"dependencies": {
    "axios": "^0.19.0",
    "firebase": "^7.2.0",
    "http-proxy-middleware": "^0.20.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-redux-firebase": "7.5.0",
    "react-router-dom": "^5.1.2",
    "react-router-redux": "^4.0.8",
    "react-scripts": "^3.2.0",
    "redux": "^4.0.4",
    "redux-form": "^8.2.6",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "reduxsauce": "^1.1.1",
    "semantic-ui-react": "^0.88.1"

this config app file can be used to reproduce the steps of how I getting this exception

**Comment by prescottprue** [comment]
Weird... It seems like the check for firebase.database existing first should catch this, I will try to replicate.

In the meantime, did you try adding `import 'firebase/database';`? Not ideal if you aren't using database, but it should fix any errors due to not importing it.

**Comment by kudenv** [comment]
hi, Yes I am trying to use your solution, but it brings me to another issue where I got what app begin been initialized twice! What lead me to make validation if firebase.app.lenght() -> het instance if not then Initialize
