### ISSUE TITLE
providerData is written as an Array with one empty Object in Firestore

### ISSUE THREAD

**Issue by lucasharada** [prescottprue/react-redux-firebase#799]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`providerData` gets written as an Array with one empty Object. My current `profileFactory` can be seen below (I saw that Firestore has some issues on storing custom Objects, that's why I parsed after stringifying the `providerData` Object):

```
profileFactory: (data, profile) => {
  const helperProviderData = (profile.providerData || data.providerData || data.user.providerData);
  const providerData = JSON.parse(JSON.stringify(helperProviderData));
  return ({
    ...profile,
    role: 'user',
    providerData,
    test: providerData[0],
  });
}
```

I just added this `test` field to see if the problem was writing the object itself or writing the object inside the Array and the result is that `test` is correctly stored, while `providerData` still has only one empty Object inside.

**What is the expected behavior?**

Have Firestore properly storing `providerData`.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

This is the first time I'm trying to use Firestore. Firebase packages were added separately, but points to `firebase@7.4.0`.

Package | Version
--- | ---
@firebase/app | 0.4.24
@firebase/auth | 0.13.0
@firebase/firestore | 1.7.1
react-redux-firebase | ^3.0.5
redux-firestore | ^0.11.0

**Comment by prescottprue** [comment]
Did you try adding logic to your profileFactory to confirm that there are values within the providerData before writing it? Something like the following:

```js
profileFactory: (data, profile) => {
  const helperProviderData = (profile.providerData || data.providerData || data.user.providerData);
  const newProfile = {
  ...profile,
    role: 'user',
  }
  const providerData = JSON.parse(JSON.stringify(helperProviderData));
  if (Object.keys(providerData).length) {
    newProfile.providerData = providerData
  }
  return newProfile;
}
```

Something else to note: As mentioned [in the roles recipes docs](http://react-redux-firebase.com/docs/recipes/roles.html#cloud-function), it is probably best to handle setting role through a cloud function so that you can have your database rules set to not let user's change roles.

**Comment by lucasharada** [comment]
@prescottprue Since the `test` field is filled correctly, I guess we can assume the `providerData` has, at least, one element which is not empty. If I'm mistaken on this, I'll reply once again tomorrow morning, when I have the time to test again.

Thanks for pointing out the roles tip. Since the app doesn't have any dangerous `admin` related data, it wasn't our main concern.

**Comment by lucasharada** [comment]
@prescottprue You were right! I'm not sure why, but creating the object the previous way was not storing the inner object. Thanks again!

**Comment by lucasharada** [comment]
@prescottprue You were right. I'm not sure, but `newProfile` already has an empty object. This issue is not related to Firestore itself. Closing it now.
