### ISSUE TITLE
fix(docs): clarify usage of resetPassword

### ISSUE THREAD

**Issue by magrinj** [prescottprue/react-redux-firebase#803]
Hello,

When I want to implement the resetPassword on my app, I faced against a documentation error.
I'll explain why:
On this link http://react-redux-firebase.com/docs/auth.html#resetpasswordcredentials, the documentation talk about a credential object, with in example this object:
```javascript
props.firebase.resetPassword({
  email: 'test@test.com',
  password: 'testest1',
  username: 'tester'
})
```
So, I was a little bit disappointed, because if we follow the documentation the user need to specify his password, if this one want a reset link...

I take a look into firebase documentation and find that, firebase only want the email, so I read the code about this feature in  `react-redux-firebase` and find on this line that only email need to be provided in the credential object.
https://github.com/prescottprue/react-redux-firebase/blob/5fc4de5516dc3468adbe9d57ea0f917e840ff869/src/createFirebaseInstance.js#L433

I try to execute this function with an object, but apparently the action itself just want an email:
https://github.com/prescottprue/react-redux-firebase/blob/51efdc7fd96e55d333a7c18f7336047281b7e1e3/src/actions/auth.js#L658

If I use resetPassword directly with an email, everything is works fine, but that need to be clarified in the documentations.

What's the behaviour should be ? Just the email string or a credential object in param ? I can make a PR to correct the documentation and this problem when I've my answer

**Comment by prescottprue** [comment]
Hmm, yeah it seems like the docs may just be incorrect. I believe the original intention was to just pass the email as a string, so feel free to make a PR. Thanks for reporting!

**Comment by magrinj** [comment]
@prescottprue You can find the PR just above !
