### ISSUE TITLE
bug(docs): useFirestoreConnect Link in docs broken

### ISSUE THREAD

**Issue by goleary** [prescottprue/react-redux-firebase#806]
**What is the current behavior?**
clicking the red circled link brings you to the `useFirebaseConnect` page in the docs.
![image](https://user-images.githubusercontent.com/16123225/70822322-1bf9ae00-1d92-11ea-960a-f92fb069a2ee.png)

http://react-redux-firebase.com/docs/api/useFirebaseConnect.html

**Comment by goleary** [comment]
https://github.com/prescottprue/react-redux-firebase/blob/master/docs/api/useFirestoreConnect.md

seems like even the docs for this function are incorrect with the examples referencing `useFirebaseConnect`, not `useFirestoreConnect`.

**Comment by prescottprue** [comment]
Fixed, thanks for posting

**Comment by goleary** [comment]
It looks like the link is fixed, but the example still uses `useFirebaseConnect`, not `useFirestoreConnect`. I'd be happy to submit a PR with the changes later
