### ISSUE TITLE
How to call firebase function?

### ISSUE THREAD

**Issue by mustaqeem** [prescottprue/react-redux-firebase#809]
**Can anybody help me to know how to call firebase functions using react-redux-firebase?**

**Comment by prescottprue** [comment]
You can use `firebase.functions()` directly if you have imported `firebase/functions` as noted [in the firebase docs](https://firebase.google.com/docs/functions/callable#call_the_function).

There are not currently any methods which dispatch actions or any cases in the reducers for updating state based on functions calls.

**Comment by mustaqeem** [comment]
Thanks @prescottprue. I was missing importing `firebase/functions`
