### ISSUE TITLE
feat(code generation): create a custom template for CRA to get started with RRF

### ISSUE THREAD

**Issue by harish-aka-shivi** [prescottprue/react-redux-firebase#818]
**Do you want to request a *feature* or report a *bug*?**  
feature

**Description**
Create React App provides support for custom templates from version `3.3.0`. It would be cool to create a template to get started with react-redux-firebase just by installing the template.

**Comment by harish-aka-shivi** [comment]
I am willing to work on it. 🙂

**Comment by prescottprue** [comment]
This is actually something I have wanted to do since I heard of the idea, love that you are willing to work on it! You may already know about it, but [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase) start projects with pretty close to the output of create-react-app, so that might be a good source of inspiration.

Let me know if you need anything from me 😄

**Comment by harish-aka-shivi** [comment]
Thank you for the response. I will have look at the generator-react-firebase and will get started with the custom template.😊

**Comment by prescottprue** [comment]
Yup! Started on a basic template here: [cra-template-rrf](https://github.com/prescottprue/cra-template-rrf)

Still needs some work though

**Comment by harish-aka-shivi** [comment]
I went through the generator-react-firebase, It is great and gives a lot of configurability. But I am confused about how dynamic should the creation of CRA Template be:
- one option is to make a project with a static config file just like the simple Firestore example or the output of generator-react-firebase. Here the user would have to just replace the Firebase config object after installation.
- Another option is taking config values from the terminal when setting up the project and the output will vary as it happens in generator-react-firebase

**Comment by prescottprue** [comment]
Going to close since we started the other repo. I referenced the other repo in the Starting A Project section of the README of this repo
