### ISSUE TITLE
upgrade to v3: TypeError: Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by ShabariRepo** [prescottprue/react-redux-firebase#823]
Upgraded from v2 briefly to v3 due to not being able to use connectedRouter (instaed of BrowserRouter)

- throws a type error at createFirebaseInstance and doesnt render DOM

Tried:
- rolling back to older version of v3
- back to v2 (but i need the connectedRouter which means i need react-redux v6 and up, etc..)
- tried putting store and configs in the index.js file to preveng issues during import

- this WORKS with v2 i just needed to upgrade to v3 due to this type of code below resulting in an error that tells me to upgrade react-redux version

...
...
export default compose(
  connect(mapStateToProps), 
  firestoreConnect([
    { collection: 'users' }
  ])
)(Index);

Note: I feel like this is something really small but new to this package and googling hasn't resulted in anything similar.  Just shows examples where Firebase is missing and that is due to configs.

![image](https://user-images.githubusercontent.com/10635357/71732070-5d6efd80-2e14-11ea-89b0-70015471c2f9.png)

*src/Index.js*
```
import React from 'react';
import { render } from 'react-dom';
import App from './App';
import { Provider, useSelector } from "react-redux";
import * as serviceWorker from './serviceWorker';
import store, { history, rrfProps } from "./store";
import { ConnectedRouter as Router } from "connected-react-router";
import { ReactReduxFirebaseProvider, isLoaded } from 'react-redux-firebase';

function AuthIsLoaded({ children }) {
  const auth = useSelector(state => state.firebase.auth);
  if (!isLoaded(auth)) return <div>splash screen...</div>;
  return children;
}

const routing = (
  <Provider store={store}>
    <ReactReduxFirebaseProvider {...rrfProps}>
      <Router history={history}>
        <AuthIsLoaded>
          <App />
        </AuthIsLoaded>
      </Router>
    </ReactReduxFirebaseProvider>
  </Provider>
);

// this was for v2 of react-redux-firebase
// store.firebaseAuthIsReady.then(() => {
render(routing, document.getElementById("root"));

serviceWorker.unregister();
// });
```

*src/App.js*
```
import React from 'react';
import { Route, Switch, Redirect } from "react-router-dom";

import extract from './components/extract';
import home from './components/home';
import AdminLayout from "./partial/Admin";
import AuthLayout from "./partial/Auth";


function App() {
  return (
    <Switch>
      {/* <Route exact path="/" component={home} />
      <Route exact path="/ext" component={extract} /> */}
      <Route path="/admin" render={props => <AdminLayout {...props} />} />
      <Route path="/auth" render={props => <AuthLayout {...props} />} />
      <Redirect from="/" to="/admin/index" />
    </Switch>
  );
}

export default App;
```

*src/store/Index.js*
```
import { createStore, compose, applyMiddleware } from "redux";
import thunk from "redux-thunk";
import { routerMiddleware } from "connected-react-router";
import { createBrowserHistory } from "history";

// firebase related things
import { createFirestoreInstance, getFirestore } from "redux-firestore";
import { getFirebase } from "react-redux-firebase";
import fbconfig from "./fbConfig";

import rootReducer from "../reducers/index";

export const history = createBrowserHistory();

// react-redux-firebase config
const rrfConfig = {
  userProfile: "users",
  useFirestoreForProfile: true, // Firestore for Profile instead of Realtime DB
  attachAuthIsReady: true, // attaches auth is ready promise to store
};

const store = createStore(
    rootReducer(history),
    {},
    compose(
        // applies middleware used in app
        applyMiddleware(
            thunk.withExtraArgument(getFirebase, getFirestore),
            routerMiddleware(history)
        )
    )
);

export const rrfProps = {
  fbconfig,
  config: rrfConfig,
  dispatch: store.dispatch,
  createFirestoreInstance // <- needed if using firestore
};

export default store;
```

*src/store/fbConfig.js*
```
import * as firebase from "firebase/app";
import "firebase/auth";
import "firebase/firestore";

const config = {
  apiKey: process.env.REACT_APP_FIREBASE_apiKey,
  authDomain: process.env.REACT_APP_FIREBASE_authDomain,
  databaseURL: process.env.REACT_APP_FIREBASE_databaseURL,
  projectId: process.env.REACT_APP_FIREBASE_projectId,
  storageBucket: process.env.REACT_APP_FIREBASE_storageBucket,
  messagingSenderId: process.env.REACT_APP_FIREBASE_messagingSenderId,
  appId: process.env.REACT_APP_FIREBASE_appId,
  measurementId: process.env.REACT_APP_FIREBASE_measurementId
};

firebase.initializeApp(config);
firebase.firestore();//.settings({ timestampsInSnapshots: true });

export default firebase;
```

*package.json*
```
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.3",
    "@testing-library/user-event": "^7.1.2",
    "axios": "^0.19.0",
    "bootstrap": "^4.4.1",
    "chart.js": "2.7.3",
    "classnames": "2.2.6",
    "connected-react-router": "^6.6.1",
    "firebase": "^7.5.2",
    "lodash": "^4.17.15",
    "moment": "2.24.0",
    "node-sass": "^4.13.0",
    "nouislider": "13.1.1",
    "qs": "^6.9.1",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-google-maps": "9.4.5",
    "react-loader-spinner": "^3.1.5",
    "react-redux": "^7.1.3",
    "react-redux-firebase": "^3.0.6",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.3.0",
    "reactstrap": "7.1.0",
    "redux": "^4.0.4",
    "redux-firestore": "^0.11.0",
    "redux-thunk": "^2.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by ShabariRepo** [comment]
ok so i found the issue.  As i suspected it was something super small.

the documentation doesnt describe this currently and my package json at this time was all LATEST for related packages to this thread.

the issue was that appart from the {...rrfprops} spread you also need to pass something into the firebase property or else it will read the whole thing as undefined.  I will post more but for now the dom renders which is a relief.  Wanted to document the above error here as when i searched it I didnt get results similar to this problem.

![image](https://user-images.githubusercontent.com/10635357/71734260-834ad100-2e19-11ea-87c0-92f255a06241.png)

**Comment by prescottprue** [comment]
Thanks for documenting - the [use section of the README](https://github.com/prescottprue/react-redux-firebase#use) covers passing in `firebase` as part of those props, but that said, since you ran into the issue, I'm sure it could happen to others.

**Comment by ShabariRepo** [comment]
hey @prescottprue thanks for updating, yeah i noticed that after i solved that as well..  I think my mistake was to look at just the Migration guide page which didnt specify this oddly particular thing and/or then google things!  My mistake, but thought it would be easily accessible if they search it this way :).

Thanks for the update above as well & love the library 👍

**Comment by SADIQQ005** [comment]
> @SADIQQ005 as mentioned in the error message, this appears when you don't pass firebase as a prop to ReactReduxFirebaseProvider - passing that as mentioned in the use section of the README should solve it for you

Yea thank you i have done just that already its working just fine

**Comment by b-gowri-sankar** [comment]
> ok so i found the issue. As i suspected it was something super small.
> 
> the documentation doesnt describe this currently and my package json at this time was all LATEST for related packages to this thread.
> 
> the issue was that appart from the {...rrfprops} spread you also need to pass something into the firebase property or else it will read the whole thing as undefined. I will post more but for now the dom renders which is a relief. Wanted to document the above error here as when i searched it I didnt get results similar to this problem.
> 
> ![image](https://user-images.githubusercontent.com/10635357/71734260-834ad100-2e19-11ea-87c0-92f255a06241.png)

Thank you sir/madam. You have just saved my mini project
