### ISSUE TITLE
how use getFireSotre() inside action ?

### ISSUE THREAD

**Issue by knour89** [prescottprue/react-redux-firebase#836]
Dears,

I am using react-redux-firebase/redux-firestore v3.... as I know there is no more getFireSotre().

I read the manual and i can't get it what I should use instead I am suing react-reudx + thunk

**Comment by prescottprue** [comment]
`getFirebase.firestore()` can be used as described in #785 . The firebase instance is now managed with react context instead of being placed on the redux store as `store.firebase` (or `store.firestore`).

**Comment by knour89** [comment]
it doesn't work,  but I found another way... using withFirestore() then send the props to action
