### ISSUE TITLE
useFirestoreConnect dependencies

### ISSUE THREAD

**Issue by Wgil** [prescottprue/react-redux-firebase#848]
**Do you want to request a *feature* or report a *bug*?**  
I want to report a bug

**What is the current behavior?**
`useFirestoreConnect` should accept a dependencies array so the queries can re-run based on another hooks. Right now, when I try to do it, I get a compilation error:
```
React Hook "useFirestoreConnect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hook
```
My custom hook goes like this:
```
const user = useUser()
  if (!user) return null
  useFirestoreConnect({
    collection: Team.collection,
    doc: user.id,
    ...moreStuffHere
  })
```

Let me know if I can open a PR.

**Comment by prescottprue** [comment]
Feel free to open a PR - maybe I'm wrong, but I was thinking that conditionally calling a hook was frowned upon though. What I have done in this case is loaded the user in a higher component then passed the value down.

**Comment by Wgil** [comment]
In fact, my implementation was wrong. I thought the listener was not getting updated on query change so I will close this issue,

Thanks.
