### ISSUE TITLE
Firebase Email Link Authentification with react-redux-firebase auth methods

### ISSUE THREAD

**Issue by wissile** [prescottprue/react-redux-firebase#849]
I'm checking in reference to a post in June 2018 about creating a new authentication method: 'EmailAuthProvider' in react-redux-firebase for developers using Firebase with Email Link in JavaScript: https://firebase.google.com/docs/auth/web/email-link-auth

I'm wondering if it is still on the roadmap? 
or is there any other alternative solutions to sync Firestore user auth data with the redux state? 

I'm on a react-native and expo platform 
Trying to implement react-redux-firebase to auth user and sync with the redux state

I'm sorry in advance if this has already been tackled but I have done a lot of research and couldn't find much about this topic.

Post reference:
That said, there have been recent changes in Firebase's v5 SDK that [are starting to be handled with the pull request for v2.1.5](https://github.com/prescottprue/react-redux-firebase/pull/481). If the existing methods don't work for your use case it would be good for us to try to get something in there for `EmailAuthProvider`.

_Originally posted by @prescottprue in https://github.com/prescottprue/react-redux-firebase/issues/485#issuecomment-395827468_

**Comment by prescottprue** [comment]
@wissile Syncing firestore user data with redux state can be done with the following config:

```js
// react-redux-firebase config
const rrfConfig = {
  userProfile: 'users',
  useFirestoreForProfile: true // Firestore for Profile instead of Realtime DB
}
```

This is described in [the firestore section of the react-redux-firebase docs](http://react-redux-firebase.com/docs/firestore.html#profile) - that said, I think I'm also going to add a section in the profile recipes so it is even easier to find.

**Comment by wissile** [comment]
@prescottprue Thank you for taking the time to answer my question. 
I have already configured the rrfConfig as you mentioned above. Probably I haven't formulated my question clearly:

1) How to log in users signed up with email link (passwordless) using the methods you have outlined in the auth section? 

2) Similarly, how to create users with createUser(credentials, profile) using email link (passwordless) auth?

ref to createUser: https://react-redux-firebase.com/docs/auth.html#createusercredentials-profile 
ref to email link (passwordless): https://firebase.google.com/docs/auth/web/email-link-auth

Thank you in advance for helping out with this.
