### ISSUE TITLE
[docs] useFirestoreConnect examples are using useFirebaseConnect instead

### ISSUE THREAD

**Issue by goleary** [prescottprue/react-redux-firebase#852]
referenced here #806

Opening a new issue to be closed with a PR I'll be submitting shortly.

**Comment by prescottprue** [comment]
Fixed in comment within src and regenerated docs. Thanks for posting!

**Comment by goleary** [comment]
for future reference, it would have been nice if you'd made the changes in my PR so that I got some amount of credit for them.

Thanks for the quick action.
