### ISSUE TITLE
feat(auth): support passwordless login (email link)

### ISSUE THREAD

**Issue by wissile** [prescottprue/react-redux-firebase#857]
@prescottprue Thank you for taking the time to answer my question. 
I have already configured the `rrfConfig` as you mentioned above and everything else according to your documentation. Perharps, I haven't formulated my question clearly:

1) How to log in users with `firebase.login({params})` that are signed up with [email link (passwordless)](https://firebase.google.com/docs/auth/web/email-link-auth
) using the methods you have outlined in the [auth section](http://react-redux-firebase.com/docs/auth.html#examples)? 

This one of your example:
```javascript
firebase.login({
  email: 'test@test.com',
  password: 'testest1'
})
```
Using your example, the user does not have a password, or credential or accessToken since he signed up using email link `firebase.auth().signInWithEmailLink(email, window.location.href)` but this wouldn't work:
```javascript
firebase.login({
  email: 'test@test.com',
  url: 'http://someurl.com' // should I add the auth url provided by firebase here?
})
```

2) Similarly, how to create users with [createUser(credentials, profile)](https://react-redux-firebase.com/docs/auth.html#createusercredentials-profile ) using [email link (passwordless)](https://firebase.google.com/docs/auth/web/email-link-auth
) auth?

```javascript
const createNewUser = ({ email, password, username }) => {
  firebase.createUser( // should password be replaced by url?
    { email, password },
    { username, email }
  )
}
```

Sorry I'm coming back with this question but it is very critical for me to understand the best implementation with your package module as this is a huge help with the project I'm trying to build.
Thank you in advance for helping out :)

_Originally posted by @wissile in https://github.com/prescottprue/react-redux-firebase/issues/849#issuecomment-581749263_

**Comment by dnewball** [comment]
+1 I’m also blocked with the same issue, I’m getting started with react native and Firebase auth and was planning to use email link auth but it is hardly documented anywhere it would be great together some advice on this

**Comment by cyonder** [comment]
+1 I can't find a proper documentation either. I would appreciate any help with this. At this moment I am not even sure if it is possible to implement passwordless authentication with this package.

**Comment by prescottprue** [comment]
Hey folks, thanks for all of the input. Yeah not sure we ever added the support in for passwordless. Open to PRs if anyone gets a chance, otherwise, I will try to get to it soon

**Comment by elron** [comment]
Any news on this?
