### ISSUE TITLE
firebase.updateProfile error in version 3.1.1

### ISSUE THREAD

**Issue by kellymestre** [prescottprue/react-redux-firebase#858]
Hi,
I'm using the profile feature using  "react-redux-firebase": "~3.1.1", and followed the https://react-redux-firebase.com/docs/recipes/profile.html.

Previously I implemented with version 2 and it worked. But with version 3.1.1 when calling the firebase.updateProfile, I'm getting the following error:

**TypeError: Cannot read property '_getService' of undefined
    at firebaseAppImpl.<computed> (firebaseNamespaceCore.ts:219)
    at updateProfileOnFirestore (auth.js:320)
    at Object.updateProfile (auth.js:835)
    at FirebaseAppImpl.updateProfile (createFirebaseInstance.js:491)
    ...**

I'm able to get the profile a perform other actions against the firebase instance.
But the same error is happening when I call firebase.updateAuth.

Can you help with this please?

**Comment by prescottprue** [comment]
@kellymestre Can you provide your app setup? Are you sure you have imported `firebase/auth`?

**Comment by kellymestre** [comment]
@prescottprue Yes I have firebase/auth imported.
And if I do firebase.auth() I get a valid result.

![image](https://user-images.githubusercontent.com/45340221/73871740-4756c180-4846-11ea-812a-a1fda8c470c8.png)

![image](https://user-images.githubusercontent.com/45340221/73871755-52a9ed00-4846-11ea-9ef8-dc07fc9e12b3.png)

![image](https://user-images.githubusercontent.com/45340221/73871797-68b7ad80-4846-11ea-9808-6270af9cbdd0.png)

![image](https://user-images.githubusercontent.com/45340221/73871967-b59b8400-4846-11ea-8e30-b68ac45f8cb8.png)

Do you need anything else?

**Comment by illuminist** [comment]
`import * as firebase from 'firebase/app'` usually cause an issue. You need to import default without star:

```
import firebase from 'firebase/app'
```

**Comment by kellymestre** [comment]
@illuminist thanks for the reply! I've tested with that change but still getting the same error.

**Comment by illuminist** [comment]
I notice that you're using an app instance from `initializeApp` function and passing it to ReactReduxFirebaseProvider props, but that is difference from generic instance gotten from `import firebase from 'firebase/app'`. Maybe try:

```js
import firebase from 'firebase/app`

const reduxFirebaseProps = {
  firebase,
  dispatch: ...,
  config: ...,
}
```

**Comment by kellymestre** [comment]
@illuminist yes that worked. Thanks a lot for the help!
