### ISSUE TITLE
inaccurate role based auth recipe for redux-auth-wrapper v2

### ISSUE THREAD

**Issue by markoelez** [prescottprue/react-redux-firebase#860]
I noticed that the Roles (Access Management) Recipe at `docs/recipes/roles.md` is out of date for react-router v4 + redux-auth-wrapper v2. 

- Redux-auth-wrapper v2 does not export a `UserAuthWrapper` object as used in the recipe. Rather, it uses `connectedRouterRedirect`.
- The example also imports `browserHistory` which is not exported by react-router.

The recipe for react-router v4 + redux-auth-wrapper v2 is currently as follows:
```
import locationHelperBuilder from 'redux-auth-wrapper/history4/locationHelper';
import { browserHistory } from 'react-router';
import LoadingScreen from '../components/LoadingScreen'; // change it to your custom component

const locationHelper = locationHelperBuilder({});

export const UserHasPermission = permission => UserAuthWrapper({
  wrapperDisplayName: 'UserHasPermission',
  AuthenticatingComponent: LoadingScreen,
  allowRedirectBack: false,
  redirectPath: (state, ownProps) =>
    locationHelper.getRedirectQueryParam(ownProps) || '/login',
  authenticatingSelector: ({ firebase: { auth, isInitializing } }) =>
    !auth.isLoaded || !profile.isLoaded || isInitializing === true,
  authenticatedSelector: ({ firebase: { auth } }) =>
    auth.isLoaded && !auth.isEmpty,
  redirectAction: newLoc => (dispatch) => {
    browserHistory.replace(newLoc); // or routerActions.replace
    dispatch({ type: UNAUTHED_REDIRECT });
  }
});
```
Which is innacurate. If possible, I would be happy to fix this issue.

**Comment by prescottprue** [comment]
@markoelez totally open to a PR fixing the issue if you get a chance. Thanks for reaching out!

**Comment by markoelez** [comment]
@prescottprue  I just opened a PR fixing the issue!

**Comment by prescottprue** [comment]
Thanks for the PR!
