### ISSUE TITLE
use auth signInWithCredential login Error

### ISSUE THREAD

**Issue by kudorori** [prescottprue/react-redux-firebase#87]
# error 1:

```
return firebase.login({
     provider: "facebook",
     token: fb_token
});
```

## error msg

```
03-22 15:47:44.664  3387  4306 W ReactNativeJS: signInWithCredential failed: Expected 1 argument but got 2.
```

## Issue File

`react-redux-firebase/src/actions/auth.js` 

```
263 let { method, params } = getLoginMethodAndParams(firebase, credentials) <== He should not return 2 parameters ??
265  return firebase.auth()[method](...params)  <=== error??
```

# error 2

```
let credential = new firebase.auth.FacebookAuthProvider.credential(fb_token);
return firebase.login(credential);
```

## error msg

```
03-22 15:57:28.104  3387  4435 W ReactNativeJS: facebook.com is not a valid Auth Provider
```

**Comment by prescottprue** [comment]
React-native is not fully supported yet. I have been working on an example to show auth, but it isn't finished yet.

Could you possibly provide a repo to reproduce the error? If you don't want to share it publicly, feel free to reach out to me privately [over gitter](https://gitter.im/redux-firebase/Lobby).

**Comment by prescottprue** [comment]
I have found out that `auth.signInWithCredential` does not work in `react-native`, as it throws an "Unsupported Browser" error.

[`v1.4.0-alpha`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-alpha) includes the initial `react-native` capabilities. Note that it requires [a different setup than usual](https://github.com/prescottprue/react-redux-firebase/blob/v1.4.0/docs/recipes/react-native.md).

Authentication is not currently supported as it does not work through the Firebase JS library. The current plan is going to be to investigating integration of [react-native-firebase](https://github.com/invertase/react-native-firebase), which might change the setup a bit again.

**Comment by kudorori** [comment]
I use firebase 3.7.3, `auth.signInWithCredential` can work

**Comment by prescottprue** [comment]
@kudorori It looks like you are right!

Currently it is being imported like so:
```js
import * as firebase from 'firebase/app'
import 'firebase/auth'
import 'firebase/database'
import 'firebase/storage'
```

But, in order to get auth to work correctly on react native, it has to look like this:

```js
import * as firebase from 'firebase';
```

This was to help solve #53 and #80, but we are going to have to see if it can be handled for both cases. Maybe we should have a `react-native` specific index file?

Will keep you updated with solutions. Thanks for pointing this out!

**Comment by prescottprue** [comment]
[`v1.4.0-beta`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-beta) includes changes to makt the auth work with `react-native`. There is now also a [complete react-native example including auth](https://github.com/prescottprue/react-redux-firebase/tree/v1.4.0/examples/complete/react-native), which will remain on the v1.4.0 branch until it it is released.

Can anyone give the example a try or try using the new version in your project and confirm?

Note the new setup:

```js
import { AsyncStorage } from 'react-native'

const createStoreWithFirebase = compose(
  reactReduxFirebase(firebaseConfig, {
    userProfile: 'users',
    ReactNative: { AsyncStorage }, // now under "ReactNative" instead of "rn"
    // enableRedirectHandling: false // no longer needed when using react-native
  }),
)(createStore)
```


@kudorori, gave you a shoutout in another issue that was solved by getting the react-native stuff fixed.

**Comment by prescottprue** [comment]
Even more good changes for `react-native` in the [v1.4.0.beta.4](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-beta.4) release including updates to the [react-native example](https://github.com/prescottprue/react-redux-firebase/tree/v1.4.0/examples/complete/react-native).

@kudorori Post if it doesn't work when you get a chance to test it out.
