### ISSUE TITLE
How to use select filter with firestoreConnect()

### ISSUE THREAD

**Issue by vivekweb2013** [prescottprue/react-redux-firebase#879]
The select query is supported by core firestore apis
[https://cloud.google.com/nodejs/docs/reference/firestore/0.8.x/Query#select
](https://cloud.google.com/nodejs/docs/reference/firestore/0.8.x/Query#select
)

> Query that applies a field mask to the result and returns only the specified subset of fields. You can specify a list of field paths to return, or use an empty list to only return the references of matching documents

This select query helps a lot when I want to just retrieve some field out of large documents to show it as a summary.

I don't see any option for using such select query with firestoreConnect()
How can I use the select query with firestoreConnect, please suggest.

**Comment by prescottprue** [comment]
@vivekweb2013 The link you provided is to the legacy API for Firestore - the [newer API docs do not show the select functionality](https://firebase.google.com/docs/reference/js/firebase.firestore.Query#methods_1). For now, only methods and queries that are supported by the official SDK are supported.

That said, I personally would really like this feature as well, not sure why they would have dropped support for it.

**Comment by 0xdevalias** [comment]
This looks like a relevant related issue: https://github.com/firebase/firebase-js-sdk/issues/212
