### ISSUE TITLE
firebase prop object documentation

### ISSUE THREAD

**Issue by marekolszewski** [prescottprue/react-redux-firebase#89]
Thanks for creating this great project. I love the concept and the examples are very helpful.

I was curious if you had an API reference for the firebase object you pass as a prop in wrapped containers. I've noticed that you have some great helpers on that object but I couldn't find any documentation other than just reading the code and your examples. It would be really helpful if these helpers and the rest of the object was succinctly described on your awesome documentation site.

**Comment by prescottprue** [comment]
Here is the link to the `props.firebase` section. Planning on making the descriptions/examples more full, but just wanted to get a framework in place.

Thanks for the suggestion.!

**Comment by marekolszewski** [comment]
Awesome. This is very helpful. Thanks!
