### ISSUE TITLE
Outdated documentation for `useFirestore`

### ISSUE THREAD

**Issue by karlmarxlopez** [prescottprue/react-redux-firebase#905]
**Do you want to request a *feature* or report a *bug*?**  

This is a bug report and documentation update request. I think the documentation uses the old API for the extended firestore object?

**What is the current behavior?**

`firestore.add` throws cannot read `apply` of `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
```ts

function Hello() {
   const firestore = useFirestore();
   
   const onPress = useCallback(() => 
        firestore.add({collection: 'myCollection', doc: 'baz'}, {
           greetings: 'Lorem ipsum',
   }),[])
   
   return <Button title="press me" onPress={onPress} />
}

```

**What is the expected behavior?**

It should add the new document successfully

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
```json
{
       "react-native": "0.61.5",
       "@react-native-firebase/firestore": "^6.4.0",
       "@react-native-firebase/app": "^6.4.0",
       "react-redux-firebase": "^3.3.0",
       "redux-firestore": "^0.13.0",
}
```

**Comment by prescottprue** [comment]
Are you sure that you have everything setup correctly? It seems that this could happen if you haven't pulled in the firebase sdk correctly with Firestore. Can you provide a codesandbox for a full reproduction of the issue?

**Comment by serinuntius** [comment]
@kadikraman Did you forget to write this?

`import 'firebase/firestore'`

https://github.com/prescottprue/react-redux-firebase#use

```js
import React from 'react'
import { render } from 'react-dom'
import { Provider } from 'react-redux'
import firebase from 'firebase/app'
import 'firebase/auth'
// import 'firebase/firestore' // <- needed if using firestore
// import 'firebase/functions' // <- needed if using httpsCallable
import { createStore, combineReducers, compose } from 'redux'
import {
  ReactReduxFirebaseProvider,
  firebaseReducer
} from 'react-redux-firebase'
// import { createFirestoreInstance, firestoreReducer } from 'redux-firestore' // <- needed if using firestore

```

**Comment by karlmarxlopez** [comment]
@serinuntius I have the import on my setup. I'll try to upload a sandbox app today or tomorrow morning.

**Comment by karlmarxlopez** [comment]
I think I've found the issue, I'm using `add` method instead of `set` when adding a document. For example `firestore.set('users/myuid/todos/randomid', {id:'randomid', task: 'eat'})`
