### ISSUE TITLE
Docs for watchEvent()

### ISSUE THREAD

**Issue by doublejosh** [prescottprue/react-redux-firebase#910]
Looks like missing and/or incorrect docs for `watchEvent()` in snippets.

https://github.com/prescottprue/react-redux-firebase/blob/master/examples/snippets/watchEvent/README.md

**Current behavior**
It doesn't include the use of `watchEvent()` in the example.

**Comment by prescottprue** [comment]
Thanks for reaching out - the example in that folder actually uses `watchEvent`, but it wasn't mentioned in the README. This has been corrected
