### ISSUE TITLE
No type definition for `profileFactory`

### ISSUE THREAD

**Issue by karlmarxlopez** [prescottprue/react-redux-firebase#917]
**Do you want to request a *feature* or report a *bug*?**  

Bug report

**What is the current behavior?**
Type error on an RN TS project.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
1. Create RN TS project
2. Create a `.ts` file (e.g. `index.ts`)
3. Paste the following code
```ts
import {ReactReduxFirebaseConfig} from 'react-redux-firebase';

const rrfConfig: Partial<ReactReduxFirebaseConfig> = {
  enableRedirectHandling: false,
  useFirestoreForProfile: true,
  userProfile: 'users',
  profileFactory: (userData, profileData, firebase) => {
    const { user } = userData
    return {
      email: user.email
    }
  }
};
```
4. Linter gets mad because it does not exist on `ReactReduxFirebaseConfig`

**What is the expected behavior?**
It should have no lint/ts errors

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
```
"react-redux-firebase": "^3.3.0",
```

**Comment by prescottprue** [comment]
Released in [v3.3.1](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.3.1)
