### ISSUE TITLE
Incomplete sentence in Queries doc page

### ISSUE THREAD

**Issue by gregfenton** [prescottprue/react-redux-firebase#925]
On the [PARSED](https://react-redux-firebase.com/docs/queries.html#parsed) section of the Queries page there is an incomplete sentence/thought:

> Useful when attempting to parse

...parse....what/why/when?  :)

**Comment by codedpills** [comment]
"query parameters into the actual value or particular data type ( e.g. null, number, boolean) instead of the string containing the value."

If the above makes sense, I'll submit a PR now to patch it.

**Comment by gregfenton** [comment]
Thanks @codedpills & @prescottprue !
