### ISSUE TITLE
Using useFirebaseConnect with null

### ISSUE THREAD

**Issue by sebadom** [prescottprue/react-redux-firebase#953]
**Do you want to request a *feature* or report a *bug*?**  BUG

The documentation says that useFirebaseConnect can be potentially used passing **null** as an argument, therefore NO sync is done.
First issue: null is not supported when using typescript, undefined is.
Second issue: using this approach makes the component to throw an error when unwatches the event

**What is the current behavior?**

Navigating away from the route containing a component with this piece: 

```
    useFirebaseConnect(editMode ? `courses/${match.params.id}` : null);

    const course:any = useSelector((state: RootState) => {
        if (editMode) {
            return state.firebase.data.courses && state.firebase.data.courses[match.params.id];
        } else {
            return initialStateCourse;
        }
    });
```

Throws this:
```Uncaught TypeError: Cannot read property 'forEach' of undefined,```

It is exploting at this code
```
export function unWatchEvents(firebase, dispatch, events) {
    events.forEach((event) => unWatchEvent(firebase, dispatch, event))
}
```

[Here](https://codesandbox.io/s/elated-cori-0nt2u) you can reproduce it. Go from HOME to TODOS, then click HOME again. see the error

**Comment by prescottprue** [comment]
`useFirebaseConnect` should recieve an array argument, so you could do:

```js
    useFirebaseConnect(editMode ? [`courses/${match.params.id}`] : []);
```

**Comment by sebadom** [comment]
Mmm I see... let me try that out. On the other hand I believe the documentation is wrong perhaps

![image](https://user-images.githubusercontent.com/3877952/83869850-9bde5080-a703-11ea-8f4d-9f64944776a2.png)

It says it supports array, string, object, function or null if we don't want to sync. And the example is using a string also

Let me set things up using just an array and I will come back. Thanks!

**Comment by sebadom** [comment]
I think its working fine with empty array!  It might have been me, but I was confused by the documentation
Thanks!
