### ISSUE TITLE
Removing a signed up user from firebase authentication

### ISSUE THREAD

**Issue by kanlanc** [prescottprue/react-redux-firebase#970]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**

Couldn't find a function for removing users that are signed up from firebase authentication in the docs

**What is the expected behavior?**

Provide a function that removes a signed up user

**Comment by prescottprue** [comment]
@kanlanc This is something that seems like it should be handled using the firebase-admin SDK in a node environment like cloud functions. There is not a method in [the firebaseJS SDK auth section](https://firebase.google.com/docs/reference/js/firebase.auth.Auth) for removing users, so there isn't really anything I am aware of that can be exposed for doing this.

Please let me know if I am misunderstanding
