### ISSUE TITLE
feat(auth): github OAuth provider option in login

### ISSUE THREAD

**Issue by zachlyoung** [prescottprue/react-redux-firebase#971]
Hello, I searched around the docs and seems like the only provider options are: `provider: "facebook | google | twitter | microsoft.com"`. It seems like there is no support for other OAuth providers like Github and I was wondering why or if that was a feature that was being looked into. The typescript declaration file also does not allow "github" as a provider

**Comment by prescottprue** [comment]
@zachlyoung Should for sure be supported. Open to a PR if you get a chance, otherwise I'll try to get to it when I can
