### ISSUE TITLE
bug(types): return type for firebase.updateProfile is not a promise

### ISSUE THREAD

**Issue by zachary-young** [prescottprue/react-redux-firebase#975]
**Do you want to request a *feature* or report a *bug*?**  

bug

**What is the current behavior?**

Typescript shows an error when appending .then() to firebase.updateProfile()

`Property 'then' does not exist on type 'void'`

**What is the expected behavior?**

Typescript recognizes updateProfile() as promise in index.d.ts

`  updateProfile: (profile: Partial<ProfileType>, options?: Object) => void`

should be
`  updateProfile: (profile: Partial<ProfileType>, options?: Object) => Promise<void>`

**Comment by prescottprue** [comment]
Thanks for reporting. Open to a PR if you get a chance
