### ISSUE TITLE
docs: image is broken (URL is 404) on React Native page

### ISSUE THREAD

**Issue by gregfenton** [prescottprue/react-redux-firebase#978]
### Bug

The [RRF docs page for React Native](http://react-redux-firebase.com/docs/integrations/react-native.html) has a link to an image that is 404 (i.e. the image is "broken").

### Repro

See the "xcode config" image just this is broken just before the title of [this section of the RN page](http://react-redux-firebase.com/docs/integrations/react-native.html#set-open-urls)

### Cause 
This broke when the image it was linked to was removed from the public repository with https://github.com/react-native-community/google-signin/pull/553/files .  Here is [the specific diff](https://github.com/react-native-community/google-signin/commit/ad5ae08d09dd167d4517e4abe29b51ab9c5c2ff2#diff-770fbc41d15abcc7b10637ee7b52ff56)

### Possible Fixes
- get a copy of the image from the repo (above) and store it in RRF's docs repo
- link to a version of the image where [it still exists](https://raw.githubusercontent.com/react-native-community/google-signin/1d20b15859fd221c0cc088d5dd47b7cfe1544ffe/img/url-config.png)

**Comment by prescottprue** [comment]
Thanks for reporting - Feel free to make a PR if you get a chance, otherwise I will get to it when I can

**Comment by gregfenton** [comment]
You want me to make a copy of the image and upload, or link to the historic
version it used to point to?  I'm unsure of your philosophy on such
things.  Your project, I don't want to "pollute it" on you.

Greg Fenton
--
email: *greg.fenton@gmail.com <greg.fenton@gmail.com>*
linkedin: *http://ca.linkedin.com/in/fentongreg*
<http://ca.linkedin.com/in/fentongreg>
twitter: *@gregfenton*
