### ISSUE TITLE
Namespace '"/usr/app/node_modules/@firebase/storage-types/index"' has no exported member 'UploadTaskSnapshot'

### ISSUE THREAD

**Issue by emilieguth** [prescottprue/react-redux-firebase#997]
This is a bug, reported using Typescript.

**What is the current behavior?**

```
node_modules/react-redux-firebase/index.d.ts:1076:28 - error TS2694: Namespace '"/usr/app/node_modules/@firebase/storage-types/index"' has no exported member 'UploadTaskSnapshot'.

1076     metadata: StorageTypes.UploadTaskSnapshot.metadata,

```

**What is the expected behavior?**

We can correct the issue writing : 
`metadata: StorageTypes.UploadTaskSnapshot['metadata'],`

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

I don't know if this bug occurred in previous versions as it's the first time I use it.

**Comment by artall64** [comment]
Reproduced on latest version OS X

**Comment by prescottprue** [comment]
Could you try v3.9.0 - there were a number of types fixes including one that I believe will fix this (in a PR from @MatthewDailey).

Please reach out if your issue persists, thanks for reporting!

**Comment by emilieguth** [comment]
thanks it's perfect 👍
